Gain: $ -286.8 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -49.95 Win %: 66.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_AV
Gain: $ -48.52 Win %: 70.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_AV
Gain: $ -44.91 Win %: 33.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ -37.04 Win %: 76.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_AV
Gain: $ -34.7 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -31.44 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -28.42 Win %: 60.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR_IR5
Gain: $ -27.9 Win %: 70.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_AL
Gain: $ -27.75 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -27.42 Win %: 61.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR_IR5
Gain: $ -27.12 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -27.12 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -27.12 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -27.12 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -27.12 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -26.92 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -26.92 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -26.92 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -26.9 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -26.9 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -26.55 Win %: 61.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR_IR5
Gain: $ -26.5 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -26.34 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -25.97 Win %: 47.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -25.93 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -25.55 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -25.48 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -25.47 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -25.47 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -25.47 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -25.47 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -25.47 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -25.47 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ -25.47 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ -25.15 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -25.15 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -25.15 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -25.15 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -25.15 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -25.15 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -25.12 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -25.1 Win %: 47.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -24.95 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -24.9 Win %: 47.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -23.99 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -23.69 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -23.69 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -23.69 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -23.69 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -23.69 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -23.69 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -23.69 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -23.69 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ -23.69 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ -23.49 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -23.49 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -23.49 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -23.49 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -23.49 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -22.86 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -22.78 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -22.67 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -22.11 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -20.8 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -20.8 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -20.8 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -20.8 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -20.8 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -20.8 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -20.8 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -20.8 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ -19.98 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -19.98 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -19.9 Win %: 30.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_LI
Gain: $ -19.81 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -19.62 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -19.62 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -19.62 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -19.62 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ -19.58 Win %: 33.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_LI
Gain: $ -19.04 Win %: 55.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_VI
Gain: $ -18.98 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -18.98 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -18.98 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -18.98 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -18.92 Win %: 33.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_LI
Gain: $ -18.79 Win %: 57.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_VI
Gain: $ -18.73 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -18.73 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -18.73 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -18.73 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -18.73 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -18.39 Win %: 33.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_VI
Gain: $ -17.31 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -16.92 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -16.92 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -16.92 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -16.91 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -16.91 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ -16.68 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -16.68 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -16.64 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -16.64 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -16.64 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -16.64 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ -16.5 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -15.75 Win %: 40.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM
Gain: $ -15.37 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -15.25 Win %: 55.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV
Gain: $ -14.14 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ -13.62 Win %: 57.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV
Gain: $ -12.94 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -12.94 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -12.9 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ -12.44 Win %: 61.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_VI
Gain: $ -12.27 Win %: 41.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -12.27 Win %: 41.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -12.27 Win %: 41.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ -12.27 Win %: 41.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ -11.9 Win %: 42.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -11.74 Win %: 42.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -11.53 Win %: 38.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ -11.5 Win %: 45.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -11.5 Win %: 45.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -11.5 Win %: 45.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ -11.5 Win %: 45.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ -11.44 Win %: 38.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_TR
Gain: $ -11.21 Win %: 50.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -11.15 Win %: 40.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_TR
Gain: $ -10.72 Win %: 57.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV
Gain: $ -10.51 Win %: 50.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ -10.22 Win %: 40.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_TR
Gain: $ -10.05 Win %: 50.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -10.02 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ -9.98 Win %: 53.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_HM_AV
Gain: $ -9.8 Win %: 40.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_QL
Gain: $ -9.68 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -9.53 Win %: 47.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ -9.49 Win %: 40.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_LI
Gain: $ -9.39 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -9.39 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -9.39 Win %: 73.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -8.77 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ -8.61 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -8.59 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM
Gain: $ -8.23 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV
Gain: $ -8.18 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -8.17 Win %: 40.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_AV
Gain: $ -8.12 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -8.11 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ -8.06 Win %: 40.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ -8.06 Win %: 40.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ -7.94 Win %: 71.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -7.74 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -7.43 Win %: 71.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_AL
Gain: $ -7.41 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ -7.36 Win %: 38.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -7.36 Win %: 38.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -7.36 Win %: 38.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ -7.3 Win %: 40.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_DB15
Gain: $ -6.75 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -6.75 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -6.75 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ -6.72 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -6.66 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -6.58 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -6.58 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -6.5 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -6.13 Win %: 42.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -6.13 Win %: 42.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -6.02 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -5.29 Win %: 42.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR
Gain: $ -5.15 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -5.15 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -5.15 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ -5.15 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ -4.85 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_SS
Gain: $ -4.78 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -4.56 Win %: 40.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR
Gain: $ -4.37 Win %: 95.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ -4.26 Win %: 47.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_TR
Gain: $ -4 Win %: 42.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR
Gain: $ -3.98 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -3.98 Win %: 71.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -3.96 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -3.66 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -3.66 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -3.66 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -3.66 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ -3.28 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ -3.28 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ -3.14 Win %: 73.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_QP_IR5
Gain: $ -3.08 Win %: 76.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ -3.08 Win %: 76.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ -3.02 Win %: 50.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ -2.91 Win %: 95.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_TR_DB
Gain: $ -2.72 Win %: 71.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_AL
Gain: $ -2.45 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -2.21 Win %: 80.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -2.16 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ -1.91 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -1.83 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -1.83 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -1.83 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ -1.83 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ -1.83 Win %: 80.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -1.83 Win %: 80.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -1.83 Win %: 80.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ -1.83 Win %: 80.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ -1.83 Win %: 80.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ -1.83 Win %: 80.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ -1.83 Win %: 80.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -1.81 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -1.81 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -1.81 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -1.81 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ -1.62 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -1.57 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -1.57 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ -1.57 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ -1.38 Win %: 40.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -1.27 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -1.27 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ -0.92 Win %: 80.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -0.9 Win %: 95.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ -0.9 Win %: 95.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ -0.73 Win %: 40.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ -0.73 Win %: 40.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ -0.45 Win %: 80.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -0.36 Win %: 42.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_TR
Gain: $ -0.13 Win %: 45.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_TR
AMC Gain: $ -0.52 Win %: 56.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_AL
AMC Gain: $ -0.52 Win %: 56.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_AL
AMC Gain: $ -0.52 Win %: 56.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_AL
AMC Gain: $ -0.58 Win %: 54.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_AL
AMC Gain: $ -0.75 Win %: 60.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_QP_IR3
AMC Gain: $ -1.18 Win %: 39.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_QL
AMC Gain: $ -1.65 Win %: 58.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_QP_IR3
AMC Gain: $ -1.97 Win %: 47.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_TR_IR3
AMC Gain: $ -10.26 Win %: 56.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_AV
AMC Gain: $ -10.26 Win %: 56.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_AV
AMC Gain: $ -10.36 Win %: 47.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_TR
AMC Gain: $ -10.79 Win %: 47.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_TR
AMC Gain: $ -11.33 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_AV
AMC Gain: $ -12.41 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_IR3
AMC Gain: $ -12.41 Win %: 54.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_IR3
AMC Gain: $ -12.99 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_TR
AMC Gain: $ -13.28 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_IR3
AMC Gain: $ -13.64 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_QP
AMC Gain: $ -13.88 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_HM_AV
AMC Gain: $ -13.88 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_HM_AV
AMC Gain: $ -13.88 Win %: 69.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_AV
AMC Gain: $ -14.22 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_HM_AV
AMC Gain: $ -14.94 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_AV
AMC Gain: $ -14.94 Win %: 54.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_AV
AMC Gain: $ -14.94 Win %: 54.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_AV
AMC Gain: $ -15.26 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_IR3
AMC Gain: $ -15.26 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_IR3
AMC Gain: $ -15.78 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_HM_QP
AMC Gain: $ -15.78 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_HM_QP
AMC Gain: $ -15.78 Win %: 69.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP
AMC Gain: $ -16.33 Win %: 75.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_QP
AMC Gain: $ -16.95 Win %: 45.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_TR_IR3
AMC Gain: $ -16.95 Win %: 45.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_TR_IR3
AMC Gain: $ -17.15 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_TR_QP
AMC Gain: $ -17.15 Win %: 66.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_TR_QP
AMC Gain: $ -17.15 Win %: 66.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_TR_QP
AMC Gain: $ -17.45 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_QP
AMC Gain: $ -17.45 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_QP
AMC Gain: $ -17.45 Win %: 69.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_QP
AMC Gain: $ -17.54 Win %: 65.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_TR_QP
AMC Gain: $ -17.54 Win %: 65.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_TR_QP
AMC Gain: $ -17.54 Win %: 65.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_TR_QP
AMC Gain: $ -17.79 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_QP
AMC Gain: $ -17.79 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_QP
AMC Gain: $ -17.79 Win %: 66.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_QP
AMC Gain: $ -18.34 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_TR_QP
AMC Gain: $ -18.52 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_HM_AV
AMC Gain: $ -18.52 Win %: 66.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_HM_AV
AMC Gain: $ -18.52 Win %: 66.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_AV
AMC Gain: $ -18.89 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_HM_QP
AMC Gain: $ -18.89 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_HM_QP
AMC Gain: $ -18.89 Win %: 66.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_HM_QP
AMC Gain: $ -18.89 Win %: 66.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP
AMC Gain: $ -19.43 Win %: 43.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_QP
AMC Gain: $ -19.43 Win %: 43.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_QP
AMC Gain: $ -19.43 Win %: 43.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_QP
AMC Gain: $ -19.59 Win %: 41.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_QP
AMC Gain: $ -19.59 Win %: 41.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_RV_QP
AMC Gain: $ -19.59 Win %: 41.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_QP
AMC Gain: $ -19.8 Win %: 43.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_TR_IR3
AMC Gain: $ -19.8 Win %: 43.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_TR_IR3
AMC Gain: $ -2.61 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_VI
AMC Gain: $ -2.8 Win %: 54.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_VI
AMC Gain: $ -21.35 Win %: 37.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_TR_IR3
AMC Gain: $ -22.98 Win %: 34.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_TR_IR3
AMC Gain: $ -23.27 Win %: 41.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_TR_IR3
AMC Gain: $ -28.97 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_AV
AMC Gain: $ -29.58 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_AV
AMC Gain: $ -3.67 Win %: 66.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_HM_TR
AMC Gain: $ -30.19 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_AV
AMC Gain: $ -30.19 Win %: 54.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_RV_AV
AMC Gain: $ -30.71 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_AV
AMC Gain: $ -30.71 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_AV
AMC Gain: $ -30.71 Win %: 52.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_AV
AMC Gain: $ -35.51 Win %: 54.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_AV
AMC Gain: $ -4.6 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_VI
AMC Gain: $ -4.6 Win %: 52.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_VI
AMC Gain: $ -4.96 Win %: 65.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_TR_QP
AMC Gain: $ -5.47 Win %: 65.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_HM_TR
AMC Gain: $ -5.47 Win %: 65.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_HM_TR
AMC Gain: $ -5.47 Win %: 65.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_TR
AMC Gain: $ -5.74 Win %: 50.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_VI
AMC Gain: $ -6.49 Win %: 62.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_HM_TR
AMC Gain: $ -6.49 Win %: 62.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_HM_TR
AMC Gain: $ -7.97 Win %: 54.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_TR
AMC Gain: $ -9.29 Win %: 50.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_TR
AMC Gain: $ -9.29 Win %: 50.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_TR
AMC Gain: $ -9.43 Win %: 47.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_TR
AMC Gain: $ 0.05 Win %: 58.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_AL
AMC Gain: $ 0.05 Win %: 58.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_AL
AMC Gain: $ 0.05 Win %: 58.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_RV_AL
AMC Gain: $ 0.52 Win %: 52.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_TR
AMC Gain: $ 10.6 Win %: 54.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_TR
AMC Gain: $ 10.62 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_TR
AMC Gain: $ 10.62 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_TR_DB3
AMC Gain: $ 10.62 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_TR
AMC Gain: $ 10.62 Win %: 54.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_RV_TR
AMC Gain: $ 10.62 Win %: 54.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_RV_TR_DB3
AMC Gain: $ 10.62 Win %: 54.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_TR_DB3
AMC Gain: $ 11.25 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_TR_DB3
AMC Gain: $ 11.54 Win %: 56.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_IR3
AMC Gain: $ 13.69 Win %: 66.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_HM
AMC Gain: $ 13.69 Win %: 66.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_HM
AMC Gain: $ 13.69 Win %: 66.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM
AMC Gain: $ 15.27 Win %: 58.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_DB10
AMC Gain: $ 15.32 Win %: 47.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_LI
AMC Gain: $ 15.32 Win %: 47.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_LI
AMC Gain: $ 15.32 Win %: 47.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_LI
AMC Gain: $ 16.16 Win %: 69.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_DB10
AMC Gain: $ 16.39 Win %: 50.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_LI
AMC Gain: $ 16.44 Win %: 65.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_AV
AMC Gain: $ 16.73 Win %: 50.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_LI
AMC Gain: $ 16.73 Win %: 50.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_LI
AMC Gain: $ 16.73 Win %: 50.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_LI
AMC Gain: $ 16.83 Win %: 62.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_AL
AMC Gain: $ 16.83 Win %: 62.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_AL
AMC Gain: $ 16.83 Win %: 62.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_AL
AMC Gain: $ 16.88 Win %: 65.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_RV
AMC Gain: $ 17.03 Win %: 65.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_AL
AMC Gain: $ 17.03 Win %: 65.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_AL
AMC Gain: $ 17.03 Win %: 65.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_AL
AMC Gain: $ 17.06 Win %: 65.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_HM_AV
AMC Gain: $ 17.35 Win %: 60.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_SS
AMC Gain: $ 17.35 Win %: 60.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_SS
AMC Gain: $ 17.56 Win %: 50.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_VI
AMC Gain: $ 17.84 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_HM
AMC Gain: $ 17.84 Win %: 69.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM
AMC Gain: $ 17.85 Win %: 60.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_DB10
AMC Gain: $ 17.85 Win %: 60.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2
AMC Gain: $ 17.85 Win %: 60.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_DB10
AMC Gain: $ 17.85 Win %: 60.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_DB10
AMC Gain: $ 17.86 Win %: 54.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV
AMC Gain: $ 17.92 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_HM
AMC Gain: $ 18.42 Win %: 62.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_SS
AMC Gain: $ 18.42 Win %: 62.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_SS
AMC Gain: $ 18.42 Win %: 62.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_SS
AMC Gain: $ 18.42 Win %: 62.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_SS
AMC Gain: $ 18.73 Win %: 66.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_AL
AMC Gain: $ 18.86 Win %: 62.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2
AMC Gain: $ 18.86 Win %: 70.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_HM
AMC Gain: $ 18.87 Win %: 56.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_VI
AMC Gain: $ 18.87 Win %: 69.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_SS
AMC Gain: $ 18.92 Win %: 62.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_DB10
AMC Gain: $ 18.92 Win %: 62.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_DB10
AMC Gain: $ 19.04 Win %: 65.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_SS
AMC Gain: $ 19.23 Win %: 47.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_QL
AMC Gain: $ 19.23 Win %: 47.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_QL
AMC Gain: $ 19.83 Win %: 62.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_DB10
AMC Gain: $ 20.3 Win %: 50.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_QL
AMC Gain: $ 20.3 Win %: 50.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_QL
AMC Gain: $ 20.3 Win %: 50.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_QL
AMC Gain: $ 20.93 Win %: 50.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_QL
AMC Gain: $ 21.09 Win %: 43.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_VI
AMC Gain: $ 21.66 Win %: 54.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV
AMC Gain: $ 21.8 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_QL
AMC Gain: $ 21.8 Win %: 69.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_RV_AL
AMC Gain: $ 22.73 Win %: 56.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV
AMC Gain: $ 22.73 Win %: 56.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV
AMC Gain: $ 22.73 Win %: 56.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV
AMC Gain: $ 23.8 Win %: 58.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV
AMC Gain: $ 23.8 Win %: 58.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_RV
AMC Gain: $ 24.44 Win %: 60.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_LI
AMC Gain: $ 28.03 Win %: 47.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_IR3
AMC Gain: $ 29.58 Win %: 73.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_HM
AMC Gain: $ 29.73 Win %: 50.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_IR3
AMC Gain: $ 3.69 Win %: 47.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_RV_TR
AMC Gain: $ 3.69 Win %: 47.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_RV_TR_DB3
AMC Gain: $ 4.5 Win %: 52.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_AL
AMC Gain: $ 4.5 Win %: 66.00 in 24 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_TR
AMC Gain: $ 5.11 Win %: 60.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_RV_AV
AMC Gain: $ 5.3 Win %: 56.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_HM_TR
AMC Gain: $ 51.59 Win %: 73.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_QP
AMC Gain: $ 52.09 Win %: 69.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_RV_QP
AMC Gain: $ 56.31 Win %: 82.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_HM_QP
AMC Gain: $ 58.3 Win %: 47.00 in 23 days with algo TB3_HL_HS_QM_OB1_OS1_CB3_CS3_QP_IR3
AMC Gain: $ 59.69 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_QP_IR3
AMC Gain: $ 59.69 Win %: 69.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_QP_IR3
AMC Gain: $ 60.05 Win %: 70.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_QP_IR3
AMC Gain: $ 60.05 Win %: 70.00 in 24 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_QP_IR3
AMC Gain: $ 60.05 Win %: 70.00 in 24 days with algo TB3_LO_QM_OB5_OS5_CB2_CS2_QP_IR3
AMC Gain: $ 9.55 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_TR
AMC Gain: $ 9.55 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB1_CS1_RV_TR_DB3
AMC Gain: $ 9.55 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_TR
AMC Gain: $ 9.55 Win %: 52.00 in 23 days with algo TB3_CC_QM_OB5_OS5_CB2_CS2_RV_TR_DB3
AMC Gain: $ 9.55 Win %: 52.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_TR
AMC Gain: $ 9.55 Win %: 52.00 in 23 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_RV_TR_DB3
Gain: $ 0 Win %: 100.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_AL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_DB8
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_LI
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QP_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_AL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_SS
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_VI
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_DB6
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ 0 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 0 Win %: 100.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0.02 Win %: 40.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 0.22 Win %: 40.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 0.51 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 0.66 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 0.66 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ 0.9 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 0.91 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 1.03 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 1.05 Win %: 47.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_TR
Gain: $ 1.09 Win %: 100.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 1.13 Win %: 42.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 1.19 Win %: 100.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 1.3 Win %: 41.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 1.3 Win %: 41.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 1.3 Win %: 41.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 1.3 Win %: 41.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ 1.34 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 1.34 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 1.34 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 1.66 Win %: 66.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QP
Gain: $ 1.71 Win %: 70.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QP
Gain: $ 1.83 Win %: 42.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 1.83 Win %: 42.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 2.07 Win %: 45.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 2.07 Win %: 45.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 2.07 Win %: 45.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ 2.07 Win %: 45.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ 2.22 Win %: 60.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_SS
Gain: $ 2.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 2.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 2.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 2.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ 2.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ 2.63 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 2.73 Win %: 66.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR_QP
Gain: $ 2.77 Win %: 70.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR_QP
Gain: $ 2.96 Win %: 66.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_TR_QP
Gain: $ 3.07 Win %: 66.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QP
Gain: $ 3.08 Win %: 50.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 3.36 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 3.61 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 4.2 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 4.4 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 4.66 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 4.66 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 4.66 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 4.66 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 4.75 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 4.97 Win %: 53.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $ 5.07 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 5.17 Win %: 75.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QP_IR5
Gain: $ 5.34 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 5.34 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 5.34 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 5.34 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 5.49 Win %: 76.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QP_IR5
Gain: $ 5.59 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 5.59 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 5.59 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 5.61 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ 6.31 Win %: 86.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 6.94 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 6.94 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 6.94 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 7.59 Win %: 80.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_QP
Gain: $ 7.78 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ 7.81 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 7.81 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 7.86 Win %: 35.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QL
Gain: $ 8.2 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 8.25 Win %: 47.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_SS
Gain: $ 8.42 Win %: 38.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QL
Gain: $ 8.79 Win %: 80.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QP_IR5
Gain: $ 8.93 Win %: 80.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_QP
Gain: $ 9.04 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 9.26 Win %: 80.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_QP
Gain: $ 9.29 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 10.51 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 10.62 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 10.67 Win %: 45.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_SS
Gain: $ 10.9 Win %: 66.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_HM_TR
Gain: $ 11.15 Win %: 42.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_QL
Gain: $ 11.16 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 11.16 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ 11.23 Win %: 47.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_SS
Gain: $ 11.94 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 11.94 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 11.94 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 11.94 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 11.94 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 11.94 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 11.94 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 12.12 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 12.45 Win %: 40.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_VI
Gain: $ 12.62 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 12.62 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 12.62 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 12.62 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 12.71 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 13.17 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 13.17 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ 13.53 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 14.16 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 14.65 Win %: 71.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 14.81 Win %: 42.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_DB8
Gain: $ 15.17 Win %: 71.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 15.21 Win %: 50.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_AV
Gain: $ 15.69 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 15.69 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 15.69 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 15.69 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ 15.69 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ 16.24 Win %: 52.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_AV
Gain: $ 16.25 Win %: 76.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 16.87 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 16.87 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 17.04 Win %: 82.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 17.04 Win %: 82.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 17.04 Win %: 82.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 17.04 Win %: 82.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ 17.48 Win %: 45.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_DB8
Gain: $ 17.52 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 17.52 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 17.55 Win %: 80.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 17.91 Win %: 47.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 18.04 Win %: 47.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_DB8
Gain: $ 18.08 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 18.38 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 19.07 Win %: 50.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 19.16 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 19.16 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 19.16 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 19.16 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 19.16 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 19.41 Win %: 47.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_AV
Gain: $ 19.76 Win %: 50.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM
Gain: $ 19.77 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 19.77 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 19.8 Win %: 52.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 19.8 Win %: 52.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 19.8 Win %: 52.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 19.8 Win %: 52.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 19.91 Win %: 50.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_AV
Gain: $ 20.03 Win %: 60.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_TR
Gain: $ 20.14 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 20.24 Win %: 52.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM_AV
Gain: $ 20.25 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 20.25 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 20.25 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5
Gain: $ 20.25 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ 20.36 Win %: 47.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 20.69 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 20.72 Win %: 52.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM
Gain: $ 20.94 Win %: 52.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_HM
Gain: $ 20.94 Win %: 66.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_IR5
Gain: $ 21.48 Win %: 47.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 21.57 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 21.79 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 21.79 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 21.79 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ 22.1 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 22.1 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 22.31 Win %: 53.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 22.31 Win %: 53.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 22.42 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 22.45 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 22.49 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5
Gain: $ 22.62 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 22.63 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 22.66 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_DB6
Gain: $ 23.22 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 23.22 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 23.22 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ 23.22 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ 23.22 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5
Gain: $ 23.22 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_DB6
Gain: $ 23.62 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 23.62 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 23.8 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 23.85 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 23.85 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 23.85 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 23.85 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 23.85 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 23.85 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 24.09 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 24.09 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 24.09 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 24.2 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5
Gain: $ 24.23 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 24.66 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 24.66 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 25.22 Win %: 73.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_IR5
Gain: $ 25.24 Win %: 57.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_AV
Gain: $ 25.3 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 25.3 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 25.3 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 25.3 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 25.3 Win %: 55.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 25.33 Win %: 73.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_DB6
Gain: $ 25.82 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 26.56 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 26.56 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 26.56 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ 26.56 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5
Gain: $ 26.56 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_DB6
Gain: $ 26.91 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 26.91 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 26.91 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 26.91 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 27.03 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 27.32 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 27.64 Win %: 73.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_RV_AL
Gain: $ 27.89 Win %: 73.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_HM
Gain: $ 28.08 Win %: 73.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_AL
Gain: $ 28.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 28.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 28.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 28.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 28.33 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 28.44 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 28.44 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 28.62 Win %: 57.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_AL
Gain: $ 28.67 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 28.85 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 28.88 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 28.88 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 28.88 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 28.88 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 28.95 Win %: 75.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_IR5
Gain: $ 28.95 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ 28.95 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5
Gain: $ 28.95 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_DB6
Gain: $ 29.05 Win %: 55.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_AL
Gain: $ 29.4 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 29.4 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 29.4 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 29.4 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 29.52 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 29.68 Win %: 80.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_TR_IR5
Gain: $ 29.71 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 29.85 Win %: 80.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $ 30.17 Win %: 57.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_AL
Gain: $ 30.51 Win %: 76.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_IR5
Gain: $ 30.86 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 31.05 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 31.05 Win %: 61.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 31.44 Win %: 80.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_RV
Gain: $ 31.79 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 31.79 Win %: 73.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 32.17 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 32.17 Win %: 52.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 32.37 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 32.37 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 32.74 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 32.74 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 33.42 Win %: 80.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_HM_QP
Gain: $ 33.71 Win %: 86.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_QP
Gain: $ 34 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 34 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 34 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 34 Win %: 65.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 34.45 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 34.45 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 34.45 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 34.45 Win %: 64.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 34.48 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 34.56 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 34.6 Win %: 80.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $ 34.66 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 34.78 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 34.78 Win %: 57.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 35.73 Win %: 70.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 35.82 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 35.82 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 35.82 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 35.82 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 35.82 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 35.82 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 35.82 Win %: 80.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_TR_QP
Gain: $ 36.58 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 38.7 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 38.7 Win %: 66.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 39.17 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 39.17 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 39.17 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 39.17 Win %: 70.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 40.4 Win %: 86.00 in 15 days with algo TB5_HL_QM_OB2_OS2_CB4_CS4_LI
Gain: $ 41.75 Win %: 57.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_QP
Gain: $ 42.95 Win %: 60.00 in 20 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_QP
Gain: $ 44.05 Win %: 61.00 in 21 days with algo TB4_EO_EC_QM_OB5_OS5_CB4_CS4_RV_QP
Gain: $ 50.9 Win %: 60.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 57.54 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ 57.54 Win %: 71.00 in 21 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ 59.57 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 59.57 Win %: 66.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 59.86 Win %: 71.00 in 21 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 59.86 Win %: 71.00 in 21 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 59.98 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 59.98 Win %: 80.00 in 15 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ 60.1 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 60.1 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ 60.1 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 60.1 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ 60.1 Win %: 75.00 in 20 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ 60.22 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 60.22 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ 60.22 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 60.22 Win %: 76.00 in 17 days with algo TB5_CC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ 61.37 Win %: 80.00 in 20 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_QP_IR5
