AVXL Gain: $ -30.38 Win %: 0 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_HM_QP
AVXL Gain: $ -29.94 Win %: 0 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_QP
AVXL Gain: $ -29.45 Win %: 0 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_QP
AVXL Gain: $ -25.21 Win %: 0 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_QP
AVXL Gain: $ -24.48 Win %: 0 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_QP
AVXL Gain: $ -24.24 Win %: 0 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_QP_IR2
AVXL Gain: $ -23.18 Win %: 0 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_HM_QP
AVXL Gain: $ -22.38 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_AV
AVXL Gain: $ -22.31 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_IT_QP
AVXL Gain: $ -19.08 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_HM_AV
AVXL Gain: $ -16.47 Win %: 0 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_QP_IR1
AVXL Gain: $ -16.47 Win %: 0 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_QP_IR1
AVXL Gain: $ -15.68 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_AV
AVXL Gain: $ -14.6 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_HM_AV
AVXL Gain: $ -12.5 Win %: 0 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_TR_QP
AVXL Gain: $ -12.13 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM_AV
AVXL Gain: $ -12.13 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM_AV
AVXL Gain: $ -12.13 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM_AV_DB1
AVXL Gain: $ -10.69 Win %: 0 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_QP
AVXL Gain: $ -10.69 Win %: 0 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_QP
AVXL Gain: $ -10.3 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_AV
AVXL Gain: $ -10.3 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_AV
AVXL Gain: $ -10.3 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_AV_DB1
AVXL Gain: $ -9.12 Win %: 0 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_QP
AVXL Gain: $ -9.06 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP_IR1
AVXL Gain: $ -9.06 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP_IR1
AVXL Gain: $ -8.38 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AV
AVXL Gain: $ -8.38 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AV
AVXL Gain: $ -8.2 Win %: 0 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_QP
AVXL Gain: $ -8.2 Win %: 0 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_QP_DB2
AVXL Gain: $ -8.06 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_TR_QP
AVXL Gain: $ -7.7 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_QP
AVXL Gain: $ -7.7 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_QP
AVXL Gain: $ -7.7 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_QP_DB1
AVXL Gain: $ -7.47 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QL
AVXL Gain: $ -7.47 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QL
AVXL Gain: $ -7.47 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QL_DB1
AVXL Gain: $ -7.47 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QL
AVXL Gain: $ -7.47 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QL
AVXL Gain: $ -7.41 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_AV
AVXL Gain: $ -7.41 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_AV
AVXL Gain: $ -7.32 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM_TR
AVXL Gain: $ -7.32 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM_TR_DB1
AVXL Gain: $ -7.26 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP
AVXL Gain: $ -7.26 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP
AVXL Gain: $ -7.26 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_QP
AVXL Gain: $ -7.26 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_QP
AVXL Gain: $ -7.26 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_QP_DB1
AVXL Gain: $ -7.14 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QP
AVXL Gain: $ -7.14 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QP_DB1
AVXL Gain: $ -7.12 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_QP
AVXL Gain: $ -7.12 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_QP
AVXL Gain: $ -7.12 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_QP_DB1
AVXL Gain: $ -7.08 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QP
AVXL Gain: $ -6.88 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_TR
AVXL Gain: $ -6.88 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_TR
AVXL Gain: $ -6.88 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_TR_DB1
AVXL Gain: $ -6.69 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_TR
AVXL Gain: $ -6.69 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_TR
AVXL Gain: $ -6.69 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_TR_DB1
AVXL Gain: $ -6.69 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_TR_DB1
AVXL Gain: $ -6.69 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_TR_DB1
AVXL Gain: $ -6.68 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR
AVXL Gain: $ -6.68 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR
AVXL Gain: $ -6.68 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
AVXL Gain: $ -6.68 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
AVXL Gain: $ -6.68 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
AVXL Gain: $ -6.64 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM_TR
AVXL Gain: $ -6.38 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV
AVXL Gain: $ -6.38 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV
AVXL Gain: $ -6.05 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IT_QP
AVXL Gain: $ -6.05 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IT_QP
AVXL Gain: $ -6.01 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IT_QP
AVXL Gain: $ -6.01 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IT_QP_DB2
AVXL Gain: $ -5.75 Win %: 0 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_TR_QP
AVXL Gain: $ -5.73 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM
AVXL Gain: $ -5.73 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM
AVXL Gain: $ -5.68 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_TR_IR1
AVXL Gain: $ -5.6 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_TR_IR1
AVXL Gain: $ -5.23 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM_QP
AVXL Gain: $ -5.23 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_HM_TR
AVXL Gain: $ -5.15 Win %: 0 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_AV
AVXL Gain: $ -5.07 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM
AVXL Gain: $ -5.07 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM
AVXL Gain: $ -4.93 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_IT_QL
AVXL Gain: $ -4.93 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_QL
AVXL Gain: $ -4.73 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM_QP
AVXL Gain: $ -4.73 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM_QP_DB2
AVXL Gain: $ -4.51 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IT_QL
AVXL Gain: $ -4.51 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IT_QL
AVXL Gain: $ -4.51 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IT_QL_DB1
AVXL Gain: $ -4.51 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_QL
AVXL Gain: $ -4.51 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_QL
AVXL Gain: $ -4.51 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV
AVXL Gain: $ -4.51 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV
AVXL Gain: $ -4.49 Win %: 0 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_TR_QP
AVXL Gain: $ -4.49 Win %: 0 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_TR_QP_DB2
AVXL Gain: $ -3.84 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_TR_DB3
AVXL Gain: $ -3.84 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_TR
AVXL Gain: $ -3.75 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_VI
AVXL Gain: $ -3.75 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_VI
AVXL Gain: $ -3.64 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_TR
AVXL Gain: $ -3.59 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IR1
AVXL Gain: $ -3.59 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IR1
AVXL Gain: $ -3.38 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_AL
AVXL Gain: $ -3.21 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_AL
AVXL Gain: $ -3.21 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_AL
AVXL Gain: $ -3.15 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_VI
AVXL Gain: $ -3.13 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_AL
AVXL Gain: $ -3.01 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AL
AVXL Gain: $ -3.01 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AL
AVXL Gain: $ -2.8 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_QL
AVXL Gain: $ -2.52 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_QP_IR2
AVXL Gain: $ -2.52 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_QP_IR2
AVXL Gain: $ -2.35 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_TR
AVXL Gain: $ -2.35 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_TR
AVXL Gain: $ -2.11 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM_QP
AVXL Gain: $ -2.11 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM_QP
AVXL Gain: $ -2.11 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM_QP_DB1
AVXL Gain: $ -1.94 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_IT_QP
AVXL Gain: $ -1.73 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_VI
AVXL Gain: $ -1.73 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_VI
AVXL Gain: $ -1.64 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_TR_QP
AVXL Gain: $ -1.64 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_TR_QP
AVXL Gain: $ -1.64 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_TR_QP_DB1
AVXL Gain: $ -1.31 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR
AVXL Gain: $ -1.31 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR
AVXL Gain: $ -1.31 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_IR1
AVXL Gain: $ -1.31 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_IR1
AVXL Gain: $ -1.18 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_QP
AVXL Gain: $ -1.18 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_QP
AVXL Gain: $ -1.13 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_SS
AVXL Gain: $ -1.08 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_DB10
AVXL Gain: $ -1.01 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_IT_QL
AVXL Gain: $ -1.01 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_QL
AVXL Gain: $ -0.91 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_QP
AVXL Gain: $ -0.91 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_QP
AVXL Gain: $ -0.91 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_QP_DB1
AVXL Gain: $ -0.81 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IT_QP
AVXL Gain: $ -0.81 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IT_QP_DB1
AVXL Gain: $ -0.72 Win %: 75.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IT_QP
AVXL Gain: $ -0.71 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IT
AVXL Gain: $ -0.56 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_DB8
AVXL Gain: $ -0.5 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_LI
AVXL Gain: $ -0.5 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_LI
AVXL Gain: $ -0.42 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QP
AVXL Gain: $ -0.39 Win %: 33.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_VI
AVXL Gain: $ -0.39 Win %: 33.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_VI
AVXL Gain: $ -0.39 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_VI
AVXL Gain: $ -0.39 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_VI
AVXL Gain: $ -0.31 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_QP
AVXL Gain: $ -0.28 Win %: 25.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QP
AVXL Gain: $ -0.28 Win %: 25.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QP_DB2
AVXL Gain: $ -0.27 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_SS
AVXL Gain: $ -0.27 Win %: 25.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_SS
AVXL Gain: $ -0.27 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_IR2
AVXL Gain: $ -0.22 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_DB6
AVXL Gain: $ -0.22 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_DB6
AVXL Gain: $ -0.15 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IR1
AVXL Gain: $ -0.15 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IR1
AVXL Gain: $ -0.15 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT
AVXL Gain: $ -0.15 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT
AVXL Gain: $ 0 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_IR3
AVXL Gain: $ 0 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_QP_IR3
AVXL Gain: $ 0 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_TR_IR3
AVXL Gain: $ 0 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_QP_IR_DB2
AVXL Gain: $ 0 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_TR_IR_DB2
AVXL Gain: $ 0 Win %: 100.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP_IR_DB2
AVXL Gain: $ 0 Win %: 100.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_IR_DB2
AVXL Gain: $ 0 Win %: 100.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_QP_IR_DB1
AVXL Gain: $ 0 Win %: 100.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_TR_IR_DB1
AVXL Gain: $ 0 Win %: 100.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP_IR_DB1
AVXL Gain: $ 0 Win %: 100.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_IR_DB1
Gain: $ -0.2 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_VI
Gain: $ -0.31 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QL
Gain: $ -0.37 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AL
Gain: $ -0.57 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_AL
Gain: $ -0.57 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_DB6
Gain: $ -0.57 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_SS
Gain: $ -0.61 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_HM_QP
Gain: $ -0.68 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_QP
Gain: $ -0.68 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_TR_QP
Gain: $ -1 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5
Gain: $ -1.04 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_QP_IR5
Gain: $ -1.07 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_AL
Gain: $ -1.09 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_DB6
Gain: $ -1.28 Win %: 0 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_QL
Gain: $ -1.43 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_VI
Gain: $ -1.45 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_VI
Gain: $ -1.66 Win %: 33.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_LI
Gain: $ -1.81 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_LI
Gain: $ -11.49 Win %: 50.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_RV_AV
Gain: $ -13.37 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_HM_AV
Gain: $ -13.77 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_IR5
Gain: $ -15.53 Win %: 0 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_HM_AV
Gain: $ -16.28 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_AV
Gain: $ -17.28 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_HM_AV
Gain: $ -17.83 Win %: 50.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_AV
Gain: $ -18.44 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_AV
Gain: $ -2.14 Win %: 0 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_VI
Gain: $ -2.3 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_TR_QP
Gain: $ -2.63 Win %: 33.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_LI
Gain: $ -2.7 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_TR_QP
Gain: $ -2.74 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_VI
Gain: $ -2.78 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -2.78 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ -2.78 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_QP_IR5
Gain: $ -2.79 Win %: 50.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_QL
Gain: $ -21.47 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_QP_IR5
Gain: $ -25.7 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_QP
Gain: $ -26.65 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_HM
Gain: $ -3.09 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_RV_QP
Gain: $ -3.73 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_HM_QP
Gain: $ -3.73 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_HM_QP
Gain: $ -3.73 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_QP
Gain: $ -3.73 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_TR_QP
Gain: $ -3.82 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_QL
Gain: $ -4.6 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -4.79 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_RV_TR
Gain: $ -5.11 Win %: 33.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -5.22 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_QL
Gain: $ -7.03 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_TR_QP
Gain: $ -7.06 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_HM_QP
Gain: $ -7.26 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_QP
Gain: $ -7.64 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_QP
Gain: $ -8.52 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_AV
Gain: $ -9.05 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_QP_IR5
Gain: $ -9.16 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_QP_IR5
Gain: $ -9.16 Win %: 0 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_TR_DB
Gain: $ 0.02 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1
Gain: $ 0.18 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ 0.18 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_DB8
Gain: $ 0.18 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ 0.18 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_IR5
Gain: $ 0.22 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_RV_AV
Gain: $ 0.29 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 0.29 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 0.36 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_HM_TR
Gain: $ 0.41 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_RV_QP
Gain: $ 0.42 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 0.52 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_LI
Gain: $ 0.68 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_AL
Gain: $ 0.74 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ 0.83 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_TR_IR5
Gain: $ 0.86 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_RV_TR_DB
Gain: $ 0.88 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_HM_TR
Gain: $ 0.88 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_DB8
Gain: $ 0.94 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_IR5
Gain: $ 0.94 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_TR_IR5
Gain: $ 0.94 Win %: 50.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_IR5
Gain: $ 0.94 Win %: 50.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_TR_IR5
Gain: $ 0.99 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_SS
Gain: $ 1.1 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ 1.17 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ 1.2 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_HM
Gain: $ 1.28 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_RV_TR_DB
Gain: $ 1.32 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 1.32 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ 1.32 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ 1.38 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_AV
Gain: $ 1.49 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_DB10
Gain: $ 1.5 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_RV_AV
Gain: $ 1.54 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ 1.58 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_RV_TR
Gain: $ 1.59 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_AL
Gain: $ 1.64 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_TR
Gain: $ 1.67 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_TR
Gain: $ 1.7 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_RV_AL
Gain: $ 1.71 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_LI
Gain: $ 1.82 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_AV
Gain: $ 1.89 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV
Gain: $ 1.94 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_TR_QP
Gain: $ 10.27 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM
Gain: $ 10.27 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 10.27 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 10.46 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_HM
Gain: $ 14.97 Win %: 50.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_RV_QP
Gain: $ 15.02 Win %: 50.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_HM_QP
Gain: $ 15.02 Win %: 50.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_QP
Gain: $ 16.19 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_QP
Gain: $ 18.38 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_RV_QP
Gain: $ 2 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_SS
Gain: $ 2.1 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_AV
Gain: $ 2.1 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_QL
Gain: $ 2.1 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_TR_IR5
Gain: $ 2.24 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_HM_AV
Gain: $ 2.29 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_IR5
Gain: $ 2.45 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_VI
Gain: $ 2.55 Win %: 50.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_SS
Gain: $ 2.57 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_RV
Gain: $ 2.65 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_LI
Gain: $ 2.7 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 2.71 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_AL
Gain: $ 2.91 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_RV_AL
Gain: $ 2.95 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_SS
Gain: $ 20.23 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_HM_QP
Gain: $ 3.02 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_HM_TR
Gain: $ 3.1 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 3.1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_SS
Gain: $ 3.1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_TR
Gain: $ 3.18 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_RV_AL
Gain: $ 3.24 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_HM
Gain: $ 3.27 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_HM
Gain: $ 3.35 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_AL
Gain: $ 3.35 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_AL
Gain: $ 3.45 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_DB10
Gain: $ 3.45 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_HM
Gain: $ 3.65 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_RV
Gain: $ 3.7 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 3.81 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 3.81 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_TR
Gain: $ 3.81 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ 3.81 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_TR_IR5
Gain: $ 3.82 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_IR5
Gain: $ 3.88 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 4.07 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_AL
Gain: $ 4.19 Win %: 100.00 in 2 days with algo TB3_HL_LO_QM_OB1_OS1_CB2_CS2_HM_TR
Gain: $ 4.2 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_LI
Gain: $ 4.38 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_AL
Gain: $ 4.51 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 4.51 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 4.52 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_DB10
Gain: $ 4.52 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_RV_TR
Gain: $ 4.55 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ 4.73 Win %: 100.00 in 2 days with algo TB5_PL_QM_OB1_OS1_CB1_CS1_TR
Gain: $ 4.79 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_TR
Gain: $ 4.99 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_TR
Gain: $ 5.05 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_LI
Gain: $ 5.16 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_AV
Gain: $ 5.23 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_TR_IR5
Gain: $ 5.29 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 5.36 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 5.53 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_SS
Gain: $ 5.59 Win %: 100.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_HM_TR
Gain: $ 5.68 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_HM_AV
Gain: $ 5.71 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB5_OS5_CB4_CS4_RV
Gain: $ 5.72 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_TR
Gain: $ 5.72 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_TR
Gain: $ 5.97 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_DB8
Gain: $ 6 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ 6.05 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_RV_TR
Gain: $ 6.18 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_QL
Gain: $ 6.42 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_RV
Gain: $ 6.59 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_HM_TR
Gain: $ 6.73 Win %: 100.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV
Gain: $ 6.76 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_HM_AV
Gain: $ 7.06 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 7.44 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 8.01 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_RV_AL
Gain: $ 8.84 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_RV_AV
Gain: $ 8.92 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 9.2 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB5_OS5_CB1_CS1_HM
Gain: $ 9.51 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_HM_QP
Gain: $ 9.57 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ 9.92 Win %: 33.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV_QP
AVXL Gain: $ 0.01 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_QP
AVXL Gain: $ 0.01 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_QP
AVXL Gain: $ 0.01 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_QP_DB2
AVXL Gain: $ 0.04 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_QP
AVXL Gain: $ 0.04 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_QP_DB2
AVXL Gain: $ 0.09 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QP
AVXL Gain: $ 0.11 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP
AVXL Gain: $ 0.11 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP
AVXL Gain: $ 0.14 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_IT_QP
AVXL Gain: $ 0.14 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_IT_QP
AVXL Gain: $ 0.2 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IT
AVXL Gain: $ 0.2 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IT
AVXL Gain: $ 0.2 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP_IR2
AVXL Gain: $ 0.2 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP_IR2
AVXL Gain: $ 0.21 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_DB6
AVXL Gain: $ 0.21 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_DB6
AVXL Gain: $ 0.31 Win %: 75.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_IT
AVXL Gain: $ 0.32 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_LI
AVXL Gain: $ 0.39 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_QP
AVXL Gain: $ 0.39 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_QP
AVXL Gain: $ 0.39 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_QP_DB2
AVXL Gain: $ 0.4 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_HM_QP
AVXL Gain: $ 0.41 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_HM_TR
AVXL Gain: $ 0.43 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_QP
AVXL Gain: $ 0.43 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_TR_QP
AVXL Gain: $ 0.49 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_AL
AVXL Gain: $ 0.49 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_AL
AVXL Gain: $ 0.52 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_QP
AVXL Gain: $ 0.52 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_QP_IR2
AVXL Gain: $ 0.55 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_LI
AVXL Gain: $ 0.59 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_QP
AVXL Gain: $ 0.61 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_QP
AVXL Gain: $ 0.62 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP
AVXL Gain: $ 0.71 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP_IR2
AVXL Gain: $ 0.8 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_QP
AVXL Gain: $ 0.81 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_SS
AVXL Gain: $ 0.81 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_SS
AVXL Gain: $ 0.85 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_AV
AVXL Gain: $ 0.88 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_IT
AVXL Gain: $ 1.08 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_VI
AVXL Gain: $ 1.35 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IT_QL
AVXL Gain: $ 1.35 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IT_QL
AVXL Gain: $ 1.35 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IT_QL_DB2
AVXL Gain: $ 1.41 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_QL
AVXL Gain: $ 1.47 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_LI
AVXL Gain: $ 1.47 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_LI
AVXL Gain: $ 1.5 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_RV
AVXL Gain: $ 1.53 Win %: 33.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_TR_IR2
AVXL Gain: $ 1.56 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_IT
AVXL Gain: $ 1.56 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV
AVXL Gain: $ 1.72 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_SS
AVXL Gain: $ 2.01 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_HM
AVXL Gain: $ 2.29 Win %: 66.00 in 3 days with algo TB3_HL_HI_QM_OB1_OS1_CB1_CS1_LI
AVXL Gain: $ 2.54 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV
AVXL Gain: $ 2.63 Win %: 75.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_VI
AVXL Gain: $ 2.63 Win %: 75.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_VI
AVXL Gain: $ 2.79 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_DB8
AVXL Gain: $ 2.86 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_SS
AVXL Gain: $ 3.08 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_SS
AVXL Gain: $ 3.22 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV
AVXL Gain: $ 3.77 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_TR
AVXL Gain: $ 3.77 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_TR_DB2
AVXL Gain: $ 3.77 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_TR
AVXL Gain: $ 3.79 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_AL
AVXL Gain: $ 3.79 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_AL
AVXL Gain: $ 3.79 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_AL_DB2
AVXL Gain: $ 4.12 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_HM
AVXL Gain: $ 4.29 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_TR_IR2
AVXL Gain: $ 4.32 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM
AVXL Gain: $ 4.32 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM
AVXL Gain: $ 4.44 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_DB8
AVXL Gain: $ 4.6 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_AL
AVXL Gain: $ 4.6 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_RV_AL
AVXL Gain: $ 4.69 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_TR_IR2
AVXL Gain: $ 4.85 Win %: 66.00 in 3 days with algo TB4_HL_LO_QM_OB1_OS1_CB1_CS1_LI
AVXL Gain: $ 4.99 Win %: 75.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_LI
AVXL Gain: $ 4.99 Win %: 75.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_LI
AVXL Gain: $ 5.37 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QL
AVXL Gain: $ 5.72 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IR2
AVXL Gain: $ 5.72 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_IR2
AVXL Gain: $ 5.77 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM_TR
AVXL Gain: $ 5.99 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_AV
AVXL Gain: $ 5.99 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_AV
AVXL Gain: $ 6.04 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_TR
AVXL Gain: $ 6.33 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_LI
AVXL Gain: $ 6.33 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_LI
AVXL Gain: $ 6.69 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_SS
AVXL Gain: $ 6.69 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_SS
AVXL Gain: $ 6.79 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_AV
AVXL Gain: $ 6.89 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
AVXL Gain: $ 6.96 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM_TR
AVXL Gain: $ 6.96 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM_TR_DB2
AVXL Gain: $ 7.06 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_IT
AVXL Gain: $ 7.06 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_IT_QL
AVXL Gain: $ 7.1 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_TR
AVXL Gain: $ 7.1 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_TR_DB2
AVXL Gain: $ 7.11 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_AL
AVXL Gain: $ 7.12 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_IR2
AVXL Gain: $ 7.12 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_TR_IR2
AVXL Gain: $ 7.14 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AL
AVXL Gain: $ 7.14 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AL
AVXL Gain: $ 7.24 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IR2
AVXL Gain: $ 7.24 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IR2
AVXL Gain: $ 7.24 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_IR2
AVXL Gain: $ 7.24 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_IR2
AVXL Gain: $ 7.29 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_SS
AVXL Gain: $ 7.29 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_DB8
AVXL Gain: $ 7.29 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_QL
AVXL Gain: $ 7.29 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_SS
AVXL Gain: $ 7.29 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_TR
AVXL Gain: $ 7.32 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_AL
AVXL Gain: $ 7.32 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_AL
AVXL Gain: $ 7.32 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_RV_AL_DB1
AVXL Gain: $ 7.41 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5
AVXL Gain: $ 7.41 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5
AVXL Gain: $ 7.41 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_DB8
AVXL Gain: $ 7.41 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_DB8
AVXL Gain: $ 7.41 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT
AVXL Gain: $ 7.41 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT
AVXL Gain: $ 7.41 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR
AVXL Gain: $ 7.41 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR
AVXL Gain: $ 7.43 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM_AV
AVXL Gain: $ 7.43 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM_AV
AVXL Gain: $ 7.43 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_HM_AV_DB2
AVXL Gain: $ 7.54 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AV
AVXL Gain: $ 7.54 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AV
AVXL Gain: $ 7.59 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_TR
AVXL Gain: $ 7.59 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_TR
AVXL Gain: $ 7.71 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR
AVXL Gain: $ 7.71 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR
AVXL Gain: $ 7.71 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
AVXL Gain: $ 7.71 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
AVXL Gain: $ 7.71 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
AVXL Gain: $ 7.75 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QL
AVXL Gain: $ 7.75 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QL
AVXL Gain: $ 7.75 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QL_DB2
AVXL Gain: $ 7.75 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QL
AVXL Gain: $ 7.8 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR
AVXL Gain: $ 7.8 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
AVXL Gain: $ 7.89 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV
AVXL Gain: $ 7.95 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AV
AVXL Gain: $ 7.97 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AV
AVXL Gain: $ 7.98 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AV
AVXL Gain: $ 8.06 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AL
AVXL Gain: $ 8.08 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IR2
AVXL Gain: $ 8.08 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_IR2
AVXL Gain: $ 8.1 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AL
AVXL Gain: $ 8.11 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_AV
AVXL Gain: $ 8.11 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_AV
AVXL Gain: $ 8.11 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_AV_DB1
AVXL Gain: $ 8.13 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_RV
AVXL Gain: $ 8.16 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AL
AVXL Gain: $ 8.2 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AV
AVXL Gain: $ 8.2 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AV_DB1
AVXL Gain: $ 8.25 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5
AVXL Gain: $ 8.25 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_DB8
AVXL Gain: $ 8.25 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT
AVXL Gain: $ 8.25 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QL
AVXL Gain: $ 8.25 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QL
AVXL Gain: $ 8.25 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR
AVXL Gain: $ 8.26 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AL
AVXL Gain: $ 8.26 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AL
AVXL Gain: $ 8.26 Win %: 50.00 in 4 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AL_DB1
AVXL Gain: $ 8.49 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_TR
AVXL Gain: $ 8.49 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
AVXL Gain: $ 8.49 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
AVXL Gain: $ 8.61 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_HM
AVXL Gain: $ 8.61 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_HM_AV
AVXL Gain: $ 8.61 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB5_OS5_CB5_CS5_HM_TR
AVXL Gain: $ 8.65 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AV
AVXL Gain: $ 8.7 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AL
AVXL Gain: $ 8.7 Win %: 50.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AL_DB2
AVXL Gain: $ 8.74 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_AV
AVXL Gain: $ 8.74 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_AV
AVXL Gain: $ 8.74 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB3_OS3_CB5_CS5_RV_AV_DB2
AVXL Gain: $ 8.8 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AL
AVXL Gain: $ 8.83 Win %: 66.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV
AVXL Gain: $ 8.91 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV
AVXL Gain: $ 9.01 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM
AVXL Gain: $ 9.01 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM
AVXL Gain: $ 9.01 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_TR
AVXL Gain: $ 9.01 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_TR
AVXL Gain: $ 9.01 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_TR_DB2
AVXL Gain: $ 9.13 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AV
AVXL Gain: $ 9.13 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AV
AVXL Gain: $ 9.13 Win %: 75.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AV_DB2
AVXL Gain: $ 9.31 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM
AVXL Gain: $ 9.31 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_AV
AVXL Gain: $ 9.31 Win %: 100.00 in 3 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_TR
AVXL Gain: $ 9.41 Win %: 100.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_AV
AVXL Gain: $ 9.41 Win %: 100.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_AV
AVXL Gain: $ 9.41 Win %: 100.00 in 4 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_AV_DB2
