BIDU Gain: $ -203.88 Win %: 42.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -203.88 Win %: 42.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -203.88 Win %: 42.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP_DB2
BIDU Gain: $ -203.88 Win %: 42.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -203.88 Win %: 42.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -203.88 Win %: 42.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP_DB2
BIDU Gain: $ -202.2 Win %: 43.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -202.19 Win %: 42.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -202.19 Win %: 42.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -201.66 Win %: 43.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -200.48 Win %: 44.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -200.2 Win %: 44.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -200.2 Win %: 44.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -199.06 Win %: 42.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -198.7 Win %: 44.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -198.67 Win %: 44.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -198.67 Win %: 44.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -197.9 Win %: 43.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -197.31 Win %: 44.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -194.69 Win %: 45.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -194.38 Win %: 45.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -194.14 Win %: 43.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -193.67 Win %: 43.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -193.67 Win %: 43.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -193.56 Win %: 45.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -193.48 Win %: 44.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -193.48 Win %: 44.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -189.56 Win %: 44.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -185.27 Win %: 48.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -181.86 Win %: 49.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -181.86 Win %: 49.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -180.95 Win %: 42.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -180.95 Win %: 42.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -180.95 Win %: 42.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP_DB1
BIDU Gain: $ -178.87 Win %: 42.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -178.55 Win %: 43.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -176.22 Win %: 43.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -176.06 Win %: 43.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -174.17 Win %: 44.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -172.45 Win %: 44.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -171.81 Win %: 44.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -169.72 Win %: 49.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -169.24 Win %: 46.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -169.17 Win %: 44.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -164.83 Win %: 43.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -155.53 Win %: 48.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -154.32 Win %: 50.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -153.68 Win %: 51.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -152.27 Win %: 45.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -152.17 Win %: 49.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -150.45 Win %: 50.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -150.45 Win %: 50.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -149.44 Win %: 50.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -149.11 Win %: 50.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -148.68 Win %: 50.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -148.02 Win %: 50.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -148.02 Win %: 50.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -148.02 Win %: 50.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP_DB1
BIDU Gain: $ -146.72 Win %: 50.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -146.4 Win %: 50.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -145.94 Win %: 50.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -144.59 Win %: 50.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -144.04 Win %: 45.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -143.83 Win %: 50.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -143.38 Win %: 53.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -143.36 Win %: 49.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -142.35 Win %: 48.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -140.29 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ -140.27 Win %: 49.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -139.07 Win %: 49.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -138.89 Win %: 47.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -138.89 Win %: 47.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -138.89 Win %: 47.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP_DB2
BIDU Gain: $ -138.89 Win %: 47.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -138.89 Win %: 47.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP_DB2
BIDU Gain: $ -138.6 Win %: 48.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -138.1 Win %: 50.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -138.09 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ -137.84 Win %: 49.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -136.88 Win %: 49.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -136.39 Win %: 47.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -136.39 Win %: 47.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -136.25 Win %: 38.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -135.95 Win %: 49.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -135.41 Win %: 48.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -135.41 Win %: 48.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -135.19 Win %: 49.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -134.61 Win %: 48.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -134.61 Win %: 48.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -134.61 Win %: 48.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -134.61 Win %: 48.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -133.19 Win %: 47.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -132.91 Win %: 49.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -131.39 Win %: 47.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -130.47 Win %: 39.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -130.47 Win %: 39.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -128.88 Win %: 49.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -128.88 Win %: 49.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -128.27 Win %: 42.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -127.56 Win %: 40.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
BIDU Gain: $ -127.23 Win %: 47.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -125.96 Win %: 51.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -125.66 Win %: 43.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -125.52 Win %: 43.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -125.52 Win %: 56.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ -125.23 Win %: 43.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -125.15 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -124.27 Win %: 43.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -124.22 Win %: 48.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -123.73 Win %: 45.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -123.54 Win %: 48.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -123.54 Win %: 49.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -123.54 Win %: 49.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -122.87 Win %: 39.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -122.87 Win %: 39.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BIDU Gain: $ -122.87 Win %: 39.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -122.23 Win %: 48.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -121.65 Win %: 43.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -120.96 Win %: 47.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -120.48 Win %: 51.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -119.25 Win %: 43.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -118.96 Win %: 49.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -118.5 Win %: 42.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR2
BIDU Gain: $ -118.08 Win %: 44.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -117.71 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -117.38 Win %: 44.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -116.67 Win %: 41.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR2
BIDU Gain: $ -114.2 Win %: 43.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -113.86 Win %: 45.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -113.61 Win %: 42.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR2
BIDU Gain: $ -113.58 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -113.58 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -113.11 Win %: 47.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR2
BIDU Gain: $ -112.97 Win %: 43.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -112.23 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -111.42 Win %: 44.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -111.38 Win %: 44.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -111.07 Win %: 42.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR2
BIDU Gain: $ -110.87 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -110.74 Win %: 50.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -110.59 Win %: 50.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -110.43 Win %: 44.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -110.35 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -110.2 Win %: 43.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -110.11 Win %: 44.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -109.72 Win %: 42.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -109.72 Win %: 43.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR2
BIDU Gain: $ -109.26 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -109.09 Win %: 51.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -108.97 Win %: 44.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -108.54 Win %: 45.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -108.54 Win %: 45.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -108.54 Win %: 45.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP_DB2
BIDU Gain: $ -108.22 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -108.22 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -108.22 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -108.22 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -107.71 Win %: 45.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -107.48 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -107.48 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -107.48 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -107.48 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -107.35 Win %: 52.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -107.11 Win %: 50.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ -106.93 Win %: 41.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -106.93 Win %: 41.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -106.93 Win %: 41.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
BIDU Gain: $ -106.93 Win %: 41.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -106.53 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -106.53 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -106.41 Win %: 50.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -106.35 Win %: 44.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -106.2 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ -105.52 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -105.4 Win %: 50.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -104.33 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ -103.78 Win %: 40.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -103.73 Win %: 40.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ -103.73 Win %: 40.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ -103.56 Win %: 50.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -103.44 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ -103.4 Win %: 41.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ -103.4 Win %: 41.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -103.4 Win %: 41.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -103.34 Win %: 65.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -103.24 Win %: 51.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -103 Win %: 57.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ -102.96 Win %: 50.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -102.69 Win %: 50.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -102.49 Win %: 51.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -102.4 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ -102.4 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ -102.4 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ -102.24 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -101.92 Win %: 51.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -101.75 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ -101.75 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ -101.15 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -101.1 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ -101.1 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ -101.1 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ -100.93 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ -100.86 Win %: 38.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ -100.72 Win %: 41.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ -100.47 Win %: 44.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -100.41 Win %: 41.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR2
BIDU Gain: $ -99.32 Win %: 51.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -99.21 Win %: 55.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -97.69 Win %: 50.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -97.65 Win %: 54.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -95.97 Win %: 50.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -95.42 Win %: 51.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -95.04 Win %: 51.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -95.04 Win %: 51.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -95.04 Win %: 51.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP_DB1
BIDU Gain: $ -94.54 Win %: 51.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -93.67 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -93.56 Win %: 50.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BIDU Gain: $ -92.96 Win %: 51.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -92.88 Win %: 51.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -91 Win %: 51.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -89.94 Win %: 69.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BIDU Gain: $ -89.72 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -88.79 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -85.43 Win %: 42.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -85.43 Win %: 42.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -85.43 Win %: 42.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
BIDU Gain: $ -85.43 Win %: 42.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -85.14 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -84.61 Win %: 57.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ -82.83 Win %: 48.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -82.83 Win %: 48.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -82.83 Win %: 48.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP_DB2
BIDU Gain: $ -80.2 Win %: 60.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BIDU Gain: $ -80.1 Win %: 48.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -79.87 Win %: 49.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -77.85 Win %: 56.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -77.35 Win %: 42.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BIDU Gain: $ -77.35 Win %: 42.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BIDU Gain: $ -77.34 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -76.44 Win %: 48.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -76.17 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -75.4 Win %: 48.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -75.13 Win %: 49.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -75.13 Win %: 49.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -74.28 Win %: 48.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -72.63 Win %: 48.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -71.87 Win %: 56.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ -71.04 Win %: 73.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -69.48 Win %: 47.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -67.49 Win %: 48.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -66.66 Win %: 51.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -66.29 Win %: 49.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ -66.26 Win %: 49.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -66.02 Win %: 45.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ -65.98 Win %: 46.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ -64.79 Win %: 59.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ -64.66 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BIDU Gain: $ -64.57 Win %: 48.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -62.86 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -61.8 Win %: 48.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -61.3 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -61.21 Win %: 53.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
BIDU Gain: $ -60.66 Win %: 49.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -60.45 Win %: 49.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -60.17 Win %: 72.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -59.95 Win %: 47.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -59.95 Win %: 47.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -59.95 Win %: 47.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -59.5 Win %: 50.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -59.32 Win %: 49.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -58.32 Win %: 57.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -58.13 Win %: 49.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -57.94 Win %: 48.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -57.61 Win %: 50.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -57.61 Win %: 50.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -57.55 Win %: 49.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -56.89 Win %: 50.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -56.77 Win %: 54.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -56.7 Win %: 49.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -55.19 Win %: 50.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -54.97 Win %: 52.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -53.87 Win %: 53.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BIDU Gain: $ -53.17 Win %: 50.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -50.83 Win %: 68.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -48.15 Win %: 77.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -47.63 Win %: 77.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP_DB2
BIDU Gain: $ -47.63 Win %: 77.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QP
BIDU Gain: $ -47.63 Win %: 77.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QP_DB2
BIDU Gain: $ -46.65 Win %: 54.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -46.05 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -46.05 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -46.05 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -45.84 Win %: 76.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -45.84 Win %: 76.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP_DB1
BIDU Gain: $ -45.74 Win %: 55.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -45.65 Win %: 53.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ -45.05 Win %: 43.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -45.05 Win %: 43.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ -45.05 Win %: 43.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -44.92 Win %: 54.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -44.72 Win %: 55.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -44.67 Win %: 54.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BIDU Gain: $ -44.51 Win %: 50.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -44.21 Win %: 50.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -44.1 Win %: 50.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -43.57 Win %: 56.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -43.37 Win %: 56.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV_DB1
BIDU Gain: $ -43.06 Win %: 50.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -43.06 Win %: 50.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -43.04 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT
BIDU Gain: $ -41.73 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -41.73 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -41.45 Win %: 50.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -40.87 Win %: 79.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -40.87 Win %: 79.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -40.71 Win %: 80.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -40.6 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -40.6 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP_DB2
BIDU Gain: $ -40.6 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -40.6 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -40.6 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP_DB2
BIDU Gain: $ -40.35 Win %: 52.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -40.35 Win %: 52.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -40.2 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -39.95 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -39.53 Win %: 80.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -39.53 Win %: 80.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QP
BIDU Gain: $ -39.46 Win %: 56.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -39.22 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -39.21 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -38.91 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -38.91 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -38.84 Win %: 50.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -38.83 Win %: 51.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -38.75 Win %: 53.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -38.43 Win %: 79.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QP
BIDU Gain: $ -38.38 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -38.2 Win %: 43.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -38.2 Win %: 43.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ -38.08 Win %: 54.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -37.86 Win %: 51.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -37.84 Win %: 81.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -37.84 Win %: 81.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QP
BIDU Gain: $ -37.83 Win %: 50.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ -37.81 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -37.81 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -37.61 Win %: 55.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -37.05 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -37.05 Win %: 56.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -36.55 Win %: 54.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -36.55 Win %: 54.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -36.5 Win %: 57.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -36.39 Win %: 51.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BIDU Gain: $ -36.3 Win %: 54.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -36.16 Win %: 53.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -36.13 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -35.75 Win %: 56.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -35.75 Win %: 56.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -35.31 Win %: 54.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -35.23 Win %: 82.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -35.14 Win %: 82.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -35.06 Win %: 82.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -34.98 Win %: 54.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -34.88 Win %: 67.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
BIDU Gain: $ -34.82 Win %: 54.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -34.82 Win %: 54.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -34.27 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ -34.07 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -33.78 Win %: 56.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -33.76 Win %: 44.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
BIDU Gain: $ -33.67 Win %: 57.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -33.56 Win %: 54.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR2
BIDU Gain: $ -31.98 Win %: 79.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QP
BIDU Gain: $ -31.56 Win %: 54.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -31.5 Win %: 53.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -31.34 Win %: 54.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -31.3 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -30.83 Win %: 55.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -29.41 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -29.41 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -29.41 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP_DB2
BIDU Gain: $ -29.24 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -28.19 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ -27.87 Win %: 46.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ -27.27 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -27.09 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -26.7 Win %: 78.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QP
BIDU Gain: $ -26.14 Win %: 57.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -24.55 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -24.55 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -24.01 Win %: 55.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -24.01 Win %: 63.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ -23.96 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -23.86 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -23.31 Win %: 58.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ -22.94 Win %: 60.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BIDU Gain: $ -22.89 Win %: 58.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ -22.18 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -21.01 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -21.01 Win %: 54.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -20.73 Win %: 53.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -20.37 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -19.87 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -19.87 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -19.2 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ -18.97 Win %: 57.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BIDU Gain: $ -18.91 Win %: 56.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -18.88 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ -18.73 Win %: 54.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -18.19 Win %: 83.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BIDU Gain: $ -18.19 Win %: 83.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP_DB2
BIDU Gain: $ -18.02 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ -17.96 Win %: 57.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ -16.8 Win %: 55.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -16.8 Win %: 55.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -16.75 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ -14.53 Win %: 55.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -14.39 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ -13.83 Win %: 81.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BIDU Gain: $ -13.22 Win %: 45.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ -13.14 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ -12.81 Win %: 43.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ -12.74 Win %: 55.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -12.07 Win %: 53.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -12.06 Win %: 44.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ -11.13 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -10.42 Win %: 45.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ -10.12 Win %: 41.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
BIDU Gain: $ -9.8 Win %: 45.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ -9.8 Win %: 45.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR2
BIDU Gain: $ -9.8 Win %: 45.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ -9.55 Win %: 41.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
BIDU Gain: $ -8.99 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ -8.94 Win %: 83.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BIDU Gain: $ -8.72 Win %: 83.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BIDU Gain: $ -8.72 Win %: 83.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BIDU Gain: $ -8.54 Win %: 62.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ -8.52 Win %: 83.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BIDU Gain: $ -8.25 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ -7.55 Win %: 58.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -6.78 Win %: 64.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ -6.53 Win %: 64.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ -6.45 Win %: 56.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -6.45 Win %: 56.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -5.32 Win %: 98.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR_DB1
BIDU Gain: $ -5.23 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ -4.84 Win %: 41.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
BIDU Gain: $ -4.76 Win %: 47.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -4.76 Win %: 47.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -4.37 Win %: 57.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -3.73 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ -3.59 Win %: 53.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
BIDU Gain: $ -3.48 Win %: 45.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ -3.2 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ -3.06 Win %: 47.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -2.68 Win %: 48.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -2.01 Win %: 50.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -1.86 Win %: 47.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -1.49 Win %: 50.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ -1.47 Win %: 47.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -0.88 Win %: 55.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ -0.88 Win %: 55.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ -0.69 Win %: 41.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
BIDU Gain: $ -0.69 Win %: 51.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ -0.69 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ -0.45 Win %: 48.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -0.45 Win %: 48.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ -0.25 Win %: 51.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ -0.2 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ -0.01 Win %: 53.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
BIDU Gain: $ -0.01 Win %: 55.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 0 Win %: 100.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BIDU Gain: $ 0 Win %: 100.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR_DB2
BIDU Gain: $ 0 Win %: 100.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR_DB2
BIDU Gain: $ 0 Win %: 100.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR_DB2
BIDU Gain: $ 0 Win %: 100.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR_DB2
BIDU Gain: $ 0 Win %: 100.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR_DB2
BIDU Gain: $ 0 Win %: 100.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR_DB1
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Gain: $ -0.24 Win %: 43.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -1.14 Win %: 46.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_AV
Gain: $ -1.14 Win %: 46.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_AV
Gain: $ -103.4 Win %: 41.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -103.73 Win %: 40.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR2
Gain: $ -103.89 Win %: 40.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -110.91 Win %: 52.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -110.91 Win %: 52.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -114.78 Win %: 46.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -114.78 Win %: 46.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -12.06 Win %: 44.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR2
Gain: $ -12.06 Win %: 44.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
Gain: $ -120.71 Win %: 40.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -122.87 Win %: 39.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -123.72 Win %: 40.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -165.85 Win %: 41.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_PA_QP
Gain: $ -165.85 Win %: 41.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_PA_QP
Gain: $ -173.23 Win %: 45.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -173.23 Win %: 45.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -21.25 Win %: 49.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_PA
Gain: $ -21.67 Win %: 49.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_PA
Gain: $ -22.19 Win %: 53.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -22.96 Win %: 50.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_PA_AV
Gain: $ -22.96 Win %: 50.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_PA_AV
Gain: $ -24.16 Win %: 55.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_PA
Gain: $ -24.16 Win %: 55.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_PA
Gain: $ -25.45 Win %: 54.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -25.45 Win %: 54.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -26.12 Win %: 56.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -26.45 Win %: 53.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -32.63 Win %: 51.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5
Gain: $ -36.92 Win %: 61.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -37 Win %: 61.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_QP
Gain: $ -37.98 Win %: 54.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ -38.2 Win %: 43.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
Gain: $ -38.2 Win %: 43.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ -43.92 Win %: 53.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_PA_QP
Gain: $ -44.16 Win %: 53.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_PA_QP
Gain: $ -44.31 Win %: 58.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_QP_IR3
Gain: $ -44.55 Win %: 58.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_QP_IR3
Gain: $ -46.45 Win %: 49.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_RV_QP
Gain: $ -46.69 Win %: 49.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -49.05 Win %: 48.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -59.95 Win %: 47.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ -67.88 Win %: 47.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -67.88 Win %: 47.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -71.74 Win %: 47.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -77.35 Win %: 42.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -81.61 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -81.61 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -82.66 Win %: 48.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -82.66 Win %: 48.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -85.83 Win %: 41.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -9.08 Win %: 53.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 100.29 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 100.29 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 100.51 Win %: 52.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_PA_TR
Gain: $ 100.51 Win %: 52.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_PA_TR
Gain: $ 102.14 Win %: 53.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 102.14 Win %: 53.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 103.05 Win %: 55.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_SS
Gain: $ 103.11 Win %: 63.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 103.11 Win %: 63.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 103.29 Win %: 55.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_SS
Gain: $ 104.84 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
Gain: $ 104.84 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
Gain: $ 105.86 Win %: 59.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 107.24 Win %: 47.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
Gain: $ 108.68 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 108.68 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 110.72 Win %: 47.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
Gain: $ 112.22 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5
Gain: $ 112.22 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
Gain: $ 112.54 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 114.22 Win %: 49.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_TR
Gain: $ 114.46 Win %: 49.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_TR
Gain: $ 114.71 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
Gain: $ 115.02 Win %: 59.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 115.15 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 115.15 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 116.67 Win %: 53.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 117.63 Win %: 61.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 117.67 Win %: 62.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 117.8 Win %: 63.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 117.8 Win %: 63.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 117.91 Win %: 59.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 117.93 Win %: 52.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_RV_TR
Gain: $ 118.35 Win %: 59.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 118.35 Win %: 59.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 119.26 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 119.26 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 12.29 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 12.74 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 12.81 Win %: 50.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 122.48 Win %: 64.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
Gain: $ 123.26 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 123.26 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 124.28 Win %: 64.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 124.28 Win %: 64.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 125.14 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 125.14 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 125.53 Win %: 52.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ 125.53 Win %: 52.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ 127.04 Win %: 61.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 127.04 Win %: 61.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 128.63 Win %: 59.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ 128.63 Win %: 59.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ 130.67 Win %: 61.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 132.78 Win %: 65.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 135.54 Win %: 64.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 135.54 Win %: 64.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 139.07 Win %: 59.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 140.65 Win %: 67.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 140.65 Win %: 67.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 143.11 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 143.11 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 143.86 Win %: 65.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 144.43 Win %: 51.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 146.3 Win %: 52.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 157.34 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 16.59 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
Gain: $ 16.59 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
Gain: $ 162.2 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 162.33 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 162.33 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 164.03 Win %: 64.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 171.46 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 173.38 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 174.82 Win %: 56.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 18.78 Win %: 53.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 182.28 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 182.3 Win %: 68.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 19.81 Win %: 43.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5
Gain: $ 2.76 Win %: 47.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_IR3
Gain: $ 20.13 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 20.34 Win %: 47.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 20.35 Win %: 44.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 20.57 Win %: 44.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_QL
Gain: $ 20.96 Win %: 58.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 20.96 Win %: 58.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 22.69 Win %: 43.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 22.76 Win %: 50.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 22.76 Win %: 56.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_PA_TR
Gain: $ 23.61 Win %: 50.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_AL
Gain: $ 23.9 Win %: 56.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 23.9 Win %: 56.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 24.15 Win %: 42.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 24.84 Win %: 58.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_PA_TR
Gain: $ 24.86 Win %: 50.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 24.86 Win %: 50.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ 26.54 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 26.91 Win %: 44.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
Gain: $ 26.91 Win %: 44.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
Gain: $ 28.73 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 3 Win %: 47.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_IR3
Gain: $ 3.09 Win %: 58.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 3.31 Win %: 58.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_LI
Gain: $ 30.6 Win %: 56.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_PA_AV
Gain: $ 30.87 Win %: 56.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_PA_AV
Gain: $ 33.3 Win %: 47.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 34.38 Win %: 56.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 34.99 Win %: 47.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 34.99 Win %: 47.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 35.11 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 35.13 Win %: 52.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 35.13 Win %: 52.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 36.34 Win %: 58.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 36.34 Win %: 58.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 36.53 Win %: 47.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_DB10
Gain: $ 36.77 Win %: 47.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4
Gain: $ 36.77 Win %: 47.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_DB10
Gain: $ 4.35 Win %: 71.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_VI
Gain: $ 4.35 Win %: 71.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 41.32 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 41.32 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 46.12 Win %: 50.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 46.69 Win %: 62.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 47.55 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 51 Win %: 48.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 51.33 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 51.33 Win %: 57.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 51.99 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 53.53 Win %: 48.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR2
Gain: $ 53.53 Win %: 48.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
Gain: $ 54.74 Win %: 56.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 54.98 Win %: 56.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_RV
Gain: $ 55.03 Win %: 45.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 55.63 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 56.59 Win %: 53.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AV
Gain: $ 56.59 Win %: 53.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 58.51 Win %: 59.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 59.04 Win %: 59.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 60.42 Win %: 50.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 60.42 Win %: 50.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 61.44 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 65.36 Win %: 52.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ 65.36 Win %: 52.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ 65.52 Win %: 49.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 65.9 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 66.16 Win %: 53.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 69.29 Win %: 60.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 69.3 Win %: 62.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 69.3 Win %: 62.00 in 67 days with algo TB1_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 72.12 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 72.66 Win %: 49.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB5_CS5_TR_IR3
Gain: $ 72.9 Win %: 49.00 in 67 days with algo TB5_HL_LO_QM_OB5_OS5_CB4_CS4_TR_IR3
Gain: $ 73.28 Win %: 54.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 75.58 Win %: 49.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 75.58 Win %: 49.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 78.45 Win %: 61.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ 78.45 Win %: 61.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ 79.53 Win %: 51.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 79.53 Win %: 51.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 82.51 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 83.18 Win %: 59.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 84.96 Win %: 58.00 in 67 days with algo TB1_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 86.72 Win %: 62.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 86.72 Win %: 62.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 87.51 Win %: 62.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 89.28 Win %: 56.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 91.1 Win %: 52.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 91.1 Win %: 52.00 in 99 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
Gain: $ 91.83 Win %: 62.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 93.63 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 93.63 Win %: 55.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ 94.28 Win %: 61.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 94.28 Win %: 61.00 in 88 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 94.45 Win %: 56.00 in 88 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 95.29 Win %: 62.00 in 88 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 0.04 Win %: 48.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ 0.04 Win %: 48.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ 0.11 Win %: 43.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
BIDU Gain: $ 0.32 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 0.32 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 0.83 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 1.11 Win %: 48.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BIDU Gain: $ 1.22 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
BIDU Gain: $ 1.45 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 1.64 Win %: 58.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
BIDU Gain: $ 2.13 Win %: 51.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 2.24 Win %: 51.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 2.24 Win %: 51.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 2.3 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 2.3 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 2.31 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 3.04 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 3.04 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 3.04 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 3.04 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 3.09 Win %: 53.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 3.59 Win %: 51.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 3.63 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 3.63 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 3.63 Win %: 66.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 3.84 Win %: 54.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
BIDU Gain: $ 4.03 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 4.87 Win %: 53.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM
BIDU Gain: $ 5.41 Win %: 50.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 5.42 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 5.42 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 5.53 Win %: 47.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 6.19 Win %: 51.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 6.82 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 6.82 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 6.92 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 6.92 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 6.92 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV_DB2
BIDU Gain: $ 6.92 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 6.92 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV_DB2
BIDU Gain: $ 6.93 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 6.93 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 6.97 Win %: 53.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 6.97 Win %: 53.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 7.08 Win %: 49.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 8.14 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 8.14 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 8.49 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 8.49 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 8.95 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 8.95 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 9.04 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BIDU Gain: $ 9.36 Win %: 52.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 9.38 Win %: 58.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 9.39 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BIDU Gain: $ 9.64 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 9.64 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 9.97 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 10.24 Win %: 48.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 10.39 Win %: 54.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 10.75 Win %: 67.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 10.89 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 10.89 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
BIDU Gain: $ 10.89 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 11.89 Win %: 53.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 12.29 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 12.74 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 12.74 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 12.74 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 12.86 Win %: 49.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 13.82 Win %: 48.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 14.22 Win %: 49.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
BIDU Gain: $ 14.25 Win %: 53.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 14.25 Win %: 53.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 14.54 Win %: 48.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 14.65 Win %: 50.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 14.79 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 15.25 Win %: 49.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 15.71 Win %: 50.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 15.75 Win %: 47.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
BIDU Gain: $ 15.76 Win %: 55.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 16.85 Win %: 50.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 16.85 Win %: 50.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 16.85 Win %: 50.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV_DB2
BIDU Gain: $ 17.32 Win %: 64.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 18.04 Win %: 62.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 19.02 Win %: 44.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 19.02 Win %: 44.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 19.02 Win %: 44.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5
BIDU Gain: $ 19.02 Win %: 44.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
BIDU Gain: $ 19.02 Win %: 44.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 19.63 Win %: 42.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 19.63 Win %: 42.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 20.09 Win %: 43.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 20.24 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 20.24 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 20.24 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
BIDU Gain: $ 20.24 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 20.25 Win %: 45.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 21.27 Win %: 50.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
BIDU Gain: $ 21.47 Win %: 50.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
BIDU Gain: $ 21.6 Win %: 56.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 21.66 Win %: 48.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 22.02 Win %: 59.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 22.09 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 22.23 Win %: 100.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR_DB2
BIDU Gain: $ 22.5 Win %: 58.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 23.01 Win %: 55.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
BIDU Gain: $ 23.33 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 23.45 Win %: 50.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
BIDU Gain: $ 23.65 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 23.65 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 23.65 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 24.15 Win %: 42.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 24.15 Win %: 42.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 24.5 Win %: 53.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 25.03 Win %: 47.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 25.86 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 26.05 Win %: 44.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 26.27 Win %: 49.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 26.45 Win %: 50.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 26.5 Win %: 55.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BIDU Gain: $ 26.54 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 26.54 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 26.77 Win %: 51.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
BIDU Gain: $ 26.91 Win %: 44.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 27.29 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 27.56 Win %: 43.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
BIDU Gain: $ 27.66 Win %: 46.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 28.19 Win %: 46.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 28.73 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 28.73 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 28.73 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 29.27 Win %: 53.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 29.27 Win %: 53.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 29.84 Win %: 53.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BIDU Gain: $ 29.84 Win %: 54.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 29.95 Win %: 54.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 30 Win %: 54.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 30.26 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
BIDU Gain: $ 30.35 Win %: 47.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
BIDU Gain: $ 30.42 Win %: 47.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 30.42 Win %: 47.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 30.59 Win %: 55.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 30.77 Win %: 54.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 30.79 Win %: 47.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 30.79 Win %: 47.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
BIDU Gain: $ 30.79 Win %: 47.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 30.8 Win %: 56.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 30.81 Win %: 62.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 30.96 Win %: 65.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BIDU Gain: $ 31 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 31.16 Win %: 47.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 31.35 Win %: 54.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 31.54 Win %: 55.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 31.68 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 31.98 Win %: 47.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 32.17 Win %: 47.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 32.7 Win %: 55.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 32.7 Win %: 55.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 32.95 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 32.95 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 33.01 Win %: 51.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 33.27 Win %: 67.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 33.3 Win %: 47.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 33.3 Win %: 47.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 33.3 Win %: 47.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 33.39 Win %: 53.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 33.54 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 33.88 Win %: 48.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 33.88 Win %: 48.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 34.02 Win %: 55.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 34.55 Win %: 51.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 34.57 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 34.57 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 34.65 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 34.86 Win %: 58.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 34.99 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 34.99 Win %: 64.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 35.27 Win %: 48.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 35.33 Win %: 53.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 35.57 Win %: 56.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 35.8 Win %: 61.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 35.83 Win %: 66.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 36.08 Win %: 53.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 36.34 Win %: 58.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 36.34 Win %: 59.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 36.34 Win %: 59.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
BIDU Gain: $ 36.34 Win %: 59.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 36.41 Win %: 51.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 36.58 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 36.58 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 36.58 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV_DB2
BIDU Gain: $ 36.67 Win %: 49.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
BIDU Gain: $ 36.77 Win %: 51.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 36.9 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 37.15 Win %: 62.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 37.16 Win %: 51.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 37.16 Win %: 53.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 37.39 Win %: 53.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 37.39 Win %: 53.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 37.7 Win %: 54.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 37.85 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 38.06 Win %: 61.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 38.2 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 38.2 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 38.2 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 38.31 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 38.31 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 38.31 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 38.4 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 38.53 Win %: 55.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 38.62 Win %: 51.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 38.69 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 38.69 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 38.86 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 38.86 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 38.89 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IR2
BIDU Gain: $ 38.91 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 39.17 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 39.24 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 39.32 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 39.63 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 39.73 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 39.86 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 39.94 Win %: 54.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 39.94 Win %: 54.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 40 Win %: 50.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 40.02 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 40.02 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 40.2 Win %: 54.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 40.59 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BIDU Gain: $ 40.59 Win %: 61.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 40.74 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 40.75 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 40.92 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 40.96 Win %: 60.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 41.03 Win %: 56.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 41.11 Win %: 59.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 41.33 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 41.4 Win %: 59.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 41.6 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 41.9 Win %: 49.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 41.94 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 41.95 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 41.95 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 42.01 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 42.05 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 42.47 Win %: 55.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 42.47 Win %: 55.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 42.58 Win %: 50.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 42.58 Win %: 50.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 42.64 Win %: 60.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 42.74 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 42.74 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 42.74 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 42.77 Win %: 59.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 42.8 Win %: 50.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 42.8 Win %: 57.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 42.8 Win %: 60.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 42.8 Win %: 60.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 42.92 Win %: 61.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 43.42 Win %: 58.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 43.78 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 44.17 Win %: 58.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 44.17 Win %: 58.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 44.17 Win %: 58.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV_DB1
BIDU Gain: $ 44.32 Win %: 51.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 44.67 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 44.67 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 44.68 Win %: 55.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 44.76 Win %: 58.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 44.76 Win %: 58.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 45.04 Win %: 51.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 45.19 Win %: 46.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 45.28 Win %: 57.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 45.53 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BIDU Gain: $ 45.83 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 46.12 Win %: 50.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 46.12 Win %: 50.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 46.12 Win %: 50.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 46.25 Win %: 58.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 46.39 Win %: 50.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 46.61 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 46.63 Win %: 60.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 47.32 Win %: 60.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
BIDU Gain: $ 47.49 Win %: 50.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 48.15 Win %: 50.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 48.15 Win %: 50.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 48.32 Win %: 50.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 48.51 Win %: 51.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 48.71 Win %: 60.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BIDU Gain: $ 48.73 Win %: 59.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 48.82 Win %: 50.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 49.81 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
BIDU Gain: $ 49.91 Win %: 56.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 49.96 Win %: 50.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 50.04 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 50.19 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 50.21 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
BIDU Gain: $ 50.23 Win %: 50.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 50.34 Win %: 53.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 50.36 Win %: 48.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 50.36 Win %: 48.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 50.36 Win %: 48.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR2
BIDU Gain: $ 50.36 Win %: 48.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 50.82 Win %: 61.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 51.11 Win %: 60.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 51.41 Win %: 60.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 51.42 Win %: 60.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 51.61 Win %: 60.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 51.65 Win %: 58.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 51.86 Win %: 52.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 51.99 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 51.99 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 52.2 Win %: 60.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 52.33 Win %: 59.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 52.33 Win %: 59.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 52.33 Win %: 59.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL_DB1
BIDU Gain: $ 52.74 Win %: 46.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 53.51 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 53.51 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 53.51 Win %: 61.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 53.53 Win %: 48.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 53.53 Win %: 48.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 53.61 Win %: 60.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 53.74 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 53.77 Win %: 62.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 53.93 Win %: 56.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 53.97 Win %: 57.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT
BIDU Gain: $ 53.97 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 54.19 Win %: 59.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 54.41 Win %: 59.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 54.7 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
BIDU Gain: $ 54.75 Win %: 56.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
BIDU Gain: $ 54.92 Win %: 61.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL
BIDU Gain: $ 55.03 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 55.03 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 55.03 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 55.15 Win %: 47.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
BIDU Gain: $ 55.25 Win %: 57.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 55.26 Win %: 57.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
BIDU Gain: $ 55.39 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 55.63 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 55.63 Win %: 46.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 55.77 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 55.9 Win %: 60.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 56.1 Win %: 53.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 56.11 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 56.11 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 56.11 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV_DB2
BIDU Gain: $ 56.11 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 56.11 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 56.11 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV_DB2
BIDU Gain: $ 56.45 Win %: 56.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 56.56 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 56.68 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 56.68 Win %: 60.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 56.69 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 56.94 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 57.37 Win %: 56.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 57.61 Win %: 59.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 57.7 Win %: 61.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 57.73 Win %: 61.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 57.77 Win %: 57.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_VI
BIDU Gain: $ 57.92 Win %: 48.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
BIDU Gain: $ 58.02 Win %: 49.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
BIDU Gain: $ 58.07 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 58.16 Win %: 58.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 58.16 Win %: 58.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 58.39 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 58.83 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 58.83 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 59.08 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 59.15 Win %: 57.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 59.31 Win %: 59.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 59.4 Win %: 54.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 59.41 Win %: 54.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 59.45 Win %: 59.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 59.85 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 59.97 Win %: 56.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 60.07 Win %: 54.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 60.11 Win %: 56.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 60.11 Win %: 56.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 60.23 Win %: 58.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 60.24 Win %: 54.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 60.24 Win %: 58.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 60.46 Win %: 54.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 60.46 Win %: 54.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 60.46 Win %: 54.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 60.46 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 60.46 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 60.69 Win %: 59.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 60.72 Win %: 52.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 60.72 Win %: 59.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 60.72 Win %: 59.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 60.73 Win %: 49.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 60.73 Win %: 49.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 60.78 Win %: 59.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 60.85 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 60.85 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 60.85 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 60.9 Win %: 57.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 61.24 Win %: 59.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 61.73 Win %: 59.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 61.76 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 61.76 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 61.83 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 61.84 Win %: 58.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 61.93 Win %: 58.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 62.24 Win %: 67.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 62.27 Win %: 59.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 62.35 Win %: 58.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 62.35 Win %: 58.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL_DB1
BIDU Gain: $ 62.46 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 62.48 Win %: 49.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BIDU Gain: $ 62.59 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 62.69 Win %: 58.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 62.7 Win %: 54.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 62.97 Win %: 64.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 63.18 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 63.18 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 63.18 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 63.19 Win %: 59.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 63.24 Win %: 53.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 63.63 Win %: 54.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 63.66 Win %: 56.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BIDU Gain: $ 63.88 Win %: 55.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 63.88 Win %: 55.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 63.92 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 64.27 Win %: 60.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 64.68 Win %: 47.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 64.68 Win %: 47.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 64.97 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 65.23 Win %: 55.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 65.23 Win %: 55.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BIDU Gain: $ 65.4 Win %: 59.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 65.4 Win %: 59.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 65.52 Win %: 49.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 65.52 Win %: 49.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 65.93 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 66.05 Win %: 49.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 66.17 Win %: 61.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 66.29 Win %: 62.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 66.3 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 66.35 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 66.67 Win %: 58.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 66.67 Win %: 58.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 66.68 Win %: 57.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 66.73 Win %: 58.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 66.79 Win %: 47.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 66.81 Win %: 50.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 66.88 Win %: 59.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 67.02 Win %: 61.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 67.02 Win %: 61.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 67.06 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 67.06 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 67.06 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 67.06 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 67.3 Win %: 58.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 67.4 Win %: 60.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 67.54 Win %: 59.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 67.58 Win %: 60.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 67.58 Win %: 60.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 67.6 Win %: 52.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 67.68 Win %: 58.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 67.75 Win %: 51.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 67.75 Win %: 60.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 68.03 Win %: 61.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 68.56 Win %: 53.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 68.68 Win %: 56.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 68.72 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 68.75 Win %: 47.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 68.75 Win %: 47.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 68.9 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 68.9 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 68.95 Win %: 60.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 69.04 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 69.28 Win %: 48.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 69.31 Win %: 61.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 69.4 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 69.48 Win %: 60.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 69.48 Win %: 66.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 69.53 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 69.54 Win %: 49.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 69.91 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 69.91 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 69.91 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL_DB2
BIDU Gain: $ 69.91 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 69.91 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 69.91 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL_DB2
BIDU Gain: $ 70.23 Win %: 48.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 70.23 Win %: 53.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 70.35 Win %: 57.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 70.54 Win %: 60.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 70.54 Win %: 60.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 70.56 Win %: 48.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 70.56 Win %: 48.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 70.56 Win %: 53.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 70.56 Win %: 53.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 70.74 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 70.79 Win %: 49.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 70.79 Win %: 49.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 70.82 Win %: 59.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 70.89 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL_DB2
BIDU Gain: $ 71.15 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 71.24 Win %: 52.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 71.27 Win %: 50.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
BIDU Gain: $ 71.34 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BIDU Gain: $ 71.42 Win %: 60.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 71.7 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 71.74 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 71.81 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 71.95 Win %: 51.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 72.11 Win %: 54.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 72.24 Win %: 58.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 72.29 Win %: 62.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 72.43 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 72.43 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 72.45 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 72.5 Win %: 48.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 72.5 Win %: 48.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 72.75 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 72.75 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 72.79 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 72.79 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 72.8 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 72.82 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 72.82 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 72.82 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 72.97 Win %: 49.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 72.97 Win %: 49.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 72.97 Win %: 49.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 72.97 Win %: 49.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 73.28 Win %: 49.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 73.28 Win %: 49.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 73.28 Win %: 49.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 73.28 Win %: 49.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 73.35 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 73.39 Win %: 53.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 73.43 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 73.63 Win %: 52.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 73.63 Win %: 52.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 73.63 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 73.66 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 73.66 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 73.68 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 73.83 Win %: 65.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 73.84 Win %: 55.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 73.89 Win %: 52.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 73.92 Win %: 66.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 74.05 Win %: 52.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 74.1 Win %: 59.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 74.21 Win %: 53.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 74.22 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 74.22 Win %: 53.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 74.26 Win %: 60.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 74.26 Win %: 60.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 74.28 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL
BIDU Gain: $ 74.3 Win %: 50.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 74.3 Win %: 50.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BIDU Gain: $ 74.42 Win %: 53.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 74.48 Win %: 61.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 74.86 Win %: 52.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 74.87 Win %: 54.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 74.91 Win %: 53.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 74.98 Win %: 58.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 75.01 Win %: 53.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 75.05 Win %: 54.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 75.05 Win %: 54.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 75.08 Win %: 54.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
BIDU Gain: $ 75.45 Win %: 59.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 75.45 Win %: 59.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 75.47 Win %: 53.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BIDU Gain: $ 75.51 Win %: 53.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 75.51 Win %: 53.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ 75.58 Win %: 49.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 75.58 Win %: 49.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 75.78 Win %: 63.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
BIDU Gain: $ 75.82 Win %: 57.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 75.87 Win %: 50.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 75.95 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 75.95 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 75.99 Win %: 65.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 76.03 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 76.03 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 76.03 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 76.03 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 76.03 Win %: 59.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 76.18 Win %: 51.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 76.23 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 76.35 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 76.38 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 76.38 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 76.44 Win %: 64.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR2
BIDU Gain: $ 76.46 Win %: 60.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 76.46 Win %: 60.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 76.46 Win %: 60.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 76.52 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 76.55 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 76.68 Win %: 56.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 76.68 Win %: 56.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 76.88 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 77.08 Win %: 62.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 77.17 Win %: 55.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 77.33 Win %: 58.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 77.5 Win %: 55.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 77.53 Win %: 58.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 77.66 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 77.69 Win %: 55.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
BIDU Gain: $ 77.71 Win %: 49.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 77.73 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 77.73 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 77.8 Win %: 60.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 77.82 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
BIDU Gain: $ 77.84 Win %: 58.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 77.85 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 77.89 Win %: 62.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 78.08 Win %: 60.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 78.37 Win %: 53.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 78.4 Win %: 59.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 78.4 Win %: 59.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 78.41 Win %: 60.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 78.87 Win %: 54.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 78.87 Win %: 54.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 78.94 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 78.94 Win %: 66.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 78.95 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 79.01 Win %: 53.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 79.16 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 79.16 Win %: 65.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 79.22 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 79.45 Win %: 54.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 79.45 Win %: 54.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 79.65 Win %: 60.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 79.65 Win %: 60.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 79.66 Win %: 60.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 79.74 Win %: 60.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR2
BIDU Gain: $ 79.81 Win %: 60.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 79.81 Win %: 60.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 79.81 Win %: 60.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR_DB1
BIDU Gain: $ 79.82 Win %: 62.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 79.96 Win %: 55.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 80.24 Win %: 53.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 80.25 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 80.25 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 80.26 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 80.26 Win %: 60.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 80.77 Win %: 60.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 80.81 Win %: 53.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 80.83 Win %: 68.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IR2
BIDU Gain: $ 81.03 Win %: 62.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 81.14 Win %: 56.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 81.14 Win %: 56.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 81.36 Win %: 54.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 81.51 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BIDU Gain: $ 81.52 Win %: 54.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 81.61 Win %: 63.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 81.69 Win %: 44.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
BIDU Gain: $ 81.7 Win %: 52.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 81.89 Win %: 60.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 82.14 Win %: 54.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BIDU Gain: $ 82.26 Win %: 44.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
BIDU Gain: $ 82.28 Win %: 53.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 82.37 Win %: 66.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 82.48 Win %: 58.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 82.49 Win %: 56.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 82.49 Win %: 56.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BIDU Gain: $ 82.56 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 82.6 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 82.6 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 82.64 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 82.64 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 82.64 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 82.64 Win %: 50.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 82.73 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 82.79 Win %: 55.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
BIDU Gain: $ 83.03 Win %: 54.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 83.09 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 83.15 Win %: 60.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
BIDU Gain: $ 83.36 Win %: 49.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 83.6 Win %: 59.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 83.64 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 83.84 Win %: 45.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
BIDU Gain: $ 83.86 Win %: 57.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR2
BIDU Gain: $ 83.91 Win %: 60.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 84.12 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 84.16 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 84.16 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL_DB2
BIDU Gain: $ 84.16 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL_DB2
BIDU Gain: $ 84.35 Win %: 63.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 84.5 Win %: 53.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 84.54 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 84.54 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 84.75 Win %: 51.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 84.88 Win %: 53.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BIDU Gain: $ 84.9 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 85.01 Win %: 54.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
BIDU Gain: $ 85.11 Win %: 53.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 85.44 Win %: 50.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 85.44 Win %: 50.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ 85.79 Win %: 52.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 85.79 Win %: 52.00 in 100 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 85.79 Win %: 52.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 85.79 Win %: 52.00 in 100 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 85.79 Win %: 52.00 in 100 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 85.79 Win %: 52.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 85.79 Win %: 52.00 in 100 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 85.91 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IR2
BIDU Gain: $ 85.99 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 86.11 Win %: 51.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 86.13 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BIDU Gain: $ 86.31 Win %: 54.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
BIDU Gain: $ 86.54 Win %: 53.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
BIDU Gain: $ 86.83 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 86.83 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ 86.95 Win %: 60.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
BIDU Gain: $ 87.09 Win %: 51.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 87.15 Win %: 54.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BIDU Gain: $ 87.27 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 87.3 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 87.33 Win %: 62.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 87.5 Win %: 52.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 87.65 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 87.65 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ 87.68 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
BIDU Gain: $ 87.69 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ 87.77 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 87.82 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 87.91 Win %: 51.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 87.92 Win %: 51.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 87.99 Win %: 45.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
BIDU Gain: $ 88.11 Win %: 60.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
BIDU Gain: $ 88.18 Win %: 61.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BIDU Gain: $ 88.25 Win %: 60.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
BIDU Gain: $ 88.28 Win %: 47.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
BIDU Gain: $ 88.32 Win %: 61.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 88.45 Win %: 60.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
BIDU Gain: $ 88.52 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 88.66 Win %: 61.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 88.69 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 88.73 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 88.73 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ 88.86 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 88.86 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL
BIDU Gain: $ 89.06 Win %: 52.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 89.12 Win %: 59.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
BIDU Gain: $ 89.17 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 89.17 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL
BIDU Gain: $ 89.6 Win %: 52.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ 89.6 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 89.86 Win %: 59.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR2
BIDU Gain: $ 89.96 Win %: 63.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 90.1 Win %: 65.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
BIDU Gain: $ 90.19 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
BIDU Gain: $ 90.19 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL
BIDU Gain: $ 90.27 Win %: 65.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 90.39 Win %: 51.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 90.39 Win %: 51.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 90.71 Win %: 60.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR2
BIDU Gain: $ 90.85 Win %: 60.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 90.93 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5
BIDU Gain: $ 90.95 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 90.95 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 91.1 Win %: 52.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 91.1 Win %: 52.00 in 99 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 91.1 Win %: 52.00 in 99 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 91.1 Win %: 52.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 91.1 Win %: 52.00 in 99 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 91.18 Win %: 53.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 91.41 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 91.44 Win %: 52.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 91.5 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5
BIDU Gain: $ 91.5 Win %: 61.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
BIDU Gain: $ 91.6 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL
BIDU Gain: $ 91.6 Win %: 60.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AV
BIDU Gain: $ 91.76 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
BIDU Gain: $ 91.82 Win %: 51.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 91.82 Win %: 55.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
BIDU Gain: $ 91.88 Win %: 51.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_DB8
BIDU Gain: $ 92.06 Win %: 51.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QP
BIDU Gain: $ 92.38 Win %: 68.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 92.59 Win %: 57.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 92.66 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_DB8
BIDU Gain: $ 92.83 Win %: 52.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 92.97 Win %: 59.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 93.08 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 93.14 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5
BIDU Gain: $ 93.25 Win %: 54.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 93.37 Win %: 62.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 94.2 Win %: 61.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 94.21 Win %: 55.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 94.21 Win %: 55.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 94.72 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_IR2
BIDU Gain: $ 95 Win %: 53.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 95 Win %: 54.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
BIDU Gain: $ 95.09 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 95.21 Win %: 52.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 95.35 Win %: 55.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR2
BIDU Gain: $ 95.67 Win %: 56.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_DB8
BIDU Gain: $ 95.78 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 95.84 Win %: 52.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 95.85 Win %: 58.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 95.95 Win %: 56.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 95.95 Win %: 56.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 96.08 Win %: 62.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 96.12 Win %: 52.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 96.23 Win %: 60.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 96.23 Win %: 60.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 96.23 Win %: 60.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR_DB2
BIDU Gain: $ 96.35 Win %: 65.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 96.4 Win %: 58.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
BIDU Gain: $ 96.74 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
BIDU Gain: $ 96.75 Win %: 53.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 96.75 Win %: 53.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 96.75 Win %: 53.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 96.75 Win %: 53.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 96.76 Win %: 61.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
BIDU Gain: $ 96.82 Win %: 53.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 96.82 Win %: 53.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 97.13 Win %: 53.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 97.16 Win %: 54.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 97.16 Win %: 54.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 97.45 Win %: 60.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
BIDU Gain: $ 97.67 Win %: 67.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 97.96 Win %: 54.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 97.96 Win %: 54.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 98.13 Win %: 65.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 98.48 Win %: 54.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 98.5 Win %: 66.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 98.78 Win %: 55.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 98.83 Win %: 53.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 98.83 Win %: 53.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 98.86 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 98.96 Win %: 55.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 99 Win %: 55.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
BIDU Gain: $ 99.09 Win %: 54.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 99.09 Win %: 54.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 99.29 Win %: 55.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 99.29 Win %: 55.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 99.52 Win %: 54.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 99.57 Win %: 55.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 99.82 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 99.82 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 99.84 Win %: 58.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 99.84 Win %: 58.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 99.84 Win %: 58.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 99.84 Win %: 58.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 100 Win %: 60.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 100.19 Win %: 60.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 100.2 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
BIDU Gain: $ 100.58 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 100.58 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 100.75 Win %: 65.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 100.91 Win %: 61.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
BIDU Gain: $ 101.06 Win %: 61.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 101.14 Win %: 54.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 101.35 Win %: 62.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
BIDU Gain: $ 101.46 Win %: 61.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 101.47 Win %: 68.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 101.79 Win %: 53.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 101.83 Win %: 59.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
BIDU Gain: $ 101.98 Win %: 55.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 101.98 Win %: 55.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BIDU Gain: $ 102.03 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 102.54 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 102.54 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 102.54 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 102.55 Win %: 58.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT
BIDU Gain: $ 102.56 Win %: 53.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR2
BIDU Gain: $ 102.67 Win %: 56.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV
BIDU Gain: $ 102.77 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 102.77 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 102.93 Win %: 53.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 103.01 Win %: 64.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 103.41 Win %: 53.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
BIDU Gain: $ 103.46 Win %: 60.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 103.62 Win %: 59.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 103.62 Win %: 59.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT
BIDU Gain: $ 103.81 Win %: 62.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BIDU Gain: $ 103.88 Win %: 62.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
BIDU Gain: $ 104.03 Win %: 60.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 104.05 Win %: 62.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 104.61 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 104.67 Win %: 61.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 104.77 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 104.77 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 104.77 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR_DB2
BIDU Gain: $ 104.77 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 104.77 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 104.77 Win %: 52.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR_DB2
BIDU Gain: $ 104.86 Win %: 53.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
BIDU Gain: $ 104.94 Win %: 58.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 105.21 Win %: 61.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 105.35 Win %: 61.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 105.36 Win %: 54.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
BIDU Gain: $ 105.36 Win %: 58.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 105.51 Win %: 60.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 105.57 Win %: 61.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 105.68 Win %: 56.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 105.69 Win %: 56.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 105.75 Win %: 53.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 105.81 Win %: 55.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 105.84 Win %: 61.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 105.95 Win %: 62.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
BIDU Gain: $ 105.97 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 106.1 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 106.1 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 106.1 Win %: 56.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 106.44 Win %: 56.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
BIDU Gain: $ 106.46 Win %: 53.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 106.6 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 106.6 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 106.67 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 106.94 Win %: 58.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 107.04 Win %: 60.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 107.41 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
BIDU Gain: $ 107.55 Win %: 48.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
BIDU Gain: $ 107.56 Win %: 58.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 107.59 Win %: 57.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 107.66 Win %: 60.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 107.67 Win %: 66.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 107.94 Win %: 56.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 107.98 Win %: 61.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 108.08 Win %: 54.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_QL
BIDU Gain: $ 108.2 Win %: 61.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 108.21 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 108.33 Win %: 57.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
BIDU Gain: $ 108.4 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 108.4 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 108.46 Win %: 60.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 108.48 Win %: 48.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
BIDU Gain: $ 108.49 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 108.56 Win %: 53.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 108.63 Win %: 57.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 108.63 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 108.63 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT
BIDU Gain: $ 108.63 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT
BIDU Gain: $ 108.65 Win %: 70.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BIDU Gain: $ 108.66 Win %: 58.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 108.68 Win %: 62.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 108.78 Win %: 59.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 108.87 Win %: 55.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 108.87 Win %: 55.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 108.87 Win %: 55.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 109.04 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 109.04 Win %: 58.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
BIDU Gain: $ 109.06 Win %: 54.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 109.06 Win %: 62.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 109.11 Win %: 60.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 109.16 Win %: 57.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
BIDU Gain: $ 109.16 Win %: 62.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 109.19 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 109.2 Win %: 62.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 109.21 Win %: 57.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 109.32 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 109.35 Win %: 59.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 109.35 Win %: 59.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 109.4 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 109.47 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_AL
BIDU Gain: $ 109.65 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_IT
BIDU Gain: $ 109.65 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT
BIDU Gain: $ 109.71 Win %: 61.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 109.74 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 109.75 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 109.75 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 109.86 Win %: 61.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 109.89 Win %: 55.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 109.91 Win %: 61.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 110.02 Win %: 61.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 110.06 Win %: 64.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BIDU Gain: $ 110.31 Win %: 54.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BIDU Gain: $ 110.31 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 110.33 Win %: 61.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 110.33 Win %: 61.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BIDU Gain: $ 110.34 Win %: 60.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 110.44 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 110.7 Win %: 57.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 110.7 Win %: 57.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 110.74 Win %: 57.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 110.93 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 110.99 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 110.99 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 111.21 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 111.21 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 111.28 Win %: 60.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 111.35 Win %: 60.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 111.46 Win %: 61.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 111.46 Win %: 61.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 111.53 Win %: 62.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 111.53 Win %: 62.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 111.58 Win %: 58.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 111.58 Win %: 58.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BIDU Gain: $ 111.82 Win %: 56.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 111.85 Win %: 62.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 111.85 Win %: 62.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 112.26 Win %: 56.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 112.5 Win %: 54.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 112.64 Win %: 55.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BIDU Gain: $ 112.7 Win %: 49.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
BIDU Gain: $ 112.92 Win %: 57.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
BIDU Gain: $ 112.93 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 112.93 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 112.93 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 113.05 Win %: 62.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_DB8
BIDU Gain: $ 113.2 Win %: 56.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 113.31 Win %: 65.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BIDU Gain: $ 113.34 Win %: 56.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 113.49 Win %: 59.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 113.83 Win %: 61.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 113.99 Win %: 63.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 114.26 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 114.26 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 114.62 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 114.77 Win %: 69.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 114.8 Win %: 62.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 114.92 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BIDU Gain: $ 114.97 Win %: 62.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BIDU Gain: $ 115.23 Win %: 57.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
BIDU Gain: $ 115.3 Win %: 49.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
BIDU Gain: $ 115.31 Win %: 50.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
BIDU Gain: $ 115.87 Win %: 56.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 115.93 Win %: 56.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 116.01 Win %: 59.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 116.13 Win %: 62.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 116.14 Win %: 62.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 116.42 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 116.52 Win %: 62.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BIDU Gain: $ 116.66 Win %: 57.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 116.66 Win %: 68.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BIDU Gain: $ 117.06 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
BIDU Gain: $ 117.06 Win %: 62.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BIDU Gain: $ 117.12 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 117.57 Win %: 58.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
BIDU Gain: $ 117.64 Win %: 54.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
BIDU Gain: $ 117.77 Win %: 64.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BIDU Gain: $ 118.07 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 118.51 Win %: 57.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 118.51 Win %: 57.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 118.64 Win %: 66.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BIDU Gain: $ 118.91 Win %: 64.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BIDU Gain: $ 119.12 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BIDU Gain: $ 119.55 Win %: 66.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BIDU Gain: $ 119.63 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 119.78 Win %: 67.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BIDU Gain: $ 120.15 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 120.15 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 120.77 Win %: 65.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BIDU Gain: $ 120.77 Win %: 65.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BIDU Gain: $ 120.9 Win %: 61.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 121.03 Win %: 63.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 121.38 Win %: 58.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 121.58 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 121.58 Win %: 67.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BIDU Gain: $ 121.7 Win %: 67.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
BIDU Gain: $ 121.81 Win %: 57.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BIDU Gain: $ 122.15 Win %: 63.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 122.16 Win %: 62.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 122.32 Win %: 59.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_LI
BIDU Gain: $ 122.32 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 122.36 Win %: 60.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
BIDU Gain: $ 122.58 Win %: 62.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 122.58 Win %: 62.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BIDU Gain: $ 122.58 Win %: 62.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL_DB2
BIDU Gain: $ 122.72 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 123.25 Win %: 62.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 123.25 Win %: 62.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 123.29 Win %: 62.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 123.45 Win %: 65.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BIDU Gain: $ 124.58 Win %: 62.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 124.85 Win %: 63.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR2
BIDU Gain: $ 124.85 Win %: 64.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 125.17 Win %: 64.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 125.23 Win %: 64.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 125.35 Win %: 57.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BIDU Gain: $ 126.18 Win %: 66.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 126.31 Win %: 64.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 126.31 Win %: 64.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 126.42 Win %: 65.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BIDU Gain: $ 126.45 Win %: 65.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 126.57 Win %: 49.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
BIDU Gain: $ 126.91 Win %: 54.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 127.16 Win %: 65.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 127.57 Win %: 65.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 127.57 Win %: 65.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 127.84 Win %: 64.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BIDU Gain: $ 127.89 Win %: 50.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
BIDU Gain: $ 127.99 Win %: 50.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
BIDU Gain: $ 128.34 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 128.59 Win %: 62.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
BIDU Gain: $ 129.06 Win %: 56.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 129.06 Win %: 56.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 129.06 Win %: 56.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 130.08 Win %: 55.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 130.32 Win %: 57.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
BIDU Gain: $ 130.45 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 130.75 Win %: 58.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 131.09 Win %: 57.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 131.96 Win %: 56.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 131.96 Win %: 56.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 131.98 Win %: 56.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 132.04 Win %: 50.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
BIDU Gain: $ 132.34 Win %: 55.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 132.48 Win %: 63.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
BIDU Gain: $ 132.79 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 132.8 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 133.07 Win %: 59.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 133.07 Win %: 59.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 133.29 Win %: 56.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 133.69 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 133.81 Win %: 56.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 133.91 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 134.26 Win %: 63.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
BIDU Gain: $ 134.49 Win %: 60.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
BIDU Gain: $ 134.61 Win %: 64.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR2
BIDU Gain: $ 134.64 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 134.64 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 134.64 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 134.64 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 134.7 Win %: 64.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
BIDU Gain: $ 134.84 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 134.87 Win %: 56.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 134.95 Win %: 57.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 135.19 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 135.19 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 135.4 Win %: 56.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 135.57 Win %: 58.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR2
BIDU Gain: $ 135.73 Win %: 58.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 135.98 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 135.98 Win %: 57.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 136.2 Win %: 56.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BIDU Gain: $ 136.59 Win %: 51.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
BIDU Gain: $ 136.95 Win %: 55.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
BIDU Gain: $ 137.06 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 137.16 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
BIDU Gain: $ 137.23 Win %: 64.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
BIDU Gain: $ 137.66 Win %: 56.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
BIDU Gain: $ 139.18 Win %: 58.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 141.6 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 141.9 Win %: 59.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 142.3 Win %: 58.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
BIDU Gain: $ 142.6 Win %: 56.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 142.6 Win %: 56.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 142.6 Win %: 56.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 143.22 Win %: 58.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_SS
BIDU Gain: $ 143.39 Win %: 60.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 143.68 Win %: 64.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 144.02 Win %: 56.00 in 104 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 145.24 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 145.36 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 145.36 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 145.52 Win %: 59.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 145.52 Win %: 59.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 146.16 Win %: 56.00 in 110 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 146.24 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 146.24 Win %: 60.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 146.47 Win %: 55.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
BIDU Gain: $ 146.95 Win %: 56.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
BIDU Gain: $ 147.14 Win %: 53.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 147.48 Win %: 61.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 147.48 Win %: 61.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 147.48 Win %: 61.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 147.48 Win %: 61.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 147.48 Win %: 61.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 147.82 Win %: 55.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
BIDU Gain: $ 148.08 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 148.08 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 148.08 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 148.26 Win %: 65.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 148.26 Win %: 65.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 148.3 Win %: 53.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 148.3 Win %: 53.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 148.61 Win %: 57.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 148.83 Win %: 59.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 149.06 Win %: 60.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 149.09 Win %: 59.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR2
BIDU Gain: $ 149.23 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 149.23 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 149.23 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 149.23 Win %: 52.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 149.27 Win %: 59.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 149.74 Win %: 59.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR2
BIDU Gain: $ 149.86 Win %: 53.00 in 106 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 150.01 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 150.21 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 150.41 Win %: 54.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 150.77 Win %: 59.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 151.19 Win %: 56.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 151.43 Win %: 57.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR
BIDU Gain: $ 151.53 Win %: 52.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 151.85 Win %: 59.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR2
BIDU Gain: $ 151.95 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 151.95 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 151.95 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 151.95 Win %: 52.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 152.2 Win %: 60.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR2
BIDU Gain: $ 152.37 Win %: 54.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 152.37 Win %: 54.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 153.05 Win %: 60.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 153.16 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 153.16 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 153.16 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 153.16 Win %: 51.00 in 108 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 153.42 Win %: 61.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 153.42 Win %: 61.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 153.43 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 153.43 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 153.43 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 153.43 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 153.43 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 153.43 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 153.43 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 153.43 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 153.58 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR2
BIDU Gain: $ 153.8 Win %: 54.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 153.86 Win %: 56.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 153.86 Win %: 56.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 153.96 Win %: 51.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 153.96 Win %: 55.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 154.06 Win %: 53.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 154.18 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 154.18 Win %: 54.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 154.46 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 154.46 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 154.46 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 154.46 Win %: 52.00 in 109 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 154.47 Win %: 54.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 154.6 Win %: 51.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 154.89 Win %: 55.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 155.13 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 155.13 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 155.13 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 155.13 Win %: 53.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 155.13 Win %: 53.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 155.36 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 155.36 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 155.36 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 155.36 Win %: 54.00 in 110 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 155.7 Win %: 55.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 155.77 Win %: 61.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 155.77 Win %: 61.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 156.05 Win %: 54.00 in 104 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 156.2 Win %: 61.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR2
BIDU Gain: $ 156.28 Win %: 53.00 in 107 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 156.49 Win %: 56.00 in 107 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 156.9 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 156.9 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 156.9 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 157.03 Win %: 55.00 in 108 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 157.07 Win %: 55.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 157.1 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BIDU Gain: $ 157.1 Win %: 60.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 157.17 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 157.17 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 157.17 Win %: 55.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 157.19 Win %: 55.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 158.09 Win %: 52.00 in 108 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 158.19 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 158.32 Win %: 55.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 158.49 Win %: 56.00 in 109 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 158.5 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 158.5 Win %: 56.00 in 112 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 158.82 Win %: 56.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 158.82 Win %: 56.00 in 113 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 158.84 Win %: 68.00 in 104 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 158.89 Win %: 56.00 in 111 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 159.33 Win %: 52.00 in 106 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 159.4 Win %: 61.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
BIDU Gain: $ 159.4 Win %: 61.00 in 104 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 159.6 Win %: 52.00 in 105 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 159.74 Win %: 56.00 in 113 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BIDU Gain: $ 160.9 Win %: 57.00 in 112 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 161.03 Win %: 52.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 161.55 Win %: 56.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BIDU Gain: $ 161.55 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 162.97 Win %: 53.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 162.97 Win %: 53.00 in 105 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 163.94 Win %: 53.00 in 102 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BIDU Gain: $ 163.94 Win %: 53.00 in 102 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BIDU Gain: $ 165.96 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
BIDU Gain: $ 165.96 Win %: 57.00 in 107 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 166.69 Win %: 56.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
BIDU Gain: $ 166.69 Win %: 56.00 in 109 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 168.79 Win %: 62.00 in 107 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 169.03 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 169.08 Win %: 63.00 in 106 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 169.96 Win %: 58.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 170.09 Win %: 64.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 170.18 Win %: 57.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
BIDU Gain: $ 170.18 Win %: 57.00 in 106 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 171.23 Win %: 64.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 171.23 Win %: 64.00 in 113 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 171.75 Win %: 63.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 171.75 Win %: 64.00 in 102 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 172.59 Win %: 64.00 in 110 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 172.93 Win %: 63.00 in 105 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 173.89 Win %: 58.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
BIDU Gain: $ 173.89 Win %: 58.00 in 102 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 174.36 Win %: 58.00 in 111 days with algo TB4_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
BIDU Gain: $ 174.54 Win %: 58.00 in 105 days with algo TB4_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
BIDU Gain: $ 175.89 Win %: 63.00 in 112 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BIDU Gain: $ 187.33 Win %: 64.00 in 108 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_TR
2.72 on2.72 on 200.58 on0.58 on 20BIDU GaBIDU Gain: $ 52.24 Win %: 63.00 in 111 days with algo TB4_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL
2.72 on2.72 on 200.58 on0.58 on 20BIDU Gain: $ 80.88 Win %: 65.00 in 111 days with algo TB4_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
