BILI Gain: $ -32.19 Win %: 33.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
BILI Gain: $ -25.63 Win %: 31.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -25.63 Win %: 31.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP_DB4
BILI Gain: $ -24.48 Win %: 25.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_QP_DB4
BILI Gain: $ -22.76 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_QP
BILI Gain: $ -21.9 Win %: 50.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BILI Gain: $ -21.9 Win %: 50.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP_DB4
BILI Gain: $ -19.87 Win %: 31.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -19.87 Win %: 31.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP_DB4
BILI Gain: $ -19.2 Win %: 37.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_AV
BILI Gain: $ -19.05 Win %: 37.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -19.03 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -18.27 Win %: 37.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_QP_IR5
BILI Gain: $ -18.15 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -18.15 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP_DB4
BILI Gain: $ -17.76 Win %: 10.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -17.35 Win %: 37.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -17.35 Win %: 37.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP_DB4
BILI Gain: $ -16.04 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -16.04 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -15.52 Win %: 25.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BILI Gain: $ -15.26 Win %: 50.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM_QP_DB4
BILI Gain: $ -15.23 Win %: 56.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_QP
BILI Gain: $ -15.17 Win %: 50.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_QP
BILI Gain: $ -14.8 Win %: 40.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_QP_IR5
BILI Gain: $ -14.73 Win %: 35.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -14.65 Win %: 33.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BILI Gain: $ -14.55 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_SS
BILI Gain: $ -14.53 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BILI Gain: $ -14.53 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP_DB4
BILI Gain: $ -14.46 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
BILI Gain: $ -14.42 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BILI Gain: $ -14.42 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP_DB4
BILI Gain: $ -14.41 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -14.39 Win %: 43.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_QP_DB5
BILI Gain: $ -13.75 Win %: 28.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_QP_IR5
BILI Gain: $ -13.74 Win %: 43.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_QP_DB4
BILI Gain: $ -13.59 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -13.59 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -13.38 Win %: 53.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_QP_DB5
BILI Gain: $ -13.19 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR_QP_DB5
BILI Gain: $ -13.17 Win %: 22.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_AL
BILI Gain: $ -12.95 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR4
BILI Gain: $ -12.71 Win %: 60.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BILI Gain: $ -12.66 Win %: 56.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_QP_DB5
BILI Gain: $ -12.46 Win %: 38.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -12.32 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -12.01 Win %: 26.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_QP_DB4
BILI Gain: $ -11.79 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -11.74 Win %: 30.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -11.62 Win %: 31.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_QP
BILI Gain: $ -11.62 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_QP_DB4
BILI Gain: $ -11.6 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_QP
BILI Gain: $ -11.57 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -11.53 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_TR_DB4
BILI Gain: $ -11.43 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
BILI Gain: $ -11.37 Win %: 26.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_QP
BILI Gain: $ -11.27 Win %: 30.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -11.24 Win %: 35.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -11.24 Win %: 35.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_QP_DB5
BILI Gain: $ -11.23 Win %: 40.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
BILI Gain: $ -11.19 Win %: 53.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_QP
BILI Gain: $ -11.16 Win %: 37.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -11.16 Win %: 50.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM_QP
BILI Gain: $ -10.9 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -10.86 Win %: 44.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
BILI Gain: $ -10.86 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_QL
BILI Gain: $ -10.84 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_HM_QP
BILI Gain: $ -10.84 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_HM_QP
BILI Gain: $ -10.84 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_HM_QP
BILI Gain: $ -10.84 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_HM_QP
BILI Gain: $ -10.84 Win %: 44.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_VI
BILI Gain: $ -10.83 Win %: 30.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_QP_IR5
BILI Gain: $ -10.74 Win %: 33.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AV_DB5
BILI Gain: $ -10.68 Win %: 55.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_TR_QP
BILI Gain: $ -10.65 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP_DB4
BILI Gain: $ -10.64 Win %: 28.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_QP
BILI Gain: $ -10.6 Win %: 20.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BILI Gain: $ -10.56 Win %: 30.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -10.55 Win %: 33.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP_DB4
BILI Gain: $ -10.53 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_QP_DB4
BILI Gain: $ -10.48 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_QP_DB5
BILI Gain: $ -10.42 Win %: 33.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -10.27 Win %: 40.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_AV
BILI Gain: $ -10.18 Win %: 33.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -10.14 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP_DB4
BILI Gain: $ -10.13 Win %: 0 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_QP_IR5
BILI Gain: $ -10.12 Win %: 0 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_QP_IR5
BILI Gain: $ -10.12 Win %: 0 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_QP_IR5
BILI Gain: $ -9.87 Win %: 73.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QP_DB4
BILI Gain: $ -9.86 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -9.76 Win %: 56.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_TR_QP_DB5
BILI Gain: $ -9.73 Win %: 35.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -9.69 Win %: 33.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_AV
BILI Gain: $ -9.67 Win %: 28.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_QP_DB4
BILI Gain: $ -9.67 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_IR3
BILI Gain: $ -9.57 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
BILI Gain: $ -9.47 Win %: 46.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ -9.47 Win %: 46.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ -9.45 Win %: 16.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_AL
BILI Gain: $ -9.3 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ -9.15 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_VI
BILI Gain: $ -9.07 Win %: 46.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_QP_DB4
BILI Gain: $ -8.98 Win %: 40.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ -8.92 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ -8.84 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -8.7 Win %: 85.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IT_QP_DB5
BILI Gain: $ -8.65 Win %: 35.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP_DB4
BILI Gain: $ -8.63 Win %: 26.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -8.62 Win %: 35.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP_DB4
BILI Gain: $ -8.55 Win %: 44.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
BILI Gain: $ -8.5 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -8.49 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_TR_QP
BILI Gain: $ -8.39 Win %: 40.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
BILI Gain: $ -8.33 Win %: 86.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QP
BILI Gain: $ -8.32 Win %: 56.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_QP
BILI Gain: $ -8.23 Win %: 44.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
BILI Gain: $ -8.2 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
BILI Gain: $ -8.15 Win %: 41.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_TR_IR4
BILI Gain: $ -8.11 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_QP
BILI Gain: $ -8.1 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -8.1 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -8.06 Win %: 46.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_VI
BILI Gain: $ -8.05 Win %: 44.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_HM_AV
BILI Gain: $ -8.05 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_QP
BILI Gain: $ -7.81 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -7.8 Win %: 41.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -7.8 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
BILI Gain: $ -7.8 Win %: 58.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
BILI Gain: $ -7.75 Win %: 38.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ -7.72 Win %: 16.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_QP_IR5
BILI Gain: $ -7.72 Win %: 43.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_AV_DB5
BILI Gain: $ -7.69 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_QP
BILI Gain: $ -7.63 Win %: 33.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_QP
BILI Gain: $ -7.55 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_QP_IR4
BILI Gain: $ -7.55 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
BILI Gain: $ -7.53 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_QP
BILI Gain: $ -7.46 Win %: 60.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_TR_QP_DB5
BILI Gain: $ -7.43 Win %: 44.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
BILI Gain: $ -7.37 Win %: 46.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ -7.31 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_QP
BILI Gain: $ -7.31 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_QP
BILI Gain: $ -7.29 Win %: 50.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_QP_IR4
BILI Gain: $ -7.26 Win %: 33.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -7.25 Win %: 40.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_QP
BILI Gain: $ -7.25 Win %: 50.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_QP
BILI Gain: $ -7.16 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
BILI Gain: $ -7.16 Win %: 71.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QP_DB4
BILI Gain: $ -7.13 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ -7.09 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
BILI Gain: $ -7.08 Win %: 40.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_QP
BILI Gain: $ -7 Win %: 30.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_AV
BILI Gain: $ -6.92 Win %: 16.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_IR5
BILI Gain: $ -6.92 Win %: 16.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_IR5
BILI Gain: $ -6.92 Win %: 16.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_IR5
BILI Gain: $ -6.85 Win %: 53.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_AL
BILI Gain: $ -6.79 Win %: 60.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_QP
BILI Gain: $ -6.78 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ -6.77 Win %: 71.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QP
BILI Gain: $ -6.74 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -6.74 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -6.73 Win %: 56.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR_QP
BILI Gain: $ -6.7 Win %: 58.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
BILI Gain: $ -6.65 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ -6.59 Win %: 37.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AV_DB5
BILI Gain: $ -6.59 Win %: 37.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -6.59 Win %: 37.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV_DB4
BILI Gain: $ -6.58 Win %: 44.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AV
BILI Gain: $ -6.58 Win %: 76.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BILI Gain: $ -6.52 Win %: 44.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
BILI Gain: $ -6.51 Win %: 40.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AV
BILI Gain: $ -6.51 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_TR_QP
BILI Gain: $ -6.45 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
BILI Gain: $ -6.45 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_QP
BILI Gain: $ -6.44 Win %: 20.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ -6.33 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_TR_DB5
BILI Gain: $ -6.31 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -6.31 Win %: 44.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_QP
BILI Gain: $ -6.22 Win %: 38.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -6.19 Win %: 50.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_QP_IR4
BILI Gain: $ -6.13 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ -6.11 Win %: 38.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -5.99 Win %: 38.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -5.98 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
BILI Gain: $ -5.97 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -5.96 Win %: 41.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_HM_QP
BILI Gain: $ -5.96 Win %: 55.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_LI
BILI Gain: $ -5.9 Win %: 44.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
BILI Gain: $ -5.88 Win %: 40.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -5.82 Win %: 80.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BILI Gain: $ -5.82 Win %: 80.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
BILI Gain: $ -5.81 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ -5.81 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ -5.78 Win %: 46.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_HM_QP
BILI Gain: $ -5.78 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ -5.74 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
BILI Gain: $ -5.7 Win %: 38.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -5.64 Win %: 30.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
BILI Gain: $ -5.56 Win %: 64.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ -5.53 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ -5.5 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_TR_QP
BILI Gain: $ -5.49 Win %: 30.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -5.48 Win %: 33.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
BILI Gain: $ -5.47 Win %: 50.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_VI
BILI Gain: $ -5.42 Win %: 46.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_AV_DB5
BILI Gain: $ -5.35 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_IR3
BILI Gain: $ -5.34 Win %: 44.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
BILI Gain: $ -5.34 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_QP
BILI Gain: $ -5.27 Win %: 40.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_HM_QP
BILI Gain: $ -5.27 Win %: 50.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_QP
BILI Gain: $ -5.24 Win %: 21.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ -5.09 Win %: 44.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_HM_QP
BILI Gain: $ -5.06 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP_IR3
BILI Gain: $ -5.06 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
BILI Gain: $ -5 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
BILI Gain: $ -4.97 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
BILI Gain: $ -4.97 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_QP
BILI Gain: $ -4.97 Win %: 62.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_TR_QP
BILI Gain: $ -4.85 Win %: 58.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
BILI Gain: $ -4.83 Win %: 40.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -4.8 Win %: 60.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ -4.79 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_QP
BILI Gain: $ -4.78 Win %: 46.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_QP
BILI Gain: $ -4.7 Win %: 33.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR4
BILI Gain: $ -4.62 Win %: 38.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ -4.62 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
BILI Gain: $ -4.58 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -4.56 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ -4.56 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
BILI Gain: $ -4.56 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_QP
BILI Gain: $ -4.55 Win %: 55.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_RV_QP
BILI Gain: $ -4.55 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
BILI Gain: $ -4.53 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ -4.48 Win %: 40.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_AL
BILI Gain: $ -4.47 Win %: 44.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_QP
BILI Gain: $ -4.44089e-16 Win %: 57.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM
BILI Gain: $ -4.43 Win %: 50.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
BILI Gain: $ -4.42 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_QP_IR5
BILI Gain: $ -4.36 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -4.3 Win %: 46.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -4.25 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ -4.25 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ -4.25 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_QP
BILI Gain: $ -4.23 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ -4.2 Win %: 58.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_TR_QP
BILI Gain: $ -4.15 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -4.12 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_VI
BILI Gain: $ -4.05 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -4.05 Win %: 46.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_AV
BILI Gain: $ -4.01 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ -3.98 Win %: 26.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ -3.98 Win %: 26.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ -3.92 Win %: 43.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AV
BILI Gain: $ -3.89 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP
BILI Gain: $ -3.81 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_QP
BILI Gain: $ -3.81 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_QP_DB3
BILI Gain: $ -3.79 Win %: 28.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ -3.72 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ -3.63 Win %: 46.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_QP_DB5
BILI Gain: $ -3.61 Win %: 58.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
BILI Gain: $ -3.61 Win %: 60.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_QP
BILI Gain: $ -3.6 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP_IR3
BILI Gain: $ -3.59 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AV
BILI Gain: $ -3.59 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AV_DB3
BILI Gain: $ -3.57 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_AV_DB5
BILI Gain: $ -3.56 Win %: 57.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_QP_IR4
BILI Gain: $ -3.49 Win %: 66.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BILI Gain: $ -3.49 Win %: 70.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
BILI Gain: $ -3.48 Win %: 50.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_QP_IR4
BILI Gain: $ -3.46 Win %: 55.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_HM_TR
BILI Gain: $ -3.42 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_VI
BILI Gain: $ -3.41 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_TR_QP
BILI Gain: $ -3.4 Win %: 80.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QP
BILI Gain: $ -3.39 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ -3.38 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_TR_IR5
BILI Gain: $ -3.38 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_TR_IR5
BILI Gain: $ -3.38 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_TR_IR5
BILI Gain: $ -3.38 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_TR_IR5
BILI Gain: $ -3.35 Win %: 46.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
BILI Gain: $ -3.33 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
BILI Gain: $ -3.33 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP_IR3
BILI Gain: $ -3.33 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP_IR3
BILI Gain: $ -3.32 Win %: 84.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_DB10
BILI Gain: $ -3.32 Win %: 84.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_DB10
BILI Gain: $ -3.3 Win %: 80.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QP_DB5
BILI Gain: $ -3.27 Win %: 50.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR
BILI Gain: $ -3.27 Win %: 50.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR_DB4
BILI Gain: $ -3.27 Win %: 56.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AV
BILI Gain: $ -3.25 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_QP
BILI Gain: $ -3.25 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_QP
BILI Gain: $ -3.25 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_QP
BILI Gain: $ -3.22 Win %: 53.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ -3.19 Win %: 81.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QP
BILI Gain: $ -3.14 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_QP_IR4
BILI Gain: $ -3.13 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AV
BILI Gain: $ -3.12 Win %: 46.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ -3.06 Win %: 60.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV
BILI Gain: $ -3.03 Win %: 60.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ -2.99 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_QP
BILI Gain: $ -2.98 Win %: 57.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_AV_DB4
BILI Gain: $ -2.97 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR4
BILI Gain: $ -2.94 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ -2.9 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_VI
BILI Gain: $ -2.86 Win %: 86.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QP
BILI Gain: $ -2.77 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_RV_QP
BILI Gain: $ -2.74 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_TR_QP
BILI Gain: $ -2.73 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ -2.72 Win %: 25.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ -2.69 Win %: 40.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR4
BILI Gain: $ -2.69 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
BILI Gain: $ -2.68 Win %: 35.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -2.66 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR_QP
BILI Gain: $ -2.66 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR_QP_DB4
BILI Gain: $ -2.63 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ -2.63 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ -2.63 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ -2.63 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -2.61 Win %: 85.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IT_QP
BILI Gain: $ -2.6 Win %: 75.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QP
BILI Gain: $ -2.56 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_QP
BILI Gain: $ -2.53 Win %: 53.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -2.53 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_TR_QP
BILI Gain: $ -2.45 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP
BILI Gain: $ -2.45 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP
BILI Gain: $ -2.45 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP
BILI Gain: $ -2.45 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_QP_DB4
BILI Gain: $ -2.43 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_HM_TR
BILI Gain: $ -2.43 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_HM_TR
BILI Gain: $ -2.41 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_QP_IR4
BILI Gain: $ -2.4 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_VI
BILI Gain: $ -2.35 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
BILI Gain: $ -2.35 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_IR3
BILI Gain: $ -2.28 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -2.28 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV
BILI Gain: $ -2.27 Win %: 40.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_AV
BILI Gain: $ -2.27 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AV
BILI Gain: $ -2.26 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_VI
BILI Gain: $ -2.26 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_VI
BILI Gain: $ -2.26 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_VI
BILI Gain: $ -2.25 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -2.2 Win %: 53.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_DB30
BILI Gain: $ -2.2 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_VI
BILI Gain: $ -2.18 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
BILI Gain: $ -2.15 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_IR3
BILI Gain: $ -2.14 Win %: 70.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_TR_QP
BILI Gain: $ -2.13 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ -2.13 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -2.13 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -2.1 Win %: 38.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
BILI Gain: $ -2.08 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QL
BILI Gain: $ -2.03 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ -1.98 Win %: 50.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_VI
BILI Gain: $ -1.97 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_VI
BILI Gain: $ -1.97 Win %: 77.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
BILI Gain: $ -1.96 Win %: 55.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_RV_AL
BILI Gain: $ -1.96 Win %: 58.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_LI
BILI Gain: $ -1.94 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_IR5
BILI Gain: $ -1.94 Win %: 60.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_QP_IR4
BILI Gain: $ -1.93 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_HM_TR
BILI Gain: $ -1.93 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_HM_TR
BILI Gain: $ -1.89 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BILI Gain: $ -1.89 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
BILI Gain: $ -1.88 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_TR_QP
BILI Gain: $ -1.88 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_TR_QP
BILI Gain: $ -1.8 Win %: 30.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ -1.8 Win %: 40.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV_DB4
BILI Gain: $ -1.76 Win %: 56.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_DB30
BILI Gain: $ -1.75 Win %: 33.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AV
BILI Gain: $ -1.75 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_VI
BILI Gain: $ -1.71 Win %: 50.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV_DB4
BILI Gain: $ -1.71 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_VI
BILI Gain: $ -1.71 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_VI
BILI Gain: $ -1.69 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
BILI Gain: $ -1.6 Win %: 42.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_AV
BILI Gain: $ -1.6 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_TR_DB4
BILI Gain: $ -1.56 Win %: 33.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
BILI Gain: $ -1.54 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_HM_TR
BILI Gain: $ -1.54 Win %: 80.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QP
BILI Gain: $ -1.46 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR_IR5
BILI Gain: $ -1.46 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_QP
BILI Gain: $ -1.42 Win %: 46.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ -1.39 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
BILI Gain: $ -1.39 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP_IR3
BILI Gain: $ -1.37 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_TR_QP
BILI Gain: $ -1.37 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_QP
BILI Gain: $ -1.37 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_QP
BILI Gain: $ -1.35 Win %: 92.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IT_QP
BILI Gain: $ -1.32 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ -1.32 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_QP_IR5
BILI Gain: $ -1.32 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_VI
BILI Gain: $ -1.32 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_RV_QP
BILI Gain: $ -1.32 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_RV_QP
BILI Gain: $ -1.32 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_RV_QP
BILI Gain: $ -1.29 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_TR
BILI Gain: $ -1.29 Win %: 62.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ -1.27 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
BILI Gain: $ -1.26 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_TR_QP
BILI Gain: $ -1.25 Win %: 33.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_RV_AL
BILI Gain: $ -1.25 Win %: 41.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ -1.25 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_IR3
BILI Gain: $ -1.24 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_RV_AV
BILI Gain: $ -1.24 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_RV_AV
BILI Gain: $ -1.22 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_HM_TR
BILI Gain: $ -1.22 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_HM_TR
BILI Gain: $ -1.21 Win %: 33.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_RV_AL
BILI Gain: $ -1.2 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_TR_DB5
BILI Gain: $ -1.2 Win %: 55.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_HM
BILI Gain: $ -1.19 Win %: 38.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ -1.19 Win %: 38.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ -1.16 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
BILI Gain: $ -1.15 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_TR_QP
BILI Gain: $ -1.15 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_TR_QP
BILI Gain: $ -1.12 Win %: 58.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ -1.08 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_HM_AV
BILI Gain: $ -1.05 Win %: 53.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ -0.99 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
BILI Gain: $ -0.99 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_IR3
BILI Gain: $ -0.99 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_QP_IR4
BILI Gain: $ -0.99 Win %: 53.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_VI
BILI Gain: $ -0.98 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_QP_DB3
BILI Gain: $ -0.94 Win %: 46.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_TR_DB5
BILI Gain: $ -0.94 Win %: 50.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_QP
BILI Gain: $ -0.9 Win %: 58.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -0.89 Win %: 53.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ -0.87 Win %: 77.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
BILI Gain: $ -0.86 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_QP
BILI Gain: $ -0.81 Win %: 28.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AV
BILI Gain: $ -0.81 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ -0.81 Win %: 93.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QP
BILI Gain: $ -0.8 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
BILI Gain: $ -0.76 Win %: 53.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -0.74 Win %: 93.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QP_DB4
BILI Gain: $ -0.73 Win %: 57.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ -0.72 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR_QP_DB4
BILI Gain: $ -0.71 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_RV_QP
BILI Gain: $ -0.7 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_AV
BILI Gain: $ -0.67 Win %: 55.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_HM_QP
BILI Gain: $ -0.66 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_HM_TR
BILI Gain: $ -0.66 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BILI Gain: $ -0.66 Win %: 93.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QP
BILI Gain: $ -0.66 Win %: 93.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QP
BILI Gain: $ -0.62 Win %: 50.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_TR_IR4
BILI Gain: $ -0.61 Win %: 50.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
BILI Gain: $ -0.58 Win %: 43.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR_IR4
BILI Gain: $ -0.58 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_TR
BILI Gain: $ -0.58 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_TR
BILI Gain: $ -0.58 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_TR_DB4
BILI Gain: $ -0.58 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_TR_DB4
BILI Gain: $ -0.57 Win %: 46.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_AV
BILI Gain: $ -0.56 Win %: 30.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AV
BILI Gain: $ -0.56 Win %: 30.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AV
BILI Gain: $ -0.55 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_HM_AV
BILI Gain: $ -0.55 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_HM_AV
BILI Gain: $ -0.55 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_HM_AV
BILI Gain: $ -0.53 Win %: 93.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QP
BILI Gain: $ -0.53 Win %: 93.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QP_DB4
BILI Gain: $ -0.51 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_QP
BILI Gain: $ -0.5 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_RV_QP
BILI Gain: $ -0.5 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_RV_QP
BILI Gain: $ -0.48 Win %: 66.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
BILI Gain: $ -0.44 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV_DB4
BILI Gain: $ -0.42 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_TR
BILI Gain: $ -0.4 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_RV_QP
BILI Gain: $ -0.39 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR_QP
BILI Gain: $ -0.35 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IR5
BILI Gain: $ -0.35 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ -0.34 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BILI Gain: $ -0.31 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BILI Gain: $ -0.31 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB4
BILI Gain: $ -0.3 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ -0.29 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
BILI Gain: $ -0.26 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_TR_IR4
BILI Gain: $ -0.26 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_TR_IR4
BILI Gain: $ -0.24 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_QP_IR5
BILI Gain: $ -0.24 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_QP_IR5
BILI Gain: $ -0.23 Win %: 58.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BILI Gain: $ -0.21 Win %: 60.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_HM_TR
BILI Gain: $ -0.19 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_TR
BILI Gain: $ -0.18 Win %: 70.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_LI
BILI Gain: $ -0.17 Win %: 81.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QP_DB5
BILI Gain: $ -0.14 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
BILI Gain: $ -0.12 Win %: 55.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_HM_TR
BILI Gain: $ -0.11 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP
BILI Gain: $ -0.11 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP
BILI Gain: $ -0.1 Win %: 38.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP
BILI Gain: $ -0.1 Win %: 46.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_AV
BILI Gain: $ -0.1 Win %: 58.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_QP
BILI Gain: $ -0.09 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
BILI Gain: $ -0.09 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
BILI Gain: $ -0.09 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
BILI Gain: $ 0 Win %: 100.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
BILI Gain: $ 0 Win %: 60.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_QP_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_TR_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_QP_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_TR_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_QP_IR5
Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_TR_IR5
Gain: $ 0.38 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_TR_IR5
Gain: $ 0.38 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 0.38 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_TR_IR5
Gain: $ 0.38 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_TR_IR5
Gain: $ 0.58 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM_AV
Gain: $ 0.58 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM_AV
Gain: $ 0.58 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ 0.58 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ 0.58 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_HM_AV
Gain: $ 0.58 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_HM_AV
Gain: $ 0.58 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_HM_AV
Gain: $ 0.58 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_HM_AV
Gain: $ 0.76 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV_QP
Gain: $ 0.76 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV_QP
Gain: $ 0.76 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ 0.76 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ 0.76 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV_QP
Gain: $ 0.76 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV_QP
Gain: $ 0.76 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV_QP
Gain: $ 0.76 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_HM_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_HM_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_HM_QP
Gain: $ 1.48 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_HM_QP
Gain: $ 1.7 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_QP_IR5
Gain: $ 1.7 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ 1.7 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_QP_IR5
Gain: $ 1.7 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_QP_IR5
Gain: $ 1.75 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV_AV
Gain: $ 1.75 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV_AV
Gain: $ 1.75 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ 1.75 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ 1.75 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV_AV
Gain: $ 1.75 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV_AV
Gain: $ 1.75 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV_AV
Gain: $ 1.75 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV_AV
Gain: $ 10.5 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_AV
Gain: $ 10.5 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_AV
Gain: $ 10.5 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_AV
Gain: $ 10.5 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_AV
Gain: $ 10.5 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_AV
Gain: $ 10.5 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_AV
Gain: $ 10.5 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_AV
Gain: $ 10.5 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_AV
Gain: $ 10.57 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_SS
Gain: $ 10.57 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_SS
Gain: $ 10.57 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_SS
Gain: $ 10.57 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_SS
Gain: $ 10.57 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_SS
Gain: $ 10.57 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_SS
Gain: $ 10.57 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_SS
Gain: $ 10.57 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_SS
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_DB30
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_DB30
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_QL
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_QL
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_DB30
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_DB30
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_QL
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_QL
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_DB30
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_DB30
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_QL
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_QL
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_DB30
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_DB30
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_QL
Gain: $ 10.77 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_QL
Gain: $ 10.91 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_AL
Gain: $ 10.91 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_AL
Gain: $ 10.91 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 10.91 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 10.91 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_AL
Gain: $ 10.91 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_AL
Gain: $ 10.91 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_AL
Gain: $ 10.91 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_AL
Gain: $ 2.19 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_TR_QP
Gain: $ 2.19 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_TR_QP
Gain: $ 2.19 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ 2.19 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ 2.19 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_TR_QP
Gain: $ 2.19 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_TR_QP
Gain: $ 2.19 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_TR_QP
Gain: $ 2.19 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_TR_QP
Gain: $ 2.52 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_VI
Gain: $ 2.52 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_VI
Gain: $ 2.52 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_VI
Gain: $ 2.52 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_VI
Gain: $ 2.52 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_VI
Gain: $ 2.52 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_VI
Gain: $ 2.52 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_VI
Gain: $ 2.52 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_VI
Gain: $ 2.84 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_IR5
Gain: $ 2.84 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 2.84 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_IR5
Gain: $ 2.84 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_IR5
Gain: $ 3.11 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_QP
Gain: $ 3.11 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_QP
Gain: $ 3.11 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_QP
Gain: $ 3.11 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_QP
Gain: $ 3.11 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_QP
Gain: $ 3.11 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_QP
Gain: $ 3.11 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_QP
Gain: $ 3.11 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_QP
Gain: $ 4.18 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV_AL
Gain: $ 4.18 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV_AL
Gain: $ 4.18 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 4.18 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 4.18 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 4.18 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 4.18 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV_AL
Gain: $ 4.18 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV_AL
Gain: $ 4.61 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_LI
Gain: $ 4.61 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_LI
Gain: $ 4.61 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 4.61 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 4.61 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_LI
Gain: $ 4.61 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_LI
Gain: $ 4.61 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_LI
Gain: $ 4.61 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_LI
Gain: $ 5.37 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM_TR
Gain: $ 5.37 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM_TR
Gain: $ 5.37 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ 5.37 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ 5.37 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_HM_TR
Gain: $ 5.37 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_HM_TR
Gain: $ 5.37 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_HM_TR
Gain: $ 5.37 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_HM_TR
Gain: $ 5.88 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_TR
Gain: $ 5.88 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_TR
Gain: $ 5.88 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 5.88 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 5.88 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_TR
Gain: $ 5.88 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_TR
Gain: $ 5.88 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_TR
Gain: $ 5.88 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_TR
Gain: $ 5.91 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV_TR
Gain: $ 5.91 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV_TR
Gain: $ 5.91 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 5.91 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 5.91 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ 5.91 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ 5.91 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV_TR
Gain: $ 5.91 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV_TR
Gain: $ 8.56 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV
Gain: $ 8.56 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_RV
Gain: $ 8.56 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV
Gain: $ 8.56 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_RV
Gain: $ 8.56 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV
Gain: $ 8.56 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_RV
Gain: $ 8.56 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV
Gain: $ 8.56 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_RV
Gain: $ 8.62 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM
Gain: $ 8.62 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB1_CS1_HM
Gain: $ 8.62 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 8.62 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 8.62 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_HM
Gain: $ 8.62 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB3_CS3_HM
Gain: $ 8.62 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_HM
Gain: $ 8.62 Win %: 100.00 in 3 days with algo TB1_OC_QM_OB4_OS4_CB4_CS4_HM
BILI Gain: $ 0.01 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
BILI Gain: $ 0.02 Win %: 50.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_AV
BILI Gain: $ 0.03 Win %: 60.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_VI
BILI Gain: $ 0.06 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_AV_DB5
BILI Gain: $ 0.08 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ 0.08 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_TR_DB5
BILI Gain: $ 0.2 Win %: 44.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_TR
BILI Gain: $ 0.21 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_QP
BILI Gain: $ 0.21 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_QP_DB3
BILI Gain: $ 0.22 Win %: 37.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IR4
BILI Gain: $ 0.22 Win %: 50.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_AV
BILI Gain: $ 0.24 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_QP
BILI Gain: $ 0.25 Win %: 33.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BILI Gain: $ 0.26 Win %: 40.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
BILI Gain: $ 0.34 Win %: 33.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AV
BILI Gain: $ 0.34 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_QP
BILI Gain: $ 0.35 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV_DB4
BILI Gain: $ 0.36 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_TR
BILI Gain: $ 0.36 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_HM_AV
BILI Gain: $ 0.39 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_HM_AV
BILI Gain: $ 0.39 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_HM_AV
BILI Gain: $ 0.39 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BILI Gain: $ 0.4 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
BILI Gain: $ 0.4 Win %: 57.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_TR_DB5
BILI Gain: $ 0.45 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ 0.45 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 0.46 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP
BILI Gain: $ 0.49 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
BILI Gain: $ 0.49 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AV
BILI Gain: $ 0.5 Win %: 77.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
BILI Gain: $ 0.5 Win %: 77.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
BILI Gain: $ 0.54 Win %: 30.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ 0.54 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_TR_DB4
BILI Gain: $ 0.61 Win %: 57.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_QP_DB4
BILI Gain: $ 0.67 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_AV
BILI Gain: $ 0.67 Win %: 57.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR
BILI Gain: $ 0.67 Win %: 57.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR_DB4
BILI Gain: $ 0.67 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ 0.68 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
BILI Gain: $ 0.71 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IR3
BILI Gain: $ 0.71 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IR3
BILI Gain: $ 0.72 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
BILI Gain: $ 0.77 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
BILI Gain: $ 0.79 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_RV_AL
BILI Gain: $ 0.8 Win %: 41.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ 0.8 Win %: 41.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 0.81 Win %: 53.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 0.81 Win %: 60.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_HM
BILI Gain: $ 0.82 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_QP
BILI Gain: $ 0.85 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR
BILI Gain: $ 0.85 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
BILI Gain: $ 0.85 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
BILI Gain: $ 0.94 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_QP_IR4
BILI Gain: $ 0.97 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_HM_AV
BILI Gain: $ 0.97 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_HM_AV
BILI Gain: $ 0.98 Win %: 50.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_AV
BILI Gain: $ 1.01 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IR5
BILI Gain: $ 1.03 Win %: 33.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ 1.04 Win %: 50.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AV
BILI Gain: $ 1.05 Win %: 42.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_VI
BILI Gain: $ 1.05 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_VI
BILI Gain: $ 1.08 Win %: 69.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_VI
BILI Gain: $ 1.1 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_TR
BILI Gain: $ 1.11 Win %: 53.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_QP_IR4
BILI Gain: $ 1.11 Win %: 78.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QP
BILI Gain: $ 1.14 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_RV_AV
BILI Gain: $ 1.15 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IR3
BILI Gain: $ 1.15 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AV
BILI Gain: $ 1.18 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 1.2 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR_IR5
BILI Gain: $ 1.23 Win %: 61.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AV
BILI Gain: $ 1.32 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
BILI Gain: $ 1.32 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_AV
BILI Gain: $ 1.34 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_AL
BILI Gain: $ 1.36 Win %: 33.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AV
BILI Gain: $ 1.36 Win %: 33.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AV
BILI Gain: $ 1.38 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_VI
BILI Gain: $ 1.39 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
BILI Gain: $ 1.4 Win %: 58.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_HM_TR
BILI Gain: $ 1.5 Win %: 42.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 1.5 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR_QP
BILI Gain: $ 1.5 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR_QP_DB4
BILI Gain: $ 1.51 Win %: 57.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 1.52 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
BILI Gain: $ 1.53 Win %: 55.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_TR_IR4
BILI Gain: $ 1.55 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 1.59 Win %: 35.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AV
BILI Gain: $ 1.6 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
BILI Gain: $ 1.61 Win %: 77.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
BILI Gain: $ 1.62 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 1.65 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_TR
BILI Gain: $ 1.65 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_TR
BILI Gain: $ 1.65 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_TR
BILI Gain: $ 1.65 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_TR
BILI Gain: $ 1.65 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP
BILI Gain: $ 1.66 Win %: 38.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
BILI Gain: $ 1.67 Win %: 57.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_TR_IR4
BILI Gain: $ 1.7 Win %: 50.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AL
BILI Gain: $ 1.72 Win %: 69.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_TR_QP
BILI Gain: $ 1.72 Win %: 85.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QP_DB3
BILI Gain: $ 1.73 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_VI
BILI Gain: $ 1.75 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_LI
BILI Gain: $ 1.76 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
BILI Gain: $ 1.77 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_TR
BILI Gain: $ 1.77 Win %: 55.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR
BILI Gain: $ 1.77 Win %: 55.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_RV_TR_DB4
BILI Gain: $ 1.8 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
BILI Gain: $ 1.81 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IR3
BILI Gain: $ 1.88 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AL
BILI Gain: $ 1.88 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AL_DB3
BILI Gain: $ 1.9 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ 1.97 Win %: 56.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ 1.97 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_VI
BILI Gain: $ 2.01 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IR3
BILI Gain: $ 2.01 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IR3
BILI Gain: $ 2.03 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM
BILI Gain: $ 2.04 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IR3
BILI Gain: $ 2.07 Win %: 58.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_TR
BILI Gain: $ 2.14 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IR3
BILI Gain: $ 2.14 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_LI
BILI Gain: $ 2.17 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV
BILI Gain: $ 2.18 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_RV_AV
BILI Gain: $ 2.21 Win %: 44.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_VI
BILI Gain: $ 2.22 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ 2.22 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 2.24 Win %: 38.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM
BILI Gain: $ 2.26 Win %: 77.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
BILI Gain: $ 2.27 Win %: 56.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 2.28 Win %: 50.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_AV
BILI Gain: $ 2.29 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 2.3 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AV
BILI Gain: $ 2.3 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AV_DB4
BILI Gain: $ 2.3 Win %: 93.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_IT_QP
BILI Gain: $ 2.32 Win %: 58.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ 2.37 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB4
BILI Gain: $ 2.43 Win %: 66.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QL
BILI Gain: $ 2.44 Win %: 46.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ 2.47 Win %: 33.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_RV_TR_DB5
BILI Gain: $ 2.5 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_QP
BILI Gain: $ 2.55 Win %: 61.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_QP
BILI Gain: $ 2.56 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AL
BILI Gain: $ 2.57 Win %: 100.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QP
BILI Gain: $ 2.59 Win %: 61.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_LI
BILI Gain: $ 2.61 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_TR
BILI Gain: $ 2.61 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_TR
BILI Gain: $ 2.61 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR_QP_DB4
BILI Gain: $ 2.62 Win %: 68.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM
BILI Gain: $ 2.63 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR
BILI Gain: $ 2.64 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
BILI Gain: $ 2.64 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AV
BILI Gain: $ 2.64 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
BILI Gain: $ 2.64 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_AV
BILI Gain: $ 2.64 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_QP
BILI Gain: $ 2.65 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_RV_TR
BILI Gain: $ 2.66 Win %: 40.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_VI
BILI Gain: $ 2.66 Win %: 66.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_TR_QP
BILI Gain: $ 2.67 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_TR
BILI Gain: $ 2.67 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_TR_DB4
BILI Gain: $ 2.67 Win %: 75.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
BILI Gain: $ 2.67 Win %: 80.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
BILI Gain: $ 2.7 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
BILI Gain: $ 2.73 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV_DB4
BILI Gain: $ 2.74 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 2.75 Win %: 33.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_RV_TR
BILI Gain: $ 2.78 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_VI
BILI Gain: $ 2.78 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_VI
BILI Gain: $ 2.8 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR
BILI Gain: $ 2.81 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
BILI Gain: $ 2.86 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_HM_QP
BILI Gain: $ 2.87 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR
BILI Gain: $ 2.87 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
BILI Gain: $ 2.91 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_AL
BILI Gain: $ 2.92 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_TR
BILI Gain: $ 2.95 Win %: 56.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_VI
BILI Gain: $ 2.98 Win %: 35.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IR4
BILI Gain: $ 3 Win %: 81.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QP_DB4
BILI Gain: $ 3.02 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_RV_TR
BILI Gain: $ 3.02 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_RV_TR_DB5
BILI Gain: $ 3.02 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_RV_TR
BILI Gain: $ 3.02 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_RV_TR_DB5
BILI Gain: $ 3.02 Win %: 33.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_RV_TR
BILI Gain: $ 3.02 Win %: 92.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_IT_QP
BILI Gain: $ 3.09 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ 3.09 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 3.09 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 3.11 Win %: 57.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_VI
BILI Gain: $ 3.11 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_HM_QP
BILI Gain: $ 3.15 Win %: 66.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_QP_IR4
BILI Gain: $ 3.15 Win %: 73.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_QP
BILI Gain: $ 3.17 Win %: 50.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ 3.19 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_QP
BILI Gain: $ 3.2 Win %: 57.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 3.24 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
BILI Gain: $ 3.24 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
BILI Gain: $ 3.24 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_AV
BILI Gain: $ 3.24 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_AV
BILI Gain: $ 3.24 Win %: 68.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_TR_QP_DB4
BILI Gain: $ 3.29 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AV
BILI Gain: $ 3.3 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 3.31 Win %: 53.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ 3.31 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
BILI Gain: $ 3.31 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AV
BILI Gain: $ 3.35 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
BILI Gain: $ 3.36 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 3.36 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 3.36 Win %: 70.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_QP
BILI Gain: $ 3.38 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IR3
BILI Gain: $ 3.38 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
BILI Gain: $ 3.38 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
BILI Gain: $ 3.39 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_AV_DB4
BILI Gain: $ 3.4 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_QP
BILI Gain: $ 3.4 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_QP
BILI Gain: $ 3.43 Win %: 64.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM_TR
BILI Gain: $ 3.44 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_HM_QP
BILI Gain: $ 3.44 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_HM_QP
BILI Gain: $ 3.46 Win %: 56.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 3.47 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
BILI Gain: $ 3.47 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_AV
BILI Gain: $ 3.51 Win %: 62.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BILI Gain: $ 3.51 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_AV
BILI Gain: $ 3.59 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV
BILI Gain: $ 3.62 Win %: 55.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_QL
BILI Gain: $ 3.63 Win %: 42.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AV
BILI Gain: $ 3.63 Win %: 50.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 3.66 Win %: 43.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 3.66 Win %: 43.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL_DB4
BILI Gain: $ 3.71 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_TR
BILI Gain: $ 3.71 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_TR
BILI Gain: $ 3.74 Win %: 80.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_HM_AV
BILI Gain: $ 3.81 Win %: 100.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_IT_QP
BILI Gain: $ 3.81 Win %: 50.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM
BILI Gain: $ 3.83 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AV
BILI Gain: $ 3.84 Win %: 66.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_HM
BILI Gain: $ 3.85 Win %: 53.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_DB30
BILI Gain: $ 3.88 Win %: 50.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
BILI Gain: $ 3.88 Win %: 60.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AL
BILI Gain: $ 3.88 Win %: 60.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AL_DB5
BILI Gain: $ 3.89 Win %: 46.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AL
BILI Gain: $ 3.96 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ 4.03 Win %: 57.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IT_QL
BILI Gain: $ 4.03 Win %: 57.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IT_QL_DB5
BILI Gain: $ 4.04 Win %: 60.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_AV
BILI Gain: $ 4.05 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AV_DB4
BILI Gain: $ 4.06 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
BILI Gain: $ 4.07 Win %: 50.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_IR4
BILI Gain: $ 4.08 Win %: 43.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 4.19 Win %: 57.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR_DB4
BILI Gain: $ 4.2 Win %: 60.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_TR
BILI Gain: $ 4.21 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
BILI Gain: $ 4.24 Win %: 50.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_IR4
BILI Gain: $ 4.26 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ 4.26 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_RV_AL
BILI Gain: $ 4.26 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_TR_IR4
BILI Gain: $ 4.31 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
BILI Gain: $ 4.31 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
BILI Gain: $ 4.31 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR
BILI Gain: $ 4.31 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
BILI Gain: $ 4.31 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
BILI Gain: $ 4.32 Win %: 56.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_VI
BILI Gain: $ 4.34 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
BILI Gain: $ 4.35 Win %: 57.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AV
BILI Gain: $ 4.4 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_DB10
BILI Gain: $ 4.4 Win %: 61.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 4.43 Win %: 57.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QL_DB4
BILI Gain: $ 4.43 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM
BILI Gain: $ 4.47 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_VI
BILI Gain: $ 4.5 Win %: 46.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_QL
BILI Gain: $ 4.51 Win %: 46.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AV
BILI Gain: $ 4.51 Win %: 46.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AV_DB4
BILI Gain: $ 4.51 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
BILI Gain: $ 4.53 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ 4.55 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 4.58 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_TR_DB3
BILI Gain: $ 4.62 Win %: 40.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_VI
BILI Gain: $ 4.65 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_AV_DB3
BILI Gain: $ 4.69 Win %: 56.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ 4.72 Win %: 73.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_QP
BILI Gain: $ 4.73 Win %: 55.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_LI
BILI Gain: $ 4.74 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AL
BILI Gain: $ 4.76 Win %: 70.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BILI Gain: $ 4.77 Win %: 68.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_QP
BILI Gain: $ 4.8 Win %: 58.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
BILI Gain: $ 4.85 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 4.88 Win %: 57.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_TR
BILI Gain: $ 4.88 Win %: 58.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ 4.89 Win %: 61.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 4.92 Win %: 58.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
BILI Gain: $ 4.98 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
BILI Gain: $ 4.98 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
BILI Gain: $ 4.98 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR
BILI Gain: $ 4.98 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
BILI Gain: $ 4.98 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR
BILI Gain: $ 4.98 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
BILI Gain: $ 5.01 Win %: 40.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IR4
BILI Gain: $ 5.02 Win %: 57.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR
BILI Gain: $ 5.03 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BILI Gain: $ 5.11 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_TR
BILI Gain: $ 5.17 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM
BILI Gain: $ 5.18 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_TR
BILI Gain: $ 5.18 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_AV
BILI Gain: $ 5.26 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 5.28 Win %: 50.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ 5.28 Win %: 50.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 5.28 Win %: 50.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 5.3 Win %: 50.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_QL
BILI Gain: $ 5.31 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_RV_TR
BILI Gain: $ 5.31 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_RV_TR_DB5
BILI Gain: $ 5.31 Win %: 80.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_AV
BILI Gain: $ 5.34 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_LI
BILI Gain: $ 5.34 Win %: 66.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_HM
BILI Gain: $ 5.35 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ 5.35 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 5.35 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 5.37 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_RV_AV
BILI Gain: $ 5.37 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_RV_AV
BILI Gain: $ 5.37 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_RV_AV
BILI Gain: $ 5.37 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 5.37 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 5.45 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_LI
BILI Gain: $ 5.46 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM
BILI Gain: $ 5.46 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM
BILI Gain: $ 5.46 Win %: 40.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM
BILI Gain: $ 5.47 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
BILI Gain: $ 5.48 Win %: 58.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_AL
BILI Gain: $ 5.53 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AL
BILI Gain: $ 5.57 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_AV
BILI Gain: $ 5.67 Win %: 46.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 5.68 Win %: 70.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_AL
BILI Gain: $ 5.69 Win %: 57.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AL
BILI Gain: $ 5.7 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
BILI Gain: $ 5.72 Win %: 61.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IT
BILI Gain: $ 5.72 Win %: 64.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 5.74 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_HM_AV_DB4
BILI Gain: $ 5.75 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
BILI Gain: $ 5.77 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
BILI Gain: $ 5.78 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
BILI Gain: $ 5.78 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_TR
BILI Gain: $ 5.78 Win %: 57.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ 5.8 Win %: 66.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT
BILI Gain: $ 5.84 Win %: 46.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR_IR4
BILI Gain: $ 5.85 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ 5.93 Win %: 73.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_QP
BILI Gain: $ 5.95 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM
BILI Gain: $ 5.97 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
BILI Gain: $ 5.98 Win %: 46.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AV
BILI Gain: $ 5.98 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
BILI Gain: $ 5.99 Win %: 53.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 6.01 Win %: 71.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ 6.08 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ 6.08 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ 6.14 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 6.14 Win %: 70.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_TR_DB4
BILI Gain: $ 6.15 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5
BILI Gain: $ 6.18 Win %: 50.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AV
BILI Gain: $ 6.18 Win %: 50.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AV_DB4
BILI Gain: $ 6.18 Win %: 76.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ 6.19 Win %: 50.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_TR
BILI Gain: $ 6.25 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_RV_TR_DB5
BILI Gain: $ 6.25 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_RV_TR_DB5
BILI Gain: $ 6.29 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_TR
BILI Gain: $ 6.33 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_IT_QL
BILI Gain: $ 6.35 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
BILI Gain: $ 6.36 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_AL
BILI Gain: $ 6.37 Win %: 57.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AL_DB4
BILI Gain: $ 6.4 Win %: 55.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_AL
BILI Gain: $ 6.43 Win %: 61.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ 6.44 Win %: 57.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_DB30
BILI Gain: $ 6.46 Win %: 60.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
BILI Gain: $ 6.46 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_AV
BILI Gain: $ 6.46 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_AV
BILI Gain: $ 6.47 Win %: 62.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AL
BILI Gain: $ 6.52 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV
BILI Gain: $ 6.52 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV
BILI Gain: $ 6.52 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV
BILI Gain: $ 6.54 Win %: 61.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 6.54 Win %: 70.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 6.55 Win %: 58.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 6.55 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_LI
BILI Gain: $ 6.55 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_LI
BILI Gain: $ 6.58 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_RV_TR
BILI Gain: $ 6.58 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_RV_TR_DB5
BILI Gain: $ 6.58 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_RV_TR
BILI Gain: $ 6.58 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_RV_TR_DB5
BILI Gain: $ 6.58 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_AV
BILI Gain: $ 6.59 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
BILI Gain: $ 6.6 Win %: 46.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
BILI Gain: $ 6.61 Win %: 62.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 6.62 Win %: 53.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 6.65 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR_DB4
BILI Gain: $ 6.66 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_AL
BILI Gain: $ 6.68 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
BILI Gain: $ 6.68 Win %: 73.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM
BILI Gain: $ 6.69 Win %: 53.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_LI
BILI Gain: $ 6.71 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
BILI Gain: $ 6.72 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_TR
BILI Gain: $ 6.72 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_TR
BILI Gain: $ 6.77 Win %: 71.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 6.78 Win %: 70.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_TR
BILI Gain: $ 6.79 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM
BILI Gain: $ 6.85 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BILI Gain: $ 6.85 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 6.87 Win %: 56.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM_TR
BILI Gain: $ 6.88 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_AV
BILI Gain: $ 6.88 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_AV
BILI Gain: $ 6.88 Win %: 50.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_AV
BILI Gain: $ 6.94 Win %: 62.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5
BILI Gain: $ 6.95 Win %: 58.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 7 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
BILI Gain: $ 7.01 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ 7.03 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM
BILI Gain: $ 7.06 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 7.06 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 7.12 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_SS
BILI Gain: $ 7.13 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV
BILI Gain: $ 7.13 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV
BILI Gain: $ 7.18 Win %: 56.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ 7.18 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QL_DB3
BILI Gain: $ 7.19 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV
BILI Gain: $ 7.2 Win %: 56.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AL
BILI Gain: $ 7.2 Win %: 56.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AL_DB4
BILI Gain: $ 7.23 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM
BILI Gain: $ 7.23 Win %: 46.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM
BILI Gain: $ 7.24 Win %: 73.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QL_DB5
BILI Gain: $ 7.25 Win %: 71.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ 7.26 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 7.26 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 7.34 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_AL
BILI Gain: $ 7.35 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
BILI Gain: $ 7.4 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL_DB4
BILI Gain: $ 7.42 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ 7.42 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR_DB4
BILI Gain: $ 7.43 Win %: 61.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ 7.43 Win %: 62.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AL_DB5
BILI Gain: $ 7.48 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_IT_QL
BILI Gain: $ 7.5 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV
BILI Gain: $ 7.51 Win %: 50.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV
BILI Gain: $ 7.52 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QL_DB4
BILI Gain: $ 7.52 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_SS
BILI Gain: $ 7.58 Win %: 61.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
BILI Gain: $ 7.61 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
BILI Gain: $ 7.61 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_TR
BILI Gain: $ 7.65 Win %: 46.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_TR_IR4
BILI Gain: $ 7.66 Win %: 64.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IT
BILI Gain: $ 7.67 Win %: 50.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR_IR4
BILI Gain: $ 7.68 Win %: 60.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_QL
BILI Gain: $ 7.69 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5
BILI Gain: $ 7.75 Win %: 84.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
BILI Gain: $ 7.76 Win %: 46.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM
BILI Gain: $ 7.78 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_DB15
BILI Gain: $ 7.8 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_TR
BILI Gain: $ 7.82 Win %: 53.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ 7.83 Win %: 66.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_AL
BILI Gain: $ 7.86 Win %: 50.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AV_DB4
BILI Gain: $ 7.87 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_IT
BILI Gain: $ 7.87 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_IT
BILI Gain: $ 7.9 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
BILI Gain: $ 7.93 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 8 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV_AV
BILI Gain: $ 8.01 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ 8.05 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ 8.08 Win %: 64.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 8.12 Win %: 46.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 8.13 Win %: 53.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 8.13 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 8.14 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 8.15 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_AL
BILI Gain: $ 8.15 Win %: 66.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 8.19 Win %: 61.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV
BILI Gain: $ 8.19 Win %: 64.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
BILI Gain: $ 8.27 Win %: 57.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 8.29 Win %: 62.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BILI Gain: $ 8.29 Win %: 62.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL_DB4
BILI Gain: $ 8.3 Win %: 61.00 in 13 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IT_QL
BILI Gain: $ 8.31 Win %: 53.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_AL
BILI Gain: $ 8.32 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QL
BILI Gain: $ 8.32 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QL_DB4
BILI Gain: $ 8.35 Win %: 75.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QL_DB5
BILI Gain: $ 8.38 Win %: 75.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
BILI Gain: $ 8.4 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
BILI Gain: $ 8.46 Win %: 64.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 8.46 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5
BILI Gain: $ 8.51 Win %: 57.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR4
BILI Gain: $ 8.54 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT
BILI Gain: $ 8.58 Win %: 57.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_AL_DB5
BILI Gain: $ 8.59 Win %: 53.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ 8.66 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BILI Gain: $ 8.68 Win %: 64.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL_DB4
BILI Gain: $ 8.73 Win %: 50.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_TR_DB4
BILI Gain: $ 8.73 Win %: 50.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_TR_DB4
BILI Gain: $ 8.75 Win %: 71.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BILI Gain: $ 8.76 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_TR_IR5
BILI Gain: $ 8.76 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_TR_IR5
BILI Gain: $ 8.81 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM
BILI Gain: $ 8.82 Win %: 46.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 8.87 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IT
BILI Gain: $ 8.87 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BILI Gain: $ 8.87 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BILI Gain: $ 8.91 Win %: 53.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_TR
BILI Gain: $ 8.95 Win %: 60.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_TR
BILI Gain: $ 8.95 Win %: 66.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_AL
BILI Gain: $ 9 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR_IR4
BILI Gain: $ 9 Win %: 75.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
BILI Gain: $ 9.02 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_RV
BILI Gain: $ 9.04 Win %: 57.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_QL
BILI Gain: $ 9.04 Win %: 66.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
BILI Gain: $ 9.06 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 9.07 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_RV
BILI Gain: $ 9.09 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_DB10
BILI Gain: $ 9.09 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_DB10
BILI Gain: $ 9.09 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_DB10
BILI Gain: $ 9.09 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_DB10
BILI Gain: $ 9.12 Win %: 53.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_AV
BILI Gain: $ 9.12 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT
BILI Gain: $ 9.16 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_AL_DB4
BILI Gain: $ 9.22 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_RV
BILI Gain: $ 9.24 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
BILI Gain: $ 9.26 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_TR
BILI Gain: $ 9.28 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_DB30
BILI Gain: $ 9.29 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV
BILI Gain: $ 9.31 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
BILI Gain: $ 9.34 Win %: 55.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
BILI Gain: $ 9.36 Win %: 75.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QL
BILI Gain: $ 9.4 Win %: 73.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_LI
BILI Gain: $ 9.41 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR
BILI Gain: $ 9.45 Win %: 64.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 9.45 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_RV_AL
BILI Gain: $ 9.45 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_RV_AL
BILI Gain: $ 9.52 Win %: 68.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT
BILI Gain: $ 9.54 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QL
BILI Gain: $ 9.55 Win %: 55.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_RV
BILI Gain: $ 9.58 Win %: 46.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 9.58 Win %: 46.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL_DB4
BILI Gain: $ 9.6 Win %: 71.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT
BILI Gain: $ 9.66 Win %: 73.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_LI
BILI Gain: $ 9.66 Win %: 73.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_LI
BILI Gain: $ 9.67 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_AL
BILI Gain: $ 9.67 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_AL
BILI Gain: $ 9.7 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_IR5
BILI Gain: $ 9.71 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AL
BILI Gain: $ 9.74 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_AL
BILI Gain: $ 9.74 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_AL
BILI Gain: $ 9.76 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_AV
BILI Gain: $ 9.76 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_AV
BILI Gain: $ 9.77 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_SS
BILI Gain: $ 9.78 Win %: 50.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM_AV
BILI Gain: $ 9.79 Win %: 64.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_AL
BILI Gain: $ 9.84 Win %: 57.00 in 14 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR
BILI Gain: $ 9.84 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QL_DB4
BILI Gain: $ 9.85 Win %: 56.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_LI
BILI Gain: $ 9.89 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
BILI Gain: $ 9.89 Win %: 88.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_AV
BILI Gain: $ 9.91 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AL
BILI Gain: $ 9.91 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AL
BILI Gain: $ 9.96 Win %: 100.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
BILI Gain: $ 9.96 Win %: 73.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_LI
BILI Gain: $ 10 Win %: 50.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM_AV
BILI Gain: $ 10.01 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
BILI Gain: $ 10.01 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AL
BILI Gain: $ 10.08 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_IR5
BILI Gain: $ 10.1 Win %: 70.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 10.11 Win %: 58.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_DB15
BILI Gain: $ 10.12 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_AV
BILI Gain: $ 10.18 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QL_DB4
BILI Gain: $ 10.21 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_HM
BILI Gain: $ 10.21 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_HM
BILI Gain: $ 10.22 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 10.25 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
BILI Gain: $ 10.26 Win %: 76.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_LI
BILI Gain: $ 10.26 Win %: 76.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_LI
BILI Gain: $ 10.28 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_AV
BILI Gain: $ 10.28 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_AV_DB4
BILI Gain: $ 10.3 Win %: 77.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
BILI Gain: $ 10.32 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5
BILI Gain: $ 10.32 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
BILI Gain: $ 10.32 Win %: 78.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_LI
BILI Gain: $ 10.32 Win %: 78.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_LI
BILI Gain: $ 10.33 Win %: 61.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR
BILI Gain: $ 10.33 Win %: 61.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR_DB4
BILI Gain: $ 10.36 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_IT_QL
BILI Gain: $ 10.37 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_DB15
BILI Gain: $ 10.43 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
BILI Gain: $ 10.44 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 10.45 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
BILI Gain: $ 10.54 Win %: 61.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_HM_TR
BILI Gain: $ 10.57 Win %: 68.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_LI
BILI Gain: $ 10.58 Win %: 80.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
BILI Gain: $ 10.63 Win %: 53.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_IR4
BILI Gain: $ 10.66 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_DB10
BILI Gain: $ 10.67 Win %: 53.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
BILI Gain: $ 10.67 Win %: 53.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BILI Gain: $ 10.67 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_AV
BILI Gain: $ 10.69 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AL
BILI Gain: $ 10.69 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_TR_IR5
BILI Gain: $ 10.69 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_TR_IR5
BILI Gain: $ 10.82 Win %: 71.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 10.83 Win %: 62.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_AL
BILI Gain: $ 10.85 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_DB30
BILI Gain: $ 10.85 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_RV
BILI Gain: $ 10.86 Win %: 70.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 10.9 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
BILI Gain: $ 10.9 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_AL
BILI Gain: $ 10.9 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_AL
BILI Gain: $ 10.91 Win %: 64.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM
BILI Gain: $ 10.92 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AL
BILI Gain: $ 10.92 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AL_DB4
BILI Gain: $ 10.92 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AL
BILI Gain: $ 10.93 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_HM
BILI Gain: $ 10.99 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_TR
BILI Gain: $ 10.99 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_TR_DB4
BILI Gain: $ 11 Win %: 75.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ 11.01 Win %: 66.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_IR4
BILI Gain: $ 11.03 Win %: 62.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR_DB4
BILI Gain: $ 11.04 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_HM
BILI Gain: $ 11.05 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM_TR_DB4
BILI Gain: $ 11.07 Win %: 53.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QL
BILI Gain: $ 11.07 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_QL
BILI Gain: $ 11.09 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL_DB4
BILI Gain: $ 11.09 Win %: 77.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_IR4
BILI Gain: $ 11.16 Win %: 70.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_SS
BILI Gain: $ 11.18 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_AL
BILI Gain: $ 11.21 Win %: 46.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 11.24 Win %: 56.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR
BILI Gain: $ 11.24 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QL
BILI Gain: $ 11.25 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_LI
BILI Gain: $ 11.25 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_LI
BILI Gain: $ 11.25 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_LI
BILI Gain: $ 11.25 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_LI
BILI Gain: $ 11.32 Win %: 53.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_SS
BILI Gain: $ 11.32 Win %: 66.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
BILI Gain: $ 11.41 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 11.41 Win %: 53.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 11.42 Win %: 66.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_SS
BILI Gain: $ 11.46 Win %: 71.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 11.64 Win %: 70.00 in 10 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_DB15
BILI Gain: $ 11.65 Win %: 83.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_HM_AV
BILI Gain: $ 11.66 Win %: 66.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
BILI Gain: $ 11.69 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 11.7 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QL
BILI Gain: $ 11.7 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
BILI Gain: $ 11.73 Win %: 75.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IR4
BILI Gain: $ 11.74 Win %: 70.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_IR4
BILI Gain: $ 11.77 Win %: 58.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_RV
BILI Gain: $ 11.81 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BILI Gain: $ 11.81 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BILI Gain: $ 11.83 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AL
BILI Gain: $ 11.86 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AL
BILI Gain: $ 11.94 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_DB10
BILI Gain: $ 11.96 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_IT_QL
BILI Gain: $ 11.97 Win %: 75.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM
BILI Gain: $ 12.03 Win %: 66.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_RV
BILI Gain: $ 12.05 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_AV
BILI Gain: $ 12.05 Win %: 44.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_AV
BILI Gain: $ 12.06 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AL
BILI Gain: $ 12.06 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BILI Gain: $ 12.06 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_DB30
BILI Gain: $ 12.08 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_HM
BILI Gain: $ 12.11 Win %: 62.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_TR_DB5
BILI Gain: $ 12.11 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_IR5
BILI Gain: $ 12.11 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_IR5
BILI Gain: $ 12.16 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
BILI Gain: $ 12.16 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AL
BILI Gain: $ 12.17 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_DB30
BILI Gain: $ 12.19 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_RV
BILI Gain: $ 12.2 Win %: 61.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_HM_AV
BILI Gain: $ 12.21 Win %: 56.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV
BILI Gain: $ 12.25 Win %: 69.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT
BILI Gain: $ 12.26 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR
BILI Gain: $ 12.26 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR
BILI Gain: $ 12.26 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR
BILI Gain: $ 12.26 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR
BILI Gain: $ 12.28 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
BILI Gain: $ 12.29 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT
BILI Gain: $ 12.3 Win %: 68.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_TR_IR4
BILI Gain: $ 12.34 Win %: 75.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 12.35 Win %: 68.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV
BILI Gain: $ 12.36 Win %: 60.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 12.4 Win %: 66.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_DB15
BILI Gain: $ 12.41 Win %: 69.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QL
BILI Gain: $ 12.44 Win %: 58.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
BILI Gain: $ 12.44 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_LI
BILI Gain: $ 12.44 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_LI
BILI Gain: $ 12.47 Win %: 66.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
BILI Gain: $ 12.5 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QL
BILI Gain: $ 12.5 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QL
BILI Gain: $ 12.5 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QL
BILI Gain: $ 12.56 Win %: 66.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_QL
BILI Gain: $ 12.56 Win %: 76.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 12.57 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR
BILI Gain: $ 12.58 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_SS
BILI Gain: $ 12.61 Win %: 53.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_QL
BILI Gain: $ 12.61 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QL
BILI Gain: $ 12.61 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QL
BILI Gain: $ 12.61 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QL
BILI Gain: $ 12.61 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT_QL
BILI Gain: $ 12.61 Win %: 68.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_DB15
BILI Gain: $ 12.63 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_DB10
BILI Gain: $ 12.64 Win %: 61.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_TR
BILI Gain: $ 12.65 Win %: 56.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_QL
BILI Gain: $ 12.78 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB2_CS2_QL
BILI Gain: $ 12.83 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
BILI Gain: $ 12.83 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
BILI Gain: $ 12.83 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AL
BILI Gain: $ 12.83 Win %: 60.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AL
BILI Gain: $ 12.83 Win %: 77.00 in 9 days with algo TB2_HL_HS_QM_OB5_OS5_CB3_CS3_RV
BILI Gain: $ 12.84 Win %: 66.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_SS
BILI Gain: $ 12.88 Win %: 62.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_HM_TR
BILI Gain: $ 12.94 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
BILI Gain: $ 12.96 Win %: 53.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_LI
BILI Gain: $ 13 Win %: 86.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT
BILI Gain: $ 13.07 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_TR
BILI Gain: $ 13.09 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_AL
BILI Gain: $ 13.14 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_RV_AL
BILI Gain: $ 13.16 Win %: 64.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 13.18 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AL
BILI Gain: $ 13.22 Win %: 69.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_HM
BILI Gain: $ 13.22 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB1_CS1_SS
BILI Gain: $ 13.47 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM
BILI Gain: $ 13.48 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QL
BILI Gain: $ 13.52 Win %: 56.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_AL
BILI Gain: $ 13.52 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT
BILI Gain: $ 13.53 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AL_DB4
BILI Gain: $ 13.55 Win %: 50.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 13.55 Win %: 50.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 13.55 Win %: 64.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV
BILI Gain: $ 13.6 Win %: 68.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_SS
BILI Gain: $ 13.67 Win %: 77.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_DB15
BILI Gain: $ 13.67 Win %: 77.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_SS
BILI Gain: $ 13.7 Win %: 75.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_HM
BILI Gain: $ 13.74 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_AL
BILI Gain: $ 13.76 Win %: 66.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
BILI Gain: $ 13.77 Win %: 71.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
BILI Gain: $ 13.78 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
BILI Gain: $ 13.79 Win %: 71.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_IR4
BILI Gain: $ 13.82 Win %: 66.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV
BILI Gain: $ 13.83 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR
BILI Gain: $ 13.83 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR
BILI Gain: $ 13.91 Win %: 80.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BILI Gain: $ 13.92 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
BILI Gain: $ 13.94 Win %: 77.00 in 9 days with algo TB2_EO_EC_QM_OB3_OS3_CB5_CS5_QL
BILI Gain: $ 13.99 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_QL
BILI Gain: $ 14.07 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QL
BILI Gain: $ 14.07 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QL
BILI Gain: $ 14.09 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR
BILI Gain: $ 14.09 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR
BILI Gain: $ 14.1 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_QL
BILI Gain: $ 14.12 Win %: 60.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR
BILI Gain: $ 14.12 Win %: 60.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR_DB5
BILI Gain: $ 14.12 Win %: 88.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
BILI Gain: $ 14.14 Win %: 66.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
BILI Gain: $ 14.14 Win %: 73.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV
BILI Gain: $ 14.2 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
BILI Gain: $ 14.25 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR
BILI Gain: $ 14.27 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QL
BILI Gain: $ 14.27 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QL
BILI Gain: $ 14.27 Win %: 70.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BILI Gain: $ 14.33 Win %: 60.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR_DB5
BILI Gain: $ 14.33 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB4_CS4_SS
BILI Gain: $ 14.38 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_IR4
BILI Gain: $ 14.38 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_IR4
BILI Gain: $ 14.4 Win %: 68.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV
BILI Gain: $ 14.42 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5
BILI Gain: $ 14.42 Win %: 53.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5
BILI Gain: $ 14.44 Win %: 77.00 in 9 days with algo TB1_HL_LO_QM_OB4_OS4_CB3_CS3_SS
BILI Gain: $ 14.51 Win %: 81.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IT
BILI Gain: $ 14.52 Win %: 66.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 14.53 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IT
BILI Gain: $ 14.53 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_IT
BILI Gain: $ 14.6 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_SS
BILI Gain: $ 14.6 Win %: 78.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_LI
BILI Gain: $ 14.64 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_QL
BILI Gain: $ 14.64 Win %: 75.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_IR4
BILI Gain: $ 14.71 Win %: 56.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_TR
BILI Gain: $ 14.71 Win %: 56.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_TR_DB4
BILI Gain: $ 14.71 Win %: 56.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_TR_DB4
BILI Gain: $ 14.79 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_QL
BILI Gain: $ 14.9 Win %: 56.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM_AV_DB4
BILI Gain: $ 14.96 Win %: 69.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 14.99 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_TR
BILI Gain: $ 15.02 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 15.02 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 15.17 Win %: 69.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_SS
BILI Gain: $ 15.24 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_RV
BILI Gain: $ 15.24 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_RV
BILI Gain: $ 15.24 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_RV
BILI Gain: $ 15.24 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_TR_DB4
BILI Gain: $ 15.24 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_TR_DB4
BILI Gain: $ 15.27 Win %: 83.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
BILI Gain: $ 15.32 Win %: 80.00 in 10 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 15.36 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_HM
BILI Gain: $ 15.36 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_HM
BILI Gain: $ 15.42 Win %: 68.00 in 16 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 15.44 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_SS
BILI Gain: $ 15.44 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_SS
BILI Gain: $ 15.45 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
BILI Gain: $ 15.46 Win %: 66.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
BILI Gain: $ 15.46 Win %: 68.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_IT
BILI Gain: $ 15.48 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
BILI Gain: $ 15.52 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_HM
BILI Gain: $ 15.6 Win %: 71.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5
BILI Gain: $ 15.71 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_QL
BILI Gain: $ 15.71 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_QL
BILI Gain: $ 15.71 Win %: 64.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_AL
BILI Gain: $ 15.71 Win %: 73.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV
BILI Gain: $ 15.76 Win %: 66.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BILI Gain: $ 15.83 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_SS
BILI Gain: $ 15.83 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_SS
BILI Gain: $ 15.83 Win %: 83.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_SS
BILI Gain: $ 15.87 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_DB15
BILI Gain: $ 15.89 Win %: 80.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_LI
BILI Gain: $ 15.93 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
BILI Gain: $ 15.93 Win %: 76.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_DB15
BILI Gain: $ 15.99 Win %: 57.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 15.99 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5
BILI Gain: $ 16.01 Win %: 69.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_IT
BILI Gain: $ 16.01 Win %: 69.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_IT_QL
BILI Gain: $ 16.02 Win %: 75.00 in 12 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_AV
BILI Gain: $ 16.07 Win %: 61.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5
BILI Gain: $ 16.31 Win %: 66.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
BILI Gain: $ 16.32 Win %: 66.00 in 15 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IR4
BILI Gain: $ 16.33 Win %: 84.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
BILI Gain: $ 16.39 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4
BILI Gain: $ 16.48 Win %: 70.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_QL
BILI Gain: $ 16.49 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_DB30
BILI Gain: $ 16.49 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB2_OS2_CB4_CS4_QL
BILI Gain: $ 16.49 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_DB30
BILI Gain: $ 16.49 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB3_OS3_CB4_CS4_QL
BILI Gain: $ 16.49 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB3_CS3_DB30
BILI Gain: $ 16.49 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_DB30
BILI Gain: $ 16.49 Win %: 100.00 in 6 days with algo TB1_CC_QM_OB4_OS4_CB4_CS4_QL
BILI Gain: $ 16.62 Win %: 71.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_SS
BILI Gain: $ 16.67 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_AL
BILI Gain: $ 16.67 Win %: 60.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV_AL
BILI Gain: $ 16.85 Win %: 64.00 in 14 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_LI
BILI Gain: $ 16.95 Win %: 73.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_RV
BILI Gain: $ 16.96 Win %: 76.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5
BILI Gain: $ 16.96 Win %: 76.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 16.99 Win %: 69.00 in 13 days with algo TB2_HL_HS_QM_OB3_OS3_CB5_CS5_QL
BILI Gain: $ 17.06 Win %: 56.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_SS
BILI Gain: $ 17.13 Win %: 60.00 in 15 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_RV_TR_DB4
BILI Gain: $ 17.2 Win %: 68.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_IR4
BILI Gain: $ 17.46 Win %: 62.00 in 16 days with algo TB2_HS_QM_OB5_OS5_CB2_CS2_LI
BILI Gain: $ 17.49 Win %: 61.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV
BILI Gain: $ 17.55 Win %: 62.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_TR
BILI Gain: $ 17.55 Win %: 69.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_AL
BILI Gain: $ 17.62 Win %: 64.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_QL
BILI Gain: $ 17.82 Win %: 76.00 in 13 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 17.88 Win %: 66.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
BILI Gain: $ 17.96 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 17.96 Win %: 73.00 in 15 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 17.99 Win %: 77.00 in 9 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
BILI Gain: $ 18.08 Win %: 73.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_TR_IR5
BILI Gain: $ 18.21 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_SS
BILI Gain: $ 18.24 Win %: 83.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
BILI Gain: $ 18.37 Win %: 66.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_SS
BILI Gain: $ 18.5 Win %: 68.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR_DB4
BILI Gain: $ 18.51 Win %: 83.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_LI
BILI Gain: $ 18.6 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_SS
BILI Gain: $ 18.79 Win %: 62.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_TR
BILI Gain: $ 18.85 Win %: 68.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR_DB4
BILI Gain: $ 18.85 Win %: 78.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 18.9 Win %: 83.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
BILI Gain: $ 18.91 Win %: 76.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_SS
BILI Gain: $ 19.15 Win %: 68.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR
BILI Gain: $ 19.34 Win %: 80.00 in 10 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_DB15
BILI Gain: $ 19.43 Win %: 81.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_LI
BILI Gain: $ 19.71 Win %: 62.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR_DB5
BILI Gain: $ 19.71 Win %: 62.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_RV_TR_DB5
BILI Gain: $ 19.71 Win %: 78.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 19.82 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_SS
BILI Gain: $ 19.82 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_SS
BILI Gain: $ 19.87 Win %: 83.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5
BILI Gain: $ 19.87 Win %: 83.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_DB15
BILI Gain: $ 19.87 Win %: 83.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_SS
BILI Gain: $ 20.14 Win %: 83.00 in 12 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QL
BILI Gain: $ 20.31 Win %: 75.00 in 12 days with algo TB2_EO_EC_QM_OB2_OS2_CB5_CS5_DB15
BILI Gain: $ 20.72 Win %: 75.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
BILI Gain: $ 20.91 Win %: 66.00 in 15 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_SS
BILI Gain: $ 21.39 Win %: 71.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_SS
BILI Gain: $ 21.46 Win %: 76.00 in 13 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_SS
BILI Gain: $ 21.57 Win %: 75.00 in 12 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
BILI Gain: $ 21.59 Win %: 76.00 in 13 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_SS
BILI Gain: $ 23.14 Win %: 75.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_TR_IR5
BILI Gain: $ 23.26 Win %: 73.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_DB15
BILI Gain: $ 23.82 Win %: 78.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_SS
BILI Gain: $ 23.95 Win %: 78.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_DB15
BILI Gain: $ 24.71 Win %: 80.00 in 15 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IR5
BILI Gain: $ 25.37 Win %: 80.00 in 15 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_DB15
BILI Gain: $ 26.73 Win %: 81.00 in 16 days with algo TB1_HL_LO_QM_OB5_OS5_CB5_CS5_IR5
BILI Gain: $ 28.41 Win %: 81.00 in 16 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_DB15
BILI Gain: $ 96.38 Win %: 42.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
BILI Gain: $ 98.54 Win %: 35.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
BILI Gain: $ 99.12 Win %: 35.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
BILI Gain: $ 103.56 Win %: 57.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_RV_QP
BILI Gain: $ 104.8 Win %: 50.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP
BILI Gain: $ 106.75 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
BILI Gain: $ 106.75 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_HM_QP
BILI Gain: $ 107.16 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
BILI Gain: $ 107.16 Win %: 64.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_RV_QP
BILI Gain: $ 107.59 Win %: 64.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_HM_QP
BILI Gain: $ 107.98 Win %: 57.00 in 14 days with algo TB2_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR4
BILI Gain: $ 108.72 Win %: 57.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_QP_IR4
BILI Gain: $ 109.05 Win %: 78.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_TR_QP
BILI Gain: $ 109.49 Win %: 42.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IR3
BILI Gain: $ 110.33 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
BILI Gain: $ 110.33 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP_IR3
BILI Gain: $ 111.61 Win %: 50.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_QP
BILI Gain: $ 113.76 Win %: 78.00 in 14 days with algo TB2_HL_LO_QM_OB5_OS5_CB5_CS5_QP
BILI Gain: $ 114.36 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
BILI Gain: $ 114.36 Win %: 57.00 in 14 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_TR_QP
