BJ Gain: $ -4.79 Win %: 0 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_TR_IR4
BJ Gain: $ -3.99 Win %: 0 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_TR_QP
BJ Gain: $ -3.99 Win %: 0 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_TR_QP
BJ Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_AV
BJ Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_AV
BJ Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM_AV
BJ Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM_AV
BJ Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_AV
BJ Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_AV
BJ Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM_AV
BJ Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM_AV
BJ Gain: $ -2.75 Win %: 0 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_TR_QP
BJ Gain: $ -2.75 Win %: 0 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_TR_QP
BJ Gain: $ -2.28 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_QP_IR4
BJ Gain: $ -2.28 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_QP_IR4
BJ Gain: $ -2.15 Win %: 0 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_AV
BJ Gain: $ -2.15 Win %: 0 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_AV
BJ Gain: $ -2.13 Win %: 0 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_AV
BJ Gain: $ -2.13 Win %: 0 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_AV
BJ Gain: $ -1.89 Win %: 0 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_HM_TR
BJ Gain: $ -1.73 Win %: 0 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_QP_IR3
BJ Gain: $ -1.73 Win %: 0 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_QP_IR3
BJ Gain: $ -1.61 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_AV
BJ Gain: $ -1.61 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_AV
BJ Gain: $ -1.61 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_AV
BJ Gain: $ -1.61 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_AV
BJ Gain: $ -1.5 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_AV
BJ Gain: $ -1.5 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_AV
BJ Gain: $ -1.5 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_HM_AV
BJ Gain: $ -1.5 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_HM_AV
BJ Gain: $ -1.47 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_QP
BJ Gain: $ -1.47 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_QP
BJ Gain: $ -1.37 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_HM_QP
BJ Gain: $ -1.37 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_HM_QP
BJ Gain: $ -1.37 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_QP
BJ Gain: $ -1.37 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_QP
BJ Gain: $ -1.36 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_QP
BJ Gain: $ -1.36 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_QP
BJ Gain: $ -1.34 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_HM_AV
BJ Gain: $ -1.34 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_HM_AV
BJ Gain: $ -0.56 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_VI
BJ Gain: $ -0.56 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_VI
BJ Gain: $ -0.56 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_VI
BJ Gain: $ -0.56 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_VI
BJ Gain: $ -0.55 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_QP
BJ Gain: $ -0.55 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_QP
BJ Gain: $ -0.54 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_HM_QP
BJ Gain: $ -0.54 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_HM_QP
BJ Gain: $ -0.52 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_TR_IR4
BJ Gain: $ -0.4 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_VI
BJ Gain: $ -0.4 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_VI
BJ Gain: $ -0.31 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_AV
BJ Gain: $ -0.31 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_AV
BJ Gain: $ -0.24 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_IR4
BJ Gain: $ -0.24 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_IR4
BJ Gain: $ -0.13 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_VI
BJ Gain: $ -0.13 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_VI
BJ Gain: $ -0.03 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_DB15
BJ Gain: $ -0.03 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_DB15
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_QP_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_QP_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_TR_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_TR_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_QP_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_QP_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_TR_IR4
BJ Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_TR_IR4
Gain: $ -0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_VI
Gain: $ -0.3 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_VI
Gain: $ -0.56 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_VI
Gain: $ -0.56 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_VI
Gain: $ -1.61 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_RV_AV
Gain: $ -1.61 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_AV
Gain: $ -1.61 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_AV
Gain: $ -1.61 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_RV_AV
Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_AV
Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_HM_AV
Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_AV
Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM_AV
Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_AV
Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM_AV
Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_AV
Gain: $ -2.91 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_HM_AV
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_TR_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_TR_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_TR_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_TR_IR5
Gain: $ 0.14 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_TR_QP
Gain: $ 0.14 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_TR_QP
Gain: $ 0.14 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_TR_QP
Gain: $ 0.14 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_TR_QP
Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM_QP
Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_QP
Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM_QP
Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_QP
Gain: $ 0.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_QP
Gain: $ 0.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_QP
Gain: $ 0.48 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_HM_QP
Gain: $ 0.48 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_HM_QP
Gain: $ 0.48 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_QP
Gain: $ 0.48 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_HM_QP
Gain: $ 0.48 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_QP
Gain: $ 0.54 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_RV_QP
Gain: $ 0.54 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_RV_QP
Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_HM_TR
Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_TR
Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM_TR
Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_TR
Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM_TR
Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_TR
Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_HM_TR
Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_TR
Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_RV_TR
Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_TR
Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_TR
Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_RV_TR
Gain: $ 1.46 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_LI
Gain: $ 1.46 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_LI
Gain: $ 1.56 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_LI
Gain: $ 1.97 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_AL
Gain: $ 1.97 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_AL
Gain: $ 2.01 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_LI
Gain: $ 2.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_AL
Gain: $ 2.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_AL
Gain: $ 2.95 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_DB15
Gain: $ 2.95 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_HM
Gain: $ 2.95 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_QL
Gain: $ 2.95 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_SS
Gain: $ 2.95 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_DB15
Gain: $ 2.95 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_HM
Gain: $ 2.95 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_QL
Gain: $ 2.95 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_SS
Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_DB15
Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM
Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_QL
Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_SS
Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2
Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_DB15
Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM
Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_QL
Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_SS
Gain: $ 3.14 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV
Gain: $ 3.14 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV
Gain: $ 3.25 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB2_OS2_CB3_CS3_RV
Gain: $ 3.25 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB3_CS3_RV
BJ Gain: $ 0.12 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_IT_QP
BJ Gain: $ 0.14 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_IT_QP
BJ Gain: $ 0.14 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_TR_QP
BJ Gain: $ 0.14 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_TR_QP
BJ Gain: $ 0.14 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_TR_QP
BJ Gain: $ 0.14 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_TR_QP
BJ Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM_QP
BJ Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM_QP
BJ Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_QP
BJ Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_QP
BJ Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM_QP
BJ Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM_QP
BJ Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_QP
BJ Gain: $ 0.15 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_QP
BJ Gain: $ 0.17 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_IT_QP
BJ Gain: $ 0.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_QP
BJ Gain: $ 0.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_QP
BJ Gain: $ 0.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_QP
BJ Gain: $ 0.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_QP
BJ Gain: $ 0.22 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_IT_QP
BJ Gain: $ 0.22 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_IT_QP
BJ Gain: $ 0.26 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_IT_QP
BJ Gain: $ 0.26 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_IT_QP
BJ Gain: $ 0.26 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_HM_TR
BJ Gain: $ 0.26 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_TR
BJ Gain: $ 0.26 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_TR
BJ Gain: $ 0.27 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_TR
BJ Gain: $ 0.27 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_TR
BJ Gain: $ 0.27 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BJ Gain: $ 0.27 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_TR_DB4
BJ Gain: $ 0.31 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_IT_QP
BJ Gain: $ 0.31 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_IT_QP
BJ Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_TR
BJ Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_TR
BJ Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_TR_DB3
BJ Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_TR_DB3
BJ Gain: $ 0.61 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_IT
BJ Gain: $ 0.61 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_IT_QL
BJ Gain: $ 0.73 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_IT
BJ Gain: $ 0.73 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_IT_QL
BJ Gain: $ 0.75 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_TR
BJ Gain: $ 0.75 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_TR
BJ Gain: $ 0.85 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_LI
BJ Gain: $ 0.85 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_LI
BJ Gain: $ 0.86 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_IT
BJ Gain: $ 0.86 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_IT_QL
BJ Gain: $ 0.96 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_LI
BJ Gain: $ 0.96 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_LI
BJ Gain: $ 0.96 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_DB10
BJ Gain: $ 0.96 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_DB10
BJ Gain: $ 0.97 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_HM_TR
BJ Gain: $ 0.97 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_HM_TR
BJ Gain: $ 0.98 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_AL
BJ Gain: $ 0.98 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV_AL
BJ Gain: $ 0.99 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_TR_IR3
BJ Gain: $ 0.99 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_TR_IR3
BJ Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM_TR
BJ Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM_TR
BJ Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_TR
BJ Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_TR
BJ Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM_TR
BJ Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM_TR
BJ Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_TR
BJ Gain: $ 1.37 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_TR
BJ Gain: $ 1.42 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV
BJ Gain: $ 1.42 Win %: 50.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_RV
BJ Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_TR
BJ Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_TR
BJ Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_TR_DB4
BJ Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_TR_DB4
BJ Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_TR
BJ Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_TR
BJ Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_TR_DB4
BJ Gain: $ 1.43 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_TR_DB4
BJ Gain: $ 1.46 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_LI
BJ Gain: $ 1.46 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_LI
BJ Gain: $ 1.46 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_LI
BJ Gain: $ 1.46 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_LI
BJ Gain: $ 1.7 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_IT
BJ Gain: $ 1.93 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_AL
BJ Gain: $ 1.93 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_AL
BJ Gain: $ 2.04 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_AL
BJ Gain: $ 2.04 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_AL
BJ Gain: $ 2.19 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_IT_QL
BJ Gain: $ 2.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_AL
BJ Gain: $ 2.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_AL
BJ Gain: $ 2.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_AL
BJ Gain: $ 2.21 Win %: 50.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_AL
BJ Gain: $ 2.26 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_IR3
BJ Gain: $ 2.26 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_IR3
BJ Gain: $ 2.29 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_AL
BJ Gain: $ 2.29 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV_AL
BJ Gain: $ 2.39 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_DB15
BJ Gain: $ 2.39 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_DB15
BJ Gain: $ 2.39 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_DB15
BJ Gain: $ 2.39 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_DB15
BJ Gain: $ 2.64 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_AL
BJ Gain: $ 2.64 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV_AL
BJ Gain: $ 2.64 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_AL
BJ Gain: $ 2.64 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV_AL
BJ Gain: $ 2.68 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_IT
BJ Gain: $ 2.68 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_IT_QL
BJ Gain: $ 2.68 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_IT
BJ Gain: $ 2.68 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_IT_QL
BJ Gain: $ 2.82 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_IT
BJ Gain: $ 2.82 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_IT_QL
BJ Gain: $ 2.82 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_IT
BJ Gain: $ 2.82 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_IT_QL
BJ Gain: $ 2.91 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_SS
BJ Gain: $ 2.91 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_SS
BJ Gain: $ 2.93 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_HM
BJ Gain: $ 2.93 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_HM
BJ Gain: $ 2.93 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_QL
BJ Gain: $ 2.93 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_QL
BJ Gain: $ 2.94 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV
BJ Gain: $ 2.94 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB4_OS4_CB5_CS5_RV
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_HM
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_QL
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_QL
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_SS
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_SS
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_HM
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_QL
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_QL
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_SS
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_SS
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_QL
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_QL
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_SS
BJ Gain: $ 3.08 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_SS
BJ Gain: $ 3.12 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_HM
BJ Gain: $ 3.12 Win %: 100.00 in 2 days with algo TB3_PL_QM_OB3_OS3_CB4_CS4_HM
BJ Gain: $ 3.14 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV
BJ Gain: $ 3.14 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB1_CS1_RV
BJ Gain: $ 3.14 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV
BJ Gain: $ 3.14 Win %: 100.00 in 2 days with algo TB2_HL_HI_QM_OB3_OS3_CB2_CS2_RV
