Gain: $ -1776.07 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_SS
Gain: $ -1776.07 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_AV
Gain: $ -181.63 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -181.63 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -3.84 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_HM_QP
Gain: $ -3.84 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_QP
Gain: $ -3.82 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_QP
Gain: $ -2.76 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_TR_QP
Gain: $ -1.37 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_VI
Gain: $ -1.23 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_HM_TR
Gain: $ -1.23 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_TR
Gain: $ -1.23 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_TR
Gain: $ -1.14 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_AL
Gain: $ -1.08 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_SS
Gain: $ -1 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_DB6
Gain: $ -1 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_HM
Gain: $ -0.98 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV
Gain: $ -0.96 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_QL
Gain: $ -0.94 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_AL
Gain: $ -0.94 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_AL
Gain: $ -0.75 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_AV
Gain: $ -0.75 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_HM_AV
Gain: $ -0.75 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_AV
Gain: $ -0.75 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_HM_AV
Gain: $ -0.71 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_TR_QP
Gain: $ -0.71 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_TR_QP
Gain: $ -0.67 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_HM_QP
Gain: $ -0.67 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_QP
Gain: $ -0.67 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_QP
Gain: $ -0.67 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_HM_QP
Gain: $ -0.67 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_QP
Gain: $ -0.67 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_QP
Gain: $ -0.55 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_AV
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_AV
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_HM_AV
Gain: $ -0.49 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_HM_TR
Gain: $ -0.49 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_TR
Gain: $ -0.49 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_TR
Gain: $ -0.49 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_HM_TR
Gain: $ -0.49 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_TR
Gain: $ -0.49 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_TR
Gain: $ -0.45 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_LI
Gain: $ -0.4 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_AV
Gain: $ -0.32 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_DB6
Gain: $ -0.32 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_HM
Gain: $ -0.32 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_QL
Gain: $ -0.32 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1
Gain: $ -0.32 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_DB6
Gain: $ -0.32 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_HM
Gain: $ -0.32 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_QL
Gain: $ -0.29 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_LI
Gain: $ -0.29 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_LI
Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_IR5
Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_TR_IR5
Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_IR5
Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_TR_IR5
Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_IR5
Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_TR_IR5
Gain: $ -0.18 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV
Gain: $ -0.18 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV
Gain: $ -0.1 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -0.1 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -0.1 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -0.09 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -0.09 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_QP_IR5
Gain: $ -0.09 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_QP_IR5
Gain: $ -0.09 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_QP_IR5
Gain: $ -0.07 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_SS
Gain: $ -0.04 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_VI
Gain: $ -0.04 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_VI
CRTO Gain: $ -0.02 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_VI
CRTO Gain: $ -0.25 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
CRTO Gain: $ -0.28 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_AL
CRTO Gain: $ -0.31 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_QP_IR1
CRTO Gain: $ -0.38 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_TR
CRTO Gain: $ -0.38 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_TR_IR1
CRTO Gain: $ -0.4 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV
CRTO Gain: $ -0.43 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_TR
CRTO Gain: $ -0.43 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_TR_DB1
CRTO Gain: $ -0.43 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_TR
CRTO Gain: $ -0.44 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_TR
CRTO Gain: $ -0.44 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_TR
CRTO Gain: $ -0.44 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_TR_IR1
CRTO Gain: $ -0.44 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_LI
CRTO Gain: $ -0.48 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_HM_AV
CRTO Gain: $ -0.52 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_DB6
CRTO Gain: $ -0.52 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_IR1
CRTO Gain: $ -0.52 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_QL
CRTO Gain: $ -0.61 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_AV
CRTO Gain: $ -0.64 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV
CRTO Gain: $ -0.68 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_IR1
CRTO Gain: $ -0.68 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_QL
CRTO Gain: $ -0.71 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1
CRTO Gain: $ -0.73 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_TR_DB1
CRTO Gain: $ -0.73 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_TR_DB1
CRTO Gain: $ -0.78 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_TR_QP
CRTO Gain: $ -0.81 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_HM_QP
CRTO Gain: $ -0.81 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_LI
CRTO Gain: $ -0.84 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_LI
CRTO Gain: $ -0.89 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_AL
CRTO Gain: $ -0.91 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_TR_QP
CRTO Gain: $ -0.92 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_AL
CRTO Gain: $ -0.98 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_TR
CRTO Gain: $ -1.03 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_HM_TR
CRTO Gain: $ -1.04 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_VI
CRTO Gain: $ -1.18 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_QP
CRTO Gain: $ -1.2 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_AL
CRTO Gain: $ -1.34 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_VI
CRTO Gain: $ -1.63 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_QP
CRTO Gain: $ -1.94 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_AL
CRTO Gain: $ -2.19 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_QP
CRTO Gain: $ -2.46 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_HM_QP
CRTO Gain: $ -2.83 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_QP_IR1
CRTO Gain: $ -2.98 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_QP
CRTO Gain: $ -3.31 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_DB6
CRTO Gain: $ -3.63 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_TR_QP
CRTO Gain: $ -4.76 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV
CRTO Gain: $ -5.37 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_QP
CRTO Gain: $ -5.44 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_HM_QP
CRTO Gain: $ -5.52 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_QP
CRTO Gain: $ -5.52 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_QP_IR1
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_AL
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_AV
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_DB6
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_IR1
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_LI
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_QL
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_QP
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR1
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_SS
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_TR
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR1
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
CRTO Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_VI
CRTO Gain: $ 0.01 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_DB6
CRTO Gain: $ 0.16 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_SS
CRTO Gain: $ 0.17 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
CRTO Gain: $ 0.29 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM
CRTO Gain: $ 0.29 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
CRTO Gain: $ 0.29 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
CRTO Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_AV
CRTO Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_AV
CRTO Gain: $ 0.32 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV
CRTO Gain: $ 0.32 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
CRTO Gain: $ 0.32 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
CRTO Gain: $ 0.32 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
CRTO Gain: $ 0.32 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB1
CRTO Gain: $ 0.41 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_SS
CRTO Gain: $ 0.49 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_IR1
CRTO Gain: $ 0.53 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_HM_TR
CRTO Gain: $ 0.54 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_AV
CRTO Gain: $ 0.55 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_SS
CRTO Gain: $ 0.57 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_TR_IR1
CRTO Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_QL
CRTO Gain: $ 0.69 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_HM
CRTO Gain: $ 0.69 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_HM_TR
CRTO Gain: $ 0.73 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_HM
CRTO Gain: $ 0.78 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_AV
CRTO Gain: $ 0.87 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_HM_AV
CRTO Gain: $ 0.88 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_AV
CRTO Gain: $ 0.91 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_AL
CRTO Gain: $ 1.06 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_HM
CRTO Gain: $ 1.11 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_HM_AV
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_AL
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB1_CS1_RV_TR_DB
Gain: $ 0.3 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_AL
Gain: $ 0.45 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB1_CS1_RV_AL
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_TR
