FCEL Gain: $ -31.52 Win %: 42.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -27.61 Win %: 36.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_QP
FCEL Gain: $ -27.14 Win %: 37.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_QP
FCEL Gain: $ -26.94 Win %: 40.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -26.82 Win %: 39.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_QP
FCEL Gain: $ -26.77 Win %: 41.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -26.75 Win %: 37.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_QP
FCEL Gain: $ -26.61 Win %: 40.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -26.53 Win %: 40.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -26.53 Win %: 40.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -26.42 Win %: 41.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -26.36 Win %: 42.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -26.36 Win %: 42.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -26.18 Win %: 42.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -26.14 Win %: 40.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -25.95 Win %: 40.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP
FCEL Gain: $ -25.93 Win %: 42.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -25.9 Win %: 42.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -25.66 Win %: 47.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -25.62 Win %: 41.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -25.59 Win %: 43.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -25.58 Win %: 41.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -25.56 Win %: 42.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -25.55 Win %: 43.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -25.49 Win %: 43.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -25.41 Win %: 40.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP
FCEL Gain: $ -25.41 Win %: 47.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -25.41 Win %: 47.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -25.39 Win %: 42.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -25.35 Win %: 37.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP_IR1
FCEL Gain: $ -25.3 Win %: 42.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -25.27 Win %: 43.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -25.26 Win %: 41.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -25.18 Win %: 41.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -25.13 Win %: 47.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -25.11 Win %: 41.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -25.11 Win %: 41.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -25.09 Win %: 41.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP
FCEL Gain: $ -24.88 Win %: 38.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP_IR1
FCEL Gain: $ -24.86 Win %: 42.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -24.83 Win %: 40.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_QP
FCEL Gain: $ -24.81 Win %: 42.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP
FCEL Gain: $ -24.8 Win %: 43.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -24.68 Win %: 41.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_QP
FCEL Gain: $ -24.63 Win %: 39.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP_IR1
FCEL Gain: $ -24.62 Win %: 41.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -24.47 Win %: 44.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -24.25 Win %: 37.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ -24.13 Win %: 44.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -24.05 Win %: 42.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_QP
FCEL Gain: $ -23.8 Win %: 38.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP_IR1
FCEL Gain: $ -23.39 Win %: 45.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -23.36 Win %: 39.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP_IR1
FCEL Gain: $ -23.36 Win %: 43.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_QP
FCEL Gain: $ -23.07 Win %: 48.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -22.95 Win %: 34.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ -22.91 Win %: 39.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP_IR1
FCEL Gain: $ -22.73 Win %: 42.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -21.03 Win %: 41.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -20.78 Win %: 37.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_QP
FCEL Gain: $ -20.77 Win %: 43.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -20.77 Win %: 48.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -20.77 Win %: 48.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -20.36 Win %: 45.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -20.24 Win %: 44.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -20.24 Win %: 44.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -20.17 Win %: 45.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -19.91 Win %: 48.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -19.84 Win %: 44.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -19.71 Win %: 53.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -19.58 Win %: 41.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -19.54 Win %: 44.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -19.41 Win %: 42.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -19.4 Win %: 53.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -19.31 Win %: 50.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -19.24 Win %: 44.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -19.18 Win %: 44.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -19.03 Win %: 46.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -18.78 Win %: 44.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -18.73 Win %: 41.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP
FCEL Gain: $ -18.57 Win %: 47.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -18.56 Win %: 47.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -18.54 Win %: 43.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -18.51 Win %: 45.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -18.5 Win %: 37.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP_IR1
FCEL Gain: $ -18.45 Win %: 46.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_QP
FCEL Gain: $ -18.4 Win %: 41.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_DB6
FCEL Gain: $ -18.36 Win %: 48.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -18.31 Win %: 47.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -18.29 Win %: 48.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -18.22 Win %: 48.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -18.22 Win %: 48.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -18.21 Win %: 47.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_QP
FCEL Gain: $ -18.18 Win %: 47.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -18.17 Win %: 47.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_QP
FCEL Gain: $ -17.86 Win %: 41.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_QP
FCEL Gain: $ -17.51 Win %: 47.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_QP
FCEL Gain: $ -17.4 Win %: 54.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -17.25 Win %: 49.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -16.32 Win %: 48.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ -16.32 Win %: 50.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -16.15 Win %: 43.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ -15.68 Win %: 43.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_IR1
FCEL Gain: $ -14.91 Win %: 39.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ -14.69 Win %: 50.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ -14.3 Win %: 59.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT
FCEL Gain: $ -13.87 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -13.73 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -13.29 Win %: 44.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR1
FCEL Gain: $ -13.27 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -13.04 Win %: 55.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP_IR1
FCEL Gain: $ -13 Win %: 51.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ -12.99 Win %: 45.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ -12.98 Win %: 51.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ -12.86 Win %: 52.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ -12.74 Win %: 43.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ -12.72 Win %: 52.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
FCEL Gain: $ -12.46 Win %: 53.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ -12.31 Win %: 53.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ -12.12 Win %: 52.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -11.72 Win %: 53.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ -11.47 Win %: 46.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_QP
FCEL Gain: $ -11.43 Win %: 48.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -11.39 Win %: 52.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ -11.21 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -11.07 Win %: 43.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ -11.04 Win %: 55.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -11 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ -10.64 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ -10.53 Win %: 46.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ -10.28 Win %: 56.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ -10.27 Win %: 49.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ -10.19 Win %: 48.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ -10.17 Win %: 47.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -9.97 Win %: 55.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -9.85 Win %: 55.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -9.77 Win %: 47.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ -9.63 Win %: 47.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ -9.58 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ -9.57 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ -9.51 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ -9.43 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ -9.42 Win %: 55.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -9.3 Win %: 53.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ -9.28 Win %: 50.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -9.03 Win %: 54.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -8.91 Win %: 55.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -8.78 Win %: 50.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -8.65 Win %: 55.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -8.57 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ -8.55 Win %: 50.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ -8.48 Win %: 52.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -8.42 Win %: 49.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ -8.41 Win %: 60.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -8.4 Win %: 51.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ -8.36 Win %: 53.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -8.33 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ -8.25 Win %: 60.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -8.15 Win %: 55.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ -8.14 Win %: 44.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -8.03 Win %: 55.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ -7.66 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -7.6 Win %: 51.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ -7.52 Win %: 60.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -7.5 Win %: 50.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -7.41 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ -7.41 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -7.4 Win %: 52.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ -7.38 Win %: 53.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ -7.23 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -7.17 Win %: 53.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_IR1
FCEL Gain: $ -7.12 Win %: 70.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -7.11 Win %: 56.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -7.02 Win %: 49.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ -6.99 Win %: 48.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ -6.74 Win %: 71.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -6.65 Win %: 69.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -6.61 Win %: 73.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -6.59 Win %: 76.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT_QP
FCEL Gain: $ -6.58 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ -6.48 Win %: 57.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -6.41 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ -6.36 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ -6.33 Win %: 53.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ -6.33 Win %: 53.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ -6.19 Win %: 54.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ -6.03 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ -5.85 Win %: 62.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -5.8 Win %: 63.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -5.78 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ -5.75 Win %: 50.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ -5.75 Win %: 62.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -5.68 Win %: 62.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -5.65 Win %: 62.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -5.62 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -5.62 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -5.61 Win %: 51.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ -5.61 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -5.61 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -5.61 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -5.61 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -5.58 Win %: 62.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -5.48 Win %: 67.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -5.39 Win %: 63.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -5.39 Win %: 63.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -5.38 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -5.37 Win %: 49.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ -5.36 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ -5.23 Win %: 60.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT_QL
FCEL Gain: $ -5.18 Win %: 55.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ -5.18 Win %: 68.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -5.15 Win %: 54.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ -4.88 Win %: 68.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -4.84 Win %: 69.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -4.77 Win %: 53.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ -4.73 Win %: 64.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT
FCEL Gain: $ -4.6 Win %: 54.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ -4.59 Win %: 69.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -4.51 Win %: 67.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -4.51 Win %: 77.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -4.46 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ -4.45 Win %: 74.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -4.42 Win %: 68.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -4.28 Win %: 52.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ -4.24 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ -4.2 Win %: 54.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ -4.18 Win %: 59.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ -4.14 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ -4.04 Win %: 52.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ -3.85 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ -3.79 Win %: 64.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -3.78 Win %: 59.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT_QL
FCEL Gain: $ -3.74 Win %: 71.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ -3.7 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ -3.63 Win %: 70.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -3.56 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ -3.49 Win %: 71.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -3.47 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ -3.45 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ -3.43 Win %: 60.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ -3.4 Win %: 72.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -3.2 Win %: 57.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ -3.07 Win %: 56.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ -3.03 Win %: 44.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_IR1
FCEL Gain: $ -3.01 Win %: 58.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ -2.99 Win %: 55.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ -2.93 Win %: 69.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -2.91 Win %: 81.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT_QP
FCEL Gain: $ -2.73 Win %: 73.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -2.7 Win %: 62.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -2.7 Win %: 62.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -2.7 Win %: 68.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ -2.64 Win %: 50.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ -2.64 Win %: 80.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT_QP
FCEL Gain: $ -2.48 Win %: 56.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ -2.47 Win %: 56.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ -2.45 Win %: 57.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ -2.44 Win %: 56.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ -2.42 Win %: 60.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ -2.42 Win %: 73.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT_QP
FCEL Gain: $ -2.4 Win %: 60.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -2.29 Win %: 49.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ -2.28 Win %: 53.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ -2.27 Win %: 62.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
FCEL Gain: $ -2.22 Win %: 68.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -2.2 Win %: 55.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ -2.2 Win %: 60.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ -2.18 Win %: 61.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT_QL
FCEL Gain: $ -2.18 Win %: 91.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT_QP
FCEL Gain: $ -2.03 Win %: 51.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ -2.03 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -2.02 Win %: 69.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ -1.98 Win %: 69.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ -1.94 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -1.85 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -1.83 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ -1.74 Win %: 55.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -1.65 Win %: 58.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ -1.62 Win %: 66.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ -1.59 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ -1.52 Win %: 51.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ -1.48 Win %: 49.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_IR1
FCEL Gain: $ -1.46 Win %: 74.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -1.46 Win %: 74.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -1.46 Win %: 92.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT_QP
FCEL Gain: $ -1.42 Win %: 74.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -1.42 Win %: 74.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -1.41 Win %: 45.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_IR1
FCEL Gain: $ -1.41 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ -1.37 Win %: 80.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -1.35 Win %: 77.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -1.32 Win %: 74.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -1.29 Win %: 74.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -1.28 Win %: 49.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_IR1
FCEL Gain: $ -1.24 Win %: 75.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
FCEL Gain: $ -1.24 Win %: 75.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -1.22 Win %: 68.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -1.22 Win %: 75.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -1.22 Win %: 75.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -1.19 Win %: 57.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ -1.17 Win %: 46.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ -1.17 Win %: 56.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ -1.17 Win %: 56.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ -1.15 Win %: 56.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ -1.15 Win %: 56.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ -1.01 Win %: 77.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -1 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ -0.95 Win %: 56.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ -0.94 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ -0.94 Win %: 88.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT_QP
FCEL Gain: $ -0.93 Win %: 75.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -0.93 Win %: 88.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT_QP
FCEL Gain: $ -0.93 Win %: 88.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT_QP
FCEL Gain: $ -0.91 Win %: 54.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ -0.83 Win %: 49.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -0.81 Win %: 60.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR_DB1
FCEL Gain: $ -0.78 Win %: 47.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ -0.78 Win %: 47.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ -0.76 Win %: 57.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ -0.76 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ -0.73 Win %: 75.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR3
FCEL Gain: $ -0.71 Win %: 56.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ -0.7 Win %: 77.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -0.69 Win %: 92.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT_QP
FCEL Gain: $ -0.68 Win %: 71.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ -0.68 Win %: 84.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -0.63 Win %: 48.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -0.62 Win %: 49.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_IR1
FCEL Gain: $ -0.6 Win %: 78.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -0.6 Win %: 78.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -0.59 Win %: 47.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_IR1
FCEL Gain: $ -0.58 Win %: 62.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ -0.56 Win %: 64.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ -0.55 Win %: 78.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -0.55 Win %: 78.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -0.55 Win %: 78.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -0.55 Win %: 78.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -0.54 Win %: 54.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ -0.52 Win %: 64.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT
FCEL Gain: $ -0.52 Win %: 78.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -0.51 Win %: 62.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ -0.5 Win %: 60.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ -0.5 Win %: 78.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
FCEL Gain: $ -0.5 Win %: 78.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -0.5 Win %: 78.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -0.42 Win %: 78.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ -0.38 Win %: 76.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ -0.31 Win %: 66.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ -0.29 Win %: 48.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ -0.24 Win %: 47.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ -0.24 Win %: 57.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ -0.21 Win %: 47.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ -0.21 Win %: 48.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -0.21 Win %: 48.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -0.21 Win %: 49.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_IR1
FCEL Gain: $ -0.2 Win %: 50.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_IR1
FCEL Gain: $ -0.2 Win %: 59.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ -0.19 Win %: 48.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -0.19 Win %: 49.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -0.17 Win %: 51.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_IR1
FCEL Gain: $ -0.17 Win %: 53.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ -0.13 Win %: 47.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ -0.12 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ -0.12 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ -0.08 Win %: 48.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ -0.06 Win %: 49.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ -0.04 Win %: 46.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ -0.03 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ -0.02 Win %: 78.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ -0.01 Win %: 78.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
Binary file (standard input) matches
FCEL Gain: $ 0 Win %: 100.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ 0 Win %: 100.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ -0.13 Win %: 99.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ -0.19 Win %: 48.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -0.35 Win %: 45.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -0.36 Win %: 99.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ -0.59 Win %: 49.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -0.64 Win %: 48.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ -0.78 Win %: 71.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -0.83 Win %: 47.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -0.85 Win %: 98.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ -0.86 Win %: 46.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -0.86 Win %: 46.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ -0.88 Win %: 52.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ -0.92 Win %: 52.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ -0.92 Win %: 52.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ -0.98 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ -1.05 Win %: 70.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -1.05 Win %: 70.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -1.05 Win %: 70.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -1.05 Win %: 70.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -1.05 Win %: 70.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -1.06 Win %: 52.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ -1.06 Win %: 52.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ -1.14 Win %: 56.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ -1.2 Win %: 70.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -1.2 Win %: 70.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -1.28 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ -1.29 Win %: 57.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -1.31 Win %: 47.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ -1.32 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ -1.33 Win %: 56.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -1.35 Win %: 55.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
Gain: $ -1.38 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -1.38 Win %: 97.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ -1.5 Win %: 55.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -1.5 Win %: 55.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ -1.54 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ -1.59 Win %: 51.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ -1.68 Win %: 51.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ -1.68 Win %: 51.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ -1.9 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ -1.95 Win %: 69.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -1.95 Win %: 69.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -1.97 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ -10.5 Win %: 49.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -10.57 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ -10.57 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5
Gain: $ -10.57 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ -10.9 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ -10.9 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ -10.95 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
Gain: $ -10.95 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ -10.95 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ -11.06 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5
Gain: $ -11.21 Win %: 51.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ -11.21 Win %: 51.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5
Gain: $ -11.21 Win %: 51.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ -11.44 Win %: 51.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ -11.55 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
Gain: $ -11.55 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ -11.55 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ -11.74 Win %: 52.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ -11.83 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -11.84 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -11.89 Win %: 52.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
Gain: $ -12.04 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -12.16 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -12.21 Win %: 51.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -12.47 Win %: 50.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -12.47 Win %: 50.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -12.81 Win %: 51.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -12.81 Win %: 51.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -13 Win %: 51.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -13.14 Win %: 48.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ -14.63 Win %: 50.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -16.12 Win %: 48.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -16.52 Win %: 48.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ -16.67 Win %: 49.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -17.35 Win %: 49.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -17.47 Win %: 47.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -17.77 Win %: 48.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -18.15 Win %: 47.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -18.41 Win %: 47.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -18.52 Win %: 45.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -2.02 Win %: 69.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ -2.07 Win %: 50.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ -2.28 Win %: 54.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -2.48 Win %: 48.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ -2.76 Win %: 57.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -2.77 Win %: 48.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -2.81 Win %: 46.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ -2.84 Win %: 46.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -20.92 Win %: 42.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -21.52 Win %: 41.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -21.8 Win %: 41.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -22.2 Win %: 40.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -22.29 Win %: 42.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -22.58 Win %: 40.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -22.58 Win %: 41.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -22.59 Win %: 41.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -22.77 Win %: 41.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -23.24 Win %: 40.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -23.24 Win %: 44.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -23.36 Win %: 43.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -23.41 Win %: 41.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -23.65 Win %: 40.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -23.94 Win %: 42.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -24.08 Win %: 40.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -24.33 Win %: 43.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -24.4 Win %: 44.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -24.45 Win %: 40.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -24.55 Win %: 42.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -24.57 Win %: 41.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -24.63 Win %: 40.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -24.81 Win %: 38.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -24.86 Win %: 43.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -24.9 Win %: 41.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -24.95 Win %: 42.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -25.02 Win %: 42.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -25.08 Win %: 41.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -25.22 Win %: 42.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -25.32 Win %: 40.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -25.43 Win %: 41.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -25.45 Win %: 42.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -25.53 Win %: 40.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -25.54 Win %: 41.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -25.78 Win %: 40.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -25.78 Win %: 41.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -25.85 Win %: 41.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -26.41 Win %: 39.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -27.08 Win %: 40.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -3.34 Win %: 47.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -3.49 Win %: 47.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ -3.64 Win %: 47.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -3.94 Win %: 45.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -34.97 Win %: 33.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -4.08 Win %: 47.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -4.14 Win %: 46.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -4.24 Win %: 46.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -4.26 Win %: 56.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
Gain: $ -4.28 Win %: 44.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -4.4 Win %: 45.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -4.61 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -4.65 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ -4.67 Win %: 48.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -4.98 Win %: 48.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -4.98 Win %: 51.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ -5.03 Win %: 50.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -5.03 Win %: 50.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ -5.04 Win %: 51.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -5.22 Win %: 56.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -5.22 Win %: 56.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ -5.27 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -5.27 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ -5.29 Win %: 49.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -5.29 Win %: 49.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ -5.33 Win %: 44.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -5.54 Win %: 54.00 in 109 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -5.54 Win %: 54.00 in 109 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ -5.56 Win %: 50.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ -5.57 Win %: 44.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -5.75 Win %: 50.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -5.77 Win %: 43.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -6.13 Win %: 50.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -6.16 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -6.16 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -6.17 Win %: 54.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -6.22 Win %: 55.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -6.23 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -6.23 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ -6.32 Win %: 57.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -6.32 Win %: 57.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -6.32 Win %: 57.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -6.32 Win %: 57.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -6.36 Win %: 57.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -6.36 Win %: 57.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -6.46 Win %: 53.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -6.6 Win %: 54.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -6.65 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -6.67 Win %: 57.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -6.67 Win %: 57.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -6.7 Win %: 52.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -6.76 Win %: 53.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -6.78 Win %: 54.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -6.95 Win %: 57.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -7.08 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -7.08 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -7.11 Win %: 56.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -7.12 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -7.12 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -7.14 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -7.15 Win %: 55.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ -7.2 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -7.21 Win %: 45.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -7.26 Win %: 54.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -7.26 Win %: 54.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -7.26 Win %: 55.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -7.26 Win %: 56.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -7.26 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -7.26 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -7.29 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -7.29 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -7.31 Win %: 55.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -7.39 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -7.4 Win %: 52.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -7.4 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -7.42 Win %: 52.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -7.42 Win %: 52.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -7.43 Win %: 53.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
Gain: $ -7.43 Win %: 53.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
Gain: $ -7.44 Win %: 52.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -7.44 Win %: 52.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -7.48 Win %: 44.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ -7.53 Win %: 51.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -7.54 Win %: 54.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -7.54 Win %: 54.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -7.69 Win %: 51.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -7.69 Win %: 51.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -7.69 Win %: 53.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -7.71 Win %: 48.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -7.73 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -7.76 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -7.86 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -7.86 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -7.92 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -7.93 Win %: 52.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -8.03 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -8.05 Win %: 55.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -8.06 Win %: 52.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -8.06 Win %: 52.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -8.17 Win %: 56.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ -8.17 Win %: 56.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ -8.2 Win %: 55.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -8.24 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -8.24 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -8.26 Win %: 55.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -8.26 Win %: 55.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -8.28 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -8.28 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -8.33 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -8.37 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -8.38 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ -8.38 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ -8.4 Win %: 50.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -8.42 Win %: 55.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ -8.42 Win %: 55.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ -8.43 Win %: 53.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -8.5 Win %: 52.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -8.53 Win %: 49.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -8.53 Win %: 50.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -8.53 Win %: 53.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ -8.54 Win %: 54.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -8.57 Win %: 55.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -8.6 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -8.6 Win %: 58.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -8.65 Win %: 50.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -8.69 Win %: 50.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -8.73 Win %: 50.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -8.8 Win %: 50.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -8.9 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -8.93 Win %: 54.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -8.97 Win %: 52.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -9 Win %: 55.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -9 Win %: 55.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -9.02 Win %: 50.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -9.04 Win %: 48.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -9.04 Win %: 48.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ -9.04 Win %: 50.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -9.06 Win %: 48.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -9.06 Win %: 48.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ -9.09 Win %: 48.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -9.09 Win %: 48.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ -9.09 Win %: 49.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ -9.15 Win %: 57.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -9.15 Win %: 57.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -9.27 Win %: 54.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ -9.27 Win %: 54.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ -9.27 Win %: 57.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -9.28 Win %: 56.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -9.28 Win %: 56.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -9.3 Win %: 48.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -9.3 Win %: 53.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ -9.3 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -9.57 Win %: 48.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -9.57 Win %: 48.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ -9.57 Win %: 56.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -9.68 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -9.77 Win %: 47.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -9.88 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -9.97 Win %: 55.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR3
Gain: $ 0 Win %: 100.00 in 110 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 110 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 0 Win %: 100.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 0 Win %: 100.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_DB6
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 0 Win %: 100.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 0 Win %: 100.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0.07 Win %: 47.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 0.12 Win %: 48.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 0.21 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 0.23 Win %: 58.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 0.39 Win %: 48.00 in 109 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 0.47 Win %: 48.00 in 109 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 0.57 Win %: 97.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0.81 Win %: 55.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 0.88 Win %: 45.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 1.18 Win %: 51.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 1.19 Win %: 52.00 in 109 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 1.19 Win %: 52.00 in 109 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 1.28 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 1.35 Win %: 55.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 1.37 Win %: 51.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 1.6 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 1.6 Win %: 52.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 1.87 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 1.88 Win %: 44.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 1.93 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 1.97 Win %: 46.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 1.97 Win %: 55.00 in 109 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 1.97 Win %: 55.00 in 109 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 10.19 Win %: 55.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 10.26 Win %: 54.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 10.31 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 10.62 Win %: 55.00 in 109 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 10.76 Win %: 54.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 10.94 Win %: 55.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 11.09 Win %: 54.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 11.11 Win %: 56.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 11.44 Win %: 59.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 11.91 Win %: 57.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 11.96 Win %: 58.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 12.18 Win %: 59.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 12.33 Win %: 54.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 12.74 Win %: 56.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 13.08 Win %: 60.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 13.15 Win %: 54.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 13.46 Win %: 55.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 16.14 Win %: 58.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 16.35 Win %: 59.00 in 114 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 16.61 Win %: 59.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 16.95 Win %: 57.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 17.6 Win %: 58.00 in 114 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 17.93 Win %: 54.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 18.32 Win %: 59.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 18.63 Win %: 59.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 18.76 Win %: 60.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 19.07 Win %: 59.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 19.41 Win %: 60.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 19.71 Win %: 55.00 in 109 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 2.06 Win %: 53.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 2.09 Win %: 43.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 2.16 Win %: 53.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 2.16 Win %: 58.00 in 117 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 2.16 Win %: 58.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 2.25 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 2.25 Win %: 54.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 2.35 Win %: 60.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 2.35 Win %: 60.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 2.43 Win %: 41.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 2.64 Win %: 56.00 in 116 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 2.7 Win %: 42.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 2.75 Win %: 61.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 2.79 Win %: 41.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 2.85 Win %: 58.00 in 115 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 2.86 Win %: 61.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 2.89 Win %: 40.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 2.99 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 20.08 Win %: 60.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 20.18 Win %: 58.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 20.66 Win %: 62.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 20.91 Win %: 57.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 21 Win %: 60.00 in 109 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 21.07 Win %: 59.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 21.67 Win %: 60.00 in 109 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ 21.93 Win %: 58.00 in 109 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 3 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 3.05 Win %: 61.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 3.06 Win %: 56.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 3.1 Win %: 56.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 3.1 Win %: 56.00 in 114 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 3.24 Win %: 43.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 3.26 Win %: 49.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_DB6
Gain: $ 3.27 Win %: 60.00 in 115 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 3.33 Win %: 45.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 3.35 Win %: 46.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 3.42 Win %: 60.00 in 109 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 3.42 Win %: 60.00 in 109 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 3.43 Win %: 61.00 in 114 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 3.5 Win %: 44.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 3.53 Win %: 42.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 3.73 Win %: 50.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 3.78 Win %: 44.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 3.78 Win %: 46.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 3.82 Win %: 44.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 4.17 Win %: 41.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 4.31 Win %: 51.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 4.33 Win %: 53.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 4.45 Win %: 42.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 4.59 Win %: 50.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 4.84 Win %: 45.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 4.88 Win %: 43.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 5.2 Win %: 51.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 5.71 Win %: 50.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 5.76 Win %: 49.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 5.97 Win %: 50.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 5.99 Win %: 50.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 6.34 Win %: 50.00 in 114 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 6.41 Win %: 57.00 in 114 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 6.42 Win %: 48.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 6.43 Win %: 54.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 6.44 Win %: 48.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 6.47 Win %: 49.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 6.49 Win %: 50.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 6.58 Win %: 50.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 6.68 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 6.7 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 6.75 Win %: 52.00 in 114 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 6.8 Win %: 51.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 6.88 Win %: 50.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 6.9 Win %: 49.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 6.92 Win %: 50.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 6.94 Win %: 50.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 6.99 Win %: 50.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 6.99 Win %: 51.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 7 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 7.01 Win %: 54.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 7.03 Win %: 54.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 7.07 Win %: 52.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 7.07 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 7.11 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 7.18 Win %: 54.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 7.24 Win %: 49.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 7.29 Win %: 50.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 7.34 Win %: 49.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM
Gain: $ 7.44 Win %: 50.00 in 115 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_DB6
Gain: $ 7.45 Win %: 49.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 7.45 Win %: 54.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 7.46 Win %: 50.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 7.5 Win %: 51.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 7.54 Win %: 50.00 in 109 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 7.57 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 7.59 Win %: 51.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 7.61 Win %: 51.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 7.63 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 7.68 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 7.71 Win %: 51.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 7.79 Win %: 50.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 7.8 Win %: 53.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 7.84 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 7.87 Win %: 53.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 7.9 Win %: 51.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 8.09 Win %: 57.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 8.1 Win %: 50.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 8.1 Win %: 53.00 in 114 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 8.17 Win %: 50.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 8.18 Win %: 52.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 8.23 Win %: 55.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 8.26 Win %: 55.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 8.32 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 8.33 Win %: 51.00 in 109 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 8.35 Win %: 52.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 8.41 Win %: 51.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 8.44 Win %: 52.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 8.51 Win %: 52.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 8.56 Win %: 52.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 8.56 Win %: 56.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 8.66 Win %: 52.00 in 109 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 8.76 Win %: 53.00 in 109 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 8.76 Win %: 57.00 in 115 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 8.88 Win %: 51.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 8.89 Win %: 50.00 in 110 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM
Gain: $ 8.92 Win %: 55.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 8.94 Win %: 52.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 8.95 Win %: 51.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 9.03 Win %: 54.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 9.06 Win %: 52.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 9.07 Win %: 53.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 9.12 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 9.34 Win %: 57.00 in 109 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 9.38 Win %: 52.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 9.44 Win %: 53.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 9.52 Win %: 53.00 in 115 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 9.69 Win %: 56.00 in 116 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 9.88 Win %: 53.00 in 116 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 9.91 Win %: 53.00 in 110 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 9.96 Win %: 55.00 in 114 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AV
FCEL Gain: $ 0.03 Win %: 50.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ 0.04 Win %: 91.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT_QP
FCEL Gain: $ 0.06 Win %: 69.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ 0.06 Win %: 77.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QP
FCEL Gain: $ 0.1 Win %: 78.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ 0.15 Win %: 79.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ 0.15 Win %: 79.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ 0.15 Win %: 79.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ 0.17 Win %: 48.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ 0.18 Win %: 79.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ 0.18 Win %: 79.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ 0.18 Win %: 79.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ 0.2 Win %: 50.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IR1
FCEL Gain: $ 0.2 Win %: 79.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ 0.2 Win %: 79.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ 0.2 Win %: 92.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT_QP
FCEL Gain: $ 0.21 Win %: 92.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT_QP
FCEL Gain: $ 0.22 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 0.23 Win %: 92.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT_QP
FCEL Gain: $ 0.23 Win %: 92.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT_QP
FCEL Gain: $ 0.26 Win %: 60.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 0.27 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 0.28 Win %: 48.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ 0.28 Win %: 48.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ 0.44 Win %: 63.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 0.52 Win %: 64.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 0.55 Win %: 50.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR_IR1
FCEL Gain: $ 0.56 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 0.57 Win %: 79.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ 0.59 Win %: 54.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 0.68 Win %: 63.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 0.8 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 0.86 Win %: 59.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 0.86 Win %: 69.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 0.87 Win %: 53.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 0.91 Win %: 70.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 0.91 Win %: 70.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 0.91 Win %: 70.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 0.91 Win %: 70.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 0.93 Win %: 62.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 0.96 Win %: 55.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 1.05 Win %: 69.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ 1.1 Win %: 47.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_IR1
FCEL Gain: $ 1.15 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 1.2 Win %: 49.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_IR1
FCEL Gain: $ 1.26 Win %: 70.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 1.27 Win %: 49.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_IR1
FCEL Gain: $ 1.32 Win %: 59.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 1.35 Win %: 64.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 1.37 Win %: 51.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 1.37 Win %: 70.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 1.37 Win %: 70.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 1.38 Win %: 64.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 1.42 Win %: 51.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 1.47 Win %: 71.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 1.47 Win %: 76.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ 1.51 Win %: 57.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 1.51 Win %: 57.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 1.53 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 1.56 Win %: 71.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 1.56 Win %: 71.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 1.56 Win %: 71.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 1.59 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT
FCEL Gain: $ 1.64 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 1.69 Win %: 51.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 1.73 Win %: 58.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 1.73 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 1.75 Win %: 50.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_IR1
FCEL Gain: $ 1.98 Win %: 51.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR_IR1
FCEL Gain: $ 1.99 Win %: 68.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_QP
FCEL Gain: $ 2.06 Win %: 53.00 in 117 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 2.11 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 2.11 Win %: 54.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 2.11 Win %: 58.00 in 118 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 2.12 Win %: 51.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_LI
FCEL Gain: $ 2.13 Win %: 44.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 2.16 Win %: 63.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 2.18 Win %: 72.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 2.21 Win %: 59.00 in 118 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 2.22 Win %: 59.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 2.27 Win %: 52.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 2.27 Win %: 52.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 2.43 Win %: 59.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 2.43 Win %: 59.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 2.48 Win %: 58.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 2.49 Win %: 59.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 2.56 Win %: 57.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 2.56 Win %: 67.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 2.65 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 2.65 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ 2.79 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 2.8 Win %: 63.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 2.82 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 2.84 Win %: 60.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 2.84 Win %: 60.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 2.86 Win %: 49.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 2.87 Win %: 64.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 2.99 Win %: 61.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 3 Win %: 60.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 3 Win %: 60.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 3.06 Win %: 45.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 3.07 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 3.13 Win %: 45.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 3.15 Win %: 42.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 3.19 Win %: 44.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 3.19 Win %: 60.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 3.19 Win %: 60.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 3.19 Win %: 72.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 3.21 Win %: 65.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ 3.27 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 3.27 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 3.27 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 3.28 Win %: 55.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 3.34 Win %: 55.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 3.36 Win %: 44.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 3.36 Win %: 63.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 3.44 Win %: 52.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_LI
FCEL Gain: $ 3.44 Win %: 60.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 3.45 Win %: 45.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 3.48 Win %: 42.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 3.48 Win %: 52.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 3.48 Win %: 52.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 3.5 Win %: 45.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 3.51 Win %: 45.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 3.53 Win %: 65.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ 3.56 Win %: 46.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 3.56 Win %: 54.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 3.56 Win %: 63.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ 3.56 Win %: 63.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 3.6 Win %: 55.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 3.63 Win %: 54.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 3.64 Win %: 53.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_LI
FCEL Gain: $ 3.64 Win %: 64.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ 3.64 Win %: 64.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 3.64 Win %: 64.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ 3.68 Win %: 64.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 3.69 Win %: 54.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 3.7 Win %: 54.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_LI
FCEL Gain: $ 3.7 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 3.74 Win %: 60.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 3.77 Win %: 59.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 3.78 Win %: 60.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ 3.8 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 3.8 Win %: 70.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 3.86 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ 3.86 Win %: 67.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ 3.86 Win %: 67.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ 3.87 Win %: 67.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ 3.88 Win %: 47.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 3.89 Win %: 75.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 3.91 Win %: 54.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_LI
FCEL Gain: $ 3.91 Win %: 64.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ 3.91 Win %: 64.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 3.92 Win %: 55.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 3.95 Win %: 44.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_VI
FCEL Gain: $ 3.96 Win %: 66.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ 3.96 Win %: 66.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ 3.99 Win %: 67.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ 4 Win %: 42.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QL
FCEL Gain: $ 4 Win %: 60.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 4.02 Win %: 45.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 4.04 Win %: 41.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QL
FCEL Gain: $ 4.07 Win %: 64.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IR3
FCEL Gain: $ 4.07 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IR3
FCEL Gain: $ 4.11 Win %: 51.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 4.11 Win %: 64.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 4.13 Win %: 67.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 4.15 Win %: 44.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_VI
FCEL Gain: $ 4.16 Win %: 71.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 4.17 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 4.2 Win %: 55.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 4.2 Win %: 55.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 4.2 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 4.22 Win %: 55.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 4.23 Win %: 42.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QL
FCEL Gain: $ 4.23 Win %: 65.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 4.29 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 4.29 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 4.3 Win %: 55.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 4.32 Win %: 65.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 4.34 Win %: 45.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_VI
FCEL Gain: $ 4.36 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 4.39 Win %: 60.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 4.44 Win %: 56.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 4.44 Win %: 56.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 4.44 Win %: 56.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 4.44 Win %: 70.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 4.44089e-16 Win %: 78.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
FCEL Gain: $ 4.44089e-16 Win %: 78.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
FCEL Gain: $ 4.48 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
FCEL Gain: $ 4.48 Win %: 65.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ 4.49 Win %: 51.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_LI
FCEL Gain: $ 4.49 Win %: 67.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
FCEL Gain: $ 4.54 Win %: 43.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 4.54 Win %: 51.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 4.55 Win %: 46.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_VI
FCEL Gain: $ 4.56 Win %: 65.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ 4.56 Win %: 65.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 4.56 Win %: 66.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ 4.58 Win %: 59.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ 4.58 Win %: 60.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 4.6 Win %: 44.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QL
FCEL Gain: $ 4.6 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 4.61 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ 4.62 Win %: 47.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_VI
FCEL Gain: $ 4.62 Win %: 55.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 4.63 Win %: 42.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 4.67 Win %: 61.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 4.69 Win %: 43.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_QL
FCEL Gain: $ 4.69 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ 4.75 Win %: 65.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 4.76 Win %: 43.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 4.77 Win %: 60.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT_QL
FCEL Gain: $ 4.81 Win %: 68.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 4.83 Win %: 65.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ 4.88 Win %: 43.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 4.88 Win %: 56.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 4.89 Win %: 58.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 4.94 Win %: 66.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 4.97 Win %: 70.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 4.98 Win %: 63.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 4.99 Win %: 66.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR3
FCEL Gain: $ 4.99 Win %: 66.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR3
FCEL Gain: $ 5.09 Win %: 56.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 5.1 Win %: 54.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 5.16 Win %: 44.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 5.17 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT_QL
FCEL Gain: $ 5.28 Win %: 67.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ 5.32 Win %: 60.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT_QL
FCEL Gain: $ 5.33 Win %: 51.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 5.33 Win %: 54.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 5.36 Win %: 44.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 5.37 Win %: 44.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 5.39 Win %: 54.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 5.39 Win %: 54.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 5.49 Win %: 52.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 5.5 Win %: 45.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 5.53 Win %: 52.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 5.54 Win %: 52.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 5.56 Win %: 52.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 5.6 Win %: 61.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 5.63 Win %: 55.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 5.63 Win %: 55.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 5.65 Win %: 60.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 5.67 Win %: 52.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 5.71 Win %: 57.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 5.75 Win %: 55.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 5.75 Win %: 55.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 5.75 Win %: 55.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 5.76 Win %: 44.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 5.8 Win %: 55.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 5.85 Win %: 60.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 5.91 Win %: 52.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 6.01 Win %: 57.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 6.01 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 6.07 Win %: 53.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 6.08 Win %: 56.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 6.1 Win %: 66.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 6.12 Win %: 56.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 6.13 Win %: 67.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 6.15 Win %: 52.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 6.16 Win %: 62.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 6.19 Win %: 64.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 6.26 Win %: 50.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 6.27 Win %: 50.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 6.28 Win %: 52.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 6.31 Win %: 53.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 6.31 Win %: 53.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 6.32 Win %: 66.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 6.35 Win %: 84.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 6.37 Win %: 60.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT
FCEL Gain: $ 6.41 Win %: 69.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT
FCEL Gain: $ 6.42 Win %: 53.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 6.42 Win %: 69.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 6.44 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT
FCEL Gain: $ 6.46 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 6.5 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 6.53 Win %: 56.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 6.55 Win %: 59.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 6.56 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT_QL
FCEL Gain: $ 6.59 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 6.62 Win %: 51.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 6.62 Win %: 51.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 6.62 Win %: 65.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 6.62 Win %: 67.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT
FCEL Gain: $ 6.65 Win %: 68.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5
FCEL Gain: $ 6.71 Win %: 60.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT
FCEL Gain: $ 6.73 Win %: 57.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 6.75 Win %: 54.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 6.79 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 6.85 Win %: 53.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 6.91 Win %: 51.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 6.91 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 6.92 Win %: 60.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT_QL
FCEL Gain: $ 6.94 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT_QL
FCEL Gain: $ 6.95 Win %: 59.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT_QL
FCEL Gain: $ 6.96 Win %: 50.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 6.96 Win %: 63.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 6.96 Win %: 69.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_IT
FCEL Gain: $ 6.98 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 7 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT_QL
FCEL Gain: $ 7 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT_QL
FCEL Gain: $ 7.02 Win %: 50.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 7.03 Win %: 51.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_DB6
FCEL Gain: $ 7.04 Win %: 49.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 7.05 Win %: 50.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_DB6
FCEL Gain: $ 7.05 Win %: 60.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 7.09 Win %: 49.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 7.09 Win %: 49.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 7.09 Win %: 64.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 7.11 Win %: 63.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 7.16 Win %: 51.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 7.18 Win %: 51.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 7.19 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ 7.21 Win %: 51.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 7.24 Win %: 49.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 7.24 Win %: 50.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 7.27 Win %: 50.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR
FCEL Gain: $ 7.27 Win %: 50.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 7.27 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 7.28 Win %: 50.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 7.28 Win %: 50.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 7.3 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 7.31 Win %: 48.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM
FCEL Gain: $ 7.31 Win %: 49.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 7.31 Win %: 49.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 7.31 Win %: 53.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 7.32 Win %: 50.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 7.33 Win %: 62.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 7.37 Win %: 53.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 7.38 Win %: 49.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AL
FCEL Gain: $ 7.39 Win %: 50.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 7.41 Win %: 52.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR
FCEL Gain: $ 7.42 Win %: 51.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 7.42 Win %: 51.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 7.44 Win %: 63.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 7.46 Win %: 49.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 7.46 Win %: 50.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 7.46 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT
FCEL Gain: $ 7.46 Win %: 64.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 7.46 Win %: 84.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 7.52 Win %: 64.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 7.52 Win %: 64.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 7.55 Win %: 50.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 7.55 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT_QL
FCEL Gain: $ 7.56 Win %: 50.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM
FCEL Gain: $ 7.56 Win %: 61.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 7.56 Win %: 61.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 7.56 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 7.58 Win %: 49.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 7.58 Win %: 49.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 7.58 Win %: 50.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 7.59 Win %: 51.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 7.59 Win %: 53.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR
FCEL Gain: $ 7.59 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 7.59 Win %: 84.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 7.59 Win %: 84.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 7.59 Win %: 84.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 7.59 Win %: 84.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 7.59 Win %: 84.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 7.6 Win %: 50.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 7.6 Win %: 51.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR
FCEL Gain: $ 7.6 Win %: 51.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 7.61 Win %: 53.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 7.61 Win %: 56.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 7.61 Win %: 56.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 7.62 Win %: 49.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 7.62 Win %: 62.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 7.62 Win %: 64.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 7.62 Win %: 64.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 7.63 Win %: 50.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 7.66 Win %: 53.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR
FCEL Gain: $ 7.67 Win %: 51.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR
FCEL Gain: $ 7.68 Win %: 59.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 7.69 Win %: 84.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 7.71 Win %: 51.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 7.71 Win %: 58.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 7.72 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 7.73 Win %: 53.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV
FCEL Gain: $ 7.73 Win %: 54.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV
FCEL Gain: $ 7.73 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 7.74 Win %: 54.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 7.77 Win %: 61.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 7.79 Win %: 56.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 7.81 Win %: 50.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 7.81 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 7.81 Win %: 65.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 7.82 Win %: 50.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 7.84 Win %: 50.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 7.84 Win %: 50.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 7.84 Win %: 56.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 7.88 Win %: 50.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 7.89 Win %: 55.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 7.9 Win %: 54.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 7.92 Win %: 50.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 7.92 Win %: 84.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 7.92 Win %: 84.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 7.92 Win %: 84.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 7.92 Win %: 84.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 7.92 Win %: 84.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 7.92 Win %: 84.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 7.94 Win %: 60.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT_QL
FCEL Gain: $ 7.95 Win %: 50.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 7.97 Win %: 50.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM
FCEL Gain: $ 7.97 Win %: 62.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 7.97 Win %: 62.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 8 Win %: 56.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 8 Win %: 66.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 8.02 Win %: 50.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM
FCEL Gain: $ 8.02 Win %: 52.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_LI
FCEL Gain: $ 8.03 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_IT
FCEL Gain: $ 8.03 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT
FCEL Gain: $ 8.04 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AL
FCEL Gain: $ 8.07 Win %: 54.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 8.07 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 8.09 Win %: 52.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM
FCEL Gain: $ 8.11 Win %: 54.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 8.13 Win %: 62.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 8.14 Win %: 56.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV
FCEL Gain: $ 8.15 Win %: 52.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AL
FCEL Gain: $ 8.17 Win %: 58.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 8.18 Win %: 54.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR
FCEL Gain: $ 8.19 Win %: 52.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR
FCEL Gain: $ 8.19 Win %: 52.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 8.19 Win %: 57.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 8.19 Win %: 57.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 8.2 Win %: 55.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV
FCEL Gain: $ 8.21 Win %: 58.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 8.22 Win %: 59.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 8.26 Win %: 50.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 8.26 Win %: 66.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 8.26 Win %: 84.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_VI
FCEL Gain: $ 8.27 Win %: 55.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 8.3 Win %: 55.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 8.32 Win %: 52.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AL
FCEL Gain: $ 8.32 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 8.33 Win %: 54.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_TR
FCEL Gain: $ 8.36 Win %: 66.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 8.37 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 8.38 Win %: 52.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AL
FCEL Gain: $ 8.38 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 8.38 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 8.38 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 8.4 Win %: 51.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_DB6
FCEL Gain: $ 8.4 Win %: 52.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 8.41 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 8.42 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 8.44 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 8.45 Win %: 54.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 8.46 Win %: 60.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 8.46 Win %: 63.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ 8.46 Win %: 63.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 8.48 Win %: 52.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 8.48 Win %: 52.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AL
FCEL Gain: $ 8.49 Win %: 52.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 8.5 Win %: 52.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AL
FCEL Gain: $ 8.5 Win %: 54.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 8.51 Win %: 68.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IT_QL
FCEL Gain: $ 8.53 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ 8.55 Win %: 51.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 8.55 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 8.57 Win %: 60.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 8.57 Win %: 60.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 8.58 Win %: 53.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AL
FCEL Gain: $ 8.61 Win %: 52.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AL
FCEL Gain: $ 8.61 Win %: 63.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
FCEL Gain: $ 8.62 Win %: 56.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 8.63 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 8.64 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT
FCEL Gain: $ 8.65 Win %: 60.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 8.65 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 8.65 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 8.66 Win %: 51.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_DB6
FCEL Gain: $ 8.69 Win %: 55.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 8.71 Win %: 56.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV
FCEL Gain: $ 8.73 Win %: 61.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 8.73 Win %: 61.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 8.75 Win %: 52.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 8.76 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 8.76 Win %: 56.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 8.76 Win %: 56.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 8.77 Win %: 51.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_DB6
FCEL Gain: $ 8.77 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_DB6
FCEL Gain: $ 8.78 Win %: 54.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 8.79 Win %: 54.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 8.79 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 8.79 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 8.8 Win %: 53.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 8.8 Win %: 56.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 8.8 Win %: 56.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 8.81 Win %: 51.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_DB6
FCEL Gain: $ 8.82 Win %: 53.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 8.84 Win %: 60.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 8.85 Win %: 52.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 8.87 Win %: 52.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 8.88 Win %: 53.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 8.88 Win %: 66.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 8.89 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 8.92 Win %: 53.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR
FCEL Gain: $ 8.92 Win %: 53.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 8.92 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 8.92 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_QL
FCEL Gain: $ 8.92 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 8.93 Win %: 54.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 8.93 Win %: 54.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 8.98 Win %: 54.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AL
FCEL Gain: $ 8.98 Win %: 63.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9 Win %: 53.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 9.01 Win %: 53.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 9.03 Win %: 57.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 9.06 Win %: 57.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 9.1 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT
FCEL Gain: $ 9.11 Win %: 54.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 9.11 Win %: 57.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 9.12 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 9.12 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 9.12 Win %: 56.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 9.14 Win %: 55.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AL
FCEL Gain: $ 9.15 Win %: 52.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.15 Win %: 52.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 9.15 Win %: 53.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AL
FCEL Gain: $ 9.21 Win %: 57.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 9.22 Win %: 52.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.22 Win %: 52.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 9.23 Win %: 52.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.23 Win %: 52.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 9.24 Win %: 52.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.24 Win %: 52.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 9.25 Win %: 54.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 9.28 Win %: 53.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 9.28 Win %: 54.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 9.28 Win %: 54.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 9.3 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.3 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 9.3 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 9.3 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 9.3 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 9.31 Win %: 61.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 9.31 Win %: 61.00 in 122 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 9.34 Win %: 57.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 9.35 Win %: 54.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 9.36 Win %: 55.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 9.37 Win %: 52.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 9.37 Win %: 52.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.38 Win %: 53.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 9.4 Win %: 58.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 9.42 Win %: 54.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 9.43 Win %: 54.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 9.44 Win %: 52.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 9.44 Win %: 54.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 9.44 Win %: 54.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 9.45 Win %: 54.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_DB6
FCEL Gain: $ 9.46 Win %: 53.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 9.46 Win %: 57.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 9.46 Win %: 61.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 9.47 Win %: 54.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 9.49 Win %: 54.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AL
FCEL Gain: $ 9.49 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 9.51 Win %: 53.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.53 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 9.53 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 9.54 Win %: 54.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 9.55 Win %: 52.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.55 Win %: 55.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 9.57 Win %: 52.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.57 Win %: 52.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.62 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 9.64 Win %: 55.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 9.64 Win %: 57.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_RV_AV
FCEL Gain: $ 9.66 Win %: 61.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
FCEL Gain: $ 9.66 Win %: 61.00 in 123 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 9.66 Win %: 61.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 9.68 Win %: 52.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.68 Win %: 55.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 9.68 Win %: 55.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 9.68 Win %: 55.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 9.7 Win %: 53.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 9.7 Win %: 54.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 9.71 Win %: 53.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 9.71 Win %: 61.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 9.71 Win %: 64.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 9.72 Win %: 61.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
FCEL Gain: $ 9.72 Win %: 61.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ 9.72 Win %: 61.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 9.72 Win %: 61.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 9.72 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
FCEL Gain: $ 9.72 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ 9.73 Win %: 53.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.73 Win %: 53.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.73 Win %: 53.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 9.73 Win %: 53.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.74 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 9.74 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 9.74 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 9.74 Win %: 61.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5
FCEL Gain: $ 9.75 Win %: 59.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 9.76 Win %: 53.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.76 Win %: 53.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 9.82 Win %: 62.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
FCEL Gain: $ 9.82 Win %: 62.00 in 124 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 9.82 Win %: 62.00 in 124 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 9.82 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
FCEL Gain: $ 9.83 Win %: 62.00 in 122 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
FCEL Gain: $ 9.85 Win %: 53.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.87 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.87 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 9.87 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 9.93 Win %: 53.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.93 Win %: 53.00 in 120 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.93 Win %: 53.00 in 120 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.93 Win %: 66.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 9.96 Win %: 61.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 9.97 Win %: 53.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 9.97 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 9.99 Win %: 62.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 10.01 Win %: 53.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 10.01 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5
FCEL Gain: $ 10.05 Win %: 79.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_VI
FCEL Gain: $ 10.12 Win %: 53.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 10.16 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 10.16 Win %: 53.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 10.17 Win %: 54.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 10.17 Win %: 64.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_IT_QL
FCEL Gain: $ 10.18 Win %: 54.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 10.25 Win %: 63.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_DB10
FCEL Gain: $ 10.29 Win %: 53.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 10.29 Win %: 54.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_TR
FCEL Gain: $ 10.37 Win %: 62.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 10.39 Win %: 55.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 10.4 Win %: 63.00 in 125 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_TR
FCEL Gain: $ 10.41 Win %: 54.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 10.41 Win %: 54.00 in 123 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 10.42 Win %: 63.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_DB10
FCEL Gain: $ 10.44 Win %: 60.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 10.47 Win %: 56.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 10.58 Win %: 54.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_TR
FCEL Gain: $ 10.65 Win %: 55.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_TR
FCEL Gain: $ 10.65 Win %: 67.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM
FCEL Gain: $ 10.68 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 10.78 Win %: 55.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AV
FCEL Gain: $ 10.81 Win %: 55.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 10.83 Win %: 53.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 10.87 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 10.87 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 10.89 Win %: 54.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 10.91 Win %: 53.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 10.96 Win %: 53.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 10.98 Win %: 53.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 10.99 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 11.03 Win %: 55.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR
FCEL Gain: $ 11.03 Win %: 55.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
FCEL Gain: $ 11.04 Win %: 56.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_TR
FCEL Gain: $ 11.07 Win %: 64.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AL
FCEL Gain: $ 11.12 Win %: 56.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AV
FCEL Gain: $ 11.15 Win %: 62.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_TR
FCEL Gain: $ 11.16 Win %: 54.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 11.17 Win %: 55.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_TR
FCEL Gain: $ 11.24 Win %: 56.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AV
FCEL Gain: $ 11.31 Win %: 53.00 in 121 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 11.35 Win %: 54.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 11.38 Win %: 54.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 11.39 Win %: 66.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
FCEL Gain: $ 11.44 Win %: 64.00 in 121 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 11.46 Win %: 54.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 11.46 Win %: 54.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 11.52 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 11.57 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 11.72 Win %: 57.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AV
FCEL Gain: $ 11.73 Win %: 55.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_TR
FCEL Gain: $ 11.78 Win %: 54.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 11.92 Win %: 57.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 11.97 Win %: 57.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_SS
FCEL Gain: $ 12.05 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV
FCEL Gain: $ 12.27 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_TR
FCEL Gain: $ 12.27 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 12.27 Win %: 58.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
FCEL Gain: $ 12.34 Win %: 57.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_RV_AV
FCEL Gain: $ 12.45 Win %: 65.00 in 125 days with algo TB3_HL_HS_QM_OB2_OS2_CB5_CS5_QL
FCEL Gain: $ 12.62 Win %: 58.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV
FCEL Gain: $ 12.83 Win %: 58.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_SS
FCEL Gain: $ 12.89 Win %: 61.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 13.12 Win %: 59.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_SS
FCEL Gain: $ 13.15 Win %: 56.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 13.27 Win %: 58.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_SS
FCEL Gain: $ 13.34 Win %: 59.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_SS
FCEL Gain: $ 13.41 Win %: 54.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 13.41 Win %: 54.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 13.45 Win %: 54.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 13.49 Win %: 55.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 13.5 Win %: 54.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 13.57 Win %: 60.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_SS
FCEL Gain: $ 13.62 Win %: 54.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 13.65 Win %: 56.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 13.82 Win %: 54.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 13.82 Win %: 57.00 in 125 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_HM
FCEL Gain: $ 14.02 Win %: 56.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_SS
FCEL Gain: $ 15.11 Win %: 56.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_RV_AV
FCEL Gain: $ 18.4 Win %: 57.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 18.42 Win %: 53.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_AV
FCEL Gain: $ 18.5 Win %: 53.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_AV
FCEL Gain: $ 18.83 Win %: 58.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 18.92 Win %: 54.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_AV
FCEL Gain: $ 19.04 Win %: 58.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 19.11 Win %: 58.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 19.12 Win %: 59.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 19.15 Win %: 59.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 19.16 Win %: 54.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_AV
FCEL Gain: $ 19.34 Win %: 58.00 in 121 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 19.37 Win %: 60.00 in 123 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 19.38 Win %: 60.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 19.48 Win %: 60.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 19.51 Win %: 54.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_HM_AV
FCEL Gain: $ 19.65 Win %: 59.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 19.88 Win %: 60.00 in 124 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 19.89 Win %: 59.00 in 125 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 19.91 Win %: 59.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 19.94 Win %: 59.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 19.99 Win %: 60.00 in 118 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 20.02 Win %: 60.00 in 120 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 20.33 Win %: 59.00 in 117 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_HM_AV
FCEL Gain: $ 20.69 Win %: 57.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 20.89 Win %: 65.00 in 122 days with algo TB5_HL_QM_OB1_OS1_CB5_CS5_AV
FCEL Gain: $ 20.97 Win %: 58.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_AV
FCEL Gain: $ 21.04 Win %: 61.00 in 121 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 21.13 Win %: 61.00 in 118 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_AV
FCEL Gain: $ 21.66 Win %: 58.00 in 124 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AV
FCEL Gain: $ 21.74 Win %: 58.00 in 122 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AV
FCEL Gain: $ 22.09 Win %: 58.00 in 117 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AV
FCEL Gain: $ 22.16 Win %: 59.00 in 120 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AV
FCEL Gain: $ 22.22 Win %: 59.00 in 123 days with algo TB5_HL_QM_OB3_OS3_CB5_CS5_AV
