KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_AC
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_AO
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_AO_AC
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_IT
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_IT_QL
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_QL
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_TR
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_AC
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_AO
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_AO_AC
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_IT
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_IT_QL
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_QL
KO Gain: $ Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_TR
KO Gain: $ -0.89 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_TR_IR2
KO Gain: $ -0.89 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_TR_IR2
KO Gain: $ -0.77 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM_AV
KO Gain: $ -0.77 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_HM_AV
KO Gain: $ -0.74 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_IT_QP
KO Gain: $ -0.74 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_IT_QP
KO Gain: $ -0.54 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_AV
KO Gain: $ -0.54 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_AV
KO Gain: $ -0.52 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_IR2
KO Gain: $ -0.52 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_IR2
KO Gain: $ -0.48 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_IT_QP_DB8
KO Gain: $ -0.48 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_IT_QP_DB8
KO Gain: $ -0.4 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV
KO Gain: $ -0.4 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_RV
KO Gain: $ -0.37 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_QP
KO Gain: $ -0.37 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_RV_QP
KO Gain: $ -0.36 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_AL
KO Gain: $ -0.36 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_AL
KO Gain: $ -0.36 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_AL
KO Gain: $ -0.36 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_RV_AL
KO Gain: $ -0.35 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_AV
KO Gain: $ -0.35 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_RV_AV
KO Gain: $ -0.34 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM_QP
KO Gain: $ -0.34 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_HM_QP
KO Gain: $ -0.33 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM_TR
KO Gain: $ -0.33 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_LI
KO Gain: $ -0.33 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_HM_TR
KO Gain: $ -0.33 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_LI
KO Gain: $ -0.24 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_AV
KO Gain: $ -0.24 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_AV
KO Gain: $ -0.23 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM
KO Gain: $ -0.23 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_HM
KO Gain: $ -0.22 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_QP_PM
KO Gain: $ -0.22 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_QP_PM
KO Gain: $ -0.17 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_RV_AV
KO Gain: $ -0.17 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_RV_AV
KO Gain: $ -0.13 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_QP
KO Gain: $ -0.13 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_TR_QP
KO Gain: $ -0.13 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_TS
KO Gain: $ -0.13 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_QP
KO Gain: $ -0.13 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_TR_QP
KO Gain: $ -0.13 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_TS
KO Gain: $ -0.06 Win %: 80.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_QP_IR2
KO Gain: $ -0.06 Win %: 80.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_QP_IR2
KO Gain: $ -0.02 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_SS
KO Gain: $ -0.02 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_SS
KO Gain: $ 0.03 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_TR
KO Gain: $ 0.03 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_RV_TR
KO Gain: $ 0.11 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM_QP_DB8
KO Gain: $ 0.11 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_HM_QP_DB8
KO Gain: $ 0.12 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM_TR_DB8
KO Gain: $ 0.12 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_HM_TR_DB8
KO Gain: $ 0.13 Win %: 60.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_QP_DB8
KO Gain: $ 0.13 Win %: 60.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_RV_QP_DB8
KO Gain: $ 0.16 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_PM
KO Gain: $ 0.16 Win %: 20.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_PM
KO Gain: $ 0.2 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_RV_AV_DB15
KO Gain: $ 0.2 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_RV_AV_DB15
KO Gain: $ 0.31 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_AL_DB8
KO Gain: $ 0.31 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_RV_AL_DB8
KO Gain: $ 0.36 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_IT_QP_DB15
KO Gain: $ 0.36 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_IT_QP_DB15
KO Gain: $ 0.37 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_TR_QP_DB8
KO Gain: $ 0.37 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_TR_QP_DB8
KO Gain: $ 0.39 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_AO_AC
KO Gain: $ 0.39 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_AO_AC
KO Gain: $ 0.45 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_DB8
KO Gain: $ 0.45 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_IT_QL_DB8
KO Gain: $ 0.45 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_DB8
KO Gain: $ 0.45 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_IT_QL_DB8
KO Gain: $ 0.48 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB8
KO Gain: $ 0.48 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB8
KO Gain: $ 0.53 Win %: 100.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_IT_QP
KO Gain: $ 0.53 Win %: 100.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_IT_QP
KO Gain: $ 0.61 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_VI
KO Gain: $ 0.61 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_VI
KO Gain: $ 0.63 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_TR
KO Gain: $ 0.63 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_TR
KO Gain: $ 0.63 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_QP_PM
KO Gain: $ 0.63 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_QP_PM
KO Gain: $ 0.76 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_RV_TR
KO Gain: $ 0.76 Win %: 40.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_RV_TR
KO Gain: $ 0.81 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_TR_IR4
KO Gain: $ 0.81 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_TR_IR4
KO Gain: $ 0.83 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_VI
KO Gain: $ 0.83 Win %: 40.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_VI
KO Gain: $ 0.88 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_HM_TR
KO Gain: $ 0.88 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_HM_TR
KO Gain: $ 0.96 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_HM_AV_DB15
KO Gain: $ 0.96 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_HM_AV_DB15
KO Gain: $ 1.01 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_TR_QP
KO Gain: $ 1.01 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_TR_QP
KO Gain: $ 1.04 Win %: 60.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM_AV_DB8
KO Gain: $ 1.04 Win %: 60.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_HM_AV_DB8
KO Gain: $ 1.12 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_HM_TR_DB15
KO Gain: $ 1.12 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_HM_TR_DB15
KO Gain: $ 1.16 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_RV_TR_DB15
KO Gain: $ 1.16 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_RV_TR_DB15
KO Gain: $ 1.21 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_RV_QP
KO Gain: $ 1.21 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_RV_QP
KO Gain: $ 1.23 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_PM
KO Gain: $ 1.23 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_PM
KO Gain: $ 1.23 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_PM
KO Gain: $ 1.23 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_HM_AV
KO Gain: $ 1.23 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_HM_AV
KO Gain: $ 1.28 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_AC
KO Gain: $ 1.28 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_AC
KO Gain: $ 1.32 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_TR_QP_DB15
KO Gain: $ 1.32 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_TR_QP_DB15
KO Gain: $ 1.46 Win %: 60.00 in 5 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_AV_DB8
KO Gain: $ 1.46 Win %: 60.00 in 5 days with algo TB4_HS_QM_OB2_OS2_CB5_CS5_RV_AV_DB8
KO Gain: $ 1.62 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_RV
KO Gain: $ 1.62 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_RV
KO Gain: $ 1.73 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_AL
KO Gain: $ 1.73 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_AL
KO Gain: $ 1.83 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_HM_QP
KO Gain: $ 1.83 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_HM_QP
KO Gain: $ 2 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_IT
KO Gain: $ 2 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_IT_QL
KO Gain: $ 2 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_IT
KO Gain: $ 2 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_IT_QL
KO Gain: $ 2.03 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_RV_QP_DB15
KO Gain: $ 2.03 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_RV_QP_DB15
KO Gain: $ 2.05 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_LI
KO Gain: $ 2.05 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_LI
KO Gain: $ 2.06 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_RV_AL
KO Gain: $ 2.06 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_RV_AL
KO Gain: $ 2.09 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_RV_AL_DB15
KO Gain: $ 2.09 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_RV_AL_DB15
KO Gain: $ 2.1 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_HM_QP_DB15
KO Gain: $ 2.1 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_HM_QP_DB15
KO Gain: $ 2.16 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_QP
KO Gain: $ 2.16 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_QP
KO Gain: $ 2.29 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_QP_IR4
KO Gain: $ 2.29 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_QP_IR4
KO Gain: $ 2.31 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_QL
KO Gain: $ 2.31 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_SS
KO Gain: $ 2.31 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_QL
KO Gain: $ 2.31 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_SS
KO Gain: $ 2.31 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_IR4
KO Gain: $ 2.31 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_IR4
KO Gain: $ 2.32 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_TS
KO Gain: $ 2.32 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_TS
KO Gain: $ 2.41 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_AO
KO Gain: $ 2.41 Win %: 60.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_AO
KO Gain: $ 2.52 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_HM
KO Gain: $ 2.52 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_HM
KO Gain: $ 2.63 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_IT_QL_DB15
KO Gain: $ 2.63 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_IT_QL_DB15
KO Gain: $ 2.8 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB1_OS1_CB3_CS3_DB15
KO Gain: $ 2.8 Win %: 80.00 in 5 days with algo TB2_HL_LO_QM_OB2_OS2_CB3_CS3_DB15
