Gain: $ -20.75 Win %: 46.00 in 71 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ -9.41 Win %: 47.00 in 71 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -9.41 Win %: 47.00 in 71 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ -6.18 Win %: 47.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_HM
Gain: $ -5.44 Win %: 50.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_HM
Gain: $ -0.62 Win %: 44.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -0.62 Win %: 44.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 0 Win %: 100.00 in 71 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_HM_AV
Gain: $ 0 Win %: 100.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_HM_QP
Gain: $ 0 Win %: 100.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_HM_TR
NIO Gain: $ -0.66 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_IR4
NIO Gain: $ -0.66 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_IR4
NIO Gain: $ -1.16 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_IR4
NIO Gain: $ -1.23 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_VI
NIO Gain: $ -1.71 Win %: 54.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_VI
NIO Gain: $ -1.71 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_AL
NIO Gain: $ -1.71 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_AL
NIO Gain: $ -11.15 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_QP_IR4
NIO Gain: $ -11.15 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_QP_IR4
NIO Gain: $ -11.19 Win %: 54.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_HM
NIO Gain: $ -12.28 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_TR_QP
NIO Gain: $ -12.28 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_TR_QP
NIO Gain: $ -12.88 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_HM
NIO Gain: $ -13.06 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_QP_IR4
NIO Gain: $ -13.15 Win %: 50.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_RV_QP
NIO Gain: $ -13.33 Win %: 55.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_RV_QP
NIO Gain: $ -13.9 Win %: 49.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_QP_IR4
NIO Gain: $ -14.02 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_TR_QP
NIO Gain: $ -15.1 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_TR_QP
NIO Gain: $ -16.88 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_QP
NIO Gain: $ -17.58 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_HM_AV
NIO Gain: $ -17.58 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_HM_AV
NIO Gain: $ -17.69 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_QP
NIO Gain: $ -18.21 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_HM_AV
NIO Gain: $ -19.41 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_HM_AV
NIO Gain: $ -19.49 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_QP
NIO Gain: $ -2.75 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_AL
NIO Gain: $ -2.87 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_VI
NIO Gain: $ -2.87 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_VI
NIO Gain: $ -23.46 Win %: 48.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_QP
NIO Gain: $ -24.65 Win %: 50.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_HM_QP
NIO Gain: $ -24.98 Win %: 48.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_HM_QP
NIO Gain: $ -25.53 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_HM_QP
NIO Gain: $ -27.77 Win %: 48.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_HM_QP
NIO Gain: $ -3.06 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_IR4
NIO Gain: $ -3.33 Win %: 62.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_HM_TR
NIO Gain: $ -3.33 Win %: 62.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_HM_TR
NIO Gain: $ -3.34 Win %: 55.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_AV
NIO Gain: $ -3.34 Win %: 55.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_AV
NIO Gain: $ -3.7 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_AL
NIO Gain: $ -4.17 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_AV
NIO Gain: $ -4.76 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_HM
NIO Gain: $ -4.76 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_HM
NIO Gain: $ -4.88 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_AV
NIO Gain: $ -6.75 Win %: 53.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_RV_AV
NIO Gain: $ -6.81 Win %: 54.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AV
NIO Gain: $ -6.81 Win %: 54.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_RV_AV
NIO Gain: $ -7.29 Win %: 54.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_RV_QP
NIO Gain: $ -7.29 Win %: 54.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_RV_QP
NIO Gain: $ -7.33 Win %: 58.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_HM_TR
NIO Gain: $ -7.44 Win %: 51.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_RV_AV
NIO Gain: $ -8.39 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_HM_TR
NIO Gain: $ 0.29 Win %: 61.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_LI
NIO Gain: $ 0.53 Win %: 62.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_DB15
NIO Gain: $ 1.78 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_LI
NIO Gain: $ 10.36 Win %: 58.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_TR_IR4
NIO Gain: $ 11.12 Win %: 62.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_TR
NIO Gain: $ 11.12 Win %: 62.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_TR
NIO Gain: $ 11.57 Win %: 59.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_RV_TR_DB4
NIO Gain: $ 12.9 Win %: 58.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_RV_TR
NIO Gain: $ 12.9 Win %: 58.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_RV_TR_DB4
NIO Gain: $ 12.9 Win %: 58.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_RV_TR
NIO Gain: $ 12.9 Win %: 58.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_RV_TR_DB4
NIO Gain: $ 15.41 Win %: 64.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_RV
NIO Gain: $ 15.41 Win %: 64.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_RV
NIO Gain: $ 2.25 Win %: 55.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_QL
NIO Gain: $ 2.71 Win %: 64.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_DB15
NIO Gain: $ 2.93 Win %: 55.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_LI
NIO Gain: $ 2.93 Win %: 55.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_LI
NIO Gain: $ 3.89 Win %: 58.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_QL
NIO Gain: $ 4.85 Win %: 63.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_SS
NIO Gain: $ 5.2 Win %: 55.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_RV_AL
NIO Gain: $ 5.81 Win %: 62.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_RV
NIO Gain: $ 6.27 Win %: 62.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_RV
NIO Gain: $ 6.29 Win %: 64.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_SS
NIO Gain: $ 6.77 Win %: 54.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_TR_IR4
NIO Gain: $ 6.77 Win %: 54.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_TR_IR4
NIO Gain: $ 6.98 Win %: 55.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_RV_AL
NIO Gain: $ 7.05 Win %: 58.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_RV_TR
NIO Gain: $ 7.05 Win %: 58.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_RV_TR_DB4
NIO Gain: $ 7.39 Win %: 59.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_QL
NIO Gain: $ 7.51 Win %: 59.00 in 77 days with algo TB2_HL_HI_QM_OB3_OS3_CB4_CS4_TR
NIO Gain: $ 7.73 Win %: 59.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_QL
NIO Gain: $ 8 Win %: 66.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4
NIO Gain: $ 8.05 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AL
NIO Gain: $ 8.05 Win %: 57.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_RV_AL
NIO Gain: $ 8.13 Win %: 54.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_TR_IR4
NIO Gain: $ 8.14 Win %: 63.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_SS
NIO Gain: $ 8.14 Win %: 63.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_SS
NIO Gain: $ 8.83 Win %: 59.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_TR
NIO Gain: $ 9.42 Win %: 66.00 in 77 days with algo TB2_HL_HI_QM_OB1_OS1_CB4_CS4_DB15
NIO Gain: $ 9.42 Win %: 66.00 in 77 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_DB15
NIO Gain: $ 9.92 Win %: 59.00 in 77 days with algo TB2_HL_HI_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ 0.6 Win %: 94.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_TR_QP
Gain: $ 5.34 Win %: 59.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ 5.54 Win %: 59.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_RV_QP
Gain: $ 5.63 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ 5.63 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ 6.86 Win %: 52.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 7.2 Win %: 75.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 7.2 Win %: 75.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ 7.2 Win %: 75.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ 7.2 Win %: 75.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_QP_IR5
Gain: $ 7.48 Win %: 84.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_VI
Gain: $ 7.66 Win %: 68.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ 7.66 Win %: 68.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ 8.18 Win %: 70.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ 9.2 Win %: 86.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 9.5 Win %: 86.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 9.5 Win %: 86.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 10.21 Win %: 77.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_QP
Gain: $ 10.32 Win %: 45.00 in 71 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_RV_AV
Gain: $ 10.43 Win %: 48.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 10.43 Win %: 48.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 10.96 Win %: 45.00 in 71 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 11.2 Win %: 75.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ 11.2 Win %: 75.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ 11.46 Win %: 76.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ 11.46 Win %: 76.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ 11.48 Win %: 80.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_QP
Gain: $ 11.48 Win %: 80.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 13.43 Win %: 46.00 in 71 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 13.43 Win %: 46.00 in 71 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 13.77 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 14.12 Win %: 45.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_RV
Gain: $ 14.76 Win %: 45.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 14.84 Win %: 75.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 15.04 Win %: 61.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_QL
Gain: $ 15.72 Win %: 70.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 15.72 Win %: 70.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 15.91 Win %: 77.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_LI
Gain: $ 16 Win %: 52.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 16 Win %: 52.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 16.26 Win %: 45.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 16.26 Win %: 45.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 17.99 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 17.99 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 17.99 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 17.99 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ 17.99 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ 17.99 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ 17.99 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_IR5
Gain: $ 17.99 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_TR_IR5
Gain: $ 18.1 Win %: 61.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 18.59 Win %: 59.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 18.59 Win %: 59.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 19.9 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_SS
Gain: $ 20.16 Win %: 64.00 in 71 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 21.54 Win %: 64.00 in 71 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 21.96 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_DB6
Gain: $ 21.96 Win %: 63.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 22.59 Win %: 67.00 in 71 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_AV
Gain: $ 22.7 Win %: 66.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_DB6
Gain: $ 23.72 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_RV_TR
Gain: $ 23.87 Win %: 67.00 in 71 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_AL
Gain: $ 24.36 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 24.42 Win %: 61.00 in 71 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 24.42 Win %: 61.00 in 71 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 24.48 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ 24.48 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 24.48 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5
Gain: $ 24.48 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_DB6
Gain: $ 24.48 Win %: 58.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 24.81 Win %: 66.00 in 72 days with algo TB5_HL_HS_QM_OB5_OS5_CB3_CS3_TR
Gain: $ 24.98 Win %: 61.00 in 71 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 24.98 Win %: 61.00 in 71 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 26.37 Win %: 54.00 in 72 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 26.37 Win %: 54.00 in 72 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
