Gain: $ -6.84 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_HM_QP
Gain: $ -6.63 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_QP
Gain: $ -6.63 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_RV_QP
Gain: $ -6.32 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_HM
Gain: $ -5.97 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_AL
Gain: $ -5.4 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_HM_AV
Gain: $ -5.4 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM_AV
Gain: $ -5.34 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_RV_AL
Gain: $ -4.3 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_RV_AV
Gain: $ -4.09 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_LI
Gain: $ -3.99 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_RV_AL
Gain: $ -3.77 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_AV
Gain: $ -3.51 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_QP_IR5
Gain: $ -3.51 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_QP_IR5
Gain: $ -3.28 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_RV_AL
Gain: $ -3.23 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_HM_AV
Gain: $ -3.2 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_AL
Gain: $ -3.04 Win %: 50.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_HM_TR
Gain: $ -3.03 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_QP_IR5
Gain: $ -2.98 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_HM_QP
Gain: $ -2.98 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_QP
Gain: $ -2.93 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_LI
Gain: $ -2.91 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_IR5
Gain: $ -2.89 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_AL
Gain: $ -2.86 Win %: 50.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_RV_TR
Gain: $ -2.85 Win %: 50.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_TR
Gain: $ -2.83 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_DB8
Gain: $ -2.83 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_HM
Gain: $ -2.78 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_RV_QP
Gain: $ -2.63 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_RV
Gain: $ -2.63 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_QP_IR5
Gain: $ -2.55 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_RV_TR
Gain: $ -2.51 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_IR5
Gain: $ -2.49 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $ -2.49 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_RV_AV
Gain: $ -2.46 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_RV_QP
Gain: $ -2.43 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_AL
Gain: $ -2.42 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_RV_QP
Gain: $ -2.34 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_HM_QP
Gain: $ -2.34 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_QP
Gain: $ -2.31 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_RV
Gain: $ -2.28 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_RV_AV
Gain: $ -2.19 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3
Gain: $ -2.19 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_DB8
Gain: $ -2.19 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_HM
Gain: $ -2.18 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_RV
Gain: $ -2.18 Win %: 50.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_QP_IR5
Gain: $ -2.08 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_QL
Gain: $ -2.08 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_QL
Gain: $ -2.04 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_RV_TR
Gain: $ -2.04 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_TR_QP
Gain: $ -1.95 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_SS
Gain: $ -1.9 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_HM_TR
Gain: $ -1.9 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_TR
Gain: $ -1.83 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_TR_IR5
Gain: $ -1.83 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_LI
Gain: $ -1.82 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_HM_TR
Gain: $ -1.82 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_TR
Gain: $ -1.74 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_IR5
Gain: $ -1.74 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_IR5
Gain: $ -1.7 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_RV_TR
Gain: $ -1.68 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_HM_QP
Gain: $ -1.68 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_HM_QP
Gain: $ -1.68 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_QP
Gain: $ -1.68 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_AV
Gain: $ -1.68 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_HM_AV
Gain: $ -1.63 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV_AL
Gain: $ -1.63 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_RV_AL
Gain: $ -1.61 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_RV_AV
Gain: $ -1.61 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_VI
Gain: $ -1.61 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_VI
Gain: $ -1.46 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_AV
Gain: $ -1.46 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_HM_AV
Gain: $ -1.44 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_RV_AV
Gain: $ -1.44 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_TR_IR5
Gain: $ -1.38 Win %: 0 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_TR_QP
Gain: $ -1.37 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_TR_IR5
Gain: $ -1.37 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_TR_IR5
Gain: $ -1.36 Win %: 0 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_HM_QP
Gain: $ -1.31 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_VI
Gain: $ -1.3 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_TR_QP
Gain: $ -1.29 Win %: 0 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_QP_IR5
Gain: $ -1.25 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_HM_TR
Gain: $ -1.25 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_TR
Gain: $ -1.25 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_RV_TR
Gain: $ -1.25 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_TR_IR5
Gain: $ -1.22 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_SS
Gain: $ -1.17 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_SS
Gain: $ -1.17 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_TR_QP
Gain: $ -1.14 Win %: 50.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_VI
Gain: $ -1.12 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_RV_AL
Gain: $ -1.11 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_RV_AV
Gain: $ -1.07 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $ -1.07 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_RV_TR
Gain: $ -1.06 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_DB10
Gain: $ -1.06 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_HM
Gain: $ -1.06 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_QL
Gain: $ -1.01 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_HM_TR
Gain: $ -1.01 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_TR
Gain: $ -0.93 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_RV_AL
Gain: $ -0.92 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_AV
Gain: $ -0.92 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_HM_AV
Gain: $ -0.91 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_AL
Gain: $ -0.8 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_TR_IR5
Gain: $ -0.8 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_TR_IR5
Gain: $ -0.72 Win %: 50.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_SS
Gain: $ -0.72 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_AV
Gain: $ -0.72 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_AV
Gain: $ -0.66 Win %: 0 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_TR_QP
Gain: $ -0.6 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_QP_IR5
Gain: $ -0.6 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_QP_IR5
Gain: $ -0.59 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $ -0.54 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_RV
Gain: $ -0.53 Win %: 0 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $ -0.46 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV
Gain: $ -0.46 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_RV
Gain: $ -0.45 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_AL
Gain: $ -0.43 Win %: 0 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_VI
Gain: $ -0.41 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_AL
Gain: $ -0.4 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_AV
Gain: $ -0.4 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_HM_AV
Gain: $ -0.39 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_RV_QP
Gain: $ -0.39 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_TR_QP
Gain: $ -0.33 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_VI
Gain: $ -0.29 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_TR
Gain: $ -0.29 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_TR
Gain: $ -0.22 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_VI
Gain: $ -0.21 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $ -0.21 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_RV_QP
Gain: $ -0.19 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_RV_TR_DB
Gain: $ -0.18 Win %: 0 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_IR5
Gain: $ -0.07 Win %: 0 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_VI
Gain: $ -0.03 Win %: 0 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_HM
Gain: $ 0 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB4_PL_QM_OB4_OS4_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB4_PL_QM_OB5_OS5_CB3_CS3_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV_TR_DB
NKE Gain: $ -0.03 Win %: 25.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_LI
NKE Gain: $ -0.08 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_VI
NKE Gain: $ -0.09 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_HM
NKE Gain: $ -0.09 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_TR_QP
NKE Gain: $ -0.13 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_RV_TR_DB3
NKE Gain: $ -0.17 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_IR2
NKE Gain: $ -0.22 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_QP_IR5
NKE Gain: $ -0.28 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_QP_IR2
NKE Gain: $ -0.39 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_TR_DB5
NKE Gain: $ -0.41 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_RV
NKE Gain: $ -0.44 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_IR5
NKE Gain: $ -0.45 Win %: 66.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_QP_IR2
NKE Gain: $ -0.51 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_VI
NKE Gain: $ -0.52 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_SS
NKE Gain: $ -0.54 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_HM_AV
NKE Gain: $ -0.54 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_TR
NKE Gain: $ -0.57 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_DB8
NKE Gain: $ -0.57 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_QL
NKE Gain: $ -0.57 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_QP
NKE Gain: $ -0.71 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_TR
NKE Gain: $ -0.72 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_HM_TR
NKE Gain: $ -0.76 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_TR_IR5
NKE Gain: $ -0.78 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_RV_AV
NKE Gain: $ -0.8 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_HM_TR
NKE Gain: $ -0.81 Win %: 0 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_RV_AV
NKE Gain: $ -0.81 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_HM_TR
NKE Gain: $ -0.82 Win %: 25.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_RV_AV
NKE Gain: $ -0.83 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_TR_IR2
NKE Gain: $ -0.83 Win %: 66.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_VI
NKE Gain: $ -0.88 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_SS
NKE Gain: $ -0.89 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_RV_AV
NKE Gain: $ -0.89 Win %: 75.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_AL
NKE Gain: $ -0.9 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_TR
NKE Gain: $ -0.93 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_RV_TR
NKE Gain: $ -0.93 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_RV_TR_DB2
NKE Gain: $ -0.97 Win %: 0 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_TR_QP
NKE Gain: $ -1.03 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_TR_IR2
NKE Gain: $ -1.05 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_RV_TR_DB2
NKE Gain: $ -1.08 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_VI
NKE Gain: $ -1.09 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_TR
NKE Gain: $ -1.09 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_TR_DB5
NKE Gain: $ -1.12 Win %: 25.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_TR
NKE Gain: $ -1.12 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_AV
NKE Gain: $ -1.14 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_HM_AV
NKE Gain: $ -1.21 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_RV_TR
NKE Gain: $ -1.23 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_RV
NKE Gain: $ -1.23 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_IR5
NKE Gain: $ -1.28 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_HM_QP
NKE Gain: $ -1.28 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_HM_QP
NKE Gain: $ -1.32 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_TR_QP
NKE Gain: $ -1.33 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_RV_AL
NKE Gain: $ -1.35 Win %: 0 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_TR
NKE Gain: $ -1.37 Win %: 0 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_LI
NKE Gain: $ -1.4 Win %: 0 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_TR_IR5
NKE Gain: $ -1.42 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_QP
NKE Gain: $ -1.43 Win %: 25.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_RV_QP
NKE Gain: $ -1.55 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_HM_TR
NKE Gain: $ -1.55 Win %: 75.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_QL
NKE Gain: $ -1.63 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_AL
NKE Gain: $ -1.63 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_HM_AV
NKE Gain: $ -1.67 Win %: 0 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_RV_AL
NKE Gain: $ -1.81 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_HM
NKE Gain: $ -1.88 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_TR
NKE Gain: $ -1.92 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_LI
NKE Gain: $ -2.01 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_IR2
NKE Gain: $ -2.02 Win %: 66.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_QP_IR5
NKE Gain: $ -2.05 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_RV_TR
NKE Gain: $ -2.05 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_RV_TR_DB5
NKE Gain: $ -2.1 Win %: 25.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_HM_TR
NKE Gain: $ -2.23 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_LI
NKE Gain: $ -2.24 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_TR_QP
NKE Gain: $ -2.27 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_HM_AV
NKE Gain: $ -2.3 Win %: 25.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_HM_QP
NKE Gain: $ -2.34 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_TR_IR2
NKE Gain: $ -2.34 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_AL
NKE Gain: $ -2.38 Win %: 0 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_HM_TR
NKE Gain: $ -2.43 Win %: 0 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_TR
NKE Gain: $ -2.44 Win %: 25.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_HM_AV
NKE Gain: $ -2.56 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_QL
NKE Gain: $ -2.84 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_TR
NKE Gain: $ -2.85 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_QP_IR5
NKE Gain: $ -2.86 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_TR_QP
NKE Gain: $ -257.49 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_HM
NKE Gain: $ -3.04 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_AL
NKE Gain: $ -3.06 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_HM_AV
NKE Gain: $ -3.07 Win %: 25.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_TR_QP
NKE Gain: $ -3.12 Win %: 25.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_RV_AL
NKE Gain: $ -3.38 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_RV_AL
NKE Gain: $ -3.39 Win %: 25.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_AL
NKE Gain: $ -3.59 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_RV_TR
NKE Gain: $ -3.59 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
NKE Gain: $ -4 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_RV_QP
NKE Gain: $ -4.03 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_DB8
NKE Gain: $ -4.08 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_AV
NKE Gain: $ -4.08 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_HM_TR
NKE Gain: $ -4.12 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_RV
NKE Gain: $ -4.13 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_RV
NKE Gain: $ -4.15 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_HM
NKE Gain: $ -4.44089e-16 Win %: 75.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_QP_IR2
NKE Gain: $ -4.46 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_QP
NKE Gain: $ -4.55 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_RV_QP
NKE Gain: $ -4.58 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_HM_QP
NKE Gain: $ -5.68 Win %: 0 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_AL
NKE Gain: $ -5.8 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_AV
NKE Gain: $ -6.6 Win %: 25.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_RV_AV
NKE Gain: $ -9.81 Win %: 25.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_AV
NKE Gain: $ 0.04 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_RV_TR
NKE Gain: $ 0.08 Win %: 25.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_TR_QP
NKE Gain: $ 0.09 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2
NKE Gain: $ 0.09 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_DB30
NKE Gain: $ 0.09 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_QL
NKE Gain: $ 0.1 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_RV_QP
NKE Gain: $ 0.12 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_QL
NKE Gain: $ 0.25 Win %: 25.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_TR_IR5
NKE Gain: $ 0.26 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_AV
NKE Gain: $ 0.3 Win %: 33.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_QP
NKE Gain: $ 0.3 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_QP
NKE Gain: $ 0.32 Win %: 50.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_HM
NKE Gain: $ 0.44 Win %: 75.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_TR_IR2
NKE Gain: $ 0.5 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_QL
NKE Gain: $ 0.52 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_VI
NKE Gain: $ 0.54 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_AV
NKE Gain: $ 0.58 Win %: 75.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_LI
NKE Gain: $ 0.6 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_AL
NKE Gain: $ 0.62 Win %: 100.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_IR5
NKE Gain: $ 0.66 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_AL
NKE Gain: $ 0.69 Win %: 75.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_IR2
NKE Gain: $ 0.7 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB1_OS1_CB5_CS5_AV
NKE Gain: $ 0.71 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_SS
NKE Gain: $ 0.73 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_VI
NKE Gain: $ 0.75 Win %: 33.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_SS
NKE Gain: $ 0.76 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2
NKE Gain: $ 0.77 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_AV
NKE Gain: $ 0.77 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_AL
NKE Gain: $ 0.82 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_AV
NKE Gain: $ 0.88 Win %: 66.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_SS
NKE Gain: $ 0.89 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_AV
NKE Gain: $ 0.91 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_SS
NKE Gain: $ 0.92 Win %: 66.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_HM_QP
NKE Gain: $ 0.92 Win %: 66.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV_QP
NKE Gain: $ 0.97 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_QP
NKE Gain: $ 1 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_DB10
NKE Gain: $ 1.02 Win %: 66.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_HM
NKE Gain: $ 1.1 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_HM_TR
NKE Gain: $ 1.2 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_RV_QP
NKE Gain: $ 1.2 Win %: 66.00 in 3 days with algo TB4_OO_QM_OB2_OS2_CB1_CS1_VI
NKE Gain: $ 1.2 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_QP
NKE Gain: $ 1.22 Win %: 33.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_SS
NKE Gain: $ 1.23 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_HM_AV
NKE Gain: $ 1.25 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_QP_IR3
NKE Gain: $ 1.27 Win %: 75.00 in 4 days with algo TB4_HL_QM_OB5_OS5_CB2_CS2_DB8
NKE Gain: $ 1.3 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_TR_IR3
NKE Gain: $ 1.33 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_HM
NKE Gain: $ 1.39 Win %: 66.00 in 3 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV
NKE Gain: $ 1.53 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_TR
NKE Gain: $ 1.53 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_TR_DB2
NKE Gain: $ 1.54 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_AL
NKE Gain: $ 1.55 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_LI
NKE Gain: $ 1.6 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_HM_AV
NKE Gain: $ 1.65 Win %: 100.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_QP
NKE Gain: $ 1.66 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_TR
NKE Gain: $ 1.97 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_DB30
NKE Gain: $ 1.97 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_RV
NKE Gain: $ 2.03 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_LI
NKE Gain: $ 2.07 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_QP
NKE Gain: $ 2.3 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_RV_AL
NKE Gain: $ 2.35 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_RV
NKE Gain: $ 2.38 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_AL
NKE Gain: $ 2.39 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_TR_QP
NKE Gain: $ 2.42 Win %: 50.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_IR2
NKE Gain: $ 2.48 Win %: 100.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_IR3
NKE Gain: $ 2.5 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_QP
NKE Gain: $ 2.56 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_LI
NKE Gain: $ 2.56 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_HM_QP
NKE Gain: $ 2.61 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_HM_QP
NKE Gain: $ 2.61 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_HM_QP
NKE Gain: $ 2.61 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_QL
NKE Gain: $ 2.62 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB5_CS5_VI
NKE Gain: $ 2.8 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_DB30
NKE Gain: $ 2.8 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_QL
NKE Gain: $ 2.85 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV
NKE Gain: $ 2.86 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_DB8
NKE Gain: $ 3.39 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_HM_QP
NKE Gain: $ 3.48 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB5_OS5_CB2_CS2_SS
NKE Gain: $ 3.51 Win %: 66.00 in 3 days with algo TB1_OC_QM_OB1_OS1_CB4_CS4_HM
NKE Gain: $ 3.7 Win %: 75.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_AV
NKE Gain: $ 5.68 Win %: 100.00 in 4 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_QP_IR2
Gain: $ 0.08 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_LI
Gain: $ 0.08 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_LI
Gain: $ 0.09 Win %: 100.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_TR_IR5
Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_IR5
Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_IR5
Gain: $ 0.21 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_TR_QP
Gain: $ 0.21 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_TR_QP
Gain: $ 0.22 Win %: 50.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_DB30
Gain: $ 0.24 Win %: 50.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_RV
Gain: $ 0.25 Win %: 50.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_QL
Gain: $ 0.27 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_HM_TR
Gain: $ 0.27 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM_TR
Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_RV_AL
Gain: $ 0.37 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_QL
Gain: $ 0.43 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_HM_QP
Gain: $ 0.43 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_QP
Gain: $ 0.59 Win %: 100.00 in 2 days with algo TB1_HI_QM_OB2_OS2_CB1_CS1_IR5
Gain: $ 0.64 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_LI
Gain: $ 0.66 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_DB10
Gain: $ 0.66 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_QL
Gain: $ 0.66 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_SS
Gain: $ 0.78 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_RV_TR_DB
Gain: $ 0.84 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB4_OS4_CB1_CS1_LI
Gain: $ 0.92 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_HM_TR
Gain: $ 0.93 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_QP
Gain: $ 0.93 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_QP
Gain: $ 1 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_QL
Gain: $ 1.05 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB3_CS3_AL
Gain: $ 1.06 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_HM_AV
Gain: $ 1.25 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_LI
Gain: $ 1.26 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_DB30
Gain: $ 1.26 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4
Gain: $ 1.26 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_DB30
Gain: $ 1.81 Win %: 100.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $ 1.89 Win %: 100.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_SS
Gain: $ 1.97 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_HM_QP
Gain: $ 1.97 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_HM_QP
Gain: $ 1.97 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM_QP
Gain: $ 1.98 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_TR
Gain: $ 2 Win %: 100.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_RV
Gain: $ 2.03 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_SS
Gain: $ 2.03 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_SS
Gain: $ 2.12 Win %: 50.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_AV
Gain: $ 2.2 Win %: 100.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_HM
Gain: $ 2.53 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_HM
Gain: $ 2.53 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM
Gain: $ 2.53 Win %: 100.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_QP
Gain: $ 2.76 Win %: 100.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_DB8
Gain: $ 2.76 Win %: 100.00 in 2 days with algo TB4_HI_QM_OB2_OS2_CB4_CS4_QL
