Gain: $ -36.08 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_HM_QP
Gain: $ -36.08 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_QP
Gain: $ -36.08 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_RV_QP
Gain: $ -30.52 Win %: 0 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_RV
Gain: $ -24.92 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_TR_QP
Gain: $ -21.47 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -21.22 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_HM_QP
Gain: $ -21.22 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_HM_QP
Gain: $ -19.98 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_RV_QP
Gain: $ -17.86 Win %: 0 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_RV_AV
Gain: $ -16.49 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ -16.49 Win %: 0 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_AV
Gain: $ -16.06 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_AV
Gain: $ -16.06 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -15.83 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ -12.09 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_AV
Gain: $ -12.09 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_HM_AV
Gain: $ -11.83 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_AL
Gain: $ -11.83 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ -10.27 Win %: 0 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_QP_IR5
Gain: $ -10.06 Win %: 0 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_RV_QP
Gain: $ -9.9 Win %: 0 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_IR5
Gain: $ -9.74 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ -9.17 Win %: 0 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_TR
Gain: $ -8.85 Win %: 0 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $ -8.85 Win %: 0 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_RV_AV
Gain: $ -8.85 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ -8.85 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_RV_AV
Gain: $ -8.75 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_HM
Gain: $ -8.63 Win %: 0 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_HM_AV
Gain: $ -8.63 Win %: 0 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_HM_AV
Gain: $ -8.63 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -8.63 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_HM_AV
Gain: $ -8.1 Win %: 0 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_RV_TR
Gain: $ -7.79 Win %: 0 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_DB6
Gain: $ -7.66 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_QP_IR5
Gain: $ -7.66 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ -7.14 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AV
Gain: $ -6.48 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_HM_TR
Gain: $ -6.48 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_TR
Gain: $ -5.18 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_QL
Gain: $ -5.02 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_QP
Gain: $ -4.96 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_TR_IR5
Gain: $ -4.59 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ -4.59 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_SS
Gain: $ -4.42 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_VI
Gain: $ -4.02 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_LI
Gain: $ -3.51 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_HM_QP
Gain: $ -3.51 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_HM_QP
Gain: $ -3.51 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_HM_QP
Gain: $ -3.51 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -3.51 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_HM_QP
Gain: $ -3.22 Win %: 0 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_VI
Gain: $ -2.74 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_HM_TR
Gain: $ -2.74 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_HM_TR
Gain: $ -2.74 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ -2.74 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_HM_TR
Gain: $ -2.71 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_TR_IR5
Gain: $ -2.71 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ -2.71 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_TR_IR5
Gain: $ -2.53 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $ -2.53 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_RV_QP
Gain: $ -2.53 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -2.53 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_RV_QP
Gain: $ -2.1 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_VI
Gain: $ -1.89 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_QL
Gain: $ -1.85 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_VI
Gain: $ -1.32 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_QP_IR5
Gain: $ -1.15 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_AV
Gain: $ -1.15 Win %: 0 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_HM_AV
Gain: $ -0.02 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_TR
Gain: $ 0 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_RV_TR_DB
NTLA Gain: $ -133.99 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_RV_QP
NTLA Gain: $ -2.91 Win %: 50.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_QP
NTLA Gain: $ -214.76 Win %: 0 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_QP
NTLA Gain: $ -22.8 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_HM
NTLA Gain: $ -222.65 Win %: 0 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_HM_QP
NTLA Gain: $ -25.98 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_QP_IR2
NTLA Gain: $ -26.04 Win %: 0 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_QP_IR2
NTLA Gain: $ -28.98 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_TR_QP
NTLA Gain: $ -3.56 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_SS
NTLA Gain: $ -3.92 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_AV
NTLA Gain: $ -3.92 Win %: 50.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_AV
NTLA Gain: $ -31.89 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_HM_QP
NTLA Gain: $ -31.89 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_HM_QP
NTLA Gain: $ -37.16 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_RV_QP
NTLA Gain: $ -37.16 Win %: 25.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_RV_QP
NTLA Gain: $ -4.11 Win %: 25.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_QL
NTLA Gain: $ -4.68 Win %: 25.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_QP_IR2
NTLA Gain: $ -6.29 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_RV
NTLA Gain: $ -9.49 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_DB8
NTLA Gain: $ -9.56 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_RV_AV
NTLA Gain: $ 10.03 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_VI
NTLA Gain: $ 10.16 Win %: 50.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_HM_AV
NTLA Gain: $ 10.16 Win %: 50.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_HM_AV
NTLA Gain: $ 10.82 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_RV_AL
NTLA Gain: $ 11.29 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_AV
NTLA Gain: $ 11.41 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_TR_QP
NTLA Gain: $ 14.94 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_SS
NTLA Gain: $ 15.06 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_RV_AL
NTLA Gain: $ 15.99 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_QL
NTLA Gain: $ 17.44 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_QP
NTLA Gain: $ 17.47 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_RV
NTLA Gain: $ 18.36 Win %: 25.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_QP_IR2
NTLA Gain: $ 18.54 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_HM_TR
NTLA Gain: $ 18.54 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM_TR
NTLA Gain: $ 19.65 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_TR
NTLA Gain: $ 20.16 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_HM_TR
NTLA Gain: $ 20.26 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_IR2
NTLA Gain: $ 20.67 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_LI
NTLA Gain: $ 20.97 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_RV_AV
NTLA Gain: $ 21.13 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_AL
NTLA Gain: $ 21.22 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_HM
NTLA Gain: $ 21.7 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_AV
NTLA Gain: $ 22.94 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_TR_IR2
NTLA Gain: $ 23.9 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM
NTLA Gain: $ 24.88 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_AL
NTLA Gain: $ 25.43 Win %: 50.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM_AV
NTLA Gain: $ 25.84 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_HM_AV
NTLA Gain: $ 26.11 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_HM_QP
NTLA Gain: $ 26.19 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_RV
NTLA Gain: $ 27.98 Win %: 25.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_QL
NTLA Gain: $ 28.03 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_AL
NTLA Gain: $ 28.26 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_RV_TR_DB2
NTLA Gain: $ 29.8 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_RV_TR
NTLA Gain: $ 31.95 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_RV_TR_DB2
NTLA Gain: $ 32.28 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_LI
NTLA Gain: $ 32.51 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_IR2
NTLA Gain: $ 32.72 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_HM_TR
NTLA Gain: $ 33.4 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_DB8
NTLA Gain: $ 34.19 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_SS
NTLA Gain: $ 34.19 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_SS
NTLA Gain: $ 34.94 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_RV_TR
NTLA Gain: $ 34.94 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_RV_TR_DB2
NTLA Gain: $ 34.94 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
NTLA Gain: $ 35.15 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_AL
NTLA Gain: $ 35.31 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_IR2
NTLA Gain: $ 35.38 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_AL
NTLA Gain: $ 35.98 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_QP
NTLA Gain: $ 36.39 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_VI
NTLA Gain: $ 36.39 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_VI
NTLA Gain: $ 37.98 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_TR
NTLA Gain: $ 37.98 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_TR
NTLA Gain: $ 38.14 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV
NTLA Gain: $ 38.85 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_RV_AL
NTLA Gain: $ 39.31 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_TR
NTLA Gain: $ 4.41 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_DB8
NTLA Gain: $ 40.67 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_LI
NTLA Gain: $ 41.21 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_RV_TR
NTLA Gain: $ 41.96 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5
NTLA Gain: $ 42.38 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_TR_IR2
NTLA Gain: $ 43.27 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_QP
NTLA Gain: $ 43.57 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_DB8
NTLA Gain: $ 44.45 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_RV_TR
NTLA Gain: $ 45.02 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_HM
NTLA Gain: $ 46.37 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_IR2
NTLA Gain: $ 5.31 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_AV
NTLA Gain: $ 56.39 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_VI
NTLA Gain: $ 56.92 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_LI
NTLA Gain: $ 6.08 Win %: 75.00 in 4 days with algo TB4_CC_QM_OB2_OS2_CB1_CS1_RV_AV
NTLA Gain: $ 6.81 Win %: 25.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_QL
NTLA Gain: $ 64.47 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB1_OS1_CB5_CS5_TR_IR2
NTLA Gain: $ 68.57 Win %: 75.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_TR_IR2
NTLA Gain: $ 8.6 Win %: 100.00 in 4 days with algo TB4_CC_QM_OB5_OS5_CB3_CS3_TR_QP
NTLA Gain: $ 8.6 Win %: 100.00 in 4 days with algo TB4_HS_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ 0.82 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_QP
Gain: $ 1.04 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_TR_IR5
Gain: $ 1.14 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_QP_IR5
Gain: $ 1.67 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_AV
Gain: $ 1.67 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_AV
Gain: $ 1.67 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_AV
Gain: $ 1.67 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_AV
Gain: $ 1.88 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ 1.88 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_QP
Gain: $ 1.88 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ 1.89 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_TR_QP
Gain: $ 1.92 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1
Gain: $ 1.92 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_RV_TR
Gain: $ 1.92 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_HM_TR
Gain: $ 1.92 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_IR5
Gain: $ 1.92 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AL
Gain: $ 2.05 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_QP
Gain: $ 2.27 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_LI
Gain: $ 2.3 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_HM_QP
Gain: $ 2.39 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_RV_AV
Gain: $ 2.41 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_SS
Gain: $ 2.43 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_DB6
Gain: $ 2.84 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_LI
Gain: $ 3.17 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_IR5
Gain: $ 3.2 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_IR5
Gain: $ 3.2 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 3.2 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_IR5
Gain: $ 3.22 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_DB8
Gain: $ 3.22 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_QL
Gain: $ 3.22 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_SS
Gain: $ 3.25 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_TR_QP
Gain: $ 3.25 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_QP
Gain: $ 3.25 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_TR_QP
Gain: $ 3.25 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_QP
Gain: $ 3.25 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ 3.25 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_TR_QP
Gain: $ 3.26 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ 3.26 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 3.3 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_QP_IR5
Gain: $ 3.31 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_HM_AV
Gain: $ 3.44 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_QP
Gain: $ 3.47 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 3.79 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_TR_QP
Gain: $ 4.01 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 4.44 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_SS
Gain: $ 4.49 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_QP_IR5
Gain: $ 4.49 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_RV
Gain: $ 4.49 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_LI
Gain: $ 4.64 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_LI
Gain: $ 4.66 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 4.75 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_HM
Gain: $ 4.75 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_HM_TR
Gain: $ 4.79 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_RV
Gain: $ 5.25 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_DB6
Gain: $ 5.25 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_HM
Gain: $ 5.63 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_TR_IR5
Gain: $ 6.51 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_TR_IR5
Gain: $ 7.07 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_RV_TR
Gain: $ 7.07 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_HM
Gain: $ 7.08 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_IR5
Gain: $ 7.1 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB3_CS3_AL
Gain: $ 7.15 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_QL
Gain: $ 7.21 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_RV_AL
Gain: $ 7.21 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 7.21 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_RV_AL
Gain: $ 7.53 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_TR
Gain: $ 7.53 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_TR
Gain: $ 7.53 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_TR
Gain: $ 7.63 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_DB15
Gain: $ 7.63 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 7.63 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_QL
Gain: $ 7.63 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB4_OS4_CB2_CS2_SS
Gain: $ 7.63 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_RV
Gain: $ 8.54 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $ 8.54 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_RV_TR
Gain: $ 8.54 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 8.54 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_RV_TR
Gain: $ 8.56 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_LI
Gain: $ 8.81 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_AL
Gain: $ 8.81 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB4_OS4_CB1_CS1_RV_AL
Gain: $ 9.79 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 9.79 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_HM
Gain: $ 10.12 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 11.01 Win %: 50.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_SS
Gain: $ 11.01 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_SS
Gain: $ 11.01 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_SS
Gain: $ 12.24 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_AL
Gain: $ 12.24 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_AL
Gain: $ 12.24 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 12.24 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_AL
Gain: $ 12.33 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_VI
Gain: $ 12.33 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_VI
Gain: $ 12.33 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_VI
Gain: $ 12.33 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_VI
Gain: $ 14.06 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_AL
Gain: $ 14.06 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB1_OS1_CB2_CS2_RV_AL
Gain: $ 14.17 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_RV
Gain: $ 14.52 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_RV
Gain: $ 14.52 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_RV
Gain: $ 14.52 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_RV
Gain: $ 15.02 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_QL
Gain: $ 15.21 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4
Gain: $ 19.98 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_HM
Gain: $ 20.06 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_DB6
Gain: $ 20.06 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_QL
Gain: $ 20.06 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ 20.06 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_DB6
Gain: $ 20.06 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB4_OS4_CB4_CS4_QL
Gain: $ 22.71 Win %: 100.00 in 2 days with algo TB5_HL_HI_QM_OB3_OS3_CB4_CS4_RV_AL
