Gain: $ -39.79 Win %: 42.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_QP
Gain: $ -35.63 Win %: 42.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_QP
Gain: $ -35.63 Win %: 42.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -35.63 Win %: 42.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_QP
Gain: $ -35.34 Win %: 42.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_QP
Gain: $ -34.66 Win %: 43.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_QP
Gain: $ -34.66 Win %: 43.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -34.42 Win %: 40.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_RV_QP
Gain: $ -34.19 Win %: 40.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_QP
Gain: $ -34.09 Win %: 44.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_QP
Gain: $ -33.87 Win %: 40.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -33.72 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV_QP
Gain: $ -33.72 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -33.72 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_QP
Gain: $ -32.45 Win %: 47.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_QP
Gain: $ -32.08 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_QP
Gain: $ -31.6 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_QP
Gain: $ -31.6 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -31.23 Win %: 47.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_QP
Gain: $ -30.68 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_QP
Gain: $ -30.68 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -30.45 Win %: 41.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV_QP
Gain: $ -30.37 Win %: 48.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_HM_QP
Gain: $ -30.37 Win %: 48.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -30.26 Win %: 47.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_QP
Gain: $ -30.26 Win %: 47.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_QP
Gain: $ -29.87 Win %: 46.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_QP
Gain: $ -29.87 Win %: 46.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -28.98 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QP
Gain: $ -28.3 Win %: 44.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_QP
Gain: $ -28.21 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP
Gain: $ -28.21 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ -28.21 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP
Gain: $ -28 Win %: 46.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP
Gain: $ -27.29 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP
Gain: $ -27.29 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP
Gain: $ -26.91 Win %: 47.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_QP
Gain: $ -26.91 Win %: 47.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ -26.47 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QP
Gain: $ -25.92 Win %: 50.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_QP
Gain: $ -25.31 Win %: 50.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -22.57 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ -22.57 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP
Gain: $ -20.78 Win %: 55.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_AV
Gain: $ -20.32 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_AV
Gain: $ -19.92 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_AV
Gain: $ -19.69 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_AV
Gain: $ -19.6 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP
Gain: $ -19.52 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -19.46 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_AV
Gain: $ -19.38 Win %: 47.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP
Gain: $ -18.99 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_AV
Gain: $ -18.72 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_QP
Gain: $ -17.77 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $ -17.77 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_QP
Gain: $ -17.28 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR_QP
Gain: $ -17.09 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ -17 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_SS
Gain: $ -16.83 Win %: 51.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ -16.68 Win %: 40.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QL
Gain: $ -16.62 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_HM_QP
Gain: $ -16.62 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_QP
Gain: $ -16.45 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_QP
Gain: $ -16.45 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_QP
Gain: $ -16.02 Win %: 55.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_AV
Gain: $ -16 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_AV
Gain: $ -15.79 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_HM_AV
Gain: $ -15.63 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_QP
Gain: $ -15.48 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_TR_QP
Gain: $ -15.48 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ -15.48 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_QP
Gain: $ -15.31 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_AV
Gain: $ -15.29 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_QP
Gain: $ -15.29 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ -14.76 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_QP
Gain: $ -14.47 Win %: 51.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR_QP
Gain: $ -14.25 Win %: 52.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AV
Gain: $ -14.19 Win %: 53.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_QP
Gain: $ -13.68 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ -13.34 Win %: 52.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AV
Gain: $ -13.3 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_QP
Gain: $ -13.3 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ -13.08 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AV
Gain: $ -13.08 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ -13.08 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AV
Gain: $ -12.91 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ -12.53 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AV
Gain: $ -12.53 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AV
Gain: $ -12.18 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_AV
Gain: $ -11.83 Win %: 55.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -11.65 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_SS
Gain: $ -11.62 Win %: 53.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_HM_QP
Gain: $ -11.62 Win %: 53.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -11.62 Win %: 53.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_HM_QP
Gain: $ -11.5 Win %: 45.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -11.46 Win %: 52.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_SS
Gain: $ -11.45 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_SS
Gain: $ -11.45 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_SS
Gain: $ -11.2 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_SS
Gain: $ -11.2 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ -11.2 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_SS
Gain: $ -10.85 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -10.72 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_AV
Gain: $ -10.72 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -10.34 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_SS
Gain: $ -10.34 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ -10.24 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_QP
Gain: $ -10.24 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ -10.24 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP
Gain: $ -10.24 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_QP
Gain: $ -10.18 Win %: 41.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QL
Gain: $ -10.01 Win %: 40.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_VI
Gain: $ -9.98 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AV
Gain: $ -9.84 Win %: 62.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_QP_IR5
Gain: $ -9.81 Win %: 46.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_HM_AV
Gain: $ -9.8 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AV
Gain: $ -9.8 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ -9.8 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ -9.8 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AV
Gain: $ -9.79 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_QP
Gain: $ -9.73 Win %: 41.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_QL
Gain: $ -9.73 Win %: 41.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ -9.73 Win %: 41.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QL
Gain: $ -9.64 Win %: 40.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_VI
Gain: $ -9.64 Win %: 40.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ -9.64 Win %: 40.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_VI
Gain: $ -9.63 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AV
Gain: $ -9.63 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ -9.63 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AV
Gain: $ -9.58 Win %: 42.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QL
Gain: $ -9.44 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_AV
Gain: $ -9.38 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP_IR5
Gain: $ -9.35 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP_IR5
Gain: $ -9.31 Win %: 41.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_VI
Gain: $ -9.3 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_VI
Gain: $ -9.29 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AV
Gain: $ -9.29 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AV
Gain: $ -9.27 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_QP
Gain: $ -9.26 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_SS
Gain: $ -9.26 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ -9.26 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_SS
Gain: $ -9.19 Win %: 55.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_SS
Gain: $ -9.13 Win %: 46.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_HM_AV
Gain: $ -9.05 Win %: 65.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_QP_IR5
Gain: $ -9.05 Win %: 65.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ -9.05 Win %: 65.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP_IR5
Gain: $ -8.96 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_QL
Gain: $ -8.9 Win %: 56.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP_IR5
Gain: $ -8.84 Win %: 41.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_VI
Gain: $ -8.84 Win %: 41.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ -8.84 Win %: 41.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QL
Gain: $ -8.79 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_AV
Gain: $ -8.66 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV_AV
Gain: $ -8.66 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ -8.66 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AV
Gain: $ -8.57 Win %: 41.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_VI
Gain: $ -8.57 Win %: 41.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ -8.57 Win %: 41.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_VI
Gain: $ -8.22 Win %: 41.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QL
Gain: $ -8.22 Win %: 42.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_VI
Gain: $ -8.07 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_VI
Gain: $ -8.07 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ -8.07 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_VI
Gain: $ -7.89 Win %: 42.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ -7.73 Win %: 46.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ -7.23 Win %: 60.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_AV
Gain: $ -7.01 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV
Gain: $ -6.87 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP_IR5
Gain: $ -6.87 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ -6.87 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP_IR5
Gain: $ -6.66 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_DB6
Gain: $ -6.64 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QL
Gain: $ -6.64 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ -6.64 Win %: 43.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QL
Gain: $ -6.61 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QP_IR5
Gain: $ -6.6 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_QP_IR5
Gain: $ -6.6 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP_IR5
Gain: $ -6.59 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ -6.58 Win %: 43.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QL
Gain: $ -6.32 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ -6.2 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV
Gain: $ -6.17 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AV
Gain: $ -6.17 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ -6.07 Win %: 43.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QL
Gain: $ -5.9 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_TR_QP
Gain: $ -5.86 Win %: 48.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_AV
Gain: $ -5.83 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_AV
Gain: $ -5.8 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4
Gain: $ -5.7 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV
Gain: $ -5.55 Win %: 65.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_QP_IR5
Gain: $ -5.44 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_DB6
Gain: $ -5.39 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV
Gain: $ -5.39 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ -5.39 Win %: 45.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV
Gain: $ -5.26 Win %: 59.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QP_IR5
Gain: $ -5.24 Win %: 46.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV
Gain: $ -5.17 Win %: 56.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ -5.17 Win %: 56.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_QP
Gain: $ -5.09 Win %: 50.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_DB6
Gain: $ -5.07 Win %: 52.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_VI
Gain: $ -5.02 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_HM
Gain: $ -4.99 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_DB6
Gain: $ -4.9 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_LI
Gain: $ -4.79 Win %: 48.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV
Gain: $ -4.79 Win %: 48.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ -4.79 Win %: 48.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV
Gain: $ -4.78 Win %: 56.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_TR_QP
Gain: $ -4.58 Win %: 47.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV
Gain: $ -4.58 Win %: 47.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ -4.48 Win %: 62.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_HM_AV
Gain: $ -4.48 Win %: 62.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_AV
Gain: $ -4.42 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ -4.22 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_DB6
Gain: $ -4.1 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2
Gain: $ -4.1 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ -4.1 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_RV
Gain: $ -3.99 Win %: 97.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR_DB
Gain: $ -3.9 Win %: 50.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_DB6
Gain: $ -3.84 Win %: 64.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ -3.72 Win %: 98.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR_DB
Gain: $ -3.48 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4
Gain: $ -3.48 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_DB6
Gain: $ -3.42 Win %: 43.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ -3.36 Win %: 47.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV
Gain: $ -3.34 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_LI
Gain: $ -3.34 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ -3.34 Win %: 46.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_LI
Gain: $ -3.33 Win %: 47.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ -3.33 Win %: 47.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_LI
Gain: $ -3.32 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_TR_QP
Gain: $ -3.26 Win %: 58.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP_IR5
Gain: $ -3.15 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4
Gain: $ -3.15 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_DB6
Gain: $ -3.15 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ -3.15 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_DB6
Gain: $ -3.1 Win %: 50.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_DB6
Gain: $ -3.03 Win %: 48.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_LI
Gain: $ -2.98 Win %: 61.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_SS
Gain: $ -2.88 Win %: 50.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ -2.59 Win %: 48.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV
Gain: $ -2.57 Win %: 47.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_LI
Gain: $ -2.47 Win %: 48.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ -2.47 Win %: 48.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV
Gain: $ -2.4 Win %: 67.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AV
Gain: $ -2.22 Win %: 48.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AV
Gain: $ -2 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_DB6
Gain: $ -1.84 Win %: 51.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_DB6
Gain: $ -1.31 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_LI
Gain: $ -1.31 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ -1.31 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_LI
Gain: $ -1.27 Win %: 47.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ -1.27 Win %: 47.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_LI
Gain: $ -0.94 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_LI
Gain: $ -0.71 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_LI
Gain: $ -0.56 Win %: 63.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $ -0.24 Win %: 49.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_RV_AV
Gain: $ -0.21 Win %: 96.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR_DB
Gain: $ -0.05 Win %: 98.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_AL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_DB6
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_LI
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QP_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_AL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_SS
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_VI
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_DB6
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_LI
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_SS
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_VI
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_DB6
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_LI
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AV
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_SS
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_IR5
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_QP
Gain: $ 0 Win %: 100.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_VI
Gain: $ 0 Win %: 100.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR_DB
Gain: $-0.12 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_AV
Gain: $-0.8 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_AV
Gain: $-10.07 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA_QP
Gain: $-10.07 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA_QP
Gain: $-10.07 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA_QP
Gain: $-104.48 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_PA_QP
Gain: $-11.23 Win %: 58.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_QP
Gain: $-11.23 Win %: 58.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_QP
Gain: $-11.28 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_TR
Gain: $-11.66 Win %: 58.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_QP
Gain: $-11.66 Win %: 58.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_QP
Gain: $-11.89 Win %: 56.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_QP
Gain: $-114.79 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_QP
Gain: $-121.06 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $-13.23 Win %: 50.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_PA_QP
Gain: $-15.19 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_PA_QP
Gain: $-16.02 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_PA_QP
Gain: $-16.99 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_RV_QP
Gain: $-16.99 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_RV_QP
Gain: $-17.82 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_RV_QP
Gain: $-19.62 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_PA_QP
Gain: $-21.7 Win %: 45.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_RV_QP
Gain: $-23.52 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_SS
Gain: $-26.5 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_PA
Gain: $-27.55 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_SS
Gain: $-3.47 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_PA_AV
Gain: $-3.72 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_PA_TR
Gain: $-33.25 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_DB10
Gain: $-36.14 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_RV
Gain: $-37.17 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5
Gain: $-4.81 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_TR
Gain: $-44.28 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_DB10
Gain: $-50.38 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4
Gain: $-50.38 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4
Gain: $-50.68 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_PA
Gain: $-51.98 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_RV
Gain: $-6.07 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $-6.83 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_PA_TR
Gain: $-7.75 Win %: 43.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_PA_AV
Gain: $-7.75 Win %: 43.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_PA_AV
Gain: $-7.75 Win %: 43.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_PA_AV
Gain: $-8.13 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $-84.34 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_QP
Gain: $-92.11 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_PA_QP
Gain: $-92.43 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $0 Win %: 100.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_SS
Gain: $0.28 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA_AV
Gain: $0.28 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA_AV
Gain: $0.28 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA_AV
Gain: $0.94 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $0.94 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $0.94 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $1.04 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_QP
Gain: $1.04 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_QP
Gain: $1.04 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_QP
Gain: $1.09 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $1.21 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_PA_AV
Gain: $1.7 Win %: 56.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_PA
Gain: $1.7 Win %: 56.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_PA
Gain: $1.87 in 38 days with algo TB1_HL_QM_OB2_OS2_CB5_CS5_PA_AV
Gain: $10.23 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_DB10
Gain: $10.82 Win %: 60.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_RV
Gain: $10.82 Win %: 60.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_RV
Gain: $11.57 Win %: 52.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_AV
Gain: $11.57 Win %: 52.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_AV
Gain: $11.57 Win %: 52.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_AV
Gain: $11.57 Win %: 52.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_AV
Gain: $11.62 Win %: 60.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_RV
Gain: $11.62 Win %: 60.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_RV
Gain: $11.7 Win %: 52.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_AV
Gain: $14.01 Win %: 52.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_RV_TR
Gain: $14.45 Win %: 63.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_RV
Gain: $14.55 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_SS
Gain: $15.2 Win %: 54.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_RV_TR
Gain: $15.2 Win %: 54.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_RV_TR
Gain: $15.78 Win %: 54.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_RV_TR
Gain: $15.78 Win %: 54.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_RV_TR
Gain: $17.39 Win %: 63.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3
Gain: $17.47 Win %: 67.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_DB10
Gain: $17.49 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_SS
Gain: $17.49 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_SS
Gain: $17.82 Win %: 65.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3
Gain: $17.82 Win %: 65.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3
Gain: $17.9 Win %: 67.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_DB10
Gain: $17.9 Win %: 67.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_DB10
Gain: $18.25 Win %: 65.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1
Gain: $18.25 Win %: 65.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2
Gain: $18.31 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_DB10
Gain: $18.31 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_DB10
Gain: $2.5 Win %: 56.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_PA
Gain: $2.5 Win %: 56.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_PA
Gain: $2.71 Win %: 50.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_PA_TR
Gain: $2.82 Win %: 58.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_PA
Gain: $20.05 Win %: 67.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_DB10
Gain: $20.12 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA
Gain: $20.12 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA
Gain: $20.12 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA
Gain: $21.23 Win %: 52.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_TR
Gain: $22.56 Win %: 54.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_TR
Gain: $22.56 Win %: 54.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_TR
Gain: $22.78 Win %: 54.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_TR
Gain: $22.78 Win %: 54.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_TR
Gain: $23.31 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_AV
Gain: $23.31 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_AV
Gain: $23.31 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_AV
Gain: $25 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV
Gain: $25 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV
Gain: $25 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV
Gain: $27.72 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4
Gain: $27.72 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4
Gain: $27.72 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4
Gain: $3.46 Win %: 78.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_DB10
Gain: $30.46 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA_TR
Gain: $30.46 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA_TR
Gain: $30.46 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_PA_TR
Gain: $37.2 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $37.2 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $37.2 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $4.28 Win %: 50.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_PA_TR
Gain: $4.29 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_RV_AV
Gain: $4.29 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_RV_AV
Gain: $4.29 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_RV_AV
Gain: $41.45 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_TR
Gain: $41.45 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_TR
Gain: $41.45 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_TR
Gain: $5 Win %: 58.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_SS
Gain: $5 Win %: 58.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_SS
Gain: $5.12 Win %: 50.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB1_CS1_PA_TR
Gain: $5.12 Win %: 50.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB2_CS2_PA_TR
Gain: $5.18 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $5.18 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $5.18 in 38 days with algo TB3_HI_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $5.24 Win %: 58.00 in 46 days with algo TB4_HL_HI_QM_OB3_OS3_CB3_CS3_SS
Gain: $5.91 in 38 days with algo TB1_HL_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $7.76 Win %: 58.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_SS
Gain: $9.25 Win %: 47.00 in 46 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_RV_AV
SNAP Gain: $ -1.3 Win %: 50.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4
SNAP Gain: $ -1.71 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_QP
SNAP Gain: $ -11.12 Win %: 53.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_SS
SNAP Gain: $ -11.22 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_AV
SNAP Gain: $ -11.22 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AV
SNAP Gain: $ -11.22 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AV
SNAP Gain: $ -11.22 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AV
SNAP Gain: $ -11.25 Win %: 53.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_SS
SNAP Gain: $ -11.25 Win %: 53.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_SS
SNAP Gain: $ -11.25 Win %: 53.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_SS
SNAP Gain: $ -12.52 Win %: 43.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QL
SNAP Gain: $ -14.65 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_AV
SNAP Gain: $ -14.65 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AV
SNAP Gain: $ -14.65 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AV
SNAP Gain: $ -14.65 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AV
SNAP Gain: $ -17.13 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR_QP
SNAP Gain: $ -17.13 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_QP
SNAP Gain: $ -17.13 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_QP
SNAP Gain: $ -17.13 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_QP
SNAP Gain: $ -2.38 Win %: 47.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_LI
SNAP Gain: $ -2.38 Win %: 47.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_LI
SNAP Gain: $ -2.38 Win %: 47.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_LI
SNAP Gain: $ -20.06 Win %: 48.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP_IR1
SNAP Gain: $ -21.11 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_AV
SNAP Gain: $ -21.11 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_AV
SNAP Gain: $ -21.11 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_AV
SNAP Gain: $ -21.11 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_AV
SNAP Gain: $ -22.65 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QP_IR1
SNAP Gain: $ -22.65 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP_IR1
SNAP Gain: $ -22.65 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP_IR1
SNAP Gain: $ -25.87 Win %: 40.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_IR1
SNAP Gain: $ -25.87 Win %: 40.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_IR1
SNAP Gain: $ -25.87 Win %: 40.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_IR1
SNAP Gain: $ -25.87 Win %: 40.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_IR1
SNAP Gain: $ -28.37 Win %: 45.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QP
SNAP Gain: $ -28.37 Win %: 45.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP
SNAP Gain: $ -28.37 Win %: 45.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QP
SNAP Gain: $ -28.37 Win %: 45.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QP
SNAP Gain: $ -31.76 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_QP
SNAP Gain: $ -31.76 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_QP
SNAP Gain: $ -31.76 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_QP
SNAP Gain: $ -35.42 Win %: 43.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_QP
SNAP Gain: $ -35.42 Win %: 43.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_QP
SNAP Gain: $ -35.42 Win %: 43.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_QP
SNAP Gain: $ -35.42 Win %: 43.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_QP
SNAP Gain: $ -4.06 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_DB6
SNAP Gain: $ -4.06 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_DB6
SNAP Gain: $ -4.06 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_DB6
SNAP Gain: $ -5.48 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV
SNAP Gain: $ -5.48 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV
SNAP Gain: $ -5.48 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV
SNAP Gain: $ -5.48 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV
SNAP Gain: $ -6.79 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_DB6
SNAP Gain: $ -9.22 Win %: 40.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_VI
SNAP Gain: $ -9.22 Win %: 40.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_VI
SNAP Gain: $ -9.22 Win %: 40.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_VI
SNAP Gain: $ -9.22 Win %: 40.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_VI
SNAP Gain: $ -9.28 Win %: 41.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_QL
SNAP Gain: $ -9.28 Win %: 41.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QL
SNAP Gain: $ -9.28 Win %: 41.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QL
SNAP Gain: $ 10.41 Win %: 50.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR
SNAP Gain: $ 14.62 Win %: 50.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_TR
SNAP Gain: $ 14.62 Win %: 50.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_TR
SNAP Gain: $ 14.62 Win %: 50.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_TR
SNAP Gain: $ 14.62 Win %: 50.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_TR
SNAP Gain: $ 16.72 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_TR
SNAP Gain: $ 16.72 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_TR_DB1
SNAP Gain: $ 16.72 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR
SNAP Gain: $ 16.72 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR_DB1
SNAP Gain: $ 16.72 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB1
SNAP Gain: $ 16.72 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR
SNAP Gain: $ 16.72 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR_DB1
SNAP Gain: $ 16.98 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR
SNAP Gain: $ 17.1 Win %: 52.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR
SNAP Gain: $ 18.15 Win %: 53.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR
SNAP Gain: $ 19.05 Win %: 58.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_AL
SNAP Gain: $ 19.05 Win %: 58.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AL
SNAP Gain: $ 19.05 Win %: 58.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AL
SNAP Gain: $ 19.05 Win %: 58.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AL
SNAP Gain: $ 19.71 Win %: 54.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR
SNAP Gain: $ 2.97 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM
SNAP Gain: $ 2.97 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM
SNAP Gain: $ 2.97 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM
SNAP Gain: $ 2.97 Win %: 49.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM
SNAP Gain: $ 4.07 Win %: 53.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_LI
SNAP Gain: $ 4.75 Win %: 45.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR_IR1
SNAP Gain: $ 4.75 Win %: 45.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_IR1
SNAP Gain: $ 5.25 Win %: 45.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_IR1
SNAP Gain: $ 5.85 Win %: 46.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_IR1
SNAP Gain: $ 9 Win %: 56.00 in 93 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_AL
SNAP Gain: $ 9 Win %: 56.00 in 93 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AL
SNAP Gain: $ 9 Win %: 56.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AL
SNAP Gain: $ 9 Win %: 56.00 in 93 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 0.02 Win %: 92.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR_DB
Gain: $ 0.14 Win %: 50.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV_AV
Gain: $ 0.47 Win %: 55.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_QP_IR5
Gain: $ 0.68 Win %: 64.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_RV_AL
Gain: $ 0.68 Win %: 64.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 0.92 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV
Gain: $ 0.96 Win %: 49.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ 0.96 Win %: 49.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_AV
Gain: $ 1.26 Win %: 60.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_TR_IR5
Gain: $ 1.39 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM
Gain: $ 1.51 Win %: 50.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AV
Gain: $ 1.53 Win %: 49.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_RV
Gain: $ 1.55 Win %: 48.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 1.69 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_IR5
Gain: $ 1.96 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_HM
Gain: $ 2.31 Win %: 50.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_AV
Gain: $ 2.7 Win %: 49.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV_AL
Gain: $ 2.7 Win %: 49.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 2.7 Win %: 49.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 2.7 Win %: 49.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_RV_AL
Gain: $ 2.93 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM
Gain: $ 2.93 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 2.93 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM
Gain: $ 3.2 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ 3.26 Win %: 63.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 3.55 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM
Gain: $ 3.6 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_TR
Gain: $ 3.88 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM
Gain: $ 3.88 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 3.88 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM
Gain: $ 3.96 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM
Gain: $ 3.96 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 3.96 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM
Gain: $ 4.36 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_AL
Gain: $ 4.81 Win %: 50.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_VI
Gain: $ 4.81 Win %: 50.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_VI
Gain: $ 4.81 Win %: 50.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_VI
Gain: $ 4.84 Win %: 48.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_IR5
Gain: $ 4.89 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_HM_TR
Gain: $ 4.89 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_TR
Gain: $ 5.17 Win %: 52.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ 5.31 Win %: 52.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ 5.36 Win %: 64.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_AL
Gain: $ 5.54 Win %: 48.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_IR5
Gain: $ 5.57 Win %: 49.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 5.65 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_IR5
Gain: $ 5.67 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_IR5
Gain: $ 5.67 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 5.81 Win %: 61.00 in 91 days with algo TB5_HS_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $ 6.11 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 6.11 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_IR5
Gain: $ 6.28 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_IR5
Gain: $ 6.73 Win %: 47.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_IR5
Gain: $ 6.75 Win %: 50.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_IR5
Gain: $ 7.13 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_IR5
Gain: $ 7.13 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 8.07 Win %: 50.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_IR5
Gain: $ 8.09 Win %: 64.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 8.09 Win %: 64.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_IR5
Gain: $ 8.09 Win %: 64.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_IR5
Gain: $ 8.15 Win %: 64.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_IR5
Gain: $ 8.64 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AL
Gain: $ 8.94 Win %: 56.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 9.52 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_TR_IR5
Gain: $ 10.27 Win %: 52.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_IR5
Gain: $ 10.35 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV_AL
Gain: $ 10.35 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 10.35 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 10.45 Win %: 56.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM
Gain: $ 10.47 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AL
Gain: $ 10.47 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 10.47 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 10.84 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_SS
Gain: $ 10.84 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ 10.84 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_SS
Gain: $ 10.84 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_SS
Gain: $ 11.19 Win %: 52.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_TR
Gain: $ 11.26 Win %: 55.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_IR5
Gain: $ 11.36 Win %: 57.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AL
Gain: $ 11.37 Win %: 58.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_AL
Gain: $ 11.46 Win %: 53.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_AL
Gain: $ 12.14 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR_IR5
Gain: $ 12.37 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_TR
Gain: $ 12.89 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_TR
Gain: $ 13.2 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR_IR5
Gain: $ 13.22 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_IR5
Gain: $ 13.22 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 13.22 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_IR5
Gain: $ 13.27 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_IR5
Gain: $ 13.27 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 13.57 Win %: 48.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_LI
Gain: $ 13.7 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 13.7 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_IR5
Gain: $ 13.72 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_IR5
Gain: $ 13.74 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR_IR5
Gain: $ 13.74 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 14.25 Win %: 53.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_AL
Gain: $ 14.25 Win %: 53.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 14.25 Win %: 53.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AL
Gain: $ 14.75 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_IR5
Gain: $ 14.78 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_HM_TR
Gain: $ 14.78 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_TR
Gain: $ 15.08 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_AL
Gain: $ 15.08 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 15.21 Win %: 51.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ 15.21 Win %: 51.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_TR
Gain: $ 15.22 Win %: 52.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ 15.69 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_AL
Gain: $ 16.37 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR
Gain: $ 16.44 Win %: 51.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_TR
Gain: $ 16.44 Win %: 51.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ 16.72 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_TR
Gain: $ 16.72 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ 17.06 Win %: 56.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_QL
Gain: $ 17.09 Win %: 52.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_HM_TR
Gain: $ 17.3 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR
Gain: $ 17.3 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 17.3 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ 17.33 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_AL
Gain: $ 17.34 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_TR
Gain: $ 17.39 Win %: 51.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_HM_TR
Gain: $ 17.46 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR
Gain: $ 17.51 Win %: 56.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_QL
Gain: $ 17.51 Win %: 56.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ 17.51 Win %: 56.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_QL
Gain: $ 17.53 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 17.69 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR
Gain: $ 17.69 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 17.69 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR
Gain: $ 17.77 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR
Gain: $ 17.77 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 17.77 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR
Gain: $ 17.83 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AL
Gain: $ 17.89 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AL
Gain: $ 17.9 Win %: 59.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AL
Gain: $ 18.01 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 18.26 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AL
Gain: $ 18.26 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 18.26 Win %: 57.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AL
Gain: $ 18.31 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR
Gain: $ 18.31 Win %: 53.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR
Gain: $ 18.43 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR
Gain: $ 18.45 Win %: 60.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 18.69 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 18.69 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ 18.8 Win %: 58.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AL
Gain: $ 18.85 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_RV_TR
Gain: $ 18.85 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 18.85 Win %: 56.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ 18.92 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_TR
Gain: $ 18.92 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 18.92 Win %: 53.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR
Gain: $ 19.25 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV_TR
Gain: $ 19.25 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 19.25 Win %: 54.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ 19.88 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_RV_TR
Gain: $ 20.22 Win %: 60.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_TR
Gain: $ 20.36 Win %: 54.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_TR
Gain: $ 20.37 Win %: 58.00 in 92 days with algo TB5_HS_QM_OB3_OS3_CB4_CS4_AL
Gain: $ 20.37 Win %: 58.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 20.37 Win %: 58.00 in 92 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_AL
Gain: $ 22.64 Win %: 68.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_TR_IR5
Gain: $ 22.64 Win %: 68.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 22.64 Win %: 68.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR_IR5
Gain: $ 23.44 Win %: 68.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_TR_IR5
Gain: $ 24.33 Win %: 63.00 in 92 days with algo TB5_HS_QM_OB1_OS1_CB4_CS4_AL
Gain: $ 24.59 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_HM_TR
Gain: $ 24.59 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ 24.59 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM_TR
Gain: $ 24.59 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_HM_TR
Gain: $ 26.65 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_LI
Gain: $ 27.58 Win %: 61.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_HM
Gain: $ 27.64 Win %: 61.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_HM
Gain: $ 27.64 Win %: 61.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ 27.64 Win %: 61.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM
Gain: $ 29.23 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ 29.65 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 29.65 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_LI
Gain: $ 29.65 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_LI
Gain: $ 29.93 Win %: 65.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_DB6
Gain: $ 29.93 Win %: 65.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ 29.93 Win %: 65.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_DB6
Gain: $ 29.93 Win %: 65.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4
Gain: $ 29.93 Win %: 65.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_DB6
Gain: $ 29.96 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_RV_TR
Gain: $ 29.96 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 29.96 Win %: 57.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_RV_TR
Gain: $ 36.16 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB1_CS1_TR
Gain: $ 36.16 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_TR
Gain: $ 36.16 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB4_CS4_TR
Gain: $ 36.45 Win %: 60.00 in 75 days with algo TB5_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ 61.53 Win %: 50.00 in 91 days with algo TB5_HS_QM_OB4_OS4_CB3_CS3_HM
