SPCE Gain: $ -376.97 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ -7.05 Win %: 30.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_IR3
SPCE Gain: $ -6.18 Win %: 20.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_IR3
SPCE Gain: $ -5.96 Win %: 50.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP_IR1
SPCE Gain: $ -5.49 Win %: 50.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ -5.49 Win %: 50.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ -5.42 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_QP_IR1
SPCE Gain: $ -4.8 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP_IR1
SPCE Gain: $ -4.8 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_QP_IR1
SPCE Gain: $ -4.78 Win %: 33.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_QP_IR1
SPCE Gain: $ -4.78 Win %: 33.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_QP_IR1
SPCE Gain: $ -4.64 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP_IR1
SPCE Gain: $ -4.57 Win %: 30.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
SPCE Gain: $ -4.55 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP_IR1
SPCE Gain: $ -4.55 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP_IR1
SPCE Gain: $ -4.49 Win %: 50.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ -4.47 Win %: 33.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_IR3
SPCE Gain: $ -3.87 Win %: 41.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
SPCE Gain: $ -3.85 Win %: 33.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_IR3
SPCE Gain: $ -3.8 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ -3.71 Win %: 53.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ -3.59 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ -3.48 Win %: 46.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
SPCE Gain: $ -3.43 Win %: 83.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IT_QP
SPCE Gain: $ -3.4 Win %: 83.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IT_QP
SPCE Gain: $ -3.4 Win %: 83.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IT_QP_DB1
SPCE Gain: $ -3.34 Win %: 41.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
SPCE Gain: $ -3.16 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
SPCE Gain: $ -3.07 Win %: 46.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ -2.36 Win %: 46.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ -2.32 Win %: 46.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
SPCE Gain: $ -2.26 Win %: 50.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ -2.12 Win %: 50.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ -1.94 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ -1.94 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV_DB4
SPCE Gain: $ -1.75 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_AV
SPCE Gain: $ -1.75 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_AV
SPCE Gain: $ -1.75 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_AV_DB4
SPCE Gain: $ -1.48 Win %: 70.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_QP
SPCE Gain: $ -1.39 Win %: 83.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QP
SPCE Gain: $ -1.39 Win %: 83.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QP_DB1
SPCE Gain: $ -1.33 Win %: 46.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ -0.94 Win %: 53.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ -0.81 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ -0.75 Win %: 60.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_HM_QP
SPCE Gain: $ -0.72 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ -0.61 Win %: 91.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QP
SPCE Gain: $ -0.31 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
SPCE Gain: $ -0.17 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
SPCE Gain: $ -0.14 Win %: 50.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ -0.08 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ -0.08 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -0.14 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_TR_IR5
Gain: $ -0.17 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_HM_AV
Gain: $ -0.21 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -0.3 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_TR_QP
Gain: $ -0.34 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_RV_TR
Gain: $ -0.61 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_RV_QP
Gain: $ -0.64 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_QP
Gain: $ -0.64 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_HM_QP
Gain: $ -0.64 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_HM_QP
Gain: $ -0.65 Win %: 80.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_SS
Gain: $ -0.77 Win %: 0 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_AV
Gain: $ -0.77 Win %: 0 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_AV
Gain: $ -0.77 Win %: 0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_AV
Gain: $ -0.77 Win %: 0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_AV
Gain: $ -0.84 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_HM_QP
Gain: $ -0.85 Win %: 25.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_RV_QP
Gain: $ -0.87 Win %: 20.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ -1.14 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_QP
Gain: $ -1.23 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_QP
Gain: $ -1.38 Win %: 20.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ -1.39 Win %: 60.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_TR_QP
Gain: $ -1.4 Win %: 0 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_RV_AV
Gain: $ -1.4 Win %: 0 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_RV_AV
Gain: $ -1.4 Win %: 0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_RV_AV
Gain: $ -1.4 Win %: 0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_RV_AV
Gain: $ -1.42 Win %: 62.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_QP_IR2
Gain: $ -1.43 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_HM_QP
Gain: $ -1.56 Win %: 40.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_QP_IR5
Gain: $ -1.64 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_TR_QP
Gain: $ -1.65 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_RV_QP
Gain: $ -1.89 Win %: 60.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ -10.02 Win %: 25.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_IR2
Gain: $ -10.38 Win %: 25.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_HM
Gain: $ -10.98 Win %: 60.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_TR
Gain: $ -11.09 Win %: 0 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -11.62 Win %: 50.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_TR_IR5
Gain: $ -2 Win %: 83.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_RV_TR_DB
Gain: $ -2.08 Win %: 25.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_QL
Gain: $ -2.2 Win %: 33.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_QP_IR5
Gain: $ -2.51 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_QP
Gain: $ -2.78 Win %: 62.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_HM_QP
Gain: $ -2.78 Win %: 62.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_HM_QP
Gain: $ -2.9 Win %: 60.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_IR5
Gain: $ -3.31 Win %: 20.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_QP_IR5
Gain: $ -3.31 Win %: 33.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_IR5
Gain: $ -3.34 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -3.39 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_HM_QP
Gain: $ -3.6 Win %: 60.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_HM_QP
Gain: $ -3.63 Win %: 40.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_QP
Gain: $ -3.88 Win %: 25.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_TR_QP
Gain: $ -4.76 Win %: 50.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_HM_QP
Gain: $ -4.98 Win %: 40.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_QP
Gain: $ -5.22 Win %: 25.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_HM_QP
Gain: $ -5.24 Win %: 50.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_QP_IR1
Gain: $ -5.24 Win %: 50.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_QP_IR1
Gain: $ -6.55 Win %: 33.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_QP_IR5
Gain: $ -6.71 Win %: 50.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_DB10
Gain: $ -7.57 Win %: 50.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ -7.58 Win %: 37.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_QP_IR2
Gain: $ -8.32 Win %: 20.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_TR_IR5
Gain: $ -8.37 Win %: 25.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_VI
Gain: $ -8.48 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_AL
Gain: $ -8.8 Win %: 50.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_HM_QP
Gain: $ 0 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_TR_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_TR_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_TR_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_TR_IR5
Gain: $ 0 Win %: 100.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_TR_DB
Gain: $ 0.06 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ 0.06 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ 0.08 Win %: 40.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_VI
Gain: $ 0.16 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_QP_IR5
Gain: $ 0.16 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_QP_IR5
Gain: $ 0.16 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_QP_IR5
Gain: $ 0.16 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_QP_IR5
Gain: $ 0.19 Win %: 40.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 0.2 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ 0.23 Win %: 50.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_RV_AL
Gain: $ 0.24 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_QP
Gain: $ 0.29 Win %: 60.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_QL
Gain: $ 0.38 Win %: 33.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 0.38 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_RV_QP
Gain: $ 0.39 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_TR_QP
Gain: $ 0.45 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_TR_QP
Gain: $ 0.45 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_TR_QP
Gain: $ 0.45 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_TR_QP
Gain: $ 0.45 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_TR_QP
Gain: $ 0.46 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_VI
Gain: $ 0.46 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_VI
Gain: $ 0.46 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_VI
Gain: $ 0.46 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_VI
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_HM_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_HM_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_RV_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_HM_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_RV_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_HM_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_RV_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_HM_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_QP
Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_RV_QP
Gain: $ 0.51 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_TR_QP
Gain: $ 0.53 Win %: 50.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_QL
Gain: $ 0.54 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_QL
Gain: $ 0.73 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_HM_AV
Gain: $ 0.73 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_HM_TR
Gain: $ 0.73 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_HM_AV
Gain: $ 0.73 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_HM_TR
Gain: $ 0.73 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_HM_AV
Gain: $ 0.73 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_HM_TR
Gain: $ 0.73 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_HM_AV
Gain: $ 0.73 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_HM_TR
Gain: $ 0.78 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_RV_TR
Gain: $ 0.78 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_TR
Gain: $ 0.78 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_RV_TR
Gain: $ 0.78 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_TR
Gain: $ 0.78 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_RV_TR
Gain: $ 0.78 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_TR
Gain: $ 0.78 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_RV_TR
Gain: $ 0.78 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_TR
Gain: $ 0.78 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_AV
Gain: $ 0.79 Win %: 50.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP
Gain: $ 0.93 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_TR_QP
Gain: $ 0.93 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_TR_QP
Gain: $ 1.1 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_LI
Gain: $ 1.1 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_LI
Gain: $ 1.1 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_LI
Gain: $ 1.1 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_LI
Gain: $ 1.11 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_SS
Gain: $ 1.11 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_SS
Gain: $ 1.11 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_SS
Gain: $ 1.11 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_SS
Gain: $ 1.23 Win %: 60.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 1.26 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_AL
Gain: $ 1.26 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_AL
Gain: $ 1.26 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_AL
Gain: $ 1.26 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_AL
Gain: $ 1.26 Win %: 66.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_QP_IR5
Gain: $ 1.27 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV
Gain: $ 1.28 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_HM
Gain: $ 1.28 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_HM
Gain: $ 1.28 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_HM
Gain: $ 1.28 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_HM
Gain: $ 1.3 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_TR_QP
Gain: $ 1.34 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_QP
Gain: $ 1.34 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_QP
Gain: $ 1.41 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_QP
Gain: $ 1.42 Win %: 60.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 1.46 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_TR_QP
Gain: $ 1.48 Win %: 20.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV
Gain: $ 1.48 Win %: 25.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_RV_AV
Gain: $ 1.54 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_QP_IR5
Gain: $ 1.57 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_DB30
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_QL
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB1_CS1_RV
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_DB30
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_QL
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB1_OS1_CB2_CS2_RV
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_DB30
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_QL
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB1_CS1_RV
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_DB30
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_QL
Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB2_CS2_RV
Gain: $ 1.73 Win %: 80.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV
Gain: $ 1.78 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_HM_TR
Gain: $ 1.79 Win %: 33.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 1.9 Win %: 25.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_IR5
Gain: $ 1.92 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_RV_AL
Gain: $ 1.93 Win %: 25.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_IR5
Gain: $ 1.94 Win %: 50.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ 1.94 Win %: 60.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_DB30
Gain: $ 1.96 Win %: 60.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_AV
Gain: $ 1.97 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_TR
Gain: $ 10 Win %: 62.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_HM_AV
Gain: $ 10.02 Win %: 100.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 10.16 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_SS
Gain: $ 10.16 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_SS
Gain: $ 10.18 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_HM
Gain: $ 10.29 Win %: 50.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_AV
Gain: $ 10.29 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 10.3 Win %: 66.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_AV
Gain: $ 10.34 Win %: 83.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 10.41 Win %: 37.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_RV_AV
Gain: $ 10.41 Win %: 37.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV
Gain: $ 10.52 Win %: 66.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_QL
Gain: $ 10.6 Win %: 100.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 10.64 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_DB8
Gain: $ 10.65 Win %: 62.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_QL
Gain: $ 10.65 Win %: 62.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_QL
Gain: $ 10.66 Win %: 100.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_LI
Gain: $ 10.88 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_HM
Gain: $ 11.06 Win %: 100.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_TR
Gain: $ 11.1 Win %: 100.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_TR_IR5
Gain: $ 11.1 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_TR_IR5
Gain: $ 11.32 Win %: 100.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_HM_TR
Gain: $ 11.45 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_TR_IR5
Gain: $ 11.46 Win %: 75.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_SS
Gain: $ 11.5 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_IR1
Gain: $ 11.5 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_IR1
Gain: $ 11.54 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV
Gain: $ 11.72 Win %: 62.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_TR_IR2
Gain: $ 11.79 Win %: 100.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM
Gain: $ 11.86 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_DB6
Gain: $ 11.86 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_DB6
Gain: $ 11.89 Win %: 100.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_LI
Gain: $ 12.21 Win %: 62.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_RV_AL
Gain: $ 12.21 Win %: 62.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AL
Gain: $ 12.4 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_AL
Gain: $ 12.64 Win %: 75.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_QL
Gain: $ 12.64 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_TR_IR1
Gain: $ 12.64 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_TR_IR1
Gain: $ 12.72 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_TR
Gain: $ 12.72 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_TR
Gain: $ 12.92 Win %: 75.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_TR_DB2
Gain: $ 13.2 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_AL
Gain: $ 13.23 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_RV
Gain: $ 13.25 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_DB8
Gain: $ 13.28 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_RV
Gain: $ 13.28 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV
Gain: $ 13.49 Win %: 62.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_RV_TR
Gain: $ 13.49 Win %: 62.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_RV_TR_DB1
Gain: $ 13.49 Win %: 62.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_TR
Gain: $ 13.49 Win %: 62.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_TR_DB1
Gain: $ 13.53 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM
Gain: $ 13.82 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_RV_TR
Gain: $ 14.25 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_TR
Gain: $ 14.38 Win %: 75.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_TR
Gain: $ 14.63 Win %: 100.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM
Gain: $ 14.67 Win %: 100.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_LI
Gain: $ 15.34 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_RV_TR_DB2
Gain: $ 15.38 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_QL
Gain: $ 15.62 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4
Gain: $ 15.92 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_TR
Gain: $ 16.21 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_TR
Gain: $ 16.39 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV
Gain: $ 17.63 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_AV
Gain: $ 17.66 Win %: 75.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_AV
Gain: $ 17.72 Win %: 62.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_HM_TR
Gain: $ 17.74 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_DB8
Gain: $ 2.01 Win %: 100.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_QP_IR5
Gain: $ 2.12 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_QP
Gain: $ 2.14 Win %: 50.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_HM_AV
Gain: $ 2.14 Win %: 50.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_HM_AV
Gain: $ 2.16 Win %: 50.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ 2.23 Win %: 66.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 2.23 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 2.31 Win %: 50.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_LI
Gain: $ 2.37 Win %: 60.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 2.39 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_TR_IR5
Gain: $ 2.4 Win %: 83.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ 2.42 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ 2.48 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_RV_QP
Gain: $ 2.48 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_QP
Gain: $ 2.49 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_QP
Gain: $ 2.52 Win %: 50.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_HM_TR
Gain: $ 2.53 Win %: 50.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ 2.54 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_QP
Gain: $ 2.6 Win %: 60.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_LI
Gain: $ 2.68 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_RV_AV
Gain: $ 2.72 Win %: 50.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 2.73 Win %: 50.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_HM_AV
Gain: $ 2.84 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_DB30
Gain: $ 2.94 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_AV
Gain: $ 3 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_HM_AV
Gain: $ 3.03 Win %: 60.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_SS
Gain: $ 3.08 Win %: 80.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_HM
Gain: $ 3.14 Win %: 50.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_RV_AV
Gain: $ 3.15 Win %: 40.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_AV
Gain: $ 3.15 Win %: 80.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_AL
Gain: $ 3.17 Win %: 60.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_TR
Gain: $ 3.18 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_HM_QP
Gain: $ 3.2 Win %: 50.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 3.22 Win %: 40.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 3.22 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_IR5
Gain: $ 3.26 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_HM_TR
Gain: $ 3.38 Win %: 50.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_VI
Gain: $ 3.44 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_QP
Gain: $ 3.44 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_TR_QP
Gain: $ 3.46 Win %: 33.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_LI
Gain: $ 3.48 Win %: 100.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_QP
Gain: $ 3.49 Win %: 100.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_TR_DB
Gain: $ 3.55 Win %: 100.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_QP
Gain: $ 3.57 Win %: 66.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 3.68 Win %: 25.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_QP_IR5
Gain: $ 3.71 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_AL
Gain: $ 3.83 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_RV_QP
Gain: $ 3.85 Win %: 50.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_RV_AV
Gain: $ 3.87 Win %: 66.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 4.02 Win %: 100.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_SS
Gain: $ 4.03 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_AL
Gain: $ 4.07 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4
Gain: $ 4.13 Win %: 100.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_HM
Gain: $ 4.18 Win %: 83.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_VI
Gain: $ 4.19 Win %: 100.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_AL
Gain: $ 4.21 Win %: 50.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_RV_AV
Gain: $ 4.24 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_AL
Gain: $ 4.24 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_RV_AL
Gain: $ 4.4 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_QP
Gain: $ 4.4 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_QP
Gain: $ 4.4 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_TR_QP
Gain: $ 4.44 Win %: 100.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_QP
Gain: $ 4.44 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_AV
Gain: $ 4.51 Win %: 100.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_QP
Gain: $ 4.53 Win %: 40.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 4.53 Win %: 60.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV
Gain: $ 4.57 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_TR
Gain: $ 4.59 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_TR
Gain: $ 4.62 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_QP
Gain: $ 4.63 Win %: 100.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_RV_TR_DB
Gain: $ 4.69 Win %: 60.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 4.7 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_IR5
Gain: $ 4.75 Win %: 66.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 4.91 Win %: 40.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_AV
Gain: $ 4.92 Win %: 60.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_TR
Gain: $ 5.07 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_SS
Gain: $ 5.08 Win %: 50.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_QP
Gain: $ 5.1 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_HM_AV
Gain: $ 5.11 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_VI
Gain: $ 5.16 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_HM_TR
Gain: $ 5.18 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_SS
Gain: $ 5.22 Win %: 25.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_QP_IR5
Gain: $ 5.22 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_TR_IR5
Gain: $ 5.33 Win %: 60.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 5.44 Win %: 60.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_TR
Gain: $ 5.45 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_LI
Gain: $ 5.47 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_HM_TR
Gain: $ 5.5 Win %: 50.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_RV_TR
Gain: $ 5.64 Win %: 62.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_LI
Gain: $ 5.64 Win %: 62.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_LI
Gain: $ 5.76 Win %: 60.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_AV
Gain: $ 5.87 Win %: 66.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_SS
Gain: $ 5.93 Win %: 87.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_VI
Gain: $ 5.93 Win %: 87.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_VI
Gain: $ 6.01 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_AV
Gain: $ 6.01 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_TR_QP
Gain: $ 6.03 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_SS
Gain: $ 6.04 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_HM
Gain: $ 6.06 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_AL
Gain: $ 6.07 Win %: 100.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_AL
Gain: $ 6.13 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_HM_AV
Gain: $ 6.13 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_AL
Gain: $ 6.14 Win %: 60.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1
Gain: $ 6.2 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_AV
Gain: $ 6.23 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_QP
Gain: $ 6.27 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_DB10
Gain: $ 6.28 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_HM
Gain: $ 6.29 Win %: 60.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AL
Gain: $ 6.34 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_DB8
Gain: $ 6.36 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_VI
Gain: $ 6.37 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_TR
Gain: $ 6.47 Win %: 50.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 6.57 Win %: 50.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_VI
Gain: $ 6.58 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_VI
Gain: $ 6.62 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_QP
Gain: $ 6.66 Win %: 60.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_DB10
Gain: $ 6.66 Win %: 60.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_QL
Gain: $ 6.66 Win %: 60.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_SS
Gain: $ 6.66 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_HM
Gain: $ 6.67 Win %: 100.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_RV_TR_DB
Gain: $ 6.67 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_SS
Gain: $ 6.69 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_AV
Gain: $ 6.7 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_VI
Gain: $ 6.74 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_AL
Gain: $ 6.76 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_AV
Gain: $ 6.76 Win %: 83.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_DB6
Gain: $ 6.77 Win %: 80.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_HM_AV
Gain: $ 6.83 Win %: 75.00 in 4 days with algo TB3_OC_QM_OB5_OS5_CB4_CS4_RV
Gain: $ 6.85 Win %: 25.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_QP_IR5
Gain: $ 6.89 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_AL
Gain: $ 6.94 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_RV_TR
Gain: $ 7.03 Win %: 62.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_SS
Gain: $ 7.04 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_RV
Gain: $ 7.07 Win %: 60.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 7.1 Win %: 80.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_AV
Gain: $ 7.11 Win %: 83.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 7.16 Win %: 50.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_LI
Gain: $ 7.19 Win %: 50.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_LI
Gain: $ 7.2 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_AL
Gain: $ 7.22 Win %: 75.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_LI
Gain: $ 7.24 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_TR
Gain: $ 7.32 Win %: 50.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_TR
Gain: $ 7.33 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_IR5
Gain: $ 7.33 Win %: 83.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ 7.35 Win %: 100.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_LI
Gain: $ 7.35 Win %: 66.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_TR
Gain: $ 7.37 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_RV_AL
Gain: $ 7.48 Win %: 100.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_QP
Gain: $ 7.51 Win %: 80.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_IR5
Gain: $ 7.52 Win %: 50.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_AV
Gain: $ 7.61 Win %: 100.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_AV
Gain: $ 7.63 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_TR
Gain: $ 7.68 Win %: 60.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_QL
Gain: $ 7.69 Win %: 50.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV_AV
Gain: $ 7.71 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_SS
Gain: $ 7.79 Win %: 62.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_TR_IR2
Gain: $ 7.82 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_TR_IR5
Gain: $ 7.82 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_AL
Gain: $ 7.87 Win %: 75.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_VI
Gain: $ 7.9 Win %: 75.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_RV
Gain: $ 7.91 Win %: 33.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV
Gain: $ 7.97 Win %: 50.00 in 4 days with algo TB3_LO_QM_OB1_OS1_CB3_CS3_TR
Gain: $ 7.97 Win %: 50.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AL
Gain: $ 7.98 Win %: 50.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_AV
Gain: $ 7.98 Win %: 50.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_AV
Gain: $ 7.99 Win %: 62.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_IR2
Gain: $ 7.99 Win %: 87.00 in 8 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_TR_QP
Gain: $ 8.03 Win %: 80.00 in 5 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_LI
Gain: $ 8.08 Win %: 83.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 8.1 Win %: 100.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_TR_IR5
Gain: $ 8.1 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_HM_AV
Gain: $ 8.13 Win %: 100.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_IR5
Gain: $ 8.14 Win %: 75.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_RV_AL
Gain: $ 8.21 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_RV
Gain: $ 8.25 Win %: 80.00 in 5 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_TR
Gain: $ 8.32 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_HM
Gain: $ 8.39 Win %: 83.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_AV
Gain: $ 8.51 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_RV
Gain: $ 8.57 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_TR
Gain: $ 8.74 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_RV_TR
Gain: $ 8.77 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_AL
Gain: $ 8.81 Win %: 100.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_RV_AL
Gain: $ 8.9 Win %: 100.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_VI
Gain: $ 9.01 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_HM_TR
Gain: $ 9.01 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_HM_TR
Gain: $ 9.03 Win %: 100.00 in 4 days with algo TB1_LO_QM_OB3_OS3_CB4_CS4_HM_TR
Gain: $ 9.12 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_HM_AV
Gain: $ 9.19 Win %: 66.00 in 6 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_QL
Gain: $ 9.21 Win %: 62.00 in 8 days with algo TB4_HS_QM_OB2_OS2_CB3_CS3_DB8
Gain: $ 9.25 Win %: 83.00 in 6 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 9.32 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_TR
Gain: $ 9.37 Win %: 80.00 in 5 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_RV
Gain: $ 9.48 Win %: 50.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_HM_TR
Gain: $ 9.49 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_IR5
Gain: $ 9.6 Win %: 75.00 in 4 days with algo TB4_LO_QM_OB3_OS3_CB3_CS3_QL
Gain: $ 9.6 Win %: 80.00 in 5 days with algo TB4_OC_QM_OB4_OS4_CB5_CS5_DB8
Gain: $ 9.63 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3
Gain: $ 9.64 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_HM
Gain: $ 9.64 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_HM
Gain: $ 9.79 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_DB8
Gain: $ 9.81 Win %: 83.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_VI
Gain: $ 9.89 Win %: 83.00 in 6 days with algo TB4_HL_HS_QM_OB1_OS1_CB4_CS4_HM_TR
Gain: $ 9.96 Win %: 75.00 in 8 days with algo TB5_HL_HI_QM_OB5_OS5_CB3_CS3_AL
Gain: $ 9.96 Win %: 75.00 in 8 days with algo TB5_HL_HS_QM_OB5_OS5_CB1_CS1_AL
Gain: $ 9.97 Win %: 66.00 in 6 days with algo TB4_EO_EC_QM_OB1_OS1_CB3_CS3_QL
SPCE Gain: $ 0 Win %: 100.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
SPCE Gain: $ 0.05 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ 0.05 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ 0.07 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
SPCE Gain: $ 0.1 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
SPCE Gain: $ 0.1 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR4
SPCE Gain: $ 0.17 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 0.18 Win %: 70.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_QP
SPCE Gain: $ 0.29 Win %: 50.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 0.56 Win %: 91.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QP_DB4
SPCE Gain: $ 0.62 Win %: 50.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 0.62 Win %: 50.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 0.62 Win %: 50.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP_DB4
SPCE Gain: $ 0.63 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 0.69 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 0.71 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_QP
SPCE Gain: $ 0.71 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_QP
SPCE Gain: $ 0.71 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_QP_DB4
SPCE Gain: $ 0.87 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP_DB4
SPCE Gain: $ 0.91 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_QP_IR4
SPCE Gain: $ 0.91 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_QP_IR4
SPCE Gain: $ 0.98 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 1 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 1.06 Win %: 33.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AV
SPCE Gain: $ 1.06 Win %: 33.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AV
SPCE Gain: $ 1.06 Win %: 33.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AV_DB1
SPCE Gain: $ 1.22 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AV
SPCE Gain: $ 1.22 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AV_DB4
SPCE Gain: $ 1.24 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 1.32 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 1.43 Win %: 100.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QP
SPCE Gain: $ 1.43 Win %: 100.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QP
SPCE Gain: $ 1.43 Win %: 100.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QP_DB4
SPCE Gain: $ 1.49 Win %: 100.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QP
SPCE Gain: $ 1.5 Win %: 76.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_QP_IR1
SPCE Gain: $ 1.52 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_QP
SPCE Gain: $ 1.56 Win %: 100.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QP
SPCE Gain: $ 1.57 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 1.59 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 1.59 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 1.68 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ 1.68 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_QP
SPCE Gain: $ 1.71 Win %: 50.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
SPCE Gain: $ 1.95 Win %: 70.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_QP_IR3
SPCE Gain: $ 1.99 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 2.01 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 2.16 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
SPCE Gain: $ 2.34 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AV
SPCE Gain: $ 2.34 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AV
SPCE Gain: $ 2.36 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 2.42 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_QP
SPCE Gain: $ 2.42 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_QP
SPCE Gain: $ 2.42 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_QP_DB1
SPCE Gain: $ 2.44 Win %: 46.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_DB10
SPCE Gain: $ 2.45 Win %: 50.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AL
SPCE Gain: $ 2.45 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_QP
SPCE Gain: $ 2.45 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_QP
SPCE Gain: $ 2.47 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 2.52 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 2.52 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 2.52 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV_DB4
SPCE Gain: $ 2.54 Win %: 50.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_AV
SPCE Gain: $ 2.55 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 2.62 Win %: 50.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_VI
SPCE Gain: $ 2.63 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 2.63 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 2.7 Win %: 75.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_QP
SPCE Gain: $ 2.7 Win %: 75.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_QP
SPCE Gain: $ 2.7 Win %: 75.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_QP_DB1
SPCE Gain: $ 2.72 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 2.74 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 2.74 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 2.76 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 2.76 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 2.78 Win %: 50.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_SS
SPCE Gain: $ 2.84 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_QP
SPCE Gain: $ 2.84 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_QP
SPCE Gain: $ 2.84 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_QP_DB4
SPCE Gain: $ 2.84 Win %: 80.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_VI
SPCE Gain: $ 2.85 Win %: 80.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_QP
SPCE Gain: $ 2.94 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 3.01 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 3.02 Win %: 46.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 3.05 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 3.05 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 3.11 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR_QP
SPCE Gain: $ 3.11 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR_QP
SPCE Gain: $ 3.11 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR_QP_DB1
SPCE Gain: $ 3.13 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_QP
SPCE Gain: $ 3.13 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_QP
SPCE Gain: $ 3.14 Win %: 70.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 3.2 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_QP
SPCE Gain: $ 3.2 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_QP
SPCE Gain: $ 3.35 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_SS
SPCE Gain: $ 3.35 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_SS
SPCE Gain: $ 3.36 Win %: 60.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 3.46 Win %: 30.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV
SPCE Gain: $ 3.46 Win %: 60.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_QP
SPCE Gain: $ 3.46 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 3.49 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_QP
SPCE Gain: $ 3.51 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QL
SPCE Gain: $ 3.51 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QL
SPCE Gain: $ 3.51 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IT_QL_DB4
SPCE Gain: $ 3.55 Win %: 83.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_QP
SPCE Gain: $ 3.55 Win %: 83.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_QP
SPCE Gain: $ 3.55 Win %: 83.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_QP_DB1
SPCE Gain: $ 3.56 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QL
SPCE Gain: $ 3.56 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QL
SPCE Gain: $ 3.56 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT_QL_DB4
SPCE Gain: $ 3.59 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 3.59 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 3.62 Win %: 46.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 3.68 Win %: 76.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_QP
SPCE Gain: $ 3.81 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AV
SPCE Gain: $ 3.85 Win %: 60.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_VI
SPCE Gain: $ 3.86 Win %: 83.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP
SPCE Gain: $ 3.86 Win %: 83.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP
SPCE Gain: $ 3.93 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 3.93 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_VI
SPCE Gain: $ 3.99 Win %: 61.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 4.03 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
SPCE Gain: $ 4.07 Win %: 50.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_IR1
SPCE Gain: $ 4.15 Win %: 58.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_VI
SPCE Gain: $ 4.3 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 4.3 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 4.32 Win %: 46.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV
SPCE Gain: $ 4.35 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_QL
SPCE Gain: $ 4.35 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_QL
SPCE Gain: $ 4.35 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 4.36 Win %: 58.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_QL
SPCE Gain: $ 4.36 Win %: 58.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_QL
SPCE Gain: $ 4.36 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QP
SPCE Gain: $ 4.38 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 4.38 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 4.38 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP_DB4
SPCE Gain: $ 4.38 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_QP
SPCE Gain: $ 4.39 Win %: 76.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR_QP
SPCE Gain: $ 4.41 Win %: 76.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_QP
SPCE Gain: $ 4.41 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR_QP
SPCE Gain: $ 4.41 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR_QP
SPCE Gain: $ 4.41 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR_QP_DB4
SPCE Gain: $ 4.42 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 4.42 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 4.42 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_VI
SPCE Gain: $ 4.42 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_VI
SPCE Gain: $ 4.52 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 4.53 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 4.53 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 4.55 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 4.55 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 4.59 Win %: 90.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_TR_QP
SPCE Gain: $ 4.62 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_AL
SPCE Gain: $ 4.62 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_AL
SPCE Gain: $ 4.63 Win %: 53.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 4.68 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 4.74 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_QP
SPCE Gain: $ 4.74 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_QP
SPCE Gain: $ 4.74 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_QP_DB1
SPCE Gain: $ 4.78 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_AV
SPCE Gain: $ 4.78 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_AV
SPCE Gain: $ 4.78 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_AV_DB1
SPCE Gain: $ 4.84 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP_IR3
SPCE Gain: $ 4.86 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 4.89 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_QP
SPCE Gain: $ 4.89 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_TR_QP
SPCE Gain: $ 4.94 Win %: 75.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 4.95 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AL
SPCE Gain: $ 4.95 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_AL
SPCE Gain: $ 4.95 Win %: 61.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 5 Win %: 46.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 5.01 Win %: 60.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 5.01 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 5.04 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 5.17 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_QP
SPCE Gain: $ 5.19 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IT_QL
SPCE Gain: $ 5.19 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IT_QL_DB1
SPCE Gain: $ 5.2 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP
SPCE Gain: $ 5.2 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_QP
SPCE Gain: $ 5.24 Win %: 50.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 5.25 Win %: 46.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 5.26 Win %: 41.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AV
SPCE Gain: $ 5.26 Win %: 41.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AV
SPCE Gain: $ 5.26 Win %: 41.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AV_DB1
SPCE Gain: $ 5.33 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QL
SPCE Gain: $ 5.41 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 5.43 Win %: 91.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 5.43 Win %: 91.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 5.45 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_DB6
SPCE Gain: $ 5.45 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_DB6
SPCE Gain: $ 5.48 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP
SPCE Gain: $ 5.48 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_QP
SPCE Gain: $ 5.53 Win %: 60.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AV
SPCE Gain: $ 5.54 Win %: 53.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 5.55 Win %: 50.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AL
SPCE Gain: $ 5.62 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AL
SPCE Gain: $ 5.62 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AL
SPCE Gain: $ 5.64 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QL
SPCE Gain: $ 5.64 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT_QL_DB1
SPCE Gain: $ 5.64 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 5.64 Win %: 83.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_QP_IR1
SPCE Gain: $ 5.64 Win %: 83.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_QP_IR1
SPCE Gain: $ 5.65 Win %: 90.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_QP
SPCE Gain: $ 5.73 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR
SPCE Gain: $ 5.73 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR
SPCE Gain: $ 5.73 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR_DB4
SPCE Gain: $ 5.82 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 5.82 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 5.82 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR_DB4
SPCE Gain: $ 5.89 Win %: 60.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 5.89 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_VI
SPCE Gain: $ 5.89 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_VI
SPCE Gain: $ 5.95 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 5.95 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 5.96 Win %: 90.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QP
SPCE Gain: $ 5.98 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IT_QL
SPCE Gain: $ 6.02 Win %: 69.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_QP
SPCE Gain: $ 6.03 Win %: 58.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_AV
SPCE Gain: $ 6.03 Win %: 58.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_AV
SPCE Gain: $ 6.05 Win %: 38.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AV
SPCE Gain: $ 6.11 Win %: 90.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 6.14 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM
SPCE Gain: $ 6.14 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_HM
SPCE Gain: $ 6.23 Win %: 40.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AV
SPCE Gain: $ 6.26 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AL
SPCE Gain: $ 6.26 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AL
SPCE Gain: $ 6.26 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AL_DB1
SPCE Gain: $ 6.28 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_VI
SPCE Gain: $ 6.29 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 6.29 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 6.33 Win %: 70.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 6.36 Win %: 53.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_QL
SPCE Gain: $ 6.37 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 6.41 Win %: 70.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 6.47 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_QP
SPCE Gain: $ 6.47 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_HM_QP
SPCE Gain: $ 6.49 Win %: 50.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV
SPCE Gain: $ 6.49 Win %: 50.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV
SPCE Gain: $ 6.54 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_QP
SPCE Gain: $ 6.64 Win %: 75.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 6.65 Win %: 100.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_QP
SPCE Gain: $ 6.66 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_DB10
SPCE Gain: $ 6.66 Win %: 91.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_QP
SPCE Gain: $ 6.66 Win %: 91.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_QP
SPCE Gain: $ 6.66 Win %: 91.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_QP_DB1
SPCE Gain: $ 6.69 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5
SPCE Gain: $ 6.69 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_DB10
SPCE Gain: $ 6.69 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AL
SPCE Gain: $ 6.69 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AL
SPCE Gain: $ 6.69 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AL_DB1
SPCE Gain: $ 6.71 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AL
SPCE Gain: $ 6.71 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_AL
SPCE Gain: $ 6.74 Win %: 38.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 6.78 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_LI
SPCE Gain: $ 6.78 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_LI
SPCE Gain: $ 6.81 Win %: 84.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 6.85 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 6.88 Win %: 61.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
SPCE Gain: $ 6.98 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_AL
SPCE Gain: $ 6.98 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_AL
SPCE Gain: $ 7.06 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 7.09 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_QP
SPCE Gain: $ 7.24 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 7.25 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 7.28 Win %: 60.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_IR3
SPCE Gain: $ 7.37 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 7.37 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 7.39 Win %: 53.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 7.42 Win %: 70.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 7.49 Win %: 61.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_AL
SPCE Gain: $ 7.51 Win %: 53.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 7.54 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 7.54 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
SPCE Gain: $ 7.54 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
SPCE Gain: $ 7.7 Win %: 60.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_LI
SPCE Gain: $ 7.73 Win %: 46.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_AV
SPCE Gain: $ 7.74 Win %: 40.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AL
SPCE Gain: $ 7.77 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
SPCE Gain: $ 7.88 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_HM_QP
SPCE Gain: $ 7.89 Win %: 92.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_TR_QP
SPCE Gain: $ 7.9 Win %: 53.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_VI
SPCE Gain: $ 7.91 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_VI
SPCE Gain: $ 7.91 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_VI
SPCE Gain: $ 7.94 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_LI
SPCE Gain: $ 7.94 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_LI
SPCE Gain: $ 7.94 Win %: 70.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IR1
SPCE Gain: $ 7.98 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_AL
SPCE Gain: $ 7.99 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 8.06 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 8.06 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL_DB4
SPCE Gain: $ 8.07 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AL
SPCE Gain: $ 8.07 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AL
SPCE Gain: $ 8.07 Win %: 58.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_AL_DB4
SPCE Gain: $ 8.15 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 8.15 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 8.22 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 8.32 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 8.35 Win %: 61.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 8.46 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
SPCE Gain: $ 8.46 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR_IR4
SPCE Gain: $ 8.46 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR_IR4
SPCE Gain: $ 8.5 Win %: 38.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 8.57 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_AL
SPCE Gain: $ 8.64 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_AV
SPCE Gain: $ 8.76 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 8.87 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 8.88 Win %: 40.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV
SPCE Gain: $ 8.92 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 8.94 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 8.95 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 8.95 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 8.95 Win %: 61.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 8.98 Win %: 60.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 8.99 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QL
SPCE Gain: $ 8.99 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QL
SPCE Gain: $ 9.21 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
SPCE Gain: $ 9.26 Win %: 58.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_IR1
SPCE Gain: $ 9.31 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_TR_QP
SPCE Gain: $ 9.32 Win %: 100.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_QP
SPCE Gain: $ 9.32 Win %: 100.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_QP
SPCE Gain: $ 9.32 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 9.32 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 9.34 Win %: 100.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_QP
SPCE Gain: $ 9.34 Win %: 100.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_QP
SPCE Gain: $ 9.36 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_SS
SPCE Gain: $ 9.39 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_SS
SPCE Gain: $ 9.41 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_LI
SPCE Gain: $ 9.44 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_LI
SPCE Gain: $ 9.48 Win %: 60.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_DB10
SPCE Gain: $ 9.49 Win %: 46.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AV
SPCE Gain: $ 9.49 Win %: 46.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_AV
SPCE Gain: $ 9.58 Win %: 70.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
SPCE Gain: $ 9.6 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 9.69 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 9.69 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 9.7 Win %: 69.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_AL
SPCE Gain: $ 9.7 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_AV
SPCE Gain: $ 9.72 Win %: 91.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_QP
SPCE Gain: $ 9.85 Win %: 46.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 9.85 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 9.92 Win %: 50.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 10.02 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 10.02 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_HM_AV
SPCE Gain: $ 10.03 Win %: 50.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 10.05 Win %: 60.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_TR
SPCE Gain: $ 10.05 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
SPCE Gain: $ 10.06 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 10.07 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_AV
SPCE Gain: $ 10.07 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_AV
SPCE Gain: $ 10.07 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_AV_DB1
SPCE Gain: $ 10.13 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_SS
SPCE Gain: $ 10.13 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 10.16 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_SS
SPCE Gain: $ 10.17 Win %: 50.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 10.17 Win %: 50.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 10.21 Win %: 58.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 10.26 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_QL
SPCE Gain: $ 10.26 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_QL
SPCE Gain: $ 10.31 Win %: 60.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 10.35 Win %: 50.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 10.39 Win %: 70.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_LI
SPCE Gain: $ 10.42 Win %: 80.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_HM_TR
SPCE Gain: $ 10.44 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_LI
SPCE Gain: $ 10.62 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AL
SPCE Gain: $ 10.62 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_AL
SPCE Gain: $ 10.62 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_TR_QP
SPCE Gain: $ 10.63 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IT
SPCE Gain: $ 10.64 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM
SPCE Gain: $ 10.64 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM
SPCE Gain: $ 10.65 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IT
SPCE Gain: $ 10.67 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT
SPCE Gain: $ 10.68 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT
SPCE Gain: $ 10.7 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 10.7 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 10.7 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IT
SPCE Gain: $ 10.79 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_LI
SPCE Gain: $ 10.92 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_QL
SPCE Gain: $ 10.98 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IT
SPCE Gain: $ 11.05 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AV
SPCE Gain: $ 11.05 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_AV
SPCE Gain: $ 11.08 Win %: 66.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_LI
SPCE Gain: $ 11.11 Win %: 50.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR
SPCE Gain: $ 11.12 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_LI
SPCE Gain: $ 11.12 Win %: 80.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
SPCE Gain: $ 11.15 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 11.15 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 11.2 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_AV
SPCE Gain: $ 11.2 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR
SPCE Gain: $ 11.2 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_TR
SPCE Gain: $ 11.23 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 11.23 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 11.26 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
SPCE Gain: $ 11.26 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
SPCE Gain: $ 11.26 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IR4
SPCE Gain: $ 11.26 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_IR4
SPCE Gain: $ 11.3 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 11.35 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 11.35 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 11.38 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 11.38 Win %: 75.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
SPCE Gain: $ 11.39 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_AV
SPCE Gain: $ 11.39 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_HM_AV
SPCE Gain: $ 11.42 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 11.53 Win %: 83.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IT
SPCE Gain: $ 11.55 Win %: 53.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 11.55 Win %: 60.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV
SPCE Gain: $ 11.55 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 11.6 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 11.63 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 11.64 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_AV
SPCE Gain: $ 11.68 Win %: 50.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 11.7 Win %: 70.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM
SPCE Gain: $ 11.73 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_SS
SPCE Gain: $ 11.73 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_SS
SPCE Gain: $ 11.76 Win %: 50.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 11.76 Win %: 84.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM
SPCE Gain: $ 11.8 Win %: 70.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 11.81 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_SS
SPCE Gain: $ 11.81 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_SS
SPCE Gain: $ 11.89 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_AV
SPCE Gain: $ 11.9 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 11.95 Win %: 70.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 11.97 Win %: 50.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 12.01 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5
SPCE Gain: $ 12.05 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 12.1 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5
SPCE Gain: $ 12.22 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 12.24 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5
SPCE Gain: $ 12.24 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5
SPCE Gain: $ 12.25 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 12.26 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 12.26 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 12.26 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
SPCE Gain: $ 12.27 Win %: 58.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 12.27 Win %: 58.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 12.31 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_TR
SPCE Gain: $ 12.31 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_TR
SPCE Gain: $ 12.31 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_TR_DB1
SPCE Gain: $ 12.31 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 12.31 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 12.32 Win %: 83.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IT
SPCE Gain: $ 12.35 Win %: 70.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_TR_IR3
SPCE Gain: $ 12.36 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 12.36 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 12.37 Win %: 61.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_LI
SPCE Gain: $ 12.41 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AL
SPCE Gain: $ 12.42 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
SPCE Gain: $ 12.46 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_VI
SPCE Gain: $ 12.49 Win %: 50.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 12.49 Win %: 50.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 12.5 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IR3
SPCE Gain: $ 12.59 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AV
SPCE Gain: $ 12.64 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 12.67 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 12.8 Win %: 80.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
SPCE Gain: $ 12.9 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_AL
SPCE Gain: $ 12.91 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_IR4
SPCE Gain: $ 12.95 Win %: 70.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 13.01 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_VI
SPCE Gain: $ 13.08 Win %: 80.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 13.32 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
SPCE Gain: $ 13.32 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
SPCE Gain: $ 13.36 Win %: 66.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_AV
SPCE Gain: $ 13.36 Win %: 66.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_AV
SPCE Gain: $ 13.4 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 13.4 Win %: 66.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 13.46 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 13.47 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_TR
SPCE Gain: $ 13.47 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_TR
SPCE Gain: $ 13.47 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_TR_DB4
SPCE Gain: $ 13.47 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_TR_DB4
SPCE Gain: $ 13.47 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV_TR_DB4
SPCE Gain: $ 13.56 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 13.56 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 13.56 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
SPCE Gain: $ 13.56 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
SPCE Gain: $ 13.56 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
SPCE Gain: $ 13.66 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
SPCE Gain: $ 13.7 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV
SPCE Gain: $ 13.75 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV
SPCE Gain: $ 13.76 Win %: 70.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_IR1
SPCE Gain: $ 13.76 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV
SPCE Gain: $ 13.76 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_RV
SPCE Gain: $ 13.8 Win %: 91.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IR1
SPCE Gain: $ 13.8 Win %: 91.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IR1
SPCE Gain: $ 13.83 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV
SPCE Gain: $ 13.87 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QL
SPCE Gain: $ 13.89 Win %: 75.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM
SPCE Gain: $ 13.89 Win %: 75.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM
SPCE Gain: $ 13.91 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
SPCE Gain: $ 13.95 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
SPCE Gain: $ 13.97 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV
SPCE Gain: $ 13.97 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV
SPCE Gain: $ 13.98 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_DB6
SPCE Gain: $ 13.98 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_DB6
SPCE Gain: $ 14.02 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_TR
SPCE Gain: $ 14.02 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_TR
SPCE Gain: $ 14.02 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 14.02 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 14.02 Win %: 75.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 14.04 Win %: 84.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_IR1
SPCE Gain: $ 14.1 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV
SPCE Gain: $ 14.12 Win %: 75.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 14.12 Win %: 75.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AL
SPCE Gain: $ 14.18 Win %: 58.00 in 12 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_RV_AV
SPCE Gain: $ 14.25 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QL
SPCE Gain: $ 14.25 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_QL
SPCE Gain: $ 14.28 Win %: 90.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_HM_AV
SPCE Gain: $ 14.37 Win %: 90.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 14.46 Win %: 91.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_TR
SPCE Gain: $ 14.46 Win %: 91.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_TR
SPCE Gain: $ 14.46 Win %: 91.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_TR_DB1
SPCE Gain: $ 14.48 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_TR_DB1
SPCE Gain: $ 14.49 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR
SPCE Gain: $ 14.49 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR
SPCE Gain: $ 14.49 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 14.49 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 14.49 Win %: 50.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 14.53 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_VI
SPCE Gain: $ 14.73 Win %: 66.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
SPCE Gain: $ 14.75 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR
SPCE Gain: $ 14.75 Win %: 58.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR
SPCE Gain: $ 15.01 Win %: 90.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_HM
SPCE Gain: $ 15.04 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR4
SPCE Gain: $ 15.05 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
SPCE Gain: $ 15.07 Win %: 70.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_QL
SPCE Gain: $ 15.08 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV
SPCE Gain: $ 15.13 Win %: 91.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM
SPCE Gain: $ 15.13 Win %: 91.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM
SPCE Gain: $ 15.21 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 15.24 Win %: 80.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 15.28 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_HM
SPCE Gain: $ 15.31 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM
SPCE Gain: $ 15.34 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_IR3
SPCE Gain: $ 15.34 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_DB6
SPCE Gain: $ 15.38 Win %: 90.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5
SPCE Gain: $ 15.38 Win %: 90.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
SPCE Gain: $ 15.39 Win %: 60.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_TR
SPCE Gain: $ 15.39 Win %: 60.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_RV_TR_DB3
SPCE Gain: $ 15.46 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR
SPCE Gain: $ 15.46 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 15.46 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_TR
SPCE Gain: $ 15.47 Win %: 50.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 15.6 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 15.6 Win %: 70.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
SPCE Gain: $ 15.72 Win %: 76.00 in 13 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
SPCE Gain: $ 15.72 Win %: 83.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_DB6
SPCE Gain: $ 15.72 Win %: 83.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_DB6
SPCE Gain: $ 15.83 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_AV
SPCE Gain: $ 15.88 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_DB15
SPCE Gain: $ 15.88 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB5_OS5_CB4_CS4_DB15
SPCE Gain: $ 15.88 Win %: 84.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 15.93 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
SPCE Gain: $ 15.93 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_DB15
SPCE Gain: $ 16.22 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_LI
SPCE Gain: $ 16.22 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_LI
SPCE Gain: $ 16.25 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV
SPCE Gain: $ 16.32 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_IR1
SPCE Gain: $ 16.32 Win %: 66.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_IR1
SPCE Gain: $ 16.33 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_HM
SPCE Gain: $ 16.36 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM
SPCE Gain: $ 16.38 Win %: 90.00 in 10 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 16.5 Win %: 70.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_AL
SPCE Gain: $ 16.51 Win %: 50.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 16.66 Win %: 58.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 16.71 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_IR1
SPCE Gain: $ 16.74 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 16.88 Win %: 70.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_DB10
SPCE Gain: $ 16.89 Win %: 84.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5
SPCE Gain: $ 16.9 Win %: 70.00 in 10 days with algo TB3_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 16.97 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_AL
SPCE Gain: $ 16.97 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_AL
SPCE Gain: $ 17.01 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 17.05 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 17.05 Win %: 66.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_AL
SPCE Gain: $ 17.07 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR_IR3
SPCE Gain: $ 17.17 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_DB6
SPCE Gain: $ 17.22 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_RV_TR
SPCE Gain: $ 17.22 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_TR
SPCE Gain: $ 17.22 Win %: 53.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV_TR_DB1
SPCE Gain: $ 17.29 Win %: 69.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_AV
SPCE Gain: $ 17.34 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_AV
SPCE Gain: $ 17.34 Win %: 80.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_DB6
SPCE Gain: $ 17.39 Win %: 84.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 17.61 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_IR1
SPCE Gain: $ 17.62 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_TR
SPCE Gain: $ 17.62 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_HM_TR
SPCE Gain: $ 17.64 Win %: 70.00 in 10 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR
SPCE Gain: $ 17.66 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_LI
SPCE Gain: $ 17.72 Win %: 75.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IR1
SPCE Gain: $ 17.72 Win %: 75.00 in 12 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IR1
SPCE Gain: $ 17.92 Win %: 91.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 17.92 Win %: 91.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 17.94 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 17.94 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 17.94 Win %: 75.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
SPCE Gain: $ 17.95 Win %: 76.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_AV
SPCE Gain: $ 18.08 Win %: 83.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR
SPCE Gain: $ 18.08 Win %: 83.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR
SPCE Gain: $ 18.21 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM_TR
SPCE Gain: $ 18.35 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_HM_TR
SPCE Gain: $ 18.35 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_HM_TR
SPCE Gain: $ 18.41 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_AV
SPCE Gain: $ 18.68 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 18.78 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_TR_IR1
SPCE Gain: $ 18.85 Win %: 83.00 in 12 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 18.92 Win %: 80.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_QL
SPCE Gain: $ 18.92 Win %: 80.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_SS
SPCE Gain: $ 18.92 Win %: 80.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_TR
SPCE Gain: $ 18.98 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 19.29 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IR1
SPCE Gain: $ 19.29 Win %: 84.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_SS
SPCE Gain: $ 19.47 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_TR
SPCE Gain: $ 19.47 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_TR
SPCE Gain: $ 19.61 Win %: 69.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 20.36 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR_IR1
SPCE Gain: $ 20.36 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_TR_IR1
SPCE Gain: $ 20.37 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_DB6
SPCE Gain: $ 20.37 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_DB6
SPCE Gain: $ 20.46 Win %: 91.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR_IR1
SPCE Gain: $ 20.46 Win %: 91.00 in 12 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR_IR1
SPCE Gain: $ 20.61 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_IR1
SPCE Gain: $ 20.64 Win %: 84.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_IR1
SPCE Gain: $ 20.7 Win %: 92.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_HM_TR
SPCE Gain: $ 20.75 Win %: 66.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_AV
SPCE Gain: $ 20.83 Win %: 84.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 21.37 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR
SPCE Gain: $ 21.37 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_TR
SPCE Gain: $ 21.52 Win %: 69.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_TR
SPCE Gain: $ 21.86 Win %: 84.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_AV
SPCE Gain: $ 22.06 Win %: 76.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_TR
SPCE Gain: $ 22.06 Win %: 76.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
SPCE Gain: $ 22.22 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_DB10
SPCE Gain: $ 22.22 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_DB10
SPCE Gain: $ 22.24 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_HM
SPCE Gain: $ 22.44 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
SPCE Gain: $ 22.64 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 22.64 Win %: 75.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_TR
SPCE Gain: $ 22.67 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 22.67 Win %: 76.00 in 13 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
SPCE Gain: $ 23.16 Win %: 84.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_DB6
SPCE Gain: $ 23.22 Win %: 76.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB1_CS1_TR
SPCE Gain: $ 23.61 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QL
SPCE Gain: $ 24.06 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 24.06 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_SS
SPCE Gain: $ 24.62 Win %: 80.00 in 10 days with algo TB3_HL_HS_QM_OB5_OS5_CB1_CS1_AV
SPCE Gain: $ 25.15 Win %: 75.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_AV
SPCE Gain: $ 25.21 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 25.52 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_TR
SPCE Gain: $ 25.73 Win %: 100.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_SS
SPCE Gain: $ 25.73 Win %: 100.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_SS
SPCE Gain: $ 25.95 Win %: 92.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR_IR1
SPCE Gain: $ 26.42 Win %: 84.00 in 13 days with algo TB5_HL_LO_QM_OB4_OS4_CB1_CS1_TR
SPCE Gain: $ 26.58 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR
SPCE Gain: $ 26.58 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
SPCE Gain: $ 26.6 Win %: 83.00 in 12 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_RV_TR_DB3
SPCE Gain: $ 28.32 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_TR
SPCE Gain: $ 28.32 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_TR_DB1
SPCE Gain: $ 28.32 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_TR_DB1
SPCE Gain: $ 28.51 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_TR_IR1
SPCE Gain: $ 28.51 Win %: 83.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_TR_IR1
SPCE Gain: $ 30.99 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_TR
SPCE Gain: $ 30.99 Win %: 91.00 in 12 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_TR
SPCE Gain: $ 57.26 Win %: 61.00 in 13 days with algo TB5_HL_HI_QM_OB4_OS4_CB3_CS3_RV
