T Gain: $ -1.48 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_QP_IR2
T Gain: $ -1.48 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_QP_IR2
T Gain: $ -1.37 Win %: 0 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_HM_QP
T Gain: $ -1.37 Win %: 0 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_QP
T Gain: $ -1.37 Win %: 0 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_RV_QP
T Gain: $ -1.26 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_LI
T Gain: $ -1.1 Win %: 0 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1
T Gain: $ -1.1 Win %: 0 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_HM
T Gain: $ -1.1 Win %: 0 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_QL
T Gain: $ -1.1 Win %: 0 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_RV
T Gain: $ -1.09 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_IR2
T Gain: $ -1.09 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_IR2
T Gain: $ -1 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_RV_TR_DB3
T Gain: $ -0.97 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_AL
T Gain: $ -0.97 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_HM_TR
T Gain: $ -0.94 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_DB10
T Gain: $ -0.92 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_RV_TR
T Gain: $ -0.91 Win %: 0 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_DB15
T Gain: $ -0.91 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_TR
T Gain: $ -0.91 Win %: 33.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_TR_QP
T Gain: $ -0.9 Win %: 0 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_SS
T Gain: $ -0.87 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_AL
T Gain: $ -0.87 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_AL
T Gain: $ -0.86 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_LI
T Gain: $ -0.85 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_LI
T Gain: $ -0.84 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_RV_AL
T Gain: $ -0.8 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_RV_AL
T Gain: $ -0.8 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_IT
T Gain: $ -0.77 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_HM_QP
T Gain: $ -0.73 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_RV
T Gain: $ -0.72 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_RV_QP
T Gain: $ -0.72 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_VI
T Gain: $ -0.72 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_VI
T Gain: $ -0.71 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_QP
T Gain: $ -0.7 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_RV_AL
T Gain: $ -0.67 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_HM_QP
T Gain: $ -0.63 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_RV_TR
T Gain: $ -0.52 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_HM
T Gain: $ -0.52 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_SS
T Gain: $ -0.51 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_TR_IR2
T Gain: $ -0.51 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_TR_IR2
T Gain: $ -0.49 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_DB8
T Gain: $ -0.49 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_DB8
T Gain: $ -0.47 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_RV
T Gain: $ -0.46 Win %: 0 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_QL
T Gain: $ -0.45 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_TR_QP
T Gain: $ -0.44 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_HM_TR
T Gain: $ -0.44 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_IT_QL
T Gain: $ -0.44 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_RV_TR
T Gain: $ -0.44 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_TR
T Gain: $ -0.4 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_RV_TR
T Gain: $ -0.4 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_RV_TR_DB2
T Gain: $ -0.4 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_TR
T Gain: $ -0.4 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_RV_TR_DB2
T Gain: $ -0.4 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_TR
T Gain: $ -0.4 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_RV_TR_DB4
T Gain: $ -0.4 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_HM_QP
T Gain: $ -0.39 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_TR_QP
T Gain: $ -0.39 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_TR_QP
T Gain: $ -0.38 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_QP
T Gain: $ -0.38 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_RV_QP
T Gain: $ -0.38 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_QP
T Gain: $ -0.38 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_RV_QP
T Gain: $ -0.34 Win %: 66.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_IT_QP
T Gain: $ -0.33 Win %: 66.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_SS
T Gain: $ -0.33 Win %: 66.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_SS
T Gain: $ -0.22 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_LI
T Gain: $ -0.2 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_HM
T Gain: $ -0.2 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_HM
T Gain: $ -0.18 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_QL
T Gain: $ -0.18 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_QL
T Gain: $ -0.18 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_RV
T Gain: $ -0.16 Win %: 0 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_HM_TR
T Gain: $ -0.16 Win %: 0 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_HM_TR
T Gain: $ -0.11 Win %: 66.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_IT
T Gain: $ -0.11 Win %: 66.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_IT_QL
T Gain: $ -0.11 Win %: 66.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_IT
T Gain: $ -0.11 Win %: 66.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_IT_QL
T Gain: $ -0.08 Win %: 33.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_VI
T Gain: $ -0.06 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_RV_AL
T Gain: $ -0.03 Win %: 33.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_VI
Gain: $ -0.03 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_SS
Gain: $ -0.03 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_SS
Gain: $ -0.03 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_SS
Gain: $ -0.03 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_SS
Gain: $ -0.03 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_SS
Gain: $ -0.03 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_SS
Gain: $ -0.09 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_QL
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_RV_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_RV_AV
Gain: $ -0.44 Win %: 0 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_RV_AV
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_TR_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_TR_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_TR_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_TR_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_QP_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_TR_IR5
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_TR_IR5
Gain: $ 0.01 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_SS
Gain: $ 0.04 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_VI
Gain: $ 0.04 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_VI
Gain: $ 0.04 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_VI
Gain: $ 0.04 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_VI
Gain: $ 0.04 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_VI
Gain: $ 0.04 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_VI
Gain: $ 0.04 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_VI
Gain: $ 0.19 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_TR_QP
Gain: $ 0.22 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_TR_QP
Gain: $ 0.22 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_TR_QP
Gain: $ 0.22 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_TR_QP
Gain: $ 0.22 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_TR_QP
Gain: $ 0.22 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_TR_QP
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_RV_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_RV_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_RV_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_RV_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_TR
Gain: $ 0.41 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_TR
Gain: $ 0.42 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_PA_TR
Gain: $ 0.42 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_PA_TR
Gain: $ 0.42 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_HM_TR
Gain: $ 0.42 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_PA_TR
Gain: $ 0.42 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_HM_TR
Gain: $ 0.42 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_PA_TR
Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_AL
Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_AL
Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_AL
Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_AL
Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_AL
Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_AL
Gain: $ 0.45 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_AL
Gain: $ 0.5 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_PA_AV
Gain: $ 0.5 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_PA_AV
Gain: $ 0.5 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_HM_AV
Gain: $ 0.5 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_PA_AV
Gain: $ 0.5 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_HM_AV
Gain: $ 0.5 Win %: 50.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_PA_AV
Gain: $ 0.51 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_LI
Gain: $ 0.51 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_LI
Gain: $ 0.51 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_LI
Gain: $ 0.51 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_LI
Gain: $ 0.51 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_LI
Gain: $ 0.51 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_LI
Gain: $ 0.51 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_LI
Gain: $ 0.57 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_QP
Gain: $ 0.57 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_RV_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_RV_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_RV_QP
Gain: $ 0.6 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_RV_QP
Gain: $ 0.63 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_PA_QP
Gain: $ 0.63 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_PA_QP
Gain: $ 0.66 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_PA_QP
Gain: $ 0.66 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_HM_QP
Gain: $ 0.66 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_PA_QP
Gain: $ 0.66 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_HM_QP
Gain: $ 0.66 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_PA_QP
Gain: $ 0.78 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_PA
Gain: $ 0.78 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_HM
Gain: $ 0.78 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_PA
Gain: $ 0.78 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_HM
Gain: $ 0.78 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_PA
Gain: $ 0.78 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_HM
Gain: $ 0.78 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_PA
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_DB30
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_QL
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB2_OS2_CB3_CS3_RV
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_DB30
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_QL
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_RV
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB1_CS1_RV
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_DB30
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_DB30
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_QL
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_QL
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_DB30
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_DB30
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_QL
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_QL
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_RV
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB1_HL_HS_QM_OB3_OS3_CB3_CS3_RV
T Gain: $ 0 Win %: 100.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_IR4
T Gain: $ 0 Win %: 100.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_QP_IR4
T Gain: $ 0 Win %: 100.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_TR_IR4
T Gain: $ 0 Win %: 100.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_IR3
T Gain: $ 0 Win %: 100.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_QP_IR3
T Gain: $ 0 Win %: 100.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_TR_IR3
T Gain: $ 0.19 Win %: 100.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_IT
T Gain: $ 0.19 Win %: 100.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_IT_QL
T Gain: $ 0.23 Win %: 100.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_IT_QP
T Gain: $ 0.27 Win %: 100.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_IT_QP
T Gain: $ 0.27 Win %: 100.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_IT_QP
T Gain: $ 0.29 Win %: 66.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_AL
T Gain: $ 0.38 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_HM_AV
T Gain: $ 0.38 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_HM_AV
T Gain: $ 0.46 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_RV_AV
T Gain: $ 0.46 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_RV_AV
T Gain: $ 0.7 Win %: 33.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_RV_AV
T Gain: $ 0.77 Win %: 66.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_HM_AV
T Gain: $ 0.78 Win %: 100.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_RV_AV
T Gain: $ 0.81 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB1_OS1_CB2_CS2_AV
T Gain: $ 0.81 Win %: 33.00 in 3 days with algo TB4_HI_QM_OB2_OS2_CB1_CS1_AV
T Gain: $ 0.83 Win %: 66.00 in 3 days with algo TB3_HS_QM_OB2_OS2_CB2_CS2_AV
T Gain: $ 1.38 Win %: 100.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_AV
T Gain: $ 1.38 Win %: 100.00 in 3 days with algo TB2_HS_QM_OB2_OS2_CB1_CS1_HM_AV
