TIGR Gain: $ -24.28 Win %: 0 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_QP
TIGR Gain: $ -23 Win %: 0 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_QP_IR5
TIGR Gain: $ -21.38 Win %: 0 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_QP_IR5
TIGR Gain: $ -21.01 Win %: 0 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_QP
TIGR Gain: $ -20.85 Win %: 0 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_QP_IR5
TIGR Gain: $ -20.51 Win %: 0 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_HM_QP
TIGR Gain: $ -20.51 Win %: 0 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_HM_QP
TIGR Gain: $ -20.45 Win %: 0 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_QP_IR5
TIGR Gain: $ -20.33 Win %: 16.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_QP
TIGR Gain: $ -20.13 Win %: 16.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_HM_QP
TIGR Gain: $ -19.65 Win %: 0 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_QP
TIGR Gain: $ -18.95 Win %: 0 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_HM_QP
TIGR Gain: $ -18.36 Win %: 0 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_QP_IR5
TIGR Gain: $ -18.14 Win %: 0 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_QP
TIGR Gain: $ -17.76 Win %: 0 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_QP
TIGR Gain: $ -17.05 Win %: 0 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_QP
TIGR Gain: $ -16.48 Win %: 0 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_QP
TIGR Gain: $ -16.11 Win %: 0 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_HM_QP
TIGR Gain: $ -15.98 Win %: 0 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_QP_IR5
TIGR Gain: $ -14.58 Win %: 0 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_QP_IR5
TIGR Gain: $ -11.39 Win %: 33.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_QP
TIGR Gain: $ -11.2 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM_QP
TIGR Gain: $ -10.99 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_QP
TIGR Gain: $ -10.97 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_QP
TIGR Gain: $ -10.44 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_QP
TIGR Gain: $ -10.37 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_HM_QP_DB1
TIGR Gain: $ -10.24 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM_QP_DB5
TIGR Gain: $ -10.19 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_HM_QP
TIGR Gain: $ -10.05 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_QP
TIGR Gain: $ -10.01 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_QP_DB5
TIGR Gain: $ -9.81 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV_QP
TIGR Gain: $ -9.32 Win %: 16.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_TR_QP
TIGR Gain: $ -9.02 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_IT_QP
TIGR Gain: $ -8.96 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_QP
TIGR Gain: $ -8.73 Win %: 0 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_IR5
TIGR Gain: $ -8.72 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_TR_QP
TIGR Gain: $ -8.37 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_QP
TIGR Gain: $ -8.26 Win %: 0 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_LI
TIGR Gain: $ -7.73 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_TR_QP_DB5
TIGR Gain: $ -7.6 Win %: 0 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_IR5
TIGR Gain: $ -6.93 Win %: 20.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_TR_QP
TIGR Gain: $ -6.78 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV_QP_DB1
TIGR Gain: $ -6.74 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_QP
TIGR Gain: $ -6.55 Win %: 0 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_LI
TIGR Gain: $ -6.55 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_HM_QP
TIGR Gain: $ -6.44 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_QP
TIGR Gain: $ -6.4 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_HM_QP
TIGR Gain: $ -6.32 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_IR3
TIGR Gain: $ -6.24 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_TR_QP
TIGR Gain: $ -6.21 Win %: 16.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_IR5
TIGR Gain: $ -6.12 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_TR_QP
TIGR Gain: $ -5.81 Win %: 33.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_AL
TIGR Gain: $ -5.78 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_HM
TIGR Gain: $ -5.76 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_TR
TIGR Gain: $ -5.62 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_DB10
TIGR Gain: $ -5.6 Win %: 33.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM_QP
TIGR Gain: $ -5.58 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_HM_TR
TIGR Gain: $ -5.43 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_DB30
TIGR Gain: $ -5.12 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_QP_IR5
TIGR Gain: $ -5.07 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_HM
TIGR Gain: $ -5 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV
TIGR Gain: $ -4.8 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV_AL_DB1
TIGR Gain: $ -4.76 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_LI
TIGR Gain: $ -4.75 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_HM_TR
TIGR Gain: $ -4.42 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_DB6
TIGR Gain: $ -4.41 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_AL
TIGR Gain: $ -4.31 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_TR_QP
TIGR Gain: $ -4.28 Win %: 20.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_IR5
TIGR Gain: $ -4.27 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_TR_QP
TIGR Gain: $ -4.27 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM
TIGR Gain: $ -4.24 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_SS
TIGR Gain: $ -4.08 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_TR_QP
TIGR Gain: $ -3.96 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_LI
TIGR Gain: $ -3.96 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_AL
TIGR Gain: $ -3.89 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_IR1
TIGR Gain: $ -3.85 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_QP_IR3
TIGR Gain: $ -3.8 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_TR_QP
TIGR Gain: $ -3.77 Win %: 0 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_QP_IR3
TIGR Gain: $ -3.73 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_TR_QP
TIGR Gain: $ -3.68 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_AL
TIGR Gain: $ -3.68 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_QP_IR1
TIGR Gain: $ -3.65 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_TR
TIGR Gain: $ -3.64 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_TR_QP
TIGR Gain: $ -3.61 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_QP
TIGR Gain: $ -3.6 Win %: 16.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_IR5
TIGR Gain: $ -3.58 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_TR
TIGR Gain: $ -3.49 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_SS
TIGR Gain: $ -3.42 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_QL
TIGR Gain: $ -3.38 Win %: 20.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_VI
TIGR Gain: $ -3.34 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_AL
TIGR Gain: $ -3.33 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM_TR
TIGR Gain: $ -3.29 Win %: 16.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_IR5
TIGR Gain: $ -3.29 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_HM_TR
TIGR Gain: $ -3.16 Win %: 20.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_VI
TIGR Gain: $ -3.12 Win %: 20.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_IR5
TIGR Gain: $ -3.02 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_TR_QP_DB1
TIGR Gain: $ -2.93 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV_AL
TIGR Gain: $ -2.93 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_TR
TIGR Gain: $ -2.85 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_LI
TIGR Gain: $ -2.85 Win %: 33.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_VI
TIGR Gain: $ -2.82 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_AV
TIGR Gain: $ -2.8 Win %: 20.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR_QP
TIGR Gain: $ -2.77 Win %: 33.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR_QP
TIGR Gain: $ -2.76 Win %: 0 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_TR_QP
TIGR Gain: $ -2.72 Win %: 0 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_TR_QP_DB3
TIGR Gain: $ -2.7 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_HM_AV
TIGR Gain: $ -2.63 Win %: 50.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM_QP
TIGR Gain: $ -2.63 Win %: 50.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM_QP
TIGR Gain: $ -2.62 Win %: 0 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_VI
TIGR Gain: $ -2.61 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV_AV
TIGR Gain: $ -2.61 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV_AV_DB1
TIGR Gain: $ -2.59 Win %: 50.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_QP_IR3
TIGR Gain: $ -2.57 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR
TIGR Gain: $ -2.57 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR_DB3
TIGR Gain: $ -2.54 Win %: 0 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_AV
TIGR Gain: $ -2.54 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_QP
TIGR Gain: $ -2.54 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_QP_DB5
TIGR Gain: $ -2.51 Win %: 33.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_VI
TIGR Gain: $ -2.44 Win %: 50.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_QP
TIGR Gain: $ -2.39 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_AL
TIGR Gain: $ -2.37 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_LI
TIGR Gain: $ -2.35 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_SS
TIGR Gain: $ -2.34 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV
TIGR Gain: $ -2.29 Win %: 0 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_VI
TIGR Gain: $ -2.28 Win %: 50.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_IR3
TIGR Gain: $ -2.28 Win %: 50.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_TR_IR3
TIGR Gain: $ -2.26 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_IT
TIGR Gain: $ -2.26 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_AV
TIGR Gain: $ -2.25 Win %: 0 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_AV
TIGR Gain: $ -2.22 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_IT_QL_DB1
TIGR Gain: $ -2.18 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_AL_DB5
TIGR Gain: $ -2.17 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1
TIGR Gain: $ -2.14 Win %: 16.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_QP_IR5
TIGR Gain: $ -2.14 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_TR
TIGR Gain: $ -2.14 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_AL
TIGR Gain: $ -2.12 Win %: 0 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_VI
TIGR Gain: $ -2.06 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV_AL
TIGR Gain: $ -2.02 Win %: 33.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_AV
TIGR Gain: $ -1.94 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_IR5
TIGR Gain: $ -1.92 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_TR
TIGR Gain: $ -1.92 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_VI
TIGR Gain: $ -1.89 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_AL
TIGR Gain: $ -1.84 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_HM_AV_DB3
TIGR Gain: $ -1.84 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_SS
TIGR Gain: $ -1.81 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_QL
TIGR Gain: $ -1.81 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_AL
TIGR Gain: $ -1.8 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_AL
TIGR Gain: $ -1.78 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV_TR
TIGR Gain: $ -1.77 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_HM_AV
TIGR Gain: $ -1.76 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_QP
TIGR Gain: $ -1.76 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV_TR_DB1
TIGR Gain: $ -1.76 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_LI
TIGR Gain: $ -1.74 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_AV
TIGR Gain: $ -1.74 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM
TIGR Gain: $ -1.72 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV_AL_DB3
TIGR Gain: $ -1.72 Win %: 50.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_QP
TIGR Gain: $ -1.68 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_QP_IR5
TIGR Gain: $ -1.65 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR_QP_DB5
TIGR Gain: $ -1.62 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV_TR
TIGR Gain: $ -1.62 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_TR_DB5
TIGR Gain: $ -1.6 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_AL
TIGR Gain: $ -1.59 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_DB30
TIGR Gain: $ -1.53 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_VI
TIGR Gain: $ -1.51 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV_TR_DB3
TIGR Gain: $ -1.51 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV_TR_DB3
TIGR Gain: $ -1.47 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM_AV
TIGR Gain: $ -1.43 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_SS
TIGR Gain: $ -1.43 Win %: 66.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_AL
TIGR Gain: $ -1.4 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_QP
TIGR Gain: $ -1.38 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_QL
TIGR Gain: $ -1.38 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_AL
TIGR Gain: $ -1.3 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_DB10
TIGR Gain: $ -1.29 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_AV
TIGR Gain: $ -1.24 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_HM
TIGR Gain: $ -1.23 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_TR_IR5
TIGR Gain: $ -1.23 Win %: 66.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_SS
TIGR Gain: $ -1.22 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_SS
TIGR Gain: $ -1.21 Win %: 33.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_IR5
TIGR Gain: $ -1.2 Win %: 20.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_QP_IR5
TIGR Gain: $ -1.18 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_TR
TIGR Gain: $ -1.14 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_IT
TIGR Gain: $ -1.14 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_HM
TIGR Gain: $ -1.13 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_SS
TIGR Gain: $ -1.12 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV_QP
TIGR Gain: $ -1.12 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_TR_IR5
TIGR Gain: $ -1.11 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV_QP_DB3
TIGR Gain: $ -1.11 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_AL
TIGR Gain: $ -1.09 Win %: 66.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_RV_TR_DB1
TIGR Gain: $ -1.04 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_TR
TIGR Gain: $ -1.03 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_AV
TIGR Gain: $ -1.03 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_AV
TIGR Gain: $ -1.02 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_LI
TIGR Gain: $ -1.02 Win %: 75.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_TR_DB5
TIGR Gain: $ -1.01 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_QL
TIGR Gain: $ -0.96 Win %: 33.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_TR_IR5
TIGR Gain: $ -0.95 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_TR
TIGR Gain: $ -0.95 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_TR_DB5
TIGR Gain: $ -0.95 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_DB30
TIGR Gain: $ -0.94 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_TR
TIGR Gain: $ -0.9 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_TR_IR1
TIGR Gain: $ -0.89 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_VI
TIGR Gain: $ -0.89 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_AV
TIGR Gain: $ -0.88 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_SS
TIGR Gain: $ -0.87 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_AL
TIGR Gain: $ -0.87 Win %: 50.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_TR_IR3
TIGR Gain: $ -0.84 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_IT_QL
TIGR Gain: $ -0.8 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_HM_QP_DB3
TIGR Gain: $ -0.77 Win %: 50.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_TR
TIGR Gain: $ -0.77 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV
TIGR Gain: $ -0.76 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_HM_TR_DB3
TIGR Gain: $ -0.75 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_AL
TIGR Gain: $ -0.75 Win %: 75.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV
TIGR Gain: $ -0.74 Win %: 50.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_QP
TIGR Gain: $ -0.74 Win %: 50.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_QP
TIGR Gain: $ -0.73 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_LI
TIGR Gain: $ -0.72 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_HM_TR
TIGR Gain: $ -0.72 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_AL
TIGR Gain: $ -0.71 Win %: 20.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_TR
TIGR Gain: $ -0.71 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV
TIGR Gain: $ -0.66 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_HM_QP
TIGR Gain: $ -0.61 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_TR_DB5
TIGR Gain: $ -0.61 Win %: 75.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_HM
TIGR Gain: $ -0.6 Win %: 33.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR_IR5
TIGR Gain: $ -0.6 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_SS
TIGR Gain: $ -0.59 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_QL
TIGR Gain: $ -0.57 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR_IR5
TIGR Gain: $ -0.55 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_QP_IR5
TIGR Gain: $ -0.55 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_TR_DB5
TIGR Gain: $ -0.54 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_HM_TR
TIGR Gain: $ -0.53 Win %: 0 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_IT_QL
TIGR Gain: $ -0.5 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV_AV_DB3
TIGR Gain: $ -0.5 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV_AV
TIGR Gain: $ -0.49 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_QP
TIGR Gain: $ -0.46 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_TR
TIGR Gain: $ -0.46 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_TR_DB5
TIGR Gain: $ -0.43 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV_AV
TIGR Gain: $ -0.43 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_TR
TIGR Gain: $ -0.42 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_VI
TIGR Gain: $ -0.39 Win %: 25.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_TR_IR5
TIGR Gain: $ -0.37 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_HM_TR_DB1
TIGR Gain: $ -0.34 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_TR
TIGR Gain: $ -0.3 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AL
TIGR Gain: $ -0.29 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AV_DB5
TIGR Gain: $ -0.29 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_TR
TIGR Gain: $ -0.27 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_QP
TIGR Gain: $ -0.27 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR_QP
TIGR Gain: $ -0.27 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_QP
TIGR Gain: $ -0.26 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AL_DB5
TIGR Gain: $ -0.25 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_QL
TIGR Gain: $ -0.22 Win %: 33.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_TR
TIGR Gain: $ -0.2 Win %: 50.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_QL
TIGR Gain: $ -0.19 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV
TIGR Gain: $ -0.17 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_TR_DB3
TIGR Gain: $ -0.16 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1
TIGR Gain: $ -0.16 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_DB30
TIGR Gain: $ -0.15 Win %: 60.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_QP
TIGR Gain: $ -0.12 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_QL
TIGR Gain: $ -0.11 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_RV
TIGR Gain: $ -0.09 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_IT_QP_DB5
TIGR Gain: $ -0.09 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_AV_DB5
TIGR Gain: $ -0.08 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_TR
TIGR Gain: $ -0.08 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_HM
TIGR Gain: $ -0.05 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_HM_AV
TIGR Gain: $ -0.04 Win %: 0 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_IT_QP
TIGR Gain: $ -0.03 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_HM
TIGR Gain: $ -0.03 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_HM_TR
TIGR Gain: $ -0.02 Win %: 33.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_IT_QP_DB1
TIGR Gain: $ -0.01 Win %: 40.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR_IR5
TIGR Gain: $ -0.01 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_AV
TIGR Gain: $ -0.01 Win %: 66.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_QP
Gain: $ -0.1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR
Gain: $ -0.15 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_TR
Gain: $ -0.16 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AV
Gain: $ -0.2 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_TR
Gain: $ -0.28 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -0.34 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_QP_IR5
Gain: $ -0.36 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR_DB
Gain: $ -0.37 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM_TR
Gain: $ -0.39 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_VI
Gain: $ -0.48 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_AL
Gain: $ -0.5 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_RV_AL
Gain: $ -0.5 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_QP_IR5
Gain: $ -0.5 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_QP_IR5
Gain: $ -0.5 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ -0.61 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_VI
Gain: $ -0.63 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_VI
Gain: $ -0.65 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_TR_QP
Gain: $ -0.67 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_TR
Gain: $ -0.73 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_TR_IR5
Gain: $ -0.85 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_IR5
Gain: $ -0.91 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_QL
Gain: $ -0.94 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_HM_TR
Gain: $ -1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_IR5
Gain: $ -1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_TR_IR5
Gain: $ -1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_IR5
Gain: $ -1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_TR_IR5
Gain: $ -1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ -1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ -1.08 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AL
Gain: $ -1.09 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_AV
Gain: $ -1.11 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_HM_AV
Gain: $ -1.12 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_AL
Gain: $ -1.27 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_DB10
Gain: $ -1.27 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -1.27 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -1.36 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_QP
Gain: $ -1.48 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM_AV
Gain: $ -1.5 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -1.5 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -1.53 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_LI
Gain: $ -1.55 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV
Gain: $ -1.77 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM_QP
Gain: $ -1.77 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM_QP
Gain: $ -1.99 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_QL
Gain: $ -128.73 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ -2.27 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_DB10
Gain: $ -2.27 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_SS
Gain: $ -2.32 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_QP
Gain: $ -2.32 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_QP
Gain: $ -2.43 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_TR_QP
Gain: $ -2.57 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_QP
Gain: $ -2.58 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_AV
Gain: $ -2.63 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_HM_QP
Gain: $ -2.69 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_AV
Gain: $ -2.78 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_HM_QP
Gain: $ -2.82 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_QP
Gain: $ -2.84 Win %: 0 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_RV_QP
Gain: $ -3.31 Win %: 0 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_HM
Gain: $ -659.35 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_SS
Gain: $ 0 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0.05 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ 0.06 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ 0.1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_AV
Gain: $ 0.11 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_AL
Gain: $ 0.12 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_VI
Gain: $ 0.13 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_LI
Gain: $ 0.17 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_RV_TR
Gain: $ 0.19 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_HM_AV
Gain: $ 0.23 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_AL
Gain: $ 0.24 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 0.25 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 0.36 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_LI
Gain: $ 0.38 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_QL
Gain: $ 0.43 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_TR_QP
Gain: $ 0.55 Win %: 50.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_RV_AV
Gain: $ 0.59 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_LI
Gain: $ 0.68 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 0.8 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 0.82 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5
Gain: $ 1 Win %: 50.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_AL
Gain: $ 1.17 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 1.23 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_HM
Gain: $ 1.27 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_RV
Gain: $ 1.34 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_TR
Gain: $ 1.43 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_HM_TR
Gain: $ 1.53 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_DB30
Gain: $ 1.64 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_DB10
Gain: $ 1.64 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM
Gain: $ 1.64 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_QL
Gain: $ 1.64 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_SS
Gain: $ 1.79 Win %: 100.00 in 2 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV
Gain: $ 2.39 Win %: 100.00 in 2 days with algo TB1_HL_HI_QM_OB3_OS3_CB2_CS2_AV
TIGR Gain: $ 0.03 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_IR5
TIGR Gain: $ 0.03 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_SS
TIGR Gain: $ 0.04 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_TR_DB5
TIGR Gain: $ 0.04 Win %: 66.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_IT_QP_DB3
TIGR Gain: $ 0.05 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_LI
TIGR Gain: $ 0.05 Win %: 66.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM_TR_DB5
TIGR Gain: $ 0.07 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_HM_TR
TIGR Gain: $ 0.11 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_QP
TIGR Gain: $ 0.12 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_TR_IR3
TIGR Gain: $ 0.14 Win %: 66.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_IR3
TIGR Gain: $ 0.17 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_AL
TIGR Gain: $ 0.19 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_IT_QP_DB5
TIGR Gain: $ 0.19 Win %: 25.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_LI
TIGR Gain: $ 0.19 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_AL
TIGR Gain: $ 0.19 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV_AL
TIGR Gain: $ 0.19 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM
TIGR Gain: $ 0.21 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_TR
TIGR Gain: $ 0.21 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_TR_DB5
TIGR Gain: $ 0.26 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_VI
TIGR Gain: $ 0.29 Win %: 66.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV
TIGR Gain: $ 0.29 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_AL
TIGR Gain: $ 0.29 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_DB30
TIGR Gain: $ 0.29 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV
TIGR Gain: $ 0.3 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_HM_TR
TIGR Gain: $ 0.3 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_HM
TIGR Gain: $ 0.31 Win %: 33.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_LI
TIGR Gain: $ 0.32 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM
TIGR Gain: $ 0.32 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_TR
TIGR Gain: $ 0.34 Win %: 66.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AV
TIGR Gain: $ 0.35 Win %: 60.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_TR
TIGR Gain: $ 0.36 Win %: 33.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_AV
TIGR Gain: $ 0.4 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_TR_IR5
TIGR Gain: $ 0.43 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_HM_TR
TIGR Gain: $ 0.44 Win %: 66.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_IT_QL_DB3
TIGR Gain: $ 0.45 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_TR
TIGR Gain: $ 0.46 Win %: 40.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_TR_IR5
TIGR Gain: $ 0.46 Win %: 66.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AL
TIGR Gain: $ 0.48 Win %: 66.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_HM_AV_DB1
TIGR Gain: $ 0.49 Win %: 66.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_HM_AV
TIGR Gain: $ 0.52 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_QL
TIGR Gain: $ 0.52 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AV
TIGR Gain: $ 0.55 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_TR_IR5
TIGR Gain: $ 0.56 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_IT_QP
TIGR Gain: $ 0.56 Win %: 83.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_TR_DB5
TIGR Gain: $ 0.57 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_TR
TIGR Gain: $ 0.59 Win %: 40.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_IR5
TIGR Gain: $ 0.59 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_TR
TIGR Gain: $ 0.59 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_TR_DB5
TIGR Gain: $ 0.6 Win %: 66.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_IT_QP
TIGR Gain: $ 0.63 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_TR
TIGR Gain: $ 0.63 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_TR_DB5
TIGR Gain: $ 0.63 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_TR_DB5
TIGR Gain: $ 0.64 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_LI
TIGR Gain: $ 0.66 Win %: 66.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_TR
TIGR Gain: $ 0.67 Win %: 66.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_IT_QL_DB5
TIGR Gain: $ 0.67 Win %: 80.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_QP
TIGR Gain: $ 0.69 Win %: 66.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_HM_QP
TIGR Gain: $ 0.71 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_TR_DB5
TIGR Gain: $ 0.73 Win %: 66.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_QP
TIGR Gain: $ 0.73 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AL
TIGR Gain: $ 0.75 Win %: 75.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_RV_AL
TIGR Gain: $ 0.76 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_RV
TIGR Gain: $ 0.79 Win %: 25.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_SS
TIGR Gain: $ 0.82 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB2_OS2_CB1_CS1_RV_AV
TIGR Gain: $ 0.82 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_DB30
TIGR Gain: $ 0.84 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR_IR5
TIGR Gain: $ 0.87 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV
TIGR Gain: $ 0.89 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_AL
TIGR Gain: $ 0.9 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR_QP
TIGR Gain: $ 0.91 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_DB30
TIGR Gain: $ 0.91 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_TR
TIGR Gain: $ 0.91 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_IR5
TIGR Gain: $ 0.92 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_HM_TR
TIGR Gain: $ 0.92 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV
TIGR Gain: $ 0.97 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR
TIGR Gain: $ 0.99 Win %: 75.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_AV
TIGR Gain: $ 1.06 Win %: 100.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM_AV
TIGR Gain: $ 1.1 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_TR_IR5
TIGR Gain: $ 1.11 Win %: 75.00 in 4 days with algo TB1_HL_QM_OB4_OS4_CB1_CS1_HM_AV
TIGR Gain: $ 1.12 Win %: 75.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_AV
TIGR Gain: $ 1.15 Win %: 75.00 in 4 days with algo TB3_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AV
TIGR Gain: $ 1.2 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_QP_DB5
TIGR Gain: $ 1.27 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3
TIGR Gain: $ 1.29 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_HM_AV
TIGR Gain: $ 1.29 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_TR_DB5
TIGR Gain: $ 1.3 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_IT
TIGR Gain: $ 1.3 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_IT_QL
TIGR Gain: $ 1.3 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_IT_QL_DB5
TIGR Gain: $ 1.32 Win %: 80.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV
TIGR Gain: $ 1.37 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_LI
TIGR Gain: $ 1.38 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_AV
TIGR Gain: $ 1.41 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_TR
TIGR Gain: $ 1.49 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_SS
TIGR Gain: $ 1.49 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_QL
TIGR Gain: $ 1.51 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM_TR
TIGR Gain: $ 1.53 Win %: 60.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM
TIGR Gain: $ 1.53 Win %: 80.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AL
TIGR Gain: $ 1.58 Win %: 50.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_RV_AV
TIGR Gain: $ 1.67 Win %: 66.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_VI
TIGR Gain: $ 1.67 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_HM_AV
TIGR Gain: $ 1.68 Win %: 80.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_QP
TIGR Gain: $ 1.75 Win %: 100.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_IT
TIGR Gain: $ 1.75 Win %: 100.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_IT_QL
TIGR Gain: $ 1.75 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_AV
TIGR Gain: $ 1.85 Win %: 100.00 in 3 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM_AV_DB5
TIGR Gain: $ 1.91 Win %: 66.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_AV
TIGR Gain: $ 1.92 Win %: 83.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_TR
TIGR Gain: $ 1.93 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_DB30
TIGR Gain: $ 2 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_QL
TIGR Gain: $ 2.02 Win %: 66.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM
TIGR Gain: $ 2.03 Win %: 80.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV
TIGR Gain: $ 2.08 Win %: 100.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_DB10
TIGR Gain: $ 2.08 Win %: 50.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_HM_AV
TIGR Gain: $ 2.13 Win %: 80.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_QL
TIGR Gain: $ 2.2 Win %: 100.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_QL
TIGR Gain: $ 2.2 Win %: 100.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_SS
TIGR Gain: $ 2.22 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_QL
TIGR Gain: $ 2.22 Win %: 80.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_VI
TIGR Gain: $ 2.22 Win %: 83.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_QP
TIGR Gain: $ 2.22 Win %: 83.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR
TIGR Gain: $ 2.25 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_DB30
TIGR Gain: $ 2.28 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_AL
TIGR Gain: $ 2.3 Win %: 100.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_HM
TIGR Gain: $ 2.31 Win %: 100.00 in 4 days with algo TB1_HL_HI_QM_OB4_OS4_CB5_CS5_VI
TIGR Gain: $ 2.39 Win %: 100.00 in 3 days with algo TB3_HL_LO_QM_OB2_OS2_CB1_CS1_RV
TIGR Gain: $ 2.46 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4
TIGR Gain: $ 2.51 Win %: 100.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_TR
TIGR Gain: $ 2.51 Win %: 100.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_TR_DB5
TIGR Gain: $ 2.52 Win %: 80.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_AV
TIGR Gain: $ 2.61 Win %: 80.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_RV_AV
TIGR Gain: $ 2.62 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_DB30
TIGR Gain: $ 2.69 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_QL
TIGR Gain: $ 2.72 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV_AV
TIGR Gain: $ 2.77 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_RV
TIGR Gain: $ 2.81 Win %: 100.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_TR
TIGR Gain: $ 2.87 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM
TIGR Gain: $ 2.9 Win %: 60.00 in 5 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_AV
TIGR Gain: $ 3.13 Win %: 100.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_SS
TIGR Gain: $ 3.23 Win %: 83.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_QL
TIGR Gain: $ 3.26 Win %: 100.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_LI
TIGR Gain: $ 3.28 Win %: 100.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_SS
TIGR Gain: $ 3.42 Win %: 100.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_LI
TIGR Gain: $ 3.55 Win %: 100.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_HM_AV
TIGR Gain: $ 3.58 Win %: 66.00 in 6 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_AV
TIGR Gain: $ 3.61 Win %: 100.00 in 5 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_HM_AV
TIGR Gain: $ 3.63 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_AV
TIGR Gain: $ 3.63 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_AV_DB5
TIGR Gain: $ 3.77 Win %: 100.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_AL
TIGR Gain: $ 3.77 Win %: 60.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_AV
TIGR Gain: $ 3.78 Win %: 100.00 in 5 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_DB30
TIGR Gain: $ 4.1 Win %: 100.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_HM_AV
TIGR Gain: $ 4.1 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB4_CS4_AV
TIGR Gain: $ 4.26 Win %: 66.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_HM_AV
TIGR Gain: $ 4.27 Win %: 100.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_AL
TIGR Gain: $ 4.29 Win %: 83.00 in 6 days with algo TB1_HL_QM_OB4_OS4_CB3_CS3_AV
TIGR Gain: $ 4.52 Win %: 100.00 in 6 days with algo TB1_HL_HI_QM_OB1_OS1_CB4_CS4_DB30
TIGR Gain: $ 5.55112e-17 Win %: 66.00 in 3 days with algo TB5_HI_QM_OB1_OS1_CB1_CS1_VI
