Gain: $ -57.63 Win %: 43.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -53.91 Win %: 44.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -51.16 Win %: 46.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -44.4 Win %: 52.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_AV
Gain: $ -43.72 Win %: 45.00 in 90 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_AV
Gain: $ -38.31 Win %: 45.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -36.54 Win %: 45.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ -36.54 Win %: 45.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ -35.99 Win %: 53.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -35.26 Win %: 45.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ -35.26 Win %: 45.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ -35.12 Win %: 46.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -35.12 Win %: 46.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ -35.12 Win %: 46.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ -35.12 Win %: 46.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ -35.01 Win %: 46.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ -32.1 Win %: 49.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -32.1 Win %: 50.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ -31.52 Win %: 55.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -29.27 Win %: 50.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_TR_QP
Gain: $ -27.09 Win %: 52.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ -27.09 Win %: 53.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -26.97 Win %: 43.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ -26.86 Win %: 52.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ -26.41 Win %: 52.00 in 90 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_AL
Gain: $ -25.98 Win %: 54.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -25.51 Win %: 49.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ -25.44 Win %: 49.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ -25.22 Win %: 46.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ -24.38 Win %: 49.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ -23.49 Win %: 49.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -23.48 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -23.16 Win %: 50.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -22.88 Win %: 49.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ -22.73 Win %: 48.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ -22.72 Win %: 46.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -22.52 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ -22.45 Win %: 50.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ -22.38 Win %: 45.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -22.27 Win %: 49.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ -22.13 Win %: 57.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP
Gain: $ -21.97 Win %: 62.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -21.88 Win %: 50.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -21.87 Win %: 49.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ -21.87 Win %: 51.00 in 90 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_RV_AV
Gain: $ -21.81 Win %: 49.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ -21.59 Win %: 49.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -21.42 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ -21.18 Win %: 46.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -21.18 Win %: 46.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ -21.11 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -21.11 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -20.97 Win %: 54.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ -20.92 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -20.89 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -20.47 Win %: 46.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -20.47 Win %: 46.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ -20.19 Win %: 47.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -20.16 Win %: 58.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -20.05 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ -19.99 Win %: 49.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ -19.66 Win %: 50.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -19.58 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -19.57 Win %: 46.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ -19.57 Win %: 46.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ -19.39 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ -19.36 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ -19.16 Win %: 50.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -19.01 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -18.88 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ -18.88 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ -18.86 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -18.79 Win %: 45.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ -18.68 Win %: 49.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ -18.39 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -18.11 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -18.11 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -18.11 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -18.11 Win %: 56.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -18.11 Win %: 56.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -17.99 Win %: 56.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -17.48 Win %: 50.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ -17.14 Win %: 50.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ -16.99 Win %: 60.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ -16.98 Win %: 58.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -16.89 Win %: 57.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -16.71 Win %: 53.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ -16.71 Win %: 57.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -16.68 Win %: 50.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ -16.6 Win %: 52.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ -16.59 Win %: 46.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QL
Gain: $ -16.55 Win %: 50.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ -16.46 Win %: 52.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -16.31 Win %: 47.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ -16.31 Win %: 47.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ -16.19 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -16.04 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -15.68 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ -15.56 Win %: 55.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_QP
Gain: $ -15.47 Win %: 50.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -15.4 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -15.15 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -14.8 Win %: 53.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
Gain: $ -14.73 Win %: 51.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ -14.71 Win %: 50.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ -14.65 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
Gain: $ -14.65 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ -14.65 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
Gain: $ -14.62 Win %: 50.00 in 90 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_PA_AV
Gain: $ -14.6 Win %: 52.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -14.59 Win %: 54.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -14.55 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -14.2 Win %: 52.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ -14.12 Win %: 59.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -13.96 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -13.95 Win %: 52.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ -13.92 Win %: 62.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -13.87 Win %: 47.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -13.87 Win %: 47.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ -13.87 Win %: 47.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ -13.75 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -13.73 Win %: 53.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
Gain: $ -13.73 Win %: 53.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ -13.66 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ -13.51 Win %: 53.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ -13.04 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
Gain: $ -12.84 Win %: 54.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ -12.67 Win %: 48.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -12.67 Win %: 48.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ -12.67 Win %: 48.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ -12.64 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -12.61 Win %: 52.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ -12.55 Win %: 56.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM
Gain: $ -12.51 Win %: 54.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
Gain: $ -12.43 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -12.25 Win %: 47.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_PA_TR
Gain: $ -12.25 Win %: 58.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -12.14 Win %: 53.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ -11.98 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ -11.96 Win %: 56.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -11.93 Win %: 56.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ -11.72 Win %: 49.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ -11.71 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -11.71 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ -11.67 Win %: 54.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -11.33 Win %: 51.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_TR
Gain: $ -11.29 Win %: 52.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ -11.1 Win %: 58.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -10.96 Win %: 56.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ -10.84 Win %: 56.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -10.71 Win %: 55.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
Gain: $ -10.54 Win %: 53.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -10.52 Win %: 47.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ -10.43 Win %: 56.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -10.18 Win %: 57.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_TR
Gain: $ -9.74 Win %: 57.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -9.43 Win %: 57.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ -8.93 Win %: 48.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ -8.78 Win %: 57.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -8.6 Win %: 57.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ -8.56 Win %: 55.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_QP
Gain: $ -8.25 Win %: 53.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ -8.15 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ -8.05 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -8.02 Win %: 51.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_RV_TR
Gain: $ -7.81 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ -7.74 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ -7.54 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -7.45 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -7.42 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ -7.42 Win %: 51.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ -7.31 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ -7.23 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
Gain: $ -7.23 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
Gain: $ -7.14 Win %: 56.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ -7.02 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ -7.02 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ -6.73 Win %: 57.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ -6.65 Win %: 58.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ -6.55 Win %: 57.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AV
Gain: $ -5.94 Win %: 52.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ -5.92 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -5.49 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -5.49 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -5.42 Win %: 62.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_QP
Gain: $ -5.32 Win %: 54.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ -5.13 Win %: 57.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR
Gain: $ -5.1 Win %: 47.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -5.01 Win %: 54.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -4.85 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -4.69 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -4.69 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -4.62 Win %: 98.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ -4.59 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -4.59 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ -4.39 Win %: 50.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -4.39 Win %: 50.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ -4.27 Win %: 47.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ -4.27 Win %: 47.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ -4.02 Win %: 61.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -3.95 Win %: 53.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ -3.78 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -3.78 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ -3.56 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -3.48 Win %: 53.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -3.48 Win %: 53.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -3.4 Win %: 50.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ -3.37 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ -3.35 Win %: 48.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ -3.35 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
Gain: $ -3.18 Win %: 58.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ -3.13 Win %: 48.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -3.11 Win %: 52.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ -2.9 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ -2.56 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ -2.49 Win %: 52.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ -2.46 Win %: 49.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ -2.36 Win %: 45.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_VI
Gain: $ -2.18 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ -2.18 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ -2.04 Win %: 51.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ -1.93 Win %: 55.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ -1.59 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ -1.59 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ -1.45 Win %: 51.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ -1.42 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ -1.37 Win %: 98.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ -1.28 Win %: 52.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_DB6
Gain: $ -1.12 Win %: 55.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ -1.03 Win %: 99.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ -0.99 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -0.91 Win %: 54.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ -0.89 Win %: 54.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_LI
Gain: $ -0.65 Win %: 59.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_SS
Gain: $ -0.64 Win %: 73.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -0.46 Win %: 64.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -0.43 Win %: 53.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ -0.43 Win %: 53.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ -0.41 Win %: 55.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ -0.2 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ -0.1 Win %: 51.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_LI
Gain: $ -0.1 Win %: 99.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB
TQQQ Gain: $ -0.03 Win %: 56.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_TR_QP
TQQQ Gain: $ -0.06 Win %: 64.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_VI
TQQQ Gain: $ -0.09 Win %: 54.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
TQQQ Gain: $ -0.57 Win %: 50.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ -0.63 Win %: 54.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
TQQQ Gain: $ -0.83 Win %: 49.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ -1.02 Win %: 51.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ -1.04 Win %: 64.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ -1.11 Win %: 48.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV
TQQQ Gain: $ -1.15 Win %: 60.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
TQQQ Gain: $ -1.31 Win %: 62.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_VI
TQQQ Gain: $ -1.41 Win %: 53.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
TQQQ Gain: $ -1.41 Win %: 53.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
TQQQ Gain: $ -1.41 Win %: 57.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
TQQQ Gain: $ -1.57 Win %: 52.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ -1.57 Win %: 52.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ -1.7 Win %: 60.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
TQQQ Gain: $ -1.9 Win %: 49.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
TQQQ Gain: $ -1.91 Win %: 51.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_TR_DB1
TQQQ Gain: $ -1.93 Win %: 51.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR
TQQQ Gain: $ -1.93 Win %: 51.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB1
TQQQ Gain: $ -10.02 Win %: 69.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
TQQQ Gain: $ -10.11 Win %: 84.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
TQQQ Gain: $ -10.14 Win %: 51.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR
TQQQ Gain: $ -10.19 Win %: 50.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -10.42 Win %: 51.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -10.5 Win %: 51.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -10.55 Win %: 51.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ -10.57 Win %: 52.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM_QP
TQQQ Gain: $ -10.63 Win %: 52.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_AV
TQQQ Gain: $ -10.74 Win %: 69.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
TQQQ Gain: $ -10.79 Win %: 54.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
TQQQ Gain: $ -10.83 Win %: 49.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ -11.11 Win %: 58.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ -11.15 Win %: 52.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_HM_QP
TQQQ Gain: $ -11.18 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ -11.18 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ -11.34 Win %: 69.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
TQQQ Gain: $ -11.35 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ -11.35 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ -11.35 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
TQQQ Gain: $ -11.69 Win %: 50.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ -11.7 Win %: 53.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
TQQQ Gain: $ -11.7 Win %: 53.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
TQQQ Gain: $ -11.85 Win %: 68.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
TQQQ Gain: $ -12.69 Win %: 55.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ -12.69 Win %: 55.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
TQQQ Gain: $ -12.87 Win %: 50.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ -12.91 Win %: 51.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ -13.05 Win %: 83.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QP
TQQQ Gain: $ -13.29 Win %: 50.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AV
TQQQ Gain: $ -13.37 Win %: 44.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_IR1
TQQQ Gain: $ -13.9 Win %: 50.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ -13.9 Win %: 50.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ -14.04 Win %: 55.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
TQQQ Gain: $ -14.08 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ -14.14 Win %: 56.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ -14.22 Win %: 50.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ -14.54 Win %: 53.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
TQQQ Gain: $ -14.54 Win %: 53.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ -14.54 Win %: 53.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
TQQQ Gain: $ -14.67 Win %: 50.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_AV
TQQQ Gain: $ -14.78 Win %: 50.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_AV
TQQQ Gain: $ -15.36 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ -15.36 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ -15.49 Win %: 50.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -15.59 Win %: 51.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_TR
TQQQ Gain: $ -15.68 Win %: 51.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ -15.68 Win %: 51.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
TQQQ Gain: $ -15.94 Win %: 51.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -16.7 Win %: 50.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
TQQQ Gain: $ -16.73 Win %: 51.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ -16.82 Win %: 51.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
TQQQ Gain: $ -16.87 Win %: 48.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -16.89 Win %: 51.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
TQQQ Gain: $ -16.94 Win %: 52.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ -16.94 Win %: 52.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ -16.94 Win %: 52.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
TQQQ Gain: $ -17.27 Win %: 50.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -17.37 Win %: 50.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR
TQQQ Gain: $ -17.47 Win %: 51.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_HM_TR
TQQQ Gain: $ -17.67 Win %: 50.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -18.08 Win %: 51.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -18.08 Win %: 51.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
TQQQ Gain: $ -18.5 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ -18.5 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ -18.5 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
TQQQ Gain: $ -18.54 Win %: 47.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
TQQQ Gain: $ -18.61 Win %: 50.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_TR
TQQQ Gain: $ -18.75 Win %: 48.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ -19.04 Win %: 55.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_QP_IR3
TQQQ Gain: $ -19.04 Win %: 55.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_QP_IR3
TQQQ Gain: $ -19.14 Win %: 51.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ -19.19 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
TQQQ Gain: $ -19.23 Win %: 49.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -19.25 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_TR
TQQQ Gain: $ -19.46 Win %: 49.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ -19.72 Win %: 51.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
TQQQ Gain: $ -19.85 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_QP
TQQQ Gain: $ -19.86 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_QP
TQQQ Gain: $ -19.93 Win %: 49.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_QP
TQQQ Gain: $ -19.96 Win %: 48.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_DB6
TQQQ Gain: $ -19.99 Win %: 50.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM_TR
TQQQ Gain: $ -2.1 Win %: 54.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -2.21 Win %: 49.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV
TQQQ Gain: $ -2.23 Win %: 51.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_TR
TQQQ Gain: $ -2.24 Win %: 63.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ -2.3 Win %: 59.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
TQQQ Gain: $ -2.3 Win %: 59.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
TQQQ Gain: $ -2.44 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV
TQQQ Gain: $ -2.49 Win %: 49.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ -2.55 Win %: 49.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ -2.61 Win %: 55.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ -2.61 Win %: 55.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ -2.61 Win %: 55.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ -2.62 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
TQQQ Gain: $ -2.64 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ -2.64 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ -2.64 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
TQQQ Gain: $ -2.65 Win %: 54.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
TQQQ Gain: $ -2.68 Win %: 56.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ -2.75 Win %: 97.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_DB15
TQQQ Gain: $ -2.85 Win %: 48.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV
TQQQ Gain: $ -2.87 Win %: 62.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_VI
TQQQ Gain: $ -2.92 Win %: 50.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ -20.07 Win %: 44.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QL
TQQQ Gain: $ -20.22 Win %: 47.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -20.25 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
TQQQ Gain: $ -20.29 Win %: 51.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_QP
TQQQ Gain: $ -20.31 Win %: 48.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ -20.37 Win %: 52.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_QP_IR1
TQQQ Gain: $ -20.42 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
TQQQ Gain: $ -20.46 Win %: 51.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ -20.48 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
TQQQ Gain: $ -20.48 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
TQQQ Gain: $ -20.56 Win %: 48.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ -20.62 Win %: 47.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -20.66 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_HM
TQQQ Gain: $ -20.9 Win %: 55.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
TQQQ Gain: $ -21.07 Win %: 46.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ -21.07 Win %: 46.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ -21.07 Win %: 46.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
TQQQ Gain: $ -21.58 Win %: 47.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_DB6
TQQQ Gain: $ -21.61 Win %: 47.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -21.64 Win %: 53.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_QP_IR1
TQQQ Gain: $ -21.69 Win %: 43.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_QL
TQQQ Gain: $ -21.89 Win %: 48.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
TQQQ Gain: $ -22.03 Win %: 79.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
TQQQ Gain: $ -22.09 Win %: 50.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -22.15 Win %: 46.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
TQQQ Gain: $ -22.4 Win %: 47.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_DB6
TQQQ Gain: $ -22.41 Win %: 46.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
TQQQ Gain: $ -22.55 Win %: 50.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM
TQQQ Gain: $ -22.62 Win %: 49.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ -22.62 Win %: 49.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
TQQQ Gain: $ -22.75 Win %: 46.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -22.95 Win %: 45.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ -23.38 Win %: 47.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -23.79 Win %: 49.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QP
TQQQ Gain: $ -23.79 Win %: 49.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QP
TQQQ Gain: $ -23.88 Win %: 49.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -23.91 Win %: 49.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -23.98 Win %: 47.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -24.07 Win %: 79.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QP
TQQQ Gain: $ -24.56 Win %: 49.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ -24.81 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -24.83 Win %: 54.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
TQQQ Gain: $ -25.02 Win %: 48.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ -25.02 Win %: 48.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
TQQQ Gain: $ -25.12 Win %: 48.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ -25.12 Win %: 48.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ -25.16 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ -25.16 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ -25.43 Win %: 48.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ -25.43 Win %: 51.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP_IR1
TQQQ Gain: $ -25.71 Win %: 49.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QP
TQQQ Gain: $ -25.87 Win %: 46.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -26.55 Win %: 50.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QP
TQQQ Gain: $ -26.76 Win %: 42.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_QL
TQQQ Gain: $ -27.33 Win %: 47.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -27.33 Win %: 47.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -27.56 Win %: 49.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
TQQQ Gain: $ -27.57 Win %: 50.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP
TQQQ Gain: $ -27.62 Win %: 51.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
TQQQ Gain: $ -28.15 Win %: 49.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM_AV
TQQQ Gain: $ -28.49 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_QP
TQQQ Gain: $ -28.78 Win %: 50.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_QP
TQQQ Gain: $ -3.26 Win %: 55.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -3.33 Win %: 56.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
TQQQ Gain: $ -3.6 Win %: 62.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ -3.69 Win %: 62.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ -3.77 Win %: 66.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR1
TQQQ Gain: $ -3.91 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ -3.94 Win %: 51.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
TQQQ Gain: $ -3.98 Win %: 54.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
TQQQ Gain: $ -32.34 Win %: 50.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
TQQQ Gain: $ -32.36 Win %: 47.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -32.36 Win %: 47.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -33.18 Win %: 51.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
TQQQ Gain: $ -33.88 Win %: 49.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ -33.91 Win %: 45.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
TQQQ Gain: $ -33.91 Win %: 45.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
TQQQ Gain: $ -33.96 Win %: 50.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
TQQQ Gain: $ -34.7 Win %: 46.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
TQQQ Gain: $ -34.91 Win %: 50.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_AV
TQQQ Gain: $ -35.26 Win %: 50.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_HM_AV
TQQQ Gain: $ -35.96 Win %: 49.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM_AV
TQQQ Gain: $ -36.69 Win %: 46.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM
TQQQ Gain: $ -37.03 Win %: 45.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -37.03 Win %: 45.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -37.03 Win %: 45.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
TQQQ Gain: $ -38.11 Win %: 44.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
TQQQ Gain: $ -38.37 Win %: 45.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_AV
TQQQ Gain: $ -39.23 Win %: 51.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ -39.23 Win %: 51.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ -4.08 Win %: 48.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ -4.08 Win %: 48.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ -4.08 Win %: 48.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ -4.08 Win %: 48.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ -4.08 Win %: 48.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
TQQQ Gain: $ -4.08 Win %: 48.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ -4.13 Win %: 55.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -4.14 Win %: 56.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -4.15 Win %: 65.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR1
TQQQ Gain: $ -4.28 Win %: 47.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV
TQQQ Gain: $ -4.28 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ -4.28 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ -4.28 Win %: 50.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
TQQQ Gain: $ -4.3 Win %: 56.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_AV
TQQQ Gain: $ -4.36 Win %: 55.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ -4.42 Win %: 51.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ -4.43 Win %: 50.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AL
TQQQ Gain: $ -4.47 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_AL
TQQQ Gain: $ -4.47 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_AL
TQQQ Gain: $ -4.52 Win %: 61.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ -4.54 Win %: 56.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP_IR1
TQQQ Gain: $ -4.54 Win %: 65.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR1
TQQQ Gain: $ -4.56 Win %: 52.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ -4.56 Win %: 52.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ -4.56 Win %: 52.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
TQQQ Gain: $ -4.82 Win %: 62.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ -4.98 Win %: 62.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ -4.99 Win %: 47.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ -43.3 Win %: 45.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_AV
TQQQ Gain: $ -5.04 Win %: 54.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ -5.22 Win %: 55.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -5.26 Win %: 65.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR1
TQQQ Gain: $ -5.26 Win %: 65.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR1
TQQQ Gain: $ -5.33 Win %: 49.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ -5.44 Win %: 56.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
TQQQ Gain: $ -5.52 Win %: 47.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ -5.52 Win %: 57.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
TQQQ Gain: $ -5.53 Win %: 53.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ -5.54 Win %: 51.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ -5.62 Win %: 48.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ -5.64 Win %: 52.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -5.72 Win %: 55.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ -5.76 Win %: 51.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
TQQQ Gain: $ -5.81 Win %: 55.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ -5.89 Win %: 54.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -5.92 Win %: 56.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_QP_IR1
TQQQ Gain: $ -5.98 Win %: 48.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM
TQQQ Gain: $ -55.04 Win %: 42.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_AV
TQQQ Gain: $ -56.42 Win %: 42.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_HM_AV
TQQQ Gain: $ -56.64 Win %: 42.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM_AV
TQQQ Gain: $ -6.15 Win %: 50.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
TQQQ Gain: $ -6.33 Win %: 48.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ -6.38 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -6.38 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ -6.43 Win %: 52.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_AV
TQQQ Gain: $ -6.43 Win %: 52.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_AV
TQQQ Gain: $ -6.62 Win %: 55.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_QP_IR1
TQQQ Gain: $ -6.8 Win %: 51.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_SS
TQQQ Gain: $ -6.84 Win %: 55.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ -6.89 Win %: 55.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ -6.96 Win %: 52.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ -6.96 Win %: 52.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
TQQQ Gain: $ -7.32 Win %: 47.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
TQQQ Gain: $ -7.44 Win %: 55.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_QP
TQQQ Gain: $ -7.45 Win %: 51.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -7.6 Win %: 51.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_SS
TQQQ Gain: $ -7.64 Win %: 55.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ -8.1 Win %: 51.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -8.1 Win %: 51.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_AV
TQQQ Gain: $ -8.18 Win %: 53.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
TQQQ Gain: $ -8.2 Win %: 55.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ -8.82 Win %: 55.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_TR_QP
TQQQ Gain: $ -9.02 Win %: 51.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_SS
TQQQ Gain: $ -9.06 Win %: 53.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_QP
TQQQ Gain: $ -9.17 Win %: 70.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
TQQQ Gain: $ -9.56 Win %: 53.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_AV
TQQQ Gain: $ 0 Win %: 100.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 0 Win %: 100.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ 0 Win %: 100.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 0 Win %: 100.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 0 Win %: 100.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 0 Win %: 100.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ 0.08 Win %: 50.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV
TQQQ Gain: $ 0.15 Win %: 64.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_VI
TQQQ Gain: $ 0.23 Win %: 51.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 0.51 Win %: 45.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 0.65 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ 0.82 Win %: 50.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV
TQQQ Gain: $ 0.9 Win %: 48.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_VI
TQQQ Gain: $ 1.2 Win %: 55.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ 1.2 Win %: 55.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ 1.21 Win %: 56.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_QP_IR1
TQQQ Gain: $ 1.24 Win %: 57.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 1.31 Win %: 50.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 1.31 Win %: 50.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 1.39 Win %: 49.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 1.51 Win %: 52.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR_DB1
TQQQ Gain: $ 1.55 Win %: 49.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 1.55 Win %: 49.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 1.56 Win %: 51.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 1.59 Win %: 50.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 1.87 Win %: 55.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ 1.87 Win %: 55.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ 1.95 Win %: 56.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 10.02 Win %: 51.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 10.05 Win %: 47.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR1
TQQQ Gain: $ 10.07 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 10.07 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 10.11 Win %: 54.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
TQQQ Gain: $ 10.14 Win %: 53.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 10.15 Win %: 52.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 10.16 Win %: 48.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ 10.16 Win %: 48.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ 10.16 Win %: 58.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 10.2 Win %: 56.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ 10.24 Win %: 56.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_LI
TQQQ Gain: $ 10.32 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_TR_QP
TQQQ Gain: $ 10.32 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_TR_QP
TQQQ Gain: $ 10.34 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 10.36 Win %: 59.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_IT_QL
TQQQ Gain: $ 10.36 Win %: 59.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_IT_QL
TQQQ Gain: $ 10.43 Win %: 52.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 10.43 Win %: 52.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 10.47 Win %: 48.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 10.57 Win %: 61.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_QP
TQQQ Gain: $ 10.57 Win %: 61.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_QP
TQQQ Gain: $ 10.61 Win %: 49.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
TQQQ Gain: $ 10.87 Win %: 65.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
TQQQ Gain: $ 10.87 Win %: 65.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ 10.87 Win %: 65.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR1
TQQQ Gain: $ 10.89 Win %: 51.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 10.96 Win %: 62.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_QP
TQQQ Gain: $ 104.57 Win %: 53.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR1
TQQQ Gain: $ 11.02 Win %: 60.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
TQQQ Gain: $ 11.11 Win %: 55.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 11.19 Win %: 57.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 11.21 Win %: 63.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 11.22 Win %: 87.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QP
TQQQ Gain: $ 11.23 Win %: 52.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
TQQQ Gain: $ 11.25 Win %: 51.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 11.25 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 11.26 Win %: 53.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 11.27 Win %: 50.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
TQQQ Gain: $ 11.28 Win %: 57.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 11.35 Win %: 49.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 11.5 Win %: 47.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 11.65 Win %: 49.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 11.76 Win %: 60.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
TQQQ Gain: $ 11.86 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 11.87 Win %: 47.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 11.87 Win %: 62.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP
TQQQ Gain: $ 11.88 Win %: 47.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 11.95 Win %: 50.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
TQQQ Gain: $ 11.98 Win %: 49.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 11.98 Win %: 55.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
TQQQ Gain: $ 12.06 Win %: 51.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 12.06 Win %: 52.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 12.35 Win %: 67.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ 12.35 Win %: 67.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ 12.35 Win %: 67.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
TQQQ Gain: $ 12.35 Win %: 68.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
TQQQ Gain: $ 12.39 Win %: 65.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ 12.39 Win %: 65.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR1
TQQQ Gain: $ 12.45 Win %: 53.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 12.45 Win %: 55.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
TQQQ Gain: $ 12.57 Win %: 52.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 12.57 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 12.6 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 12.62 Win %: 57.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ 12.62 Win %: 57.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ 12.67 Win %: 52.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 12.73 Win %: 61.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
TQQQ Gain: $ 12.73 Win %: 61.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
TQQQ Gain: $ 12.83 Win %: 51.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 12.98 Win %: 50.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
TQQQ Gain: $ 12.98 Win %: 50.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
TQQQ Gain: $ 122.86 Win %: 55.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR1
TQQQ Gain: $ 123.29 Win %: 55.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ 123.36 Win %: 56.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 123.87 Win %: 56.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ 13.05 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 13.5 Win %: 60.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR1
TQQQ Gain: $ 13.5 Win %: 87.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QP
TQQQ Gain: $ 13.53 Win %: 61.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
TQQQ Gain: $ 13.75 Win %: 52.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 13.78 Win %: 52.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 13.8 Win %: 47.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 131.63 Win %: 59.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 133.77 Win %: 56.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 14.03 Win %: 50.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM_TR
TQQQ Gain: $ 14.16 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_TR
TQQQ Gain: $ 14.17 Win %: 52.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 14.21 Win %: 49.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 14.21 Win %: 55.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_HM_QP
TQQQ Gain: $ 14.22 Win %: 51.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
TQQQ Gain: $ 14.22 Win %: 51.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
TQQQ Gain: $ 14.25 Win %: 60.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR1
TQQQ Gain: $ 14.3 Win %: 50.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM_TR
TQQQ Gain: $ 14.37 Win %: 54.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 14.39 Win %: 49.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 14.46 Win %: 50.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 14.48 Win %: 48.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 14.5 Win %: 60.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR1
TQQQ Gain: $ 14.65 Win %: 47.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 14.65 Win %: 47.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 14.65 Win %: 50.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_IR1
TQQQ Gain: $ 14.76 Win %: 50.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 14.78 Win %: 56.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 14.8 Win %: 49.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 14.92 Win %: 55.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_QP
TQQQ Gain: $ 146.31 Win %: 62.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 148.38 Win %: 60.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 15.11 Win %: 51.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 15.19 Win %: 60.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR1
TQQQ Gain: $ 15.19 Win %: 60.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR1
TQQQ Gain: $ 15.28 Win %: 68.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ 15.32 Win %: 63.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_VI
TQQQ Gain: $ 15.32 Win %: 63.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_VI
TQQQ Gain: $ 15.39 Win %: 50.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 15.43 Win %: 52.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
TQQQ Gain: $ 15.43 Win %: 52.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
TQQQ Gain: $ 15.45 Win %: 56.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM_QP
TQQQ Gain: $ 15.46 Win %: 54.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AL
TQQQ Gain: $ 15.98 Win %: 51.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
TQQQ Gain: $ 153.3 Win %: 58.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 155.92 Win %: 57.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 159.56 Win %: 60.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 16.24 Win %: 64.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_VI
TQQQ Gain: $ 16.26 Win %: 54.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 16.35 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 16.35 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 16.54 Win %: 50.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 16.6 Win %: 49.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ 16.63 Win %: 49.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 16.81 Win %: 48.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 166.86 Win %: 62.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 17.02 Win %: 50.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 17.17 Win %: 52.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 17.18 Win %: 50.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
TQQQ Gain: $ 17.18 Win %: 50.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
TQQQ Gain: $ 17.33 Win %: 50.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 17.55 Win %: 50.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_IR1
TQQQ Gain: $ 17.61 Win %: 53.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_AL
TQQQ Gain: $ 17.62 Win %: 53.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 17.62 Win %: 53.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 17.72 Win %: 48.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 17.75 Win %: 49.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ 17.83 Win %: 54.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 17.97 Win %: 50.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR_DB3
TQQQ Gain: $ 178.79 Win %: 66.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP_IR4
TQQQ Gain: $ 18.07 Win %: 51.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 18.07 Win %: 51.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 18.08 Win %: 54.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
TQQQ Gain: $ 18.09 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_IR1
TQQQ Gain: $ 18.67 Win %: 50.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 18.82 Win %: 48.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ 181.76 Win %: 63.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 19.01 Win %: 54.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 19.04 Win %: 48.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 19.07 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 19.26 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 19.41 Win %: 51.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 19.51 Win %: 54.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 19.51 Win %: 54.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 19.53 Win %: 61.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 19.6 Win %: 55.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_AL
TQQQ Gain: $ 19.6 Win %: 61.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 19.65 Win %: 47.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 19.65 Win %: 47.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 19.96 Win %: 53.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR
TQQQ Gain: $ 2.07 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_TR_IR1
TQQQ Gain: $ 2.11 Win %: 56.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 2.56 Win %: 58.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 2.74 Win %: 64.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ 2.78 Win %: 52.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
TQQQ Gain: $ 2.87 Win %: 54.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR1
TQQQ Gain: $ 2.93 Win %: 49.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_TR_IR1
TQQQ Gain: $ 20.11 Win %: 61.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 20.47 Win %: 51.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ 20.48 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 20.48 Win %: 64.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 20.62 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_QP
TQQQ Gain: $ 20.69 Win %: 61.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 20.71 Win %: 56.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ 20.78 Win %: 55.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_SS
TQQQ Gain: $ 20.78 Win %: 55.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_SS
TQQQ Gain: $ 20.81 Win %: 63.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 20.89 Win %: 56.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_SS
TQQQ Gain: $ 20.92 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 20.97 Win %: 62.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 21.04 Win %: 55.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 21.16 Win %: 49.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ 21.34 Win %: 59.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 21.36 Win %: 55.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_SS
TQQQ Gain: $ 21.42 Win %: 55.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 21.42 Win %: 55.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 21.53 Win %: 52.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 21.53 Win %: 52.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 21.6 Win %: 59.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 21.62 Win %: 58.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR3
TQQQ Gain: $ 21.63 Win %: 55.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ 21.72 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 21.81 Win %: 53.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_AL
TQQQ Gain: $ 21.81 Win %: 53.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_AL
TQQQ Gain: $ 22.05 Win %: 52.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_DB6
TQQQ Gain: $ 22.13 Win %: 62.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 22.14 Win %: 56.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
TQQQ Gain: $ 22.15 Win %: 56.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM_QP
TQQQ Gain: $ 22.16 Win %: 52.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_DB6
TQQQ Gain: $ 22.2 Win %: 59.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 22.22 Win %: 50.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ 22.44 Win %: 53.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR
TQQQ Gain: $ 22.61 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 22.61 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 22.61 Win %: 54.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_TR
TQQQ Gain: $ 22.63 Win %: 52.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_DB6
TQQQ Gain: $ 22.82 Win %: 55.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_IR4
TQQQ Gain: $ 22.95 Win %: 57.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 23.14 Win %: 55.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_LI
TQQQ Gain: $ 23.22 Win %: 58.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 23.34 Win %: 55.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR
TQQQ Gain: $ 23.38 Win %: 54.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_TR
TQQQ Gain: $ 23.55 Win %: 58.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 24.04 Win %: 57.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
TQQQ Gain: $ 24.08 Win %: 61.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 24.12 Win %: 51.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_QL
TQQQ Gain: $ 24.12 Win %: 51.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_QL
TQQQ Gain: $ 24.23 Win %: 52.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_QL
TQQQ Gain: $ 24.33 Win %: 60.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 24.55 Win %: 55.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 24.57 Win %: 56.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 24.58 Win %: 53.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QL
TQQQ Gain: $ 24.62 Win %: 49.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_TR
TQQQ Gain: $ 24.62 Win %: 49.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_TR_DB1
TQQQ Gain: $ 24.62 Win %: 52.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
TQQQ Gain: $ 24.63 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 24.7 Win %: 51.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QL
TQQQ Gain: $ 24.81 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
TQQQ Gain: $ 24.88 Win %: 52.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR1
TQQQ Gain: $ 24.95 Win %: 52.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_DB6
TQQQ Gain: $ 25.06 Win %: 56.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 25.08 Win %: 57.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
TQQQ Gain: $ 25.1 Win %: 58.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 25.12 Win %: 55.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 25.18 Win %: 55.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 25.31 Win %: 49.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR
TQQQ Gain: $ 25.31 Win %: 49.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR_DB1
TQQQ Gain: $ 25.31 Win %: 55.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
TQQQ Gain: $ 25.32 Win %: 56.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
TQQQ Gain: $ 25.48 Win %: 57.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
TQQQ Gain: $ 25.55 Win %: 55.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 25.55 Win %: 55.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
TQQQ Gain: $ 25.58 Win %: 56.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 25.81 Win %: 55.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 25.87 Win %: 58.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
TQQQ Gain: $ 25.91 Win %: 53.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 26.04 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 26.05 Win %: 52.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 26.05 Win %: 56.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ 26.14 Win %: 55.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 26.25 Win %: 53.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QL
TQQQ Gain: $ 26.31 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 26.4 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 26.4 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 26.47 Win %: 54.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ 26.61 Win %: 57.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 26.62 Win %: 58.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR3
TQQQ Gain: $ 26.69 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 26.69 Win %: 54.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
TQQQ Gain: $ 26.69 Win %: 60.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_QP
TQQQ Gain: $ 26.82 Win %: 55.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
TQQQ Gain: $ 26.84 Win %: 54.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
TQQQ Gain: $ 26.89 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 26.89 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 26.95 Win %: 56.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ 26.97 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 26.97 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 27.06 Win %: 59.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
TQQQ Gain: $ 27.07 Win %: 56.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 27.15 Win %: 54.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_TR
TQQQ Gain: $ 27.19 Win %: 58.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
TQQQ Gain: $ 27.22 Win %: 63.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_IT
TQQQ Gain: $ 27.22 Win %: 63.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_IT
TQQQ Gain: $ 27.25 Win %: 59.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_QP
TQQQ Gain: $ 27.27 Win %: 57.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
TQQQ Gain: $ 27.37 Win %: 57.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
TQQQ Gain: $ 27.42 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 27.42 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 27.45 Win %: 59.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
TQQQ Gain: $ 27.55 Win %: 58.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 27.55 Win %: 58.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
TQQQ Gain: $ 27.6 Win %: 58.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
TQQQ Gain: $ 27.63 Win %: 57.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 27.7 Win %: 54.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 27.8 Win %: 56.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 27.99 Win %: 52.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
TQQQ Gain: $ 27.99 Win %: 52.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR1
TQQQ Gain: $ 27.99 Win %: 52.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR1
TQQQ Gain: $ 27.99 Win %: 54.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR
TQQQ Gain: $ 28.07 Win %: 58.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
TQQQ Gain: $ 28.09 Win %: 54.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QL
TQQQ Gain: $ 28.14 Win %: 53.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
TQQQ Gain: $ 28.2 Win %: 52.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 28.2 Win %: 56.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ 28.21 Win %: 55.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 28.21 Win %: 55.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 28.28 Win %: 56.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ 28.4 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 28.42 Win %: 53.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AV
TQQQ Gain: $ 28.44 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 28.53 Win %: 53.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
TQQQ Gain: $ 28.56 Win %: 58.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR3
TQQQ Gain: $ 28.56 Win %: 58.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR3
TQQQ Gain: $ 28.62 Win %: 56.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 28.63 Win %: 58.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
TQQQ Gain: $ 28.64 Win %: 54.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_AV
TQQQ Gain: $ 28.72 Win %: 59.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
TQQQ Gain: $ 28.72 Win %: 59.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
TQQQ Gain: $ 28.74 Win %: 58.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_DB10
TQQQ Gain: $ 28.77 Win %: 56.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
TQQQ Gain: $ 28.8 Win %: 55.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_QL
TQQQ Gain: $ 28.82 Win %: 53.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_IR4
TQQQ Gain: $ 28.95 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 28.95 Win %: 60.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
TQQQ Gain: $ 28.97 Win %: 55.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AV
TQQQ Gain: $ 28.99 Win %: 53.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_IR4
TQQQ Gain: $ 29.1 Win %: 54.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 29.27 Win %: 56.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_IR4
TQQQ Gain: $ 29.39 Win %: 53.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_IR4
TQQQ Gain: $ 29.39 Win %: 53.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_IR4
TQQQ Gain: $ 29.4 Win %: 57.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
TQQQ Gain: $ 29.42 Win %: 54.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 29.42 Win %: 60.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
TQQQ Gain: $ 29.61 Win %: 56.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_VI
TQQQ Gain: $ 29.65 Win %: 55.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 29.66 Win %: 53.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 29.68 Win %: 49.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 29.69 Win %: 48.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 29.79 Win %: 49.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 29.83 Win %: 56.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 29.96 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
TQQQ Gain: $ 3.2 Win %: 47.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AL
TQQQ Gain: $ 3.38 Win %: 50.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 3.42 Win %: 50.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_IR1
TQQQ Gain: $ 3.56 Win %: 61.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
TQQQ Gain: $ 3.74 Win %: 48.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_VI
TQQQ Gain: $ 3.74 Win %: 48.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_VI
TQQQ Gain: $ 3.78 Win %: 47.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_AL
TQQQ Gain: $ 3.8 Win %: 50.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_VI
TQQQ Gain: $ 3.88 Win %: 57.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 30 Win %: 57.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
TQQQ Gain: $ 30 Win %: 59.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_DB6
TQQQ Gain: $ 30.01 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
TQQQ Gain: $ 30.15 Win %: 53.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 30.17 Win %: 54.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_IR4
TQQQ Gain: $ 30.22 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_QP
TQQQ Gain: $ 30.24 Win %: 54.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 30.25 Win %: 55.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
TQQQ Gain: $ 30.38 Win %: 56.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 30.39 Win %: 54.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
TQQQ Gain: $ 30.43 Win %: 57.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 30.5 Win %: 61.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL
TQQQ Gain: $ 30.57 Win %: 53.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 30.7 Win %: 57.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR
TQQQ Gain: $ 30.79 Win %: 53.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 30.8 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
TQQQ Gain: $ 30.8 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
TQQQ Gain: $ 30.84 Win %: 55.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 30.87 Win %: 53.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_IR4
TQQQ Gain: $ 30.99 Win %: 54.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
TQQQ Gain: $ 31.01 Win %: 59.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 31.02 Win %: 57.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 31.02 Win %: 57.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 31.03 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 31.19 Win %: 57.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
TQQQ Gain: $ 31.19 Win %: 57.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
TQQQ Gain: $ 31.22 Win %: 54.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 31.35 Win %: 60.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_SS
TQQQ Gain: $ 31.43 Win %: 59.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_QP
TQQQ Gain: $ 31.5 Win %: 57.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
TQQQ Gain: $ 31.5 Win %: 58.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 31.54 Win %: 58.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_DB10
TQQQ Gain: $ 31.54 Win %: 58.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_DB10
TQQQ Gain: $ 31.56 Win %: 53.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 31.72 Win %: 60.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
TQQQ Gain: $ 31.77 Win %: 56.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 31.77 Win %: 56.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 32.04 Win %: 50.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 32.11 Win %: 60.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 32.13 Win %: 51.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 32.17 Win %: 56.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_IR4
TQQQ Gain: $ 32.17 Win %: 56.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_IR4
TQQQ Gain: $ 32.19 Win %: 55.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR1
TQQQ Gain: $ 32.26 Win %: 54.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 32.31 Win %: 53.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 32.34 Win %: 50.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 32.36 Win %: 59.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_DB10
TQQQ Gain: $ 32.85 Win %: 52.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_DB15
TQQQ Gain: $ 32.9 Win %: 52.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 32.9 Win %: 56.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 32.92 Win %: 55.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 32.93 Win %: 56.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 32.93 Win %: 56.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 33.06 Win %: 61.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 33.06 Win %: 61.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 33.06 Win %: 61.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
TQQQ Gain: $ 33.13 Win %: 54.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 33.16 Win %: 55.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 33.19 Win %: 56.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 33.22 Win %: 59.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 33.26 Win %: 61.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IT_QL
TQQQ Gain: $ 33.29 Win %: 56.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 33.35 Win %: 54.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_IR4
TQQQ Gain: $ 33.35 Win %: 54.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR
TQQQ Gain: $ 33.41 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 33.43 Win %: 58.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QL
TQQQ Gain: $ 33.47 Win %: 57.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 33.49 Win %: 51.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 33.6 Win %: 54.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 33.71 Win %: 52.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
TQQQ Gain: $ 33.71 Win %: 52.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 33.77 Win %: 49.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 33.78 Win %: 51.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 33.8 Win %: 54.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM_TR
TQQQ Gain: $ 33.81 Win %: 50.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 33.81 Win %: 50.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 33.81 Win %: 50.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 33.91 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
TQQQ Gain: $ 33.98 Win %: 58.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 33.98 Win %: 58.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 34.01 Win %: 60.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 34.03 Win %: 50.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 34.24 Win %: 60.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 34.24 Win %: 60.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 34.27 Win %: 56.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 34.28 Win %: 57.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 34.32 Win %: 55.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 34.33 Win %: 54.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
TQQQ Gain: $ 34.36 Win %: 56.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 34.36 Win %: 56.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 34.46 Win %: 61.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
TQQQ Gain: $ 34.47 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
TQQQ Gain: $ 34.47 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 34.55 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 34.6 Win %: 56.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_IR4
TQQQ Gain: $ 34.7 Win %: 51.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 34.7 Win %: 52.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR3
TQQQ Gain: $ 34.77 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
TQQQ Gain: $ 34.79 Win %: 58.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 34.89 Win %: 57.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 34.94 Win %: 58.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 34.96 Win %: 52.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 35.12 Win %: 52.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 35.15 Win %: 56.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 35.15 Win %: 56.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 35.16 Win %: 60.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT
TQQQ Gain: $ 35.2 Win %: 50.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR
TQQQ Gain: $ 35.2 Win %: 50.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR
TQQQ Gain: $ 35.2 Win %: 50.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR_DB1
TQQQ Gain: $ 35.2 Win %: 50.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_TR_DB1
TQQQ Gain: $ 35.2 Win %: 58.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 35.22 Win %: 60.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 35.41 Win %: 61.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 35.71 Win %: 57.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 35.84 Win %: 54.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_HM_TR
TQQQ Gain: $ 35.9 Win %: 60.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 35.96 Win %: 55.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB6
TQQQ Gain: $ 35.97 Win %: 56.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 36 Win %: 54.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR3
TQQQ Gain: $ 36.02 Win %: 61.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT
TQQQ Gain: $ 36.07 Win %: 57.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 36.13 Win %: 52.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 36.21 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IT_QL
TQQQ Gain: $ 36.33 Win %: 52.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 36.4 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
TQQQ Gain: $ 36.4 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 36.62 Win %: 57.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_IR4
TQQQ Gain: $ 36.62 Win %: 57.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 36.65 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
TQQQ Gain: $ 36.69 Win %: 51.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 36.85 Win %: 58.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_IR4
TQQQ Gain: $ 36.87 Win %: 57.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 36.88 Win %: 56.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 36.94 Win %: 57.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_IR4
TQQQ Gain: $ 37.03 Win %: 55.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 37.03 Win %: 55.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 37.28 Win %: 54.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 37.29 Win %: 52.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
TQQQ Gain: $ 37.31 Win %: 62.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 37.45 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 37.5 Win %: 53.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 37.68 Win %: 56.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_SS
TQQQ Gain: $ 37.73 Win %: 57.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 37.89 Win %: 54.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 37.89 Win %: 54.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 37.96 Win %: 57.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 37.96 Win %: 57.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB6
TQQQ Gain: $ 37.99 Win %: 55.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 38.14 Win %: 51.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 38.14 Win %: 51.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_TR_DB3
TQQQ Gain: $ 38.14 Win %: 51.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_RV_TR_DB3
TQQQ Gain: $ 38.28 Win %: 49.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 38.28 Win %: 52.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
TQQQ Gain: $ 38.34 Win %: 55.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 38.55 Win %: 62.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 38.57 Win %: 52.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR3
TQQQ Gain: $ 38.57 Win %: 52.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR3
TQQQ Gain: $ 38.69 Win %: 51.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 38.76 Win %: 51.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 38.76 Win %: 52.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 38.92 Win %: 57.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 38.93 Win %: 54.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 39.1 Win %: 57.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_IR4
TQQQ Gain: $ 39.13 Win %: 57.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 39.13 Win %: 57.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
TQQQ Gain: $ 39.14 Win %: 53.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 39.26 Win %: 53.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 39.26 Win %: 53.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 39.32 Win %: 52.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 39.32 Win %: 52.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
TQQQ Gain: $ 39.76 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IT_QL
TQQQ Gain: $ 39.79 Win %: 58.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_SS
TQQQ Gain: $ 39.89 Win %: 60.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 4.15 Win %: 57.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 4.26 Win %: 54.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 4.26 Win %: 54.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_AL
TQQQ Gain: $ 4.29 Win %: 47.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_LI
TQQQ Gain: $ 4.32 Win %: 48.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AL
TQQQ Gain: $ 4.33 Win %: 51.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_AV
TQQQ Gain: $ 4.43 Win %: 59.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 4.46 Win %: 50.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
TQQQ Gain: $ 4.48 Win %: 49.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
TQQQ Gain: $ 4.53 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ 4.53 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ 4.76 Win %: 55.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 4.82 Win %: 64.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
TQQQ Gain: $ 40.02 Win %: 53.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 40.18 Win %: 51.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 40.27 Win %: 57.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 40.31 Win %: 63.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 40.31 Win %: 63.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 40.42 Win %: 59.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 40.45 Win %: 62.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 40.46 Win %: 53.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 40.48 Win %: 51.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 40.48 Win %: 51.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 40.67 Win %: 52.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
TQQQ Gain: $ 40.7 Win %: 59.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 40.85 Win %: 57.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_SS
TQQQ Gain: $ 40.85 Win %: 57.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_SS
TQQQ Gain: $ 40.94 Win %: 59.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_TR
TQQQ Gain: $ 41.04 Win %: 51.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 41.13 Win %: 51.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 41.13 Win %: 51.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
TQQQ Gain: $ 41.26 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 41.26 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
TQQQ Gain: $ 41.33 Win %: 52.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 41.33 Win %: 52.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 41.33 Win %: 52.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
TQQQ Gain: $ 41.33 Win %: 52.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
TQQQ Gain: $ 41.5 Win %: 63.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 41.6 Win %: 52.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 41.63 Win %: 53.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 41.63 Win %: 53.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 41.66 Win %: 62.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP
TQQQ Gain: $ 41.76 Win %: 51.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 41.95 Win %: 51.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 41.95 Win %: 51.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 41.98 Win %: 52.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 41.98 Win %: 52.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 42.04 Win %: 52.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
TQQQ Gain: $ 42.19 Win %: 61.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 42.25 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 42.61 Win %: 59.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_DB10
TQQQ Gain: $ 42.61 Win %: 59.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_DB10
TQQQ Gain: $ 42.79 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 43.03 Win %: 51.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 43.06 Win %: 51.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 43.09 Win %: 53.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 43.17 Win %: 53.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
TQQQ Gain: $ 43.17 Win %: 53.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
TQQQ Gain: $ 43.17 Win %: 53.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 43.17 Win %: 53.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 43.29 Win %: 52.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 43.29 Win %: 52.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 43.43 Win %: 52.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 43.43 Win %: 52.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR_DB4
TQQQ Gain: $ 43.53 Win %: 61.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 43.99 Win %: 53.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 44.08 Win %: 54.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 44.12 Win %: 51.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 44.17 Win %: 51.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 44.21 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 44.21 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 44.35 Win %: 59.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_AV
TQQQ Gain: $ 44.37 Win %: 61.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IT
TQQQ Gain: $ 44.37 Win %: 61.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IT
TQQQ Gain: $ 44.39 Win %: 62.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 44.46 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 44.46 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
TQQQ Gain: $ 44.46 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 44.51 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 44.74 Win %: 62.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 44.89 Win %: 53.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 44.9 Win %: 52.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 44.9 Win %: 52.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 44.94 Win %: 54.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 44.98 Win %: 54.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 45.03 Win %: 51.00 in 127 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 45.36 Win %: 53.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 45.43 Win %: 54.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 45.46 Win %: 56.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
TQQQ Gain: $ 45.56 Win %: 51.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 45.6 Win %: 62.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 45.63 Win %: 53.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 45.63 Win %: 53.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 45.93 Win %: 56.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
TQQQ Gain: $ 46.08 Win %: 59.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AV
TQQQ Gain: $ 46.17 Win %: 58.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 46.21 Win %: 53.00 in 130 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 46.23 Win %: 53.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_DB15
TQQQ Gain: $ 46.59 Win %: 58.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 46.72 Win %: 66.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP_IR4
TQQQ Gain: $ 46.95 Win %: 54.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 47.04 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 47.12 Win %: 52.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
TQQQ Gain: $ 47.12 Win %: 53.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 47.17 Win %: 52.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 47.24 Win %: 54.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
TQQQ Gain: $ 47.35 Win %: 58.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 47.48 Win %: 58.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 47.64 Win %: 66.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP_IR4
TQQQ Gain: $ 47.69 Win %: 53.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_DB15
TQQQ Gain: $ 48.05 Win %: 53.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 48.24 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AV
TQQQ Gain: $ 48.24 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AV
TQQQ Gain: $ 48.34 Win %: 56.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM
TQQQ Gain: $ 48.45 Win %: 55.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_DB15
TQQQ Gain: $ 48.51 Win %: 55.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 48.65 Win %: 66.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP_IR4
TQQQ Gain: $ 48.73 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
TQQQ Gain: $ 48.73 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
TQQQ Gain: $ 48.74 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 48.75 Win %: 57.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 48.92 Win %: 62.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 48.92 Win %: 62.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 48.96 Win %: 57.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
TQQQ Gain: $ 49.02 Win %: 56.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 49.14 Win %: 55.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 49.19 Win %: 53.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 49.41 Win %: 54.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 49.45 Win %: 52.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV
TQQQ Gain: $ 49.47 Win %: 56.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM
TQQQ Gain: $ 49.54 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 49.54 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 49.61 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 49.61 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 49.61 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 49.61 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 49.73 Win %: 53.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 49.74 Win %: 55.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 49.74 Win %: 55.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 49.83 Win %: 52.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV
TQQQ Gain: $ 49.93 Win %: 57.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM
TQQQ Gain: $ 5.08 Win %: 51.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_HM
TQQQ Gain: $ 5.1 Win %: 55.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
TQQQ Gain: $ 5.12 Win %: 51.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 5.12 Win %: 51.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
TQQQ Gain: $ 5.12 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
TQQQ Gain: $ 5.2 Win %: 52.00 in 119 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
TQQQ Gain: $ 5.22 Win %: 53.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
TQQQ Gain: $ 5.25 Win %: 58.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 5.27 Win %: 56.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 5.27 Win %: 56.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 5.28 Win %: 64.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
TQQQ Gain: $ 5.32 Win %: 48.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_TR_IR1
TQQQ Gain: $ 5.37 Win %: 48.00 in 118 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_LI
TQQQ Gain: $ 5.41 Win %: 50.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM
TQQQ Gain: $ 5.42 Win %: 50.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_HM
TQQQ Gain: $ 5.45 Win %: 65.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
TQQQ Gain: $ 5.68 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
TQQQ Gain: $ 5.72 Win %: 65.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
TQQQ Gain: $ 5.75 Win %: 50.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_IR3
TQQQ Gain: $ 5.75 Win %: 50.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_IR3
TQQQ Gain: $ 5.79 Win %: 54.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_LI
TQQQ Gain: $ 5.85 Win %: 52.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 5.86 Win %: 56.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ 5.9 Win %: 54.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_LI
TQQQ Gain: $ 5.99 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
TQQQ Gain: $ 5.99 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 5.99 Win %: 55.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
TQQQ Gain: $ 50.02 Win %: 53.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_DB15
TQQQ Gain: $ 50.06 Win %: 62.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 50.06 Win %: 62.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
TQQQ Gain: $ 50.12 Win %: 68.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP_IR4
TQQQ Gain: $ 50.15 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 50.15 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 50.25 Win %: 52.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 50.27 Win %: 55.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
TQQQ Gain: $ 50.53 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
TQQQ Gain: $ 50.53 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 50.8 Win %: 55.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
TQQQ Gain: $ 50.82 Win %: 67.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP_IR4
TQQQ Gain: $ 50.93 Win %: 53.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_DB15
TQQQ Gain: $ 51.08 Win %: 53.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 51.14 Win %: 62.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 51.72 Win %: 53.00 in 127 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 51.81 Win %: 55.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
TQQQ Gain: $ 51.82 Win %: 51.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 51.9 Win %: 55.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 51.93 Win %: 54.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR_DB1
TQQQ Gain: $ 51.94 Win %: 66.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IT
TQQQ Gain: $ 51.99 Win %: 53.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 52.25 Win %: 53.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_DB15
TQQQ Gain: $ 52.25 Win %: 55.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 52.3 Win %: 58.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_LI
TQQQ Gain: $ 52.3 Win %: 58.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_LI
TQQQ Gain: $ 52.97 Win %: 53.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
TQQQ Gain: $ 52.99 Win %: 64.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 53.6 Win %: 55.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 53.72 Win %: 55.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
TQQQ Gain: $ 53.72 Win %: 55.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
TQQQ Gain: $ 53.74 Win %: 66.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IT
TQQQ Gain: $ 53.84 Win %: 53.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV
TQQQ Gain: $ 53.85 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_AL
TQQQ Gain: $ 53.9 Win %: 64.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 53.95 Win %: 53.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM
TQQQ Gain: $ 54.29 Win %: 59.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_LI
TQQQ Gain: $ 54.66 Win %: 67.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP_IR4
TQQQ Gain: $ 54.66 Win %: 67.00 in 123 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_QP_IR4
TQQQ Gain: $ 54.97 Win %: 63.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 55.63 Win %: 59.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_HM
TQQQ Gain: $ 55.84 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_AL
TQQQ Gain: $ 56.14 Win %: 53.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV
TQQQ Gain: $ 56.2 Win %: 59.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
TQQQ Gain: $ 56.56 Win %: 63.00 in 128 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 57.99 Win %: 62.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AL
TQQQ Gain: $ 59.77 Win %: 61.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_TR_IR3
TQQQ Gain: $ 59.8 Win %: 61.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_TR_IR3
TQQQ Gain: $ 6.01 Win %: 87.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_IT_QP
TQQQ Gain: $ 6.01 Win %: 87.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_IT_QP
TQQQ Gain: $ 6.12 Win %: 58.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR1
TQQQ Gain: $ 6.12 Win %: 58.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR1
TQQQ Gain: $ 6.14 Win %: 60.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ 6.33 Win %: 50.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 6.33 Win %: 56.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_AV
TQQQ Gain: $ 6.4 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 6.4 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 6.45 Win %: 48.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_IR1
TQQQ Gain: $ 6.45 Win %: 52.00 in 130 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
TQQQ Gain: $ 6.49 Win %: 64.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
TQQQ Gain: $ 6.59 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 6.59 Win %: 58.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 6.83 Win %: 53.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 6.89 Win %: 59.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR1
TQQQ Gain: $ 6.95 Win %: 65.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
TQQQ Gain: $ 60.32 Win %: 61.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_AL
TQQQ Gain: $ 62.97 Win %: 55.00 in 125 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
TQQQ Gain: $ 63.44 Win %: 55.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
TQQQ Gain: $ 66.24 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
TQQQ Gain: $ 66.24 Win %: 56.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
TQQQ Gain: $ 66.47 Win %: 56.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
TQQQ Gain: $ 66.48 Win %: 59.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_RV_AL
TQQQ Gain: $ 68.21 Win %: 59.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AL
TQQQ Gain: $ 69.49 Win %: 61.00 in 130 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IR3
TQQQ Gain: $ 7.14 Win %: 59.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR1
TQQQ Gain: $ 7.23 Win %: 53.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM
TQQQ Gain: $ 7.26 Win %: 56.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 7.26 Win %: 64.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
TQQQ Gain: $ 7.36 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 7.43 Win %: 59.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
TQQQ Gain: $ 7.52 Win %: 55.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_HM_QP
TQQQ Gain: $ 7.57 Win %: 53.00 in 131 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 7.65 Win %: 49.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
TQQQ Gain: $ 7.66 Win %: 63.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ 7.66 Win %: 63.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ 7.69 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 7.69 Win %: 52.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 7.83 Win %: 57.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AV
TQQQ Gain: $ 7.93 Win %: 57.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
TQQQ Gain: $ 70.37 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AL
TQQQ Gain: $ 70.37 Win %: 60.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AL
TQQQ Gain: $ 77.11 Win %: 64.00 in 129 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IR3
TQQQ Gain: $ 77.44 Win %: 62.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IR3
TQQQ Gain: $ 77.44 Win %: 62.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_IR3
TQQQ Gain: $ 8.03 Win %: 64.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP
TQQQ Gain: $ 8.04 Win %: 60.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_TR_QP
TQQQ Gain: $ 8.33 Win %: 46.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_IR1
TQQQ Gain: $ 8.38 Win %: 47.00 in 119 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_LI
TQQQ Gain: $ 8.43 Win %: 56.00 in 127 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 8.61 Win %: 60.00 in 126 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_HM_QP
TQQQ Gain: $ 8.63 Win %: 54.00 in 131 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS5_LI
TQQQ Gain: $ 8.63 Win %: 57.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_AV
TQQQ Gain: $ 8.63 Win %: 57.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_AV
TQQQ Gain: $ 8.64 Win %: 56.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ 8.72 Win %: 63.00 in 131 days with algo TB3_HS_QM_OB4_OS4_CB5_CS5_TR_QP
TQQQ Gain: $ 8.74 Win %: 48.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 8.74 Win %: 48.00 in 123 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_HM
TQQQ Gain: $ 8.76 Win %: 47.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_IR1
TQQQ Gain: $ 8.76 Win %: 47.00 in 125 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 8.79 Win %: 65.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
TQQQ Gain: $ 8.79 Win %: 65.00 in 123 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
TQQQ Gain: $ 8.8 Win %: 46.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_IR1
TQQQ Gain: $ 8.84 Win %: 46.00 in 118 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
TQQQ Gain: $ 8.84 Win %: 46.00 in 118 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_IR1
TQQQ Gain: $ 8.84 Win %: 53.00 in 130 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 8.87 Win %: 52.00 in 126 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_RV_QP
TQQQ Gain: $ 8.93 Win %: 49.00 in 125 days with algo TB5_HL_HS_QM_OB4_OS4_CB3_CS3_HM_TR
TQQQ Gain: $ 8.95 Win %: 59.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_QP
TQQQ Gain: $ 8.97 Win %: 54.00 in 129 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 9.17 Win %: 53.00 in 125 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
TQQQ Gain: $ 9.46 Win %: 47.00 in 118 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR1
TQQQ Gain: $ 9.47 Win %: 49.00 in 126 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR1
TQQQ Gain: $ 9.48 Win %: 52.00 in 119 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
TQQQ Gain: $ 9.5 Win %: 56.00 in 126 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
TQQQ Gain: $ 9.53 Win %: 52.00 in 129 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 9.54 Win %: 48.00 in 129 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AL
TQQQ Gain: $ 9.58 Win %: 49.00 in 127 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_HM_TR
TQQQ Gain: $ 9.59 Win %: 57.00 in 128 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_QP
TQQQ Gain: $ 9.64 Win %: 48.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_TR_IR1
TQQQ Gain: $ 9.64 Win %: 48.00 in 123 days with algo TB5_HL_HS_QM_OB4_OS4_CB4_CS4_TR_IR1
TQQQ Gain: $ 9.7 Win %: 65.00 in 128 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_QP
TQQQ Gain: $ 9.71 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 9.71 Win %: 51.00 in 131 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_HM_TR
TQQQ Gain: $ 9.9 Win %: 57.00 in 128 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 0.35 Win %: 49.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 0.37 Win %: 52.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 0.67 Win %: 56.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 0.8 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 0.91 Win %: 64.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 1.19 Win %: 53.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 1.2 Win %: 62.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 1.54 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 1.67 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 1.76 Win %: 52.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ 1.83 Win %: 64.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 1.83 Win %: 64.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ 1.84 Win %: 56.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 1.84 Win %: 56.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 1.86 Win %: 59.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 1.89 Win %: 51.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ 2.2 Win %: 52.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 2.22 Win %: 66.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 2.22 Win %: 66.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ 2.25 Win %: 50.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 2.39 Win %: 100.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 2.6 Win %: 56.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 2.64 Win %: 93.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_QP_IR5
Gain: $ 2.8 Win %: 93.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_TR_IR5
Gain: $ 3.03 Win %: 54.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 3.24 Win %: 93.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_IR5
Gain: $ 3.33 Win %: 65.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 3.33 Win %: 65.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ 3.67 Win %: 53.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 3.8 Win %: 57.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 3.85 Win %: 66.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 3.97 Win %: 57.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ 3.97 Win %: 68.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 3.97 Win %: 68.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ 4.39 Win %: 73.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 4.73 Win %: 57.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 4.93 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 4.93 Win %: 51.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 5.07 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 5.1 Win %: 48.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 5.29 Win %: 60.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_AL
Gain: $ 5.33 Win %: 55.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 5.44 Win %: 50.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 5.9 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 5.9 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 5.9 Win %: 52.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 5.99 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 5.99 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 5.99 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 6.12 Win %: 65.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 6.38 Win %: 59.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 6.42 Win %: 54.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 6.73 Win %: 58.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_TR
Gain: $ 6.92 Win %: 49.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 6.92 Win %: 49.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_LI
Gain: $ 6.99 Win %: 51.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 7.03 Win %: 52.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 7.25 Win %: 53.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV
Gain: $ 7.47 Win %: 48.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 7.48 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 7.8 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 8.09 Win %: 56.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 8.55 Win %: 50.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AL
Gain: $ 8.69 Win %: 56.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 9.71 Win %: 71.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 9.97 Win %: 69.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ 10.61 Win %: 53.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 10.61 Win %: 53.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 10.79 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 10.95 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 11.98 Win %: 59.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ 12.35 Win %: 67.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 12.35 Win %: 67.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 12.38 Win %: 61.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_PA_QP
Gain: $ 13.06 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 13.21 Win %: 67.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 13.25 Win %: 56.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 13.35 Win %: 64.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ 13.35 Win %: 68.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ 13.62 Win %: 67.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 13.62 Win %: 67.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 13.67 Win %: 67.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 13.78 Win %: 65.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ 14.02 Win %: 56.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 14.02 Win %: 64.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_QP_IR5
Gain: $ 14.1 Win %: 64.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ 14.79 Win %: 66.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 15.34 Win %: 54.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 15.74 Win %: 64.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ 15.79 Win %: 62.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 15.88 Win %: 68.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 17.19 Win %: 68.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 17.36 Win %: 63.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 17.64 Win %: 64.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_VI
Gain: $ 17.95 Win %: 68.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 18.32 Win %: 68.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 19.1 Win %: 59.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ 19.31 Win %: 64.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP
Gain: $ 19.31 Win %: 64.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_QP
Gain: $ 20.95 Win %: 63.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ 20.95 Win %: 63.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ 21.66 Win %: 62.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_RV_QP
Gain: $ 22 Win %: 50.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_QL
Gain: $ 22.03 Win %: 62.00 in 90 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 23.51 Win %: 60.00 in 90 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_PA_AV
Gain: $ 23.61 Win %: 64.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 23.78 Win %: 56.00 in 90 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_AV
Gain: $ 23.86 Win %: 63.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 23.9 Win %: 62.00 in 90 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_PA_AV
Gain: $ 23.96 Win %: 61.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_PA_QP
Gain: $ 24 Win %: 66.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 24.57 Win %: 60.00 in 90 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_PA_AV
Gain: $ 26.68 Win %: 61.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_PA_QP
Gain: $ 27.19 Win %: 57.00 in 90 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AV
Gain: $ 27.31 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 27.31 Win %: 56.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 27.37 Win %: 58.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 27.85 Win %: 57.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 27.85 Win %: 57.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 28.07 Win %: 55.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ 28.4 Win %: 62.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ 28.6 Win %: 58.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 28.82 Win %: 57.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 28.82 Win %: 57.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 28.9 Win %: 57.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 29.75 Win %: 58.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 30.19 Win %: 62.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 30.23 Win %: 58.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 31.5 Win %: 58.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_PA
Gain: $ 32.01 Win %: 58.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 32.13 Win %: 56.00 in 115 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ 32.33 Win %: 62.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_QP
Gain: $ 32.72 Win %: 57.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_RV_AV
Gain: $ 33.08 Win %: 62.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 33.17 Win %: 63.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 33.17 Win %: 63.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 33.37 Win %: 59.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_SS
Gain: $ 33.48 Win %: 62.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 33.48 Win %: 62.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 33.55 Win %: 58.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 33.83 Win %: 58.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 33.84 Win %: 67.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ 33.86 Win %: 58.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 34 Win %: 57.00 in 116 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_IR5
Gain: $ 34.02 Win %: 62.00 in 115 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 34.02 Win %: 62.00 in 115 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 34.13 Win %: 62.00 in 115 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 34.42 Win %: 67.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ 34.79 Win %: 50.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 34.8 Win %: 60.00 in 90 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 34.96 Win %: 62.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 35 Win %: 50.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 35.01 Win %: 60.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_DB10
Gain: $ 35.09 Win %: 53.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_DB10
Gain: $ 35.24 Win %: 57.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 35.35 Win %: 61.00 in 91 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_RV
Gain: $ 35.89 Win %: 63.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 37.03 Win %: 55.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ 37.79 Win %: 58.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 37.79 Win %: 58.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ 38.25 Win %: 58.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 38.4 Win %: 58.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 38.55 Win %: 64.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ 39.25 Win %: 57.00 in 117 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ 39.47 Win %: 58.00 in 117 days with algo TB5_HL_HS_QM_OB4_OS4_CB2_CS2_TR_IR5
Gain: $ 39.47 Win %: 58.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 40.47 Win %: 64.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ 40.8 Win %: 61.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5
Gain: $ 40.94 Win %: 63.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 41.17 Win %: 58.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 41.8 Win %: 58.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 42.01 Win %: 57.00 in 116 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 42.38 Win %: 62.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_DB10
Gain: $ 42.43 Win %: 57.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_PA
Gain: $ 42.55 Win %: 58.00 in 117 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 42.64 Win %: 60.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_PA_QP
Gain: $ 43.41 Win %: 57.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 43.6 Win %: 54.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_PA_TR
Gain: $ 43.91 Win %: 58.00 in 116 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 43.91 Win %: 58.00 in 116 days with algo TB5_EO_EC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ 43.95 Win %: 60.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 44.17 Win %: 57.00 in 117 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 44.79 Win %: 57.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 45.1 Win %: 65.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ 45.15 Win %: 56.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ 46.63 Win %: 59.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 46.79 Win %: 54.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_PA_TR
Gain: $ 46.89 Win %: 66.00 in 90 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 47.09 Win %: 58.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ 47.22 Win %: 60.00 in 90 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_AL
Gain: $ 47.22 Win %: 60.00 in 90 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_AL
Gain: $ 47.93 Win %: 63.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_PA_TR
Gain: $ 48.75 Win %: 58.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_PA
Gain: $ 48.81 Win %: 58.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 49.02 Win %: 59.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_PA
Gain: $ 51.28 Win %: 69.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 52.89 Win %: 57.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 58.97 Win %: 56.00 in 90 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 58.97 Win %: 56.00 in 90 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 60.62 Win %: 59.00 in 91 days with algo TB5_EO_EC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 67.94 Win %: 57.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 69.54 Win %: 57.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 73.92 Win %: 60.00 in 91 days with algo TB5_EO_EC_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 73.92 Win %: 60.00 in 91 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_RV
