Gain: $ -3204.64 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_DB30
Gain: $ -389.83 Win %: 60.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_RV_AV
Gain: $ -375.92 Win %: 57.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_RV
Gain: $ -369.52 Win %: 59.00 in 101 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ -369.52 Win %: 59.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_RV_AL
Gain: $ -369.52 Win %: 59.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_RV_AL
Gain: $ -357.98 Win %: 60.00 in 101 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ -356.77 Win %: 60.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_RV_AV
Gain: $ -347.03 Win %: 60.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_RV_AL
Gain: $ -335.15 Win %: 59.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_RV
Gain: $ -309.51 Win %: 60.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ -309.32 Win %: 61.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_RV_AV
Gain: $ -294.28 Win %: 59.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -290.33 Win %: 57.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -279.11 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -279.11 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -277.08 Win %: 59.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_HM_QP
Gain: $ -273.15 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -268.25 Win %: 61.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_RV
Gain: $ -267.97 Win %: 59.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ -267.97 Win %: 59.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM_QP
Gain: $ -255.03 Win %: 59.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -251.34 Win %: 58.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -234.07 Win %: 59.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -230.95 Win %: 59.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_QP
Gain: $ -225.27 Win %: 60.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -207.1 Win %: 49.00 in 117 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ -207.09 Win %: 48.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_PA_AV
Gain: $ -203.35 Win %: 60.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -203.17 Win %: 47.00 in 90 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_PA_AV
Gain: $ -196.19 Win %: 70.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ -195.76 Win %: 60.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -195.75 Win %: 48.00 in 91 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_PA_AV
Gain: $ -194.08 Win %: 61.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ -190.89 Win %: 63.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -188.9 Win %: 49.00 in 117 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_HM_AV
Gain: $ -171.11 Win %: 48.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_PA_AV
Gain: $ -159.27 Win %: 63.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -152.39 Win %: 57.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ -148.27 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -148.27 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -148.27 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -145.14 Win %: 52.00 in 117 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -144.56 Win %: 52.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ -142.58 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -141.15 Win %: 64.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -141.04 Win %: 52.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ -140.43 Win %: 64.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -137.78 Win %: 63.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ -136.18 Win %: 62.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_QP_IR5
Gain: $ -131.53 Win %: 65.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_RV_QP
Gain: $ -130.6 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -130.28 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -130.28 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ -129 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM
Gain: $ -129 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ -125.22 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV
Gain: $ -124.1 Win %: 53.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ -119.59 Win %: 62.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ -118.85 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ -118.44 Win %: 70.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_QP
Gain: $ -115.96 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_QP_IR5
Gain: $ -115.43 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM
Gain: $ -115.32 Win %: 64.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_QP
Gain: $ -106.52 Win %: 58.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM
Gain: $ -106.52 Win %: 58.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ -106.52 Win %: 58.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_HM
Gain: $ -106.52 Win %: 58.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ -101.38 Win %: 63.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -100.49 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -98.08 Win %: 50.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ -89.66 Win %: 58.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_TR_QP
Gain: $ -89.03 Win %: 58.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -84.97 Win %: 47.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ -84.05 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM
Gain: $ -81.1 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ -80.34 Win %: 59.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -79.64 Win %: 61.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -78.89 Win %: 47.00 in 117 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_AV
Gain: $ -78.89 Win %: 47.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ -75.36 Win %: 62.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_PA_QP
Gain: $ -71.16 Win %: 63.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_PA_QP
Gain: $ -71.16 Win %: 63.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_PA_QP
Gain: $ -71.16 Win %: 63.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_PA_QP
Gain: $ -70.84 Win %: 48.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ -70.28 Win %: 47.00 in 117 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -68.11 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_AL
Gain: $ -68.02 Win %: 60.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_QP
Gain: $ -68.02 Win %: 60.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -65.44 Win %: 60.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -64.93 Win %: 63.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -64.88 Win %: 69.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -64.41 Win %: 47.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ -60.67 Win %: 47.00 in 117 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_AV
Gain: $ -59.5 Win %: 64.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_RV_QP
Gain: $ -57.39 Win %: 52.00 in 117 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ -56.75 Win %: 61.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -52.19 Win %: 94.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ -48.19 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR2
Gain: $ -47.26 Win %: 55.00 in 101 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ -47.26 Win %: 55.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_HM_AV
Gain: $ -47.26 Win %: 55.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_HM_AV
Gain: $ -44.83 Win %: 63.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ -44.62 Win %: 75.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_AL
Gain: $ -43.71 Win %: 69.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -43.71 Win %: 69.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -43.71 Win %: 69.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -41.91 Win %: 65.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ -41.91 Win %: 65.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_RV_QP
Gain: $ -41.91 Win %: 65.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_RV_QP
Gain: $ -39.73 Win %: 98.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ -38.26 Win %: 69.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -32.62 Win %: 69.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_QP
Gain: $ -32.62 Win %: 69.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_QP
Gain: $ -31.69 Win %: 48.00 in 117 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_AL
Gain: $ -31.5 Win %: 69.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -31.41 Win %: 63.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_QP_IR5
Gain: $ -30.3 Win %: 63.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ -28.61 Win %: 69.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ -27.8 Win %: 50.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_AV
Gain: $ -26.47 Win %: 69.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -25.52 Win %: 63.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -25.52 Win %: 63.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -21.63 Win %: 52.00 in 117 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_AL
Gain: $ -20.38 Win %: 63.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_QP_IR5
Gain: $ -16.38 Win %: 55.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_HM_AV
Gain: $ -15.09 Win %: 51.00 in 117 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ -14.69 Win %: 65.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -13.34 Win %: 58.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_PA
Gain: $ -11.48 Win %: 52.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ -10.13 Win %: 62.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ -10.13 Win %: 62.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ -9.76 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ -9.76 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ -8.61 Win %: 99.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ -8.06 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ -7.77 Win %: 53.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ -7.71 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ -7.71 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ -7.71 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ -6.88 Win %: 99.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB
Gain: $ -4.7 Win %: 58.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_PA
Gain: $ -4.7 Win %: 58.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_PA
Gain: $ -2.53 Win %: 48.00 in 117 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_AV
Gain: $ -2.44 Win %: 98.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ -1.9 Win %: 62.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ -1.9 Win %: 62.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ -1.9 Win %: 62.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM_AV
Gain: $ -1.75 Win %: 99.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ -1.26 Win %: 99.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_TR_DB
TSLA Gain: $ -100.49 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
TSLA Gain: $ -120.7 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_AV
TSLA Gain: $ -13.94 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_TR_QP
TSLA Gain: $ -14.76 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_QP_IR2
TSLA Gain: $ -166.23 Win %: 49.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_HM_AV
TSLA Gain: $ -170.58 Win %: 50.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_HM_AV
TSLA Gain: $ -207.48 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AV
TSLA Gain: $ -221.7 Win %: 59.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_QP
TSLA Gain: $ -244.32 Win %: 58.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_QP
TSLA Gain: $ -251.34 Win %: 58.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_QP
TSLA Gain: $ -29.52 Win %: 48.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_AL
TSLA Gain: $ -36.03 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_AV
TSLA Gain: $ -36.83 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_QP
TSLA Gain: $ -40.04 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_AL
TSLA Gain: $ -41.13 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_TR_QP
TSLA Gain: $ -5.53 Win %: 50.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_AV
TSLA Gain: $ -54.39 Win %: 61.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_QP_IR2
TSLA Gain: $ -57.32 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AL
TSLA Gain: $ -62.88 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_AV
TSLA Gain: $ -68.11 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_AL
TSLA Gain: $ -78.85 Win %: 59.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QP
TSLA Gain: $ -8.06 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QL
TSLA Gain: $ -8.35 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV
TSLA Gain: $ -8.56 Win %: 64.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_QP
TSLA Gain: $ -8.78 Win %: 49.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_AL
TSLA Gain: $ -81.18 Win %: 76.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_VI
TSLA Gain: $ -87.02 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR2
TSLA Gain: $ 1.4 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
TSLA Gain: $ 100.58 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_HM
TSLA Gain: $ 101.8 Win %: 61.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_HM_TR
TSLA Gain: $ 102.37 Win %: 61.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
TSLA Gain: $ 106.06 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_TR
TSLA Gain: $ 106.06 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_TR_DB2
TSLA Gain: $ 11.12 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_QL
TSLA Gain: $ 117.48 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_SS
TSLA Gain: $ 125.7 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_TR
TSLA Gain: $ 128.08 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM
TSLA Gain: $ 13.76 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
TSLA Gain: $ 131.35 Win %: 54.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_SS
TSLA Gain: $ 136.21 Win %: 59.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_LI
TSLA Gain: $ 136.68 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_HM
TSLA Gain: $ 138.03 Win %: 62.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_LI
TSLA Gain: $ 138.45 Win %: 54.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
TSLA Gain: $ 151.6 Win %: 53.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_TR
TSLA Gain: $ 152.13 Win %: 58.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_DB8
TSLA Gain: $ 157.54 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_LI
TSLA Gain: $ 161.45 Win %: 55.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR_DB2
TSLA Gain: $ 17.17 Win %: 50.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
TSLA Gain: $ 20.2 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_IR2
TSLA Gain: $ 26.38 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV
TSLA Gain: $ 37.04 Win %: 47.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_QL
TSLA Gain: $ 39.45 Win %: 51.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_TR_IR2
TSLA Gain: $ 46.47 Win %: 53.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_IR2
TSLA Gain: $ 50.73 Win %: 68.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_HM_QP
TSLA Gain: $ 60.05 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_TR_IR2
TSLA Gain: $ 64.76 Win %: 51.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR2
TSLA Gain: $ 71.99 Win %: 68.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_HM_QP
TSLA Gain: $ 77.89 Win %: 55.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_DB8
TSLA Gain: $ 86.39 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR
TSLA Gain: $ 86.39 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR_DB2
TSLA Gain: $ 91.42 Win %: 61.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_HM_TR
TSLA Gain: $ 93.52 Win %: 76.00 in 119 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_VI
TSLA Gain: $ 93.83 Win %: 76.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_VI
TSLA Gain: $ 95.32 Win %: 55.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_SS
TSLA Gain: $ 96.12 Win %: 57.00 in 119 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_DB8
Gain: $ 0.69 Win %: 49.00 in 117 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 0.69 Win %: 49.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 0.97 Win %: 58.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_PA
Gain: $ 1.4 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AL
Gain: $ 1.68 Win %: 47.00 in 117 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 2.65 Win %: 52.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ 2.71 Win %: 47.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_QL
Gain: $ 2.71 Win %: 47.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 2.99 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 4.96 Win %: 50.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 5.4 Win %: 100.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_TR_DB
Gain: $ 5.57 Win %: 64.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ 6.29 Win %: 63.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_HM_AV
Gain: $ 6.7 Win %: 57.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV
Gain: $ 6.7 Win %: 57.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 7.89 Win %: 50.00 in 117 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_AV
Gain: $ 8.11 Win %: 57.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 8.4 Win %: 98.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 13.76 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ 14.52 Win %: 53.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 15.38 Win %: 50.00 in 116 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ 15.91 Win %: 50.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_AV
Gain: $ 16.38 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_DB30
Gain: $ 18.23 Win %: 44.00 in 90 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_RV_AV
Gain: $ 18.39 Win %: 64.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ 19.35 Win %: 63.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ 20.34 Win %: 50.00 in 117 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_AL
Gain: $ 21.47 Win %: 52.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ 21.89 Win %: 48.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 22.25 Win %: 64.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_HM_QP
Gain: $ 23.48 Win %: 48.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 23.9 Win %: 68.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ 23.97 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_IR2
Gain: $ 24.62 Win %: 68.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_HM_QP
Gain: $ 24.62 Win %: 68.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_HM_QP
Gain: $ 24.62 Win %: 68.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_HM_QP
Gain: $ 26.31 Win %: 45.00 in 91 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 26.31 Win %: 45.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_RV_AV
Gain: $ 26.31 Win %: 45.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_RV_AV
Gain: $ 26.66 Win %: 53.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ 28.18 Win %: 65.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_TR_QP
Gain: $ 29.36 Win %: 58.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 29.36 Win %: 58.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV
Gain: $ 30.99 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5
Gain: $ 30.99 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_DB30
Gain: $ 30.99 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_DB30
Gain: $ 32.13 Win %: 61.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_DB30
Gain: $ 33.44 Win %: 59.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ 33.78 Win %: 51.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_TR_IR5
Gain: $ 35.74 Win %: 65.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ 36.69 Win %: 60.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_DB30
Gain: $ 38.31 Win %: 52.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_IR2
Gain: $ 38.6 Win %: 66.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_QP
Gain: $ 39.97 Win %: 51.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR5
Gain: $ 39.97 Win %: 51.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ 39.97 Win %: 51.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ 41.16 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_DB30
Gain: $ 43.47 Win %: 53.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 43.76 Win %: 45.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 44.38 Win %: 50.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_QL
Gain: $ 44.56 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5
Gain: $ 45.85 Win %: 43.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 49.93 Win %: 43.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 49.93 Win %: 43.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 53.04 Win %: 43.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 53.69 Win %: 71.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 54.69 Win %: 55.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_IR5
Gain: $ 55.03 Win %: 54.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_IR5
Gain: $ 55.56 Win %: 61.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5
Gain: $ 55.56 Win %: 61.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_DB30
Gain: $ 55.56 Win %: 61.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_DB30
Gain: $ 55.56 Win %: 61.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_DB30
Gain: $ 56.78 Win %: 95.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_RV_TR_DB
Gain: $ 64.6 Win %: 54.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 64.6 Win %: 54.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ 64.76 Win %: 51.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_TR_IR2
Gain: $ 65.94 Win %: 54.00 in 91 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 65.94 Win %: 54.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_AV
Gain: $ 66.61 Win %: 44.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 66.75 Win %: 55.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_RV_QP
Gain: $ 67.18 Win %: 73.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 68.82 Win %: 55.00 in 90 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_AV
Gain: $ 68.82 Win %: 55.00 in 90 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_AV
Gain: $ 72.49 Win %: 71.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_TR_QP
Gain: $ 73.58 Win %: 74.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_QP
Gain: $ 74.13 Win %: 58.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV
Gain: $ 74.31 Win %: 72.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_QP_IR5
Gain: $ 74.31 Win %: 72.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_QP_IR5
Gain: $ 74.31 Win %: 72.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_QP_IR5
Gain: $ 74.48 Win %: 72.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 74.5 Win %: 44.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 76.33 Win %: 49.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_QL
Gain: $ 76.99 Win %: 44.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_QL
Gain: $ 77.44 Win %: 71.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 77.44 Win %: 71.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ 77.44 Win %: 71.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ 77.89 Win %: 55.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5
Gain: $ 77.89 Win %: 55.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_DB8
Gain: $ 78.94 Win %: 72.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ 79.36 Win %: 73.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_QP
Gain: $ 79.47 Win %: 52.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 80.56 Win %: 69.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ 81.18 Win %: 73.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_QP
Gain: $ 81.6 Win %: 55.00 in 101 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 83.37 Win %: 71.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ 84.66 Win %: 55.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_DB8
Gain: $ 85.75 Win %: 44.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_QL
Gain: $ 85.94 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 86.46 Win %: 58.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_DB8
Gain: $ 87.43 Win %: 76.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_QP_IR5
Gain: $ 87.91 Win %: 55.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5
Gain: $ 87.91 Win %: 55.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_DB8
Gain: $ 88.53 Win %: 72.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ 88.53 Win %: 72.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_TR_QP
Gain: $ 90.16 Win %: 63.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 91.06 Win %: 75.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 91.49 Win %: 77.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ 91.49 Win %: 77.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_QP_IR5
Gain: $ 91.59 Win %: 69.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 92.16 Win %: 56.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_RV_QP
Gain: $ 92.93 Win %: 76.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 93.4 Win %: 56.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 93.93 Win %: 74.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_VI
Gain: $ 94.04 Win %: 77.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 94.34 Win %: 75.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_QP
Gain: $ 94.58 Win %: 69.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_HM_QP
Gain: $ 94.6 Win %: 56.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ 94.6 Win %: 56.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_RV_QP
Gain: $ 95.32 Win %: 55.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 98.4 Win %: 76.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ 98.4 Win %: 76.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_QP
Gain: $ 99.32 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ 100.95 Win %: 65.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ 100.95 Win %: 65.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ 101.07 Win %: 76.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_QP
Gain: $ 101.65 Win %: 74.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QP
Gain: $ 102.37 Win %: 61.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 102.85 Win %: 53.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 103.07 Win %: 61.00 in 90 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_AL
Gain: $ 103.07 Win %: 61.00 in 90 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_AL
Gain: $ 103.09 Win %: 76.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_VI
Gain: $ 104.82 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 104.94 Win %: 54.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 105.34 Win %: 55.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 105.99 Win %: 54.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 106.14 Win %: 57.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_DB8
Gain: $ 107.46 Win %: 55.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_AV
Gain: $ 107.46 Win %: 55.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_AV
Gain: $ 107.46 Win %: 55.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_AV
Gain: $ 107.47 Win %: 51.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 107.47 Win %: 51.00 in 119 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 108.35 Win %: 61.00 in 91 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 108.35 Win %: 61.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_AL
Gain: $ 110.91 Win %: 61.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_AL
Gain: $ 112.77 Win %: 55.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 112.91 Win %: 54.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 113.98 Win %: 64.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_HM
Gain: $ 114.35 Win %: 51.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_TR
Gain: $ 114.52 Win %: 65.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ 115.04 Win %: 56.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_SS
Gain: $ 115.77 Win %: 61.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 116.21 Win %: 55.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_VI
Gain: $ 116.21 Win %: 55.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_VI
Gain: $ 116.29 Win %: 55.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 116.65 Win %: 58.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 116.65 Win %: 58.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 117.29 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 118.27 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_RV_AL
Gain: $ 121.67 Win %: 61.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 122.04 Win %: 61.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 124.12 Win %: 63.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_HM
Gain: $ 125.07 Win %: 52.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 125.29 Win %: 56.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 125.52 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ 126.95 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 126.95 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 127.5 Win %: 57.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 127.55 Win %: 62.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 128.65 Win %: 53.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR_DB2
Gain: $ 128.84 Win %: 57.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 130.24 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 132.34 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 132.34 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 133.27 Win %: 61.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_HM_TR
Gain: $ 133.39 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_IR5
Gain: $ 134.02 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 135.95 Win %: 62.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 135.96 Win %: 60.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 136.15 Win %: 59.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 136.15 Win %: 59.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 136.21 Win %: 59.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_LI
Gain: $ 136.89 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_IR5
Gain: $ 137.93 Win %: 62.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_HM_TR
Gain: $ 138.22 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ 138.45 Win %: 54.00 in 119 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 138.79 Win %: 58.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_DB8
Gain: $ 138.84 Win %: 62.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 138.85 Win %: 56.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 139.03 Win %: 61.00 in 101 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 139.68 Win %: 61.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 140.6 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_RV_AV
Gain: $ 141.13 Win %: 62.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 141.45 Win %: 59.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 141.45 Win %: 59.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 141.45 Win %: 59.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_AL
Gain: $ 141.48 Win %: 64.00 in 118 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 142.5 Win %: 59.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 142.57 Win %: 61.00 in 118 days with algo TB4_HL_HS_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 145.25 Win %: 61.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_AL
Gain: $ 145.86 Win %: 52.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 145.91 Win %: 62.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ 147.56 Win %: 65.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 148.98 Win %: 79.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_QP_IR5
Gain: $ 150.4 Win %: 76.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_VI
Gain: $ 153.02 Win %: 63.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 153.81 Win %: 53.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_RV_TR
Gain: $ 154.91 Win %: 55.00 in 118 days with algo TB4_HL_HS_QM_OB1_OS1_CB5_CS5_RV_TR
Gain: $ 155.23 Win %: 62.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 155.23 Win %: 62.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_AV
Gain: $ 155.8 Win %: 62.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 155.8 Win %: 62.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_SS
Gain: $ 157.04 Win %: 58.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_SS
Gain: $ 161.99 Win %: 58.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 163.92 Win %: 60.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 165.33 Win %: 59.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 166.09 Win %: 65.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_HM
Gain: $ 166.59 Win %: 64.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ 167.02 Win %: 63.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 167.02 Win %: 63.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_HM
Gain: $ 167.02 Win %: 63.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_HM
Gain: $ 167.09 Win %: 64.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 169.09 Win %: 65.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_HM
Gain: $ 172.61 Win %: 63.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_LI
Gain: $ 172.64 Win %: 59.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 174.06 Win %: 54.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR
Gain: $ 174.47 Win %: 58.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_LI
Gain: $ 174.68 Win %: 58.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_LI
Gain: $ 174.87 Win %: 58.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_DB8
Gain: $ 177.03 Win %: 61.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_LI
Gain: $ 179.41 Win %: 60.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 179.46 Win %: 63.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_HM
Gain: $ 180.5 Win %: 63.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_SS
Gain: $ 182.94 Win %: 60.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 182.94 Win %: 60.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_RV
Gain: $ 182.94 Win %: 60.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV
Gain: $ 183.73 Win %: 81.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_TR_QP
Gain: $ 184 Win %: 62.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ 184.24 Win %: 58.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 184.24 Win %: 58.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_LI
Gain: $ 187.63 Win %: 56.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_SS
Gain: $ 187.79 Win %: 81.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ 187.79 Win %: 81.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_TR_QP
Gain: $ 187.79 Win %: 81.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_TR_QP
Gain: $ 189.53 Win %: 61.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 192.55 Win %: 60.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 192.91 Win %: 55.00 in 118 days with algo TB4_HL_HS_QM_OB5_OS5_CB3_CS3_TR
Gain: $ 194.86 Win %: 67.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_PA_TR
Gain: $ 195.94 Win %: 58.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 196.37 Win %: 56.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 199.63 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 201.23 Win %: 58.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_VI
Gain: $ 201.62 Win %: 80.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ 204.68 Win %: 61.00 in 101 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_AL
Gain: $ 209.57 Win %: 58.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_LI
Gain: $ 209.67 Win %: 64.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 210.43 Win %: 80.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_TR_QP
Gain: $ 211.58 Win %: 58.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_LI
Gain: $ 217.45 Win %: 81.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_TR_QP
Gain: $ 217.72 Win %: 65.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ 218.85 Win %: 59.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 218.85 Win %: 59.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_VI
Gain: $ 219.29 Win %: 59.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_LI
Gain: $ 219.69 Win %: 82.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_TR_QP
Gain: $ 220.89 Win %: 64.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_RV_TR
Gain: $ 220.89 Win %: 64.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_RV_TR
Gain: $ 220.89 Win %: 64.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_RV_TR
Gain: $ 221.85 Win %: 53.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_QL
Gain: $ 222.09 Win %: 65.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 223.07 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 224.46 Win %: 58.00 in 117 days with algo TB4_HL_HS_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ 225.45 Win %: 68.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_PA_TR
Gain: $ 225.92 Win %: 60.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_VI
Gain: $ 230.19 Win %: 68.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_PA_TR
Gain: $ 230.51 Win %: 67.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ 230.57 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ 231.82 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ 231.82 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ 232.64 Win %: 68.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_PA_TR
Gain: $ 237.13 Win %: 57.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_SS
Gain: $ 237.3 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 237.3 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_HM_TR
Gain: $ 243.96 Win %: 59.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 243.96 Win %: 59.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_VI
Gain: $ 243.96 Win %: 59.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_VI
Gain: $ 243.96 Win %: 59.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_VI
Gain: $ 245.92 Win %: 57.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_SS
Gain: $ 251.42 Win %: 57.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 251.42 Win %: 57.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_IR5
Gain: $ 251.42 Win %: 57.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_IR5
Gain: $ 251.42 Win %: 57.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_IR5
Gain: $ 252.68 Win %: 61.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_RV
Gain: $ 252.74 Win %: 67.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_HM_TR
Gain: $ 253.44 Win %: 57.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 253.44 Win %: 57.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_SS
Gain: $ 266.08 Win %: 60.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2
Gain: $ 269.4 Win %: 54.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 269.4 Win %: 54.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_QL
Gain: $ 270.61 Win %: 61.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_RV
Gain: $ 272.45 Win %: 65.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 273.62 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 275.84 Win %: 61.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 277.76 Win %: 54.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_QL
Gain: $ 279.11 Win %: 61.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV
Gain: $ 279.31 Win %: 61.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_RV
Gain: $ 280.3 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 280.3 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_LI
Gain: $ 280.3 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 282.5 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 282.68 Win %: 64.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 284.78 Win %: 63.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 287.14 Win %: 65.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ 293.54 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 293.54 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 293.54 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_LI
Gain: $ 297.76 Win %: 65.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 299.16 Win %: 59.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 299.43 Win %: 75.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_TR_IR5
Gain: $ 303.89 Win %: 67.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 308.2 Win %: 59.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 308.2 Win %: 59.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 308.2 Win %: 59.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_AV
Gain: $ 308.2 Win %: 59.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 308.97 Win %: 60.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 308.97 Win %: 60.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 309.69 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 309.9 Win %: 66.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ 311.45 Win %: 60.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_AV
Gain: $ 311.55 Win %: 67.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ 311.55 Win %: 67.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_HM_TR
Gain: $ 311.55 Win %: 67.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_HM_TR
Gain: $ 318.71 Win %: 65.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_IR5
Gain: $ 320.83 Win %: 64.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_IR5
Gain: $ 321.37 Win %: 61.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 321.56 Win %: 67.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 322.2 Win %: 67.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_HM_TR
Gain: $ 322.66 Win %: 63.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2
Gain: $ 325.74 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_TR
Gain: $ 325.93 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 325.93 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 325.93 Win %: 66.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_TR
Gain: $ 330.39 Win %: 54.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_QL
Gain: $ 330.39 Win %: 54.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_QL
Gain: $ 333.19 Win %: 58.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_SS
Gain: $ 333.19 Win %: 58.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_SS
Gain: $ 334.43 Win %: 58.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 335.29 Win %: 64.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_IR5
Gain: $ 335.64 Win %: 63.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_TR
Gain: $ 341.59 Win %: 55.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_QL
Gain: $ 344.79 Win %: 65.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ 346.48 Win %: 70.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 347.56 Win %: 59.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_SS
Gain: $ 347.84 Win %: 65.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_DB30
Gain: $ 354.73 Win %: 63.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 355.51 Win %: 64.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_DB10
Gain: $ 357.42 Win %: 64.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 357.42 Win %: 64.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_TR_IR5
Gain: $ 357.42 Win %: 64.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_TR_IR5
Gain: $ 357.9 Win %: 63.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_TR
Gain: $ 358.33 Win %: 63.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 358.97 Win %: 64.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_TR_IR5
Gain: $ 359.71 Win %: 68.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 360.95 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 361.07 Win %: 55.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 361.18 Win %: 70.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 362.41 Win %: 65.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_DB10
Gain: $ 362.41 Win %: 65.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_DB10
Gain: $ 362.41 Win %: 65.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_DB10
Gain: $ 362.73 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 362.73 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_AL
Gain: $ 362.73 Win %: 64.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 367.4 Win %: 64.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 367.4 Win %: 64.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_TR
Gain: $ 369.99 Win %: 63.00 in 91 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_RV_TR
Gain: $ 370.24 Win %: 70.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ 370.24 Win %: 70.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ 373.03 Win %: 64.00 in 116 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 373.03 Win %: 64.00 in 116 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_AL
Gain: $ 375.81 Win %: 64.00 in 92 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 375.81 Win %: 64.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_RV_TR
Gain: $ 375.81 Win %: 64.00 in 92 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_RV_TR
Gain: $ 378.23 Win %: 70.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ 378.23 Win %: 70.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ 379.1 Win %: 66.00 in 116 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_AL
Gain: $ 385.01 Win %: 67.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 386.27 Win %: 71.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ 386.27 Win %: 71.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 386.4 Win %: 68.00 in 117 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 386.4 Win %: 68.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 388.18 Win %: 68.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 395.22 Win %: 68.00 in 117 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 395.22 Win %: 68.00 in 117 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 396.59 Win %: 71.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_TR_IR5
Gain: $ 399.36 Win %: 62.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 399.36 Win %: 62.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_TR
Gain: $ 399.36 Win %: 62.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_TR
Gain: $ 399.36 Win %: 62.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_TR
Gain: $ 404.67 Win %: 64.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_DB30
Gain: $ 404.67 Win %: 64.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_DB30
Gain: $ 404.67 Win %: 64.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_DB30
Gain: $ 405.09 Win %: 68.00 in 118 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 405.09 Win %: 68.00 in 118 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ 405.09 Win %: 68.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB4_CS4_RV_TR
Gain: $ 405.09 Win %: 68.00 in 118 days with algo TB1_OC_QM_OB5_OS5_CB5_CS5_RV_TR
Gain: $ 409.55 Win %: 62.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB3_CS3_TR_IR5
Gain: $ 440.65 Win %: 63.00 in 102 days with algo TB1_OC_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ 463.3 Win %: 63.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB1_CS1_TR_IR5
Gain: $ 466.84 Win %: 65.00 in 102 days with algo TB1_OC_QM_OB5_OS5_CB2_CS2_TR_IR5
