TTD Gain: $ -94.79 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_QP
TTD Gain: $ -92.21 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_TR_QP
TTD Gain: $ -92.21 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_TR_QP
TTD Gain: $ -92.21 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_TR_QP
TTD Gain: $ -91.88 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_QP
TTD Gain: $ -90.69 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_TR_QP
TTD Gain: $ -90.69 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_TR_QP
TTD Gain: $ -89.99 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_RV_QP
TTD Gain: $ -89.68 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_HM_QP
TTD Gain: $ -89.53 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_HM_QP
TTD Gain: $ -89.53 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_QP
TTD Gain: $ -89.53 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_QP
TTD Gain: $ -89.26 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_TR_QP
TTD Gain: $ -87.89 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_HM_QP
TTD Gain: $ -84.44 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_QP
TTD Gain: $ -79.15 Win %: 0 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_RV_QP
TTD Gain: $ -78.61 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_TR
TTD Gain: $ -76.74 Win %: 0 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_HM_QP
TTD Gain: $ -73.89 Win %: 0 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_QP
TTD Gain: $ -71.01 Win %: 0 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_TR_QP
TTD Gain: $ -66.08 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_TR_DB5
TTD Gain: $ -65.13 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_RV_TR_DB5
TTD Gain: $ -63.91 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_RV_TR
TTD Gain: $ -63.91 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_TR
TTD Gain: $ -63.91 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_TR
TTD Gain: $ -61.8 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_TR_DB5
TTD Gain: $ -60.11 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_RV_TR
TTD Gain: $ -60.11 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_RV_TR_DB5
TTD Gain: $ -60.11 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_TR_DB5
TTD Gain: $ -60.11 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_TR
TTD Gain: $ -60.11 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_TR_DB5
TTD Gain: $ -59.2 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_HM_TR
TTD Gain: $ -59.2 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_TR
TTD Gain: $ -59.2 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_HM_TR
TTD Gain: $ -59.2 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_TR
TTD Gain: $ -59.2 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_HM_TR
TTD Gain: $ -59.2 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_TR
TTD Gain: $ -55.9 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_TR
TTD Gain: $ -55.79 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_TR
TTD Gain: $ -55.13 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_TR
TTD Gain: $ -55.1 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_HM_TR
TTD Gain: $ -55.1 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_HM_TR
TTD Gain: $ -55.1 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_HM_TR
TTD Gain: $ -50.79 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_DB30
TTD Gain: $ -50.79 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_DB30
TTD Gain: $ -50.79 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_DB30
TTD Gain: $ -49.65 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_VI
TTD Gain: $ -45.28 Win %: 33.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_RV_TR_DB5
TTD Gain: $ -43.27 Win %: 0 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_SS
TTD Gain: $ -41.92 Win %: 33.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_RV_TR
TTD Gain: $ -41.72 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_AV
TTD Gain: $ -38.21 Win %: 33.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_DB30
TTD Gain: $ -37.55 Win %: 33.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_TR
TTD Gain: $ -37.11 Win %: 0 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_RV_AV
TTD Gain: $ -36.52 Win %: 66.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_HM_TR
TTD Gain: $ -35.77 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_TR
TTD Gain: $ -35.37 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_TR
TTD Gain: $ -35.37 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_TR_DB5
TTD Gain: $ -34.43 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_AV
TTD Gain: $ -33.84 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_HM_TR
TTD Gain: $ -32.13 Win %: 33.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_AV
TTD Gain: $ -32.13 Win %: 33.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_HM_AV
TTD Gain: $ -31.99 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2
TTD Gain: $ -31.99 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_DB30
TTD Gain: $ -31.57 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_HM
TTD Gain: $ -30.47 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV
TTD Gain: $ -29.75 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_VI
TTD Gain: $ -29.72 Win %: 33.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_VI
TTD Gain: $ -29.47 Win %: 0 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_VI
TTD Gain: $ -28.95 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_AV
TTD Gain: $ -28.52 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_HM_AV
TTD Gain: $ -27.12 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_VI
TTD Gain: $ -27.03 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_RV_AV
TTD Gain: $ -27.03 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_AV
TTD Gain: $ -27.03 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_AV
TTD Gain: $ -26.89 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_RV_AV
TTD Gain: $ -26.89 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_AV
TTD Gain: $ -26.89 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_AV
TTD Gain: $ -26.78 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_VI
TTD Gain: $ -26.78 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_VI
TTD Gain: $ -23.98 Win %: 33.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_RV_AL
TTD Gain: $ -22.61 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_AV
TTD Gain: $ -22.09 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_AV
TTD Gain: $ -22.09 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_AV
TTD Gain: $ -21.66 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_HM_AV
TTD Gain: $ -21.66 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_HM_AV
TTD Gain: $ -21.66 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_HM_AV
TTD Gain: $ -21.29 Win %: 0 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_VI
TTD Gain: $ -20.95 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_AV
TTD Gain: $ -20.95 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_HM_AV
TTD Gain: $ -20.95 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_AV
TTD Gain: $ -20.95 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_HM_AV
TTD Gain: $ -20.95 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_HM_AV
TTD Gain: $ -19.62 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_LI
TTD Gain: $ -19.24 Win %: 33.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_AL
TTD Gain: $ -17.51 Win %: 0 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_AL
TTD Gain: $ -17.21 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_AL
TTD Gain: $ -10.87 Win %: 0 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_QL
TTD Gain: $ -9.9 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_IR5
TTD Gain: $ -9.36 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_TR_IR5
TTD Gain: $ -8.93 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_TR_IR5
TTD Gain: $ -8.93 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_TR_IR5
TTD Gain: $ -8.93 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_TR_IR5
TTD Gain: $ -7.97 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2
TTD Gain: $ -4.22 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_QP_IR5
TTD Gain: $ -3.75 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_IR5
TTD Gain: $ -1.94 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_QL
TTD Gain: $ -1.7 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_HM
TTD Gain: $ -1.7 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_HM
TTD Gain: $ -1.7 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_HM
TTD Gain: $ -1.39 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_RV
TTD Gain: $ -1.39 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV
TTD Gain: $ -1.39 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV
TTD Gain: $ -1.21 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_DB30
TTD Gain: $ -1.21 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_DB30
TTD Gain: $ -1.21 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_DB30
TTD Gain: $ -1.07 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_HM
TTD Gain: $ -1.07 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_HM
TTD Gain: $ -1.07 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_HM
TTD Gain: $ -0.86 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_RV
TTD Gain: $ -0.86 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV
TTD Gain: $ -0.86 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV
TTD Gain: $ -0.73 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_RV_AL
TTD Gain: $ -0.73 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_AL
TTD Gain: $ -0.73 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_AL
TTD Gain: $ -0.43 Win %: 66.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_IR5
TTD Gain: $ -0.12 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_RV_AL
TTD Gain: $ -0.12 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_AL
TTD Gain: $ -0.12 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_AL
Gain: $ -0.27 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_VI
Gain: $ -0.37 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV
Gain: $ -0.37 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_RV
Gain: $ -0.64 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ -0.64 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_RV_TR
Gain: $ -1.2 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_LI
Gain: $ -11.05 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_AV
Gain: $ -11.05 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_HM_AV
Gain: $ -11.07 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_RV_AV
Gain: $ -11.5 Win %: 0 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_AL
Gain: $ -11.56 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_IR5
Gain: $ -11.88 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_TR_IR5
Gain: $ -12.32 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_RV
Gain: $ -12.57 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_QL
Gain: $ -12.96 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_RV_AL
Gain: $ -123.99 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_LI
Gain: $ -13.13 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_AL
Gain: $ -14.41 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_DB10
Gain: $ -14.41 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_HM
Gain: $ -14.41 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_HM_TR
Gain: $ -14.41 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_SS
Gain: $ -14.41 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_TR
Gain: $ -15.92 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_RV_TR
Gain: $ -182.02 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_IR5
Gain: $ -2.12 Win %: 0 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ -2.12 Win %: 0 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_TR_IR5
Gain: $ -2.54 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_QL
Gain: $ -214.63 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_QP_IR5
Gain: $ -26.47 Win %: 0 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM
Gain: $ -278.42 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_DB15
Gain: $ -278.42 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_HM
Gain: $ -278.42 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_RV
Gain: $ -278.42 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_SS
Gain: $ -3.36 Win %: 0 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ -3.36 Win %: 0 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -3.36 Win %: 0 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_IR5
Gain: $ -3.36 Win %: 0 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_QP_IR5
Gain: $ -39.49 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5
Gain: $ -434.6 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_HM_QP
Gain: $ -434.6 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_QP
Gain: $ -434.6 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_RV_QP
Gain: $ -48.72 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_VI
Gain: $ -5.66 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_QP_IR5
Gain: $ -62.89 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_TR_IR5
Gain: $ -67.32 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_HM_TR
Gain: $ -67.32 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_RV_TR
Gain: $ -67.32 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_TR
Gain: $ -8.62 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_HM_QP
Gain: $ -8.62 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_QP
Gain: $ -8.62 Win %: 0 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_TR_QP
Gain: $ -88.53 Win %: 0 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_TR_QP
Gain: $ -9.85 Win %: 50.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_RV_AV
Gain: $ 0 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_RV_TR_DB
Gain: $ 0.09 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 0.09 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ 0.09 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_RV_AL
Gain: $ 0.09 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_RV_QP
Gain: $ 0.1 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_VI
Gain: $ 0.1 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_VI
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_DB6
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_AV
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_DB6
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_HM
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_HM_AV
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_HM_TR
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_QL
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_SS
Gain: $ 0.31 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_TR
Gain: $ 0.39 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 0.39 Win %: 50.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_RV_AV
Gain: $ 0.51 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 0.51 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_LI
Gain: $ 0.64 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ 0.64 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ 0.64 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_QP
Gain: $ 0.64 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 0.64 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_HM_QP
Gain: $ 0.64 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_QP
Gain: $ 0.64 Win %: 100.00 in 2 days with algo TB5_LO_QM_OB4_OS4_CB5_CS5_TR_QP
Gain: $ 11.94 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_HM_AV
Gain: $ 544.78 Win %: 50.00 in 2 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_RV_QP
Gain: $ 8.3 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_AV
Gain: $ 9.71 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_AL
Gain: $ 9.71 Win %: 100.00 in 2 days with algo TB2_PL_QM_OB1_OS1_CB1_CS1_RV_AL
TTD Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_QP_IR5
TTD Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_TR_IR5
TTD Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_QP_IR5
TTD Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_TR_IR5
TTD Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_QP_IR5
TTD Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_TR_IR5
TTD Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_QP_IR5
TTD Gain: $ 0 Win %: 100.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_TR_IR5
TTD Gain: $ 0.12 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_LI
TTD Gain: $ 0.12 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_LI
TTD Gain: $ 0.12 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_LI
TTD Gain: $ 0.26 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_LI
TTD Gain: $ 0.26 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_LI
TTD Gain: $ 0.26 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_LI
TTD Gain: $ 0.31 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_IT_QP
TTD Gain: $ 0.31 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_IT_QP
TTD Gain: $ 0.31 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_IT_QP
TTD Gain: $ 0.31 Win %: 100.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_IT_QP
TTD Gain: $ 0.42 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_SS
TTD Gain: $ 0.42 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_SS
TTD Gain: $ 0.42 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_SS
TTD Gain: $ 0.64 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_AL
TTD Gain: $ 0.7 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_IR5
TTD Gain: $ 0.7 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_AL
TTD Gain: $ 0.7 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_AL
TTD Gain: $ 0.7 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_AL
TTD Gain: $ 1.06 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_IR5
TTD Gain: $ 1.21 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_AL
TTD Gain: $ 1.21 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_AL
TTD Gain: $ 3 Win %: 66.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_IT
TTD Gain: $ 3.65 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_SS
TTD Gain: $ 4.21 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_SS
TTD Gain: $ 4.5 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_IT
TTD Gain: $ 4.82 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_IR5
TTD Gain: $ 4.82 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_IR5
TTD Gain: $ 4.82 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_IR5
TTD Gain: $ 5.16 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_QL
TTD Gain: $ 5.16 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_QL
TTD Gain: $ 5.16 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_QL
TTD Gain: $ 5.55 Win %: 100.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_IT_QL
TTD Gain: $ 5.65 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_QL
TTD Gain: $ 5.65 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_QL
TTD Gain: $ 5.82 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_SS
TTD Gain: $ 5.86 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_IT
TTD Gain: $ 6.34 Win %: 100.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_LI
TTD Gain: $ 7.26 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB1_CS1_IT_QL
TTD Gain: $ 7.26 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_IT
TTD Gain: $ 7.26 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_IT_QL
TTD Gain: $ 7.26 Win %: 100.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_IT_QL
TTD Gain: $ 7.31 Win %: 100.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_SS
TTD Gain: $ 8.89 Win %: 100.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_HM
TTD Gain: $ 8.89 Win %: 100.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_QL
TTD Gain: $ 8.89 Win %: 100.00 in 3 days with algo TB1_HL_LO_QM_OB1_OS1_CB1_CS1_RV
TTD Gain: $ 513.69 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_QP
TTD Gain: $ 513.69 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_QP
TTD Gain: $ 513.69 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_QP
TTD Gain: $ 513.84 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_HM_QP
TTD Gain: $ 513.84 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_HM_QP
TTD Gain: $ 513.84 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_HM_QP
TTD Gain: $ 513.84 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_HM_QP
TTD Gain: $ 514 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_RV_QP
TTD Gain: $ 514 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_RV_QP
TTD Gain: $ 514 Win %: 66.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_RV_QP
TTD Gain: $ 516.45 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_QP
TTD Gain: $ 517.8 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_HM_QP
TTD Gain: $ 523.52 Win %: 33.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_TR_QP
TTD Gain: $ 527.44 Win %: 66.00 in 3 days with algo TB1_HL_HS_QM_OB3_OS3_CB2_CS2_RV_QP
TTD Gain: $ 533.96 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB1_OS1_CB2_CS2_QP_IR5
TTD Gain: $ 533.96 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB1_CS1_QP_IR5
TTD Gain: $ 533.96 Win %: 33.00 in 3 days with algo TB1_HL_HI_QM_OB2_OS2_CB2_CS2_QP_IR5
