VERB Gain: $ Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_AL
VERB Gain: $ Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_DB15
VERB Gain: $ Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_IT
VERB Gain: $ Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_IT_QL
VERB Gain: $ Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_IT_QL_DB15
VERB Gain: $ Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_QL
VERB Gain: $ Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_SS
VERB Gain: $ Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_TR
VERB Gain: $ Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_AC
VERB Gain: $ Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_AO
VERB Gain: $ Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_AO_AC
VERB Gain: $ Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_DB10
VERB Gain: $ Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_QL
VERB Gain: $ Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT
VERB Gain: $ Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QL
VERB Gain: $ Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QL
VERB Gain: $ Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_SS
VERB Gain: $ Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR
VERB Gain: $ Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_HM_AV_DB6
VERB Gain: $ Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5
VERB Gain: $ Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5
VERB Gain: $ Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_SS
VERB Gain: $ Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_TR
VERB Gain: $ -1.13 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_RV_QP
VERB Gain: $ -1.13 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_RV_QP_DB6
VERB Gain: $ -1.03 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_HM_QP
VERB Gain: $ -1.03 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_HM_QP_DB6
VERB Gain: $ -0.94 Win %: 33.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_IT_QP_DB10
VERB Gain: $ -0.88 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QP
VERB Gain: $ -0.88 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QP_DB6
VERB Gain: $ -0.88 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_QP
VERB Gain: $ -0.88 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_TR_QP
VERB Gain: $ -0.88 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_TR_QP_DB6
VERB Gain: $ -0.84 Win %: 33.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_AO_AC
VERB Gain: $ -0.78 Win %: 0 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_QP_IR1
VERB Gain: $ -0.71 Win %: 0 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_QP
VERB Gain: $ -0.71 Win %: 0 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_QP
VERB Gain: $ -0.7 Win %: 0 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP
VERB Gain: $ -0.66 Win %: 0 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_QP
VERB Gain: $ -0.66 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR_DB6
VERB Gain: $ -0.65 Win %: 0 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_QP_DB8
VERB Gain: $ -0.65 Win %: 0 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_QP_DB8
VERB Gain: $ -0.64 Win %: 0 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QP_DB8
VERB Gain: $ -0.63 Win %: 16.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QP
VERB Gain: $ -0.6 Win %: 0 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_QP_DB8
VERB Gain: $ -0.55 Win %: 16.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR
VERB Gain: $ -0.54 Win %: 0 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_QP_IR2
VERB Gain: $ -0.52 Win %: 16.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AV_DB8
VERB Gain: $ -0.51 Win %: 16.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_RV_QP_DB15
VERB Gain: $ -0.49 Win %: 33.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_IR3
VERB Gain: $ -0.46 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IR2
VERB Gain: $ -0.46 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TR_IR2
VERB Gain: $ -0.39 Win %: 16.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AL_DB8
VERB Gain: $ -0.39 Win %: 33.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_QP_IR4
VERB Gain: $ -0.38 Win %: 16.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR_DB8
VERB Gain: $ -0.38 Win %: 33.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC
VERB Gain: $ -0.36 Win %: 33.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_IT_QP_DB15
VERB Gain: $ -0.34 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_AO
VERB Gain: $ -0.32 Win %: 33.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_RV
VERB Gain: $ -0.3 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_HM_TR_DB6
VERB Gain: $ -0.27 Win %: 33.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_AV_DB8
VERB Gain: $ -0.25 Win %: 33.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_RV_QP
VERB Gain: $ -0.25 Win %: 33.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_RV_QP_DB10
VERB Gain: $ -0.24 Win %: 33.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_AC
VERB Gain: $ -0.22 Win %: 33.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_AL
VERB Gain: $ -0.21 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AV
VERB Gain: $ -0.21 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AV
VERB Gain: $ -0.2 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_AO
VERB Gain: $ -0.19 Win %: 33.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_LI
VERB Gain: $ -0.19 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_IT_QL
VERB Gain: $ -0.19 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_IT_QL_DB10
VERB Gain: $ -0.19 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_HM_TR
VERB Gain: $ -0.18 Win %: 33.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_HM_QP_DB15
VERB Gain: $ -0.18 Win %: 33.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_IT_QP
VERB Gain: $ -0.18 Win %: 33.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_LI
VERB Gain: $ -0.18 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_TR
VERB Gain: $ -0.17 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_QP_IR3
VERB Gain: $ -0.17 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_IR1
VERB Gain: $ -0.17 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_TR_IR1
VERB Gain: $ -0.16 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_HM_QP
VERB Gain: $ -0.16 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_HM_QP_DB10
VERB Gain: $ -0.16 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_QP
VERB Gain: $ -0.16 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_HM
VERB Gain: $ -0.15 Win %: 33.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_AV
VERB Gain: $ -0.15 Win %: 33.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_HM_QP
VERB Gain: $ -0.15 Win %: 33.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QL_DB8
VERB Gain: $ -0.15 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_RV_TR
VERB Gain: $ -0.15 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_TR_QP
VERB Gain: $ -0.15 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_TR_QP_DB10
VERB Gain: $ -0.15 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_AV
VERB Gain: $ -0.13 Win %: 33.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_RV_QP
VERB Gain: $ -0.12 Win %: 33.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_DB8
VERB Gain: $ -0.12 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_RV_TR_DB10
VERB Gain: $ -0.11 Win %: 33.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_QP
VERB Gain: $ -0.11 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_HM_TR
VERB Gain: $ -0.11 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_HM_TR_DB10
VERB Gain: $ -0.11 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_TR
VERB Gain: $ -0.11 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_VI
VERB Gain: $ -0.11 Win %: 66.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_RV
VERB Gain: $ -0.11 Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_DB6
VERB Gain: $ -0.1 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AL
VERB Gain: $ -0.1 Win %: 66.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_IT
VERB Gain: $ -0.1 Win %: 66.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_IT
VERB Gain: $ -0.09 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_RV
VERB Gain: $ -0.08 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AL
VERB Gain: $ -0.08 Win %: 83.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_TS
VERB Gain: $ -0.07 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_LI
VERB Gain: $ -0.06 Win %: 33.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_TR_DB8
VERB Gain: $ -0.06 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_RV_AL
VERB Gain: $ -0.06 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_TR_IR3
VERB Gain: $ -0.06 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AL_DB6
VERB Gain: $ -0.04 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_IT_QP
VERB Gain: $ -0.04 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_RV_TR
VERB Gain: $ -0.04 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_RV_TR_DB15
VERB Gain: $ -0.04 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_TR_QP
VERB Gain: $ -0.04 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_AV
VERB Gain: $ -0.04 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AV_DB6
VERB Gain: $ -0.03 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_TR_QP_DB15
VERB Gain: $ -0.03 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_HM
VERB Gain: $ -0.02 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_RV_AL_DB10
VERB Gain: $ -0.02 Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_AC
VERB Gain: $ -0.01 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AL
VERB Gain: $ -0.01 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AL_DB15
VERB Gain: $ -0.01 Win %: 66.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_VI
VERB Gain: $ -0.01 Win %: 66.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_TS
VERB Gain: $ 0.01 Win %: 66.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_HM_AV
VERB Gain: $ 0.01 Win %: 66.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_VI
VERB Gain: $ 0.01 Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_IT
VERB Gain: $ 0.03 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AV
VERB Gain: $ 0.03 Win %: 50.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AV_DB15
VERB Gain: $ 0.03 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_RV_AV
VERB Gain: $ 0.03 Win %: 50.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_RV_AV_DB10
VERB Gain: $ 0.04 Win %: 66.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_TS
VERB Gain: $ 0.04 Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QL_DB6
VERB Gain: $ 0.05 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AL
VERB Gain: $ 0.05 Win %: 66.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_TS
VERB Gain: $ 0.06 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM
VERB Gain: $ 0.06 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_HM_TR
VERB Gain: $ 0.07 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_RV_AV
VERB Gain: $ 0.07 Win %: 66.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_SS
VERB Gain: $ 0.09 Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_AO_AC
VERB Gain: $ 0.1 Win %: 50.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_LI
VERB Gain: $ 0.1 Win %: 66.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_VI
VERB Gain: $ 0.11 Win %: 50.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_HM_AV
VERB Gain: $ 0.11 Win %: 66.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_RV
VERB Gain: $ 0.12 Win %: 66.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_HM_TR
VERB Gain: $ 0.12 Win %: 66.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_HM_TR_DB15
VERB Gain: $ 0.12 Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_AL
VERB Gain: $ 0.14 Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_AV
VERB Gain: $ 0.14 Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_QL
VERB Gain: $ 0.15 Win %: 66.00 in 6 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_IT_QL
VERB Gain: $ 0.2 Win %: 66.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_IR4
VERB Gain: $ 0.2 Win %: 66.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_TR_IR4
VERB Gain: $ 0.2 Win %: 66.00 in 6 days with algo TB3_OO_QM_OB5_OS5_CB4_CS4_HM_AV_DB10
VERB Gain: $ 0.2 Win %: 83.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_HM
VERB Gain: $ 0.2 Win %: 83.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_HM_AV
VERB Gain: $ 0.2 Win %: 83.00 in 6 days with algo TB2_HL_HI_QM_OB5_OS5_CB5_CS5_HM_AV_DB15
VERB Gain: $ 0.26 Win %: 83.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AO_AC
VERB Gain: $ 0.67 Win %: 100.00 in 6 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AO
