Gain: $ -46.57 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_HM_AV
Gain: $ -36.81 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_HM_QP
Gain: $ -36.81 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_QP
Gain: $ -36.81 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_QP_IR1
Gain: $ -36.81 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_RV_QP
Gain: $ -34.82 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_TR_QP
Gain: $ -29.59 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_AV
Gain: $ -23.31 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_HM_TR
Gain: $ -12.8 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_LI
Gain: $ -11.2 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_RV_QP
Gain: $ -11.2 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_RV_QP
Gain: $ -9.9 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_AL
Gain: $ -9.9 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_TR_IR1
Gain: $ -9.41 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_HM_QP
Gain: $ -9.41 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_TR_QP
Gain: $ -9.41 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_HM_QP
Gain: $ -8.61 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_IR1
Gain: $ -8.61 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_SS
Gain: $ -7.45 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_QP_IR1
Gain: $ -4.3 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_RV_TR
Gain: $ -4.25 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_QP
Gain: $ -3.91 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -3.91 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -3.91 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_QP_IR1
Gain: $ -3.91 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ -2.73 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -1.52 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_HM_TR
Gain: $ -1.52 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_RV_TR
Gain: $ -1.52 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_RV_TR_DB1
Gain: $ -1.52 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_TR_IR1
Gain: $ -1.4 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_QL
Gain: $ -0.91 Win %: 0 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_RV_AL
Gain: $ -0.91 Win %: 0 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_RV_AL
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_VI
VERV Gain: $ -1.53 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_HM
VERV Gain: $ -1.55 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_RV_TR
VERV Gain: $ -1.63 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_SS
VERV Gain: $ -10.18 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_TR_QP
VERV Gain: $ -10.34 Win %: 0 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_QP_IR1
VERV Gain: $ -16.91 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_HM_AV
VERV Gain: $ -2.07 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_RV
VERV Gain: $ -2.19 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_DB6
VERV Gain: $ -2.19 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_IR1
VERV Gain: $ -2.7 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_HM_QP
VERV Gain: $ -3.46 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_TR_IR1
VERV Gain: $ -30.55 Win %: 0 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_TR_QP
VERV Gain: $ -30.55 Win %: 0 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_TR_QP
VERV Gain: $ -4.64 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_QP
VERV Gain: $ -40.26 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_HM_QP
VERV Gain: $ -42.21 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_QP_IR2
VERV Gain: $ -42.57 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_TR_QP
VERV Gain: $ -42.59 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_QP
VERV Gain: $ -43.63 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_HM_QP
VERV Gain: $ -44.89 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_RV_QP
VERV Gain: $ -48.45 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_RV_QP
VERV Gain: $ -5 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_HM_TR
VERV Gain: $ -5 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_RV_TR_DB1
VERV Gain: $ -5.12 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_AV
VERV Gain: $ -5.44 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_RV_QP
VERV Gain: $ -56 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_RV_QP
VERV Gain: $ -6.5 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_QL
VERV Gain: $ -68.22 Win %: 0 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_QP_IR2
VERV Gain: $ -68.31 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_QP_IR1
VERV Gain: $ -7.52 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_TR
VERV Gain: $ -71.68 Win %: 0 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_QP
VERV Gain: $ -81.66 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_HM_QP
VERV Gain: $ -82.16 Win %: 0 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_QP
VERV Gain: $ 0.87 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_VI
VERV Gain: $ 1.4 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_VI
VERV Gain: $ 10.09 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_AL
VERV Gain: $ 10.19 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_HM_AV
VERV Gain: $ 10.29 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_HM_TR
VERV Gain: $ 10.66 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_RV_TR
VERV Gain: $ 11.77 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_SS
VERV Gain: $ 11.94 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_IR1
VERV Gain: $ 12.18 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_TR
VERV Gain: $ 12.38 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_HM
VERV Gain: $ 12.65 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_VI
VERV Gain: $ 12.65 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_VI
VERV Gain: $ 13.04 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_AL
VERV Gain: $ 13.15 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_RV
VERV Gain: $ 13.52 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_TR_IR1
VERV Gain: $ 13.53 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_DB8
VERV Gain: $ 13.53 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_HM
VERV Gain: $ 13.53 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_IR2
VERV Gain: $ 13.53 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_SS
VERV Gain: $ 13.66 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_RV_AL
VERV Gain: $ 14.26 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_RV_AL
VERV Gain: $ 14.29 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2
VERV Gain: $ 14.85 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_SS
VERV Gain: $ 15.33 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_RV_TR_DB1
VERV Gain: $ 17.37 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_RV
VERV Gain: $ 2.23 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_QL
VERV Gain: $ 2.34 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_LI
VERV Gain: $ 2.41 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_RV_AV
VERV Gain: $ 2.75 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_DB8
VERV Gain: $ 3.08 Win %: 50.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_AL
VERV Gain: $ 3.15 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_TR
VERV Gain: $ 3.96 Win %: 50.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_RV_AL
VERV Gain: $ 4.27 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_QL
VERV Gain: $ 4.8 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_AV
VERV Gain: $ 4.89 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_QL
VERV Gain: $ 5 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_AV
VERV Gain: $ 5.12 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_LI
VERV Gain: $ 5.13 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_RV_AV
VERV Gain: $ 5.92 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_RV_AV
VERV Gain: $ 6.05 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_TR_IR2
VERV Gain: $ 6.14 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_DB6
VERV Gain: $ 6.25 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_HM_AV
VERV Gain: $ 6.28 Win %: 50.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_RV_AV
VERV Gain: $ 6.42 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_HM_TR
VERV Gain: $ 6.99 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_RV
VERV Gain: $ 7.19 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_HM_AV
VERV Gain: $ 7.2 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_TR_IR2
VERV Gain: $ 7.5 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_AV
VERV Gain: $ 7.96 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_TR
VERV Gain: $ 7.97 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_LI
VERV Gain: $ 8.26 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_HM
VERV Gain: $ 8.27 Win %: 100.00 in 2 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_RV_AL
VERV Gain: $ 8.69 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_RV_TR
VERV Gain: $ 8.73 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_AL
VERV Gain: $ 8.98 Win %: 100.00 in 2 days with algo TB5_HL_LO_QM_OB1_OS1_CB4_CS4_LI
VERV Gain: $ 9.02 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_RV_TR
VERV Gain: $ 9.04 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_HM_TR
VERV Gain: $ 9.04 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_RV_TR_DB2
VERV Gain: $ 9.04 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB2_OS2_CB1_CS1_RV_TR_DB2
VERV Gain: $ 9.44 Win %: 100.00 in 2 days with algo TB4_HL_HS_QM_OB1_OS1_CB2_CS2_IR2
Gain: $ 0.3 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_QP
Gain: $ 0.45 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_HM
Gain: $ 0.63 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_LI
Gain: $ 1.05 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_RV_AV
Gain: $ 1.05 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_RV_AV
Gain: $ 1.29 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2
Gain: $ 1.29 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_DB6
Gain: $ 1.29 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_HM
Gain: $ 1.29 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_IR1
Gain: $ 1.29 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_RV
Gain: $ 1.29 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_SS
Gain: $ 1.37 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_VI
Gain: $ 1.37 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_VI
Gain: $ 1.55 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_DB6
Gain: $ 1.55 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_QL
Gain: $ 1.55 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_TR
Gain: $ 1.55 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_HM_TR
Gain: $ 1.55 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_QL
Gain: $ 1.55 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_TR
Gain: $ 1.68 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_LI
Gain: $ 1.92 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_TR
Gain: $ 2 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_RV_AL
Gain: $ 2.03 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_VI
Gain: $ 2.19 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_QP
Gain: $ 3.01 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 3.17 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_RV_AV
Gain: $ 3.2 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_AV
Gain: $ 3.2 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_AV
Gain: $ 3.2 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_HM_AV
Gain: $ 3.22 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_AL
Gain: $ 3.33 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 3.33 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ 3.33 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV_TR_DB1
Gain: $ 3.33 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_QP_IR1
Gain: $ 3.33 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_TR_QP
Gain: $ 3.55 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_AL
Gain: $ 3.55 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_AV
Gain: $ 3.55 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB3_OS3_CB2_CS2_HM_AV
Gain: $ 3.8 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_DB6
Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_DB6
Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_HM
Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_QL
Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_SS
Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_TR
Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_TR_IR1
Gain: $ 3.98 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_IR1
Gain: $ 4.24 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_SS
Gain: $ 4.39 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_LI
Gain: $ 4.8 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_IR1
Gain: $ 4.8 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_TR_IR1
Gain: $ 5.62 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_RV
Gain: $ 5.62 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_HM
Gain: $ 5.79 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_RV
Gain: $ 5.79 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_RV_TR
Gain: $ 5.79 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB4_OS4_CB1_CS1_RV_TR_DB1
Gain: $ 5.79 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_RV
Gain: $ 5.79 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB2_OS2_CB4_CS4_RV_TR_DB1
