VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_HM_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_RV_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_RV_TR_DB2
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_TR_IR2
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_HM_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_RV_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_RV_TR_DB2
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_TR_IR2
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_HM_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_TR_DB2
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_TR_IR2
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_HM_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_RV_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_RV_TR_DB2
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_TR
VOOV Gain: $ -0.06 Win %: 0 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_TR_IR2
Gain: $ -0.09 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_VI
Gain: $ -0.1 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_IR5
Gain: $ -0.1 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_QP_IR5
Gain: $ -0.1 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_SS
Gain: $ -0.1 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_TR_IR5
Gain: $ -0.12 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_LI
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_DB8
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_HM
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_HM_QP
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_HM_TR
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_QL
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_QP
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_RV
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_RV_QP
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_RV_TR
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_TR
Gain: $ -0.16 Win %: 0 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_TR_QP
Gain: $ -0.43 Win %: 0 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_TR_IR5
Gain: $ -0.43 Win %: 0 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_TR_IR5
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_DB6
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_HM
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_HM_QP
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_HM_TR
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_QL
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_QP
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_RV
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_RV_QP
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_RV_TR
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_TR
Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_TR_QP
Gain: $ 0 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_QP_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_RV_TR_DB
Gain: $ 0 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_TR_IR5
Gain: $ 0 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_RV_TR_DB
Gain: $ 0.04 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_IR5
Gain: $ 0.04 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_QP_IR5
Gain: $ 0.04 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_IR5
Gain: $ 0.04 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_QP_IR5
Gain: $ 0.05 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_SS
Gain: $ 0.08 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_LI
Gain: $ 0.1 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_VI
Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_AL
Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_AV
Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_HM_AV
Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_RV_AL
Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB3_OS3_CB5_CS5_RV_AV
Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_LI
Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_LI
Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_AL
Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_AV
Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_HM_AV
Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_RV_AL
Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB4_OS4_CB3_CS3_RV_AV
Gain: $ 0.38 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_VI
Gain: $ 0.38 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_VI
Gain: $ 0.41 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_AV
Gain: $ 0.41 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_HM_AV
Gain: $ 0.41 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_RV_AV
Gain: $ 0.41 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_AV
Gain: $ 0.41 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_HM_AV
Gain: $ 0.41 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_RV_AV
Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_HM_TR
Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_RV_TR
Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_TR
Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_TR_QP
Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_HM_TR
Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_RV_TR
Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_TR
Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_TR_QP
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_DB10
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_HM
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_HM_QP
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_HM_QP
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_QL
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_QP
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_RV
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_RV_QP
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_SS
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_DB10
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_HM
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_HM_QP
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_QL
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_QP
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_RV
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_RV_QP
Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_SS
Gain: $ 0.64 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_AL
Gain: $ 0.64 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB1_CS1_RV_AL
Gain: $ 0.64 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_AL
Gain: $ 0.64 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS3_CB3_CS3_RV_AL
VOOV Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_IT
VOOV Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_IT_QL
VOOV Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_IT
VOOV Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_IT_QL
VOOV Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_IT
VOOV Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_IT_QL
VOOV Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_IT
VOOV Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_IT_QL
VOOV Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_LI
VOOV Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_LI
VOOV Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_LI
VOOV Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_LI
VOOV Gain: $ 0.14 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_VI
VOOV Gain: $ 0.14 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_VI
VOOV Gain: $ 0.14 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_VI
VOOV Gain: $ 0.14 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_VI
VOOV Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_DB8
VOOV Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_DB8
VOOV Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_DB8
VOOV Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_DB8
VOOV Gain: $ 0.27 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_TR_QP
VOOV Gain: $ 0.27 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_TR_QP
VOOV Gain: $ 0.27 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_TR_QP
VOOV Gain: $ 0.27 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_TR_QP
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_AL
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_HM_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_RV_AL
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_RV_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_AL
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_HM_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_RV_AL
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_RV_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_AL
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_HM_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_AL
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_AL
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_HM_AV
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_RV_AL
VOOV Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_RV_AV
VOOV Gain: $ 0.4 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_IT_QP
VOOV Gain: $ 0.4 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_IT_QP
VOOV Gain: $ 0.4 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_IT_QP
VOOV Gain: $ 0.4 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_IT_QP
VOOV Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_SS
VOOV Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_SS
VOOV Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_SS
VOOV Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_SS
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_HM
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_IR2
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_QL
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_RV
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_HM
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_IR2
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_QL
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_RV
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_HM
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_IR2
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_QL
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_HM
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_IR2
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_QL
VOOV Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_RV
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_HM_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_QP_IR2
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB2_OS2_CB3_CS3_RV_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_HM_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_QP_IR2
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB1_CS1_RV_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_HM_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_QP_IR2
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB2_CS2_RV_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_HM_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_QP
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_QP_IR2
VOOV Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB3_OS3_CB3_CS3_RV_QP
