daysBest = 1
['AUVI', 'GOVX', 'AEHR', 'ORMP', 'BNTX', 'MRNA', 'AFRM', 'AZN', 'UPST', 'AGEN', 'GPS', 'LTHM', 'ADBE', 'NVAX', 'NVDA', 'NURO', 'NFLX', 'BCRX', 'AMD', 'M', 'SAVA', 'UPS', 'ORCL', 'SQ', 'HD', 'PYPL', 'KR', 'TQQQ', 'DELL', 'TTD', 'SNAP', 'FB', 'WMT', 'MSFT', 'KO', 'MS', 'CLF', 'AAL', 'AAPL', 'MRVL', 'NKE', 'MMM', 'PFE', 'CSCO', 'AMZN', 'PBR', 'DIS', 'ABNB', 'OCGN', 'AMAT', 'DBVT', 'ASML', 'FCX', 'OXBR', 'CRM', 'VNE', 'MARA', 'TSLA', 'INTC', 'FRO', 'MRO', 'CEMI', 'BLIN', 'VTNR', 'FCEL', 'GLD', 'QCOM', 'NIO', 'GS', 'XOM', 'PG', 'ANY']
stocks len
72
daysBestStocks ['NVAX', 'BKNG', 'SAM', 'REGN', 'AMZN', 'DPZ', 'W', 'AZO', 'SE', 'BNTX', 'MDB', 'KOSS', 'AFRM', 'ASML', 'EJH', 'DE', 'UPST', 'ZM', 'GOOG', 'TSLA', 'GPN', 'CARV', 'SNOW', 'NRXP', 'ANVS', 'ROLL', 'ADGI', 'AUVI', 'DQ', 'SCPS', 'UNH', 'SAVA', 'NEGG', 'NVCR', 'GME', 'MRNA', 'DASH', 'GS', 'DDS', 'OSTK', 'DIS', 'ACRS', 'UHAL', 'AMD', 'SQ', 'KSS', 'LMT', 'BTBT', 'HOOD', 'BIDU', 'VRPX', 'CRMT', 'HD', 'DKS']
stocks ['AUVI', 'GOVX', 'AEHR', 'ORMP', 'BNTX', 'MRNA', 'AFRM', 'AZN', 'UPST', 'AGEN', 'GPS', 'LTHM', 'ADBE', 'NVAX', 'NVDA', 'NURO', 'NFLX', 'BCRX', 'AMD', 'M', 'SAVA', 'UPS', 'ORCL', 'SQ', 'HD', 'PYPL', 'KR', 'TQQQ', 'DELL', 'TTD', 'SNAP', 'FB', 'WMT', 'MSFT', 'KO', 'MS', 'CLF', 'AAL', 'AAPL', 'MRVL', 'NKE', 'MMM', 'PFE', 'CSCO', 'AMZN', 'PBR', 'DIS', 'ABNB', 'OCGN', 'AMAT', 'DBVT', 'ASML', 'FCX', 'OXBR', 'CRM', 'VNE', 'MARA', 'TSLA', 'INTC', 'FRO', 'MRO', 'CEMI', 'BLIN', 'VTNR', 'FCEL', 'GLD', 'QCOM', 'NIO', 'GS', 'XOM', 'PG', 'ANY']
days best ordered with preMarket stocks
['AUVI', 'BNTX', 'MRNA', 'AFRM', 'UPST', 'NVAX', 'AMD', 'SAVA', 'SQ', 'HD', 'AMZN', 'DIS', 'ASML', 'TSLA', 'GS']

daysBest = 2

daysBestStocks ['EJH', 'SCPS', 'NEGG', 'VRPX', 'AUVI', 'NRXP', 'KOSS', 'BTBT', 'CARV', 'GME', 'BIDU', 'SAVA', 'ACRS', 'TSLA', 'ANVS', 'NVAX', 'ADGI', 'HOOD', 'DQ', 'AFRM', 'ZM', 'SE', 'BNTX', 'KSS', 'GPN', 'NVCR', 'AMZN', 'W', 'MRNA', 'UPST', 'SQ', 'OSTK', 'AMD', 'DPZ', 'SAM', 'REGN', 'DE', 'ROLL', 'MDB', 'SNOW', 'DASH', 'DIS', 'CRMT', 'DKS', 'UNH', 'DDS', 'GS', 'ASML', 'LMT', 'HD', 'BKNG', 'AZO', 'GOOG', 'UHAL']
stocks ['AUVI', 'GOVX', 'AEHR', 'ORMP', 'BNTX', 'MRNA', 'AFRM', 'AZN', 'UPST', 'AGEN', 'GPS', 'CIEN', 'ADBE', 'NVAX', 'NVDA', 'NURO', 'NFLX', 'LTHM', 'SE', 'BCRX', 'GOOG', 'AMD', 'M', 'UPS', 'SAVA', 'ORCL', 'SQ', 'HD', 'TTD', 'TQQQ', 'PYPL', 'KR', 'DELL', 'FB', 'KO', 'MSFT', 'WMT', 'SNAP', 'MS', 'CLF', 'PBR', 'AAPL', 'MRVL', 'NKE', 'MMM', 'AAL', 'CSCO', 'PFE', 'AMZN', 'FCX', 'ABNB', 'OCGN', 'AMAT', 'DBVT', 'INTC', 'OXBR', 'VNE', 'MARA', 'TSLA', 'CRM', 'ASML', 'GLD', 'FRO', 'MRO', 'OXY', 'CEMI', 'DIS', 'BLIN', 'VTNR', 'QCOM', 'NIO', 'FCEL', 'XOM', 'PG', 'GS', 'ANY']
days best ordered with preMarket stocks
['AUVI', 'BNTX', 'MRNA', 'AFRM', 'UPST', 'NVAX', 'SE', 'GOOG', 'AMD', 'SAVA', 'SQ', 'HD', 'AMZN', 'TSLA', 'ASML', 'DIS', 'GS']

daysBest = 0
stockSegs 0 ['AUVI', 'GOVX', 'AEHR', 'ORMP', 'MRNA', 'BNTX', 'AFRM', 'AZN', 'UPST', 'AGEN', 'GPS', 'CIEN', 'ADBE', 'NVAX', 'NVDA', 'NURO', 'NFLX', 'LTHM', 'SE', 'BCRX', 'SAVA']

