NVDA Gain: $ -16.54 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 6
PEP Gain: $ -2.11 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS5_CB4_CS2_AL_UA_DU7_DL2 4
YETI Gain: $ -1.43 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS5_CB5_CS5_AV_VI_DU6_UA 3
ATVI Gain: $ -1.41 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB2_CS5_DU6_AL 2
VLO Gain: $ -0.97 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB4_OS4_CB5_CS4_HM_AV_DU7_DL2_TG 13
DELL Gain: $ -0.59 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM 15
FIGS Gain: $ -0.39 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB5_CS5_HM_TR_DB10_DU7_AV_DL2 7
FCX Gain: $ -0.29 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB1_OS4_CB3_CS2_AV_TS_DU8_UA_DL2 9
FLO Gain: $ -0.29 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 11
WYNN Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB4_CS5_RV_AV_DU7 18
T Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 2 3 5 12 17
F Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS2_CB5_CS4_HM_AV_DU7_AL_UA 7 9 11 14
PBR Gain: $ 0.14 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB3_OS2_CB2_CS5_HM_TR_DU6_AL_UA 10
RKT Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB2_OS2_CB3_CS4_QL_DU6_UA 12
ALC Gain: $ 0.25 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_AV_TG_DU7 21
WM Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB5_LO_HL_QM_OB3_OS2_CB3_CS2_RV_AV_UA_DU8_AL_DL2 16
CL Gain: $ 0.38 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB5_OS2_CB2_CS5_RV_AV_DU7_DL1 20
NNOX Gain: $ 0.5 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB5_CS5_IR3 8
SPG Gain: $ 1.08 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_HM_AV_DB6 19
ARGX Gain: $ 5.0 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB4_CS3_HM_TR_DB30_DU7_DL1 1
TSLA Gain: $ 10.96 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB3_CS3_AL_LI_DU6_AV_UA_DU7 17
Days gain with 21 stocks: -5.29 20230717
