RGEN Gain: $ -7.28 Win %: 0.0 in 1 days with algo TB2_HL_LO_QM_OB1_OS1_CB5_CS5_HM_AL 1 1
TRI Gain: $ -2.86 Win %: 0.0 in 1 days with algo TB5_HI_HL_QM_OB3_OS2_CB2_CS5_HM_AV_DB6_DU6 20
JBL Gain: $ -2.15 Win %: 0.0 in 1 days with algo TB2_HL_HS_QM_OB1_OS1_CB4_CS4_SS 17
FANG Gain: $ -1.94 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS5_UA_WT_DU8_AV_DL2 15
NEM Gain: $ -1.73 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB3_OS2_CB5_CS5_RV_AV_DU7 9
VIPS Gain: $ -1.12 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS2_DU8_TG 11
BABA Gain: $ -0.92 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS3_CB5_CS4_AV_VI_DU6_UA_AL_DU7 10
MLCO Gain: $ -0.9 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB2_OS2_CB4_CS5_UA_DU7 3
TAL Gain: $ -0.79 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB3_OS3_CB3_CS4_LI_DU7_UA 2
QCOM Gain: $ -0.78 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_AV_TS_UA_AL 13
XLV Gain: $ -0.53 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB2_CS5_RV_AL_DU7_DL1 15 4
PFGC Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS5_CB5_CS3_DU8_AL 10
TME Gain: $ -0.45 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB3_OS4_CB5_CS3_DU12_TG_AL 7
NOV Gain: $ -0.25 Win %: 0.0 in 1 days with algo TB3_HL_QM_TG_OB1_OS5_CB5_CS2_AV_IT_DU8_DL2 19
ZLAB Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB5_CS2_HM_TR_DB6_UA_DU8_AV_DL2 3
GOGL Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 21
GSM Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB1_HL_QM_OB3_OS3_CB3_CS3_TR_IR5 11
CPG Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_AO_AC 8
SOFI Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 5
UWMC Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS2_CB2_CS4_AV_UA_DU7 9
XLP Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS5_CB5_CS3_IT_QL_DB6_AV_TG_DU7_UA_DL1 12
ALVR Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS2_CB3_CS2_AL_TS_TG 7
MT Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB5_OS2_CB5_CS5_HM_AL_DU7_UA_DL2 14 6
YPF Gain: $ -0.1 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB4_OS2_CB4_CS4_HM_AV_DU8_DL2_UA 16
SBLK Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB3_CS5_AL_TS_DU8_AV_DL2 14
ACI Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB5_HI_HL_QM_OB3_OS3_CB3_CS3_LI_DU7 8
AEO Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB4_OS4_CB5_CS4_HM_TG_DU8_UA_AV_DL2 6
SKX Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB4_OS2_CB5_CS5_AL_LI_UA_DU7_AV_DL2 20
EVO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS5_RV_DU7 19
GLD Gain: $ 0.02 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB4_OS2_CB5_CS5_AO_DU6 21
SLV Gain: $ 0.05 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB5_OS2_CB2_CS5_AV_TS_DU7_UA_DL1 2
LITE Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB5_CS3_VI_AL 4
GWRE Gain: $ 0.17 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_TR_TS 16
CPE Gain: $ 0.3 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB5_OS5_CB5_CS5_RV_AL_DB30 18
FRO Gain: $ 0.4 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 12
GM Gain: $ 0.94 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB2_OS4_CB5_CS2_AL_TS_DU7 17
PDD Gain: $ 1.17 Win %: 100.00 in 1 days with algo TB5_HL_QM_OB3_OS4_CB1_CS5_RV_DU6_AV 13
NXPI Gain: $ 1.44 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB1_OS1_CB5_CS5_HM_AV 18
MCD Gain: $ 2.45 Win %: 100.00 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB2_CS5_DU8_AL 5
Days gain with 39 stocks: -16.73 20230620
