AAPL Gain: $ -4.49 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB2_OS2_CB2_CS5_IR3_DU4_AL_UA_UA_UA_UA_UA 10 14
LLY Gain: $ -4.38 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 7
TTC Gain: $ -3.76 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_HM 1 1
TMUS Gain: $ -3.09 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS4_HM_AV_DU7_AL_DL2 11
AMAT Gain: $ -2.12 Win %: 0.0 in 1 days with algo TB4_LO_QM_OB3_OS3_CB4_CS4_HM 13 16
DUK Gain: $ -0.99 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_QL_DU7_AL_DL2 9
SNA Gain: $ -0.93 Win %: 0.0 in 1 days with algo TB1_HL_HI_QM_OB4_OS4_CB4_CS4_HM_AL 15
JNJ Gain: $ -0.7 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS3_AV_TS_DU8_UA_DL2 21 19
QCOM Gain: $ -0.45 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_AV_TS_UA_AL 9 10
AEHR Gain: $ -0.44 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 6 4
CI Gain: $ -0.38 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AL 21
CAH Gain: $ -0.37 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU7_DL2 14 18
UNIT Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB1_OS4_CB3_CS3_AV_TS_DU7 3 3
CHPT Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB3_OS4_CB3_CS2_AV_TS_DU8_UA_DL2_AL 5 8
OSTK Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV 12
SOXL Gain: $ -0.04 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB5_OS2_CB5_CS4_SS_AL 20
STX Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB3_CS3_RV_AV_DB30_DU7_DL1_UA_DL2_AL_TG_DU8 4 6
TIGR Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB3_OS2_CB3_CS5_DU6_AL 8 13
AMEH Gain: $ 0.04 Win %: 100.00 in 1 days with algo TB5_HL_LO_QM_OB1_OS1_CB3_CS3_RV_AV 7 5
AUPH Gain: $ 0.06 Win %: 100.00 in 1 days with algo TB3_HL_HS_QM_OB2_OS2_CB4_CS4_RV 17
DDD Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB1_OS1_CB5_CS5_IT 20
CL Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB5_OS2_CB2_CS5_RV_AV_DU7_DL1 11
VRNT Gain: $ 0.51 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB3_OS3_CB5_CS5_AC 2 2
IMVT Gain: $ 0.79 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS3_DU8_AL 19
JBL Gain: $ 0.81 Win %: 100.00 in 1 days with algo TB2_HL_HS_QM_OB1_OS1_CB4_CS4_SS 17 15
BROS Gain: $ 0.94 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB2_OS2_CB5_CS4_DU7_DL2_DL1 16
SITM Gain: $ 0.96 Win %: 100.00 in 1 days with algo TB4_HI_QM_OB1_OS1_CB5_CS5_RV_AL 18 12
Days gain with 27 stocks: -18.19 20230907
