CRM Gain: $ -3.19 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB5_OS2_CB3_CS5_TR_TS_DU7_DL1 14
NEWR Gain: $ -2.06 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_TR 6
GH Gain: $ -1.09 Win %: 0.0 in 1 days with algo TB2_HL_HI_QM_OB2_OS2_CB5_CS5_RV 9
FRO Gain: $ -0.75 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 5
F Gain: $ -0.74 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS2_CB5_CS4_HM_AV_DU7_AL_UA 5 16
AZN Gain: $ -0.56 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS4_CB3_CS2_RV_DU7_AV_DL2_DU5 21
SE Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS2_CB2_CS4_HM_TR_DU8_DL2 12
KO Gain: $ -0.4 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS4_CB4_CS4_IT_QL_DB6_DU7_UA_DL1 11
LOGI Gain: $ -0.33 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB5_OS3_CB5_CS4_SS_DU7_DL2 17
LABU Gain: $ -0.22 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS2_CB2_CS5_AL_LI_DU7_AV_DL2 8
SLV Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB5_OS2_CB2_CS5_AV_TS_DU7_UA_DL1 10
GPS Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB3_OS2_CB5_CS5_DU6_AL 4
RIG Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 18
COTY Gain: $ 0.14 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS5_LI 20
SOXL Gain: $ 1.31 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB5_OS2_CB5_CS4_SS_AL 15
MRVL Gain: $ 1.63 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_IT_TS 1
BBY Gain: $ 1.65 Win %: 100.00 in 1 days with algo TB5_EO_EC_QM_OB3_OS4_CB5_CS4_TR_UA_AL 7
WDAY Gain: $ 2.12 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB5_OS3_CB2_CS5_AL_TS_TG_DU7_DL2 2
PDD Gain: $ 2.24 Win %: 100.00 in 1 days with algo TB5_HL_QM_OB3_OS4_CB1_CS5_RV_DU6_AV 3
ORCL Gain: $ 2.52 Win %: 100.00 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5 19
AMD Gain: $ 22.86 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB3_OS4_CB4_CS4_HM_AL_DU6_UA_AV 13
Days gain with 21 stocks: 24.37 20230526
