AXP Gain: $ -1.98 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB3_OS2_CB5_CS3_TR_TS_DU7_UA_DL2 19
BIDU Gain: $ -1.7 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB3_OS3_CB5_CS3_AL_TS_DU6_AV_DU6 21
KR Gain: $ -1.69 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS3_CB3_CS5_TR_IR3_DU8_DL2_UA_AV 3
ANET Gain: $ -0.88 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB2_OS5_CB5_CS2_QP_QL_PM_DU6_UA_AV_DU7_AL 4
LAZR Gain: $ -0.81 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS2_AL_DU6_AL 17
LEN Gain: $ -0.55 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB4_OS4_CB5_CS5_RV_AV 7
AFRM Gain: $ -0.53 Win %: 0.0 in 1 days with algo TB3_HI_QM_OB2_OS2_CB5_CS5_RV_AV 9
LI Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB5_OS5_CB2_CS4_IT_QL_DB10_AV_TG_DU7_DL1_DU8_UA_DL2_AL 10 12
WOOF Gain: $ -0.35 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS4_DU6_TG_UA 18
UNH Gain: $ -0.29 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS3_CB4_CS4_RV_TR_AV_DU8_AL_DL2 2
PPC Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS3_HM_DU7_UA_DL2 8
INTC Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 6
CHPT Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB3_OS4_CB3_CS2_AV_TS_DU8_UA_DL2_AL 14
HAS Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB2_OS2_CB5_CS5_PM_DU7_UA_AV_DL2 13
PG Gain: $ 0.35 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 20
MDT Gain: $ 0.38 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB3_CS3_AL_TS 11
SOFI Gain: $ 0.41 Win %: 100.00 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 5
LITE Gain: $ 1.0 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB5_CS3_VI_AL 12
BZ Gain: $ 1.11 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB5_OS2_CB2_CS5_TR_TS_DU8_AV_DL2 16
MNSO Gain: $ 1.38 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 15
ALDX Gain: $ 3.13 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB2_OS4_CB5_CS4_HM_AV_UA_DU7 1
Days gain with 21 stocks: -1.53 20230615
