MCD Gain: $ -3.27 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB2_CS5_DU8_AL 19
ABBV Gain: $ -2.77 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS3_CB5_CS5_HM_AV_DB6_DU7_UA_DL2 20
IMVT Gain: $ -1.49 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS3_DU8_AL 6 15
VRTX Gain: $ -1.03 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB5_CS2_SS_UA_AL_DU8_AV_DL2 6
AN Gain: $ -0.82 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB4_OS2_CB4_CS4_HM_AV_DB6_DU7_DL2_DU8_AL 13 17
APP Gain: $ -0.81 Win %: 0.0 in 1 days with algo TB3_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR_DB10 4
PENN Gain: $ -0.66 Win %: 0.0 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5_AL 14
TH Gain: $ -0.65 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS4_CB4_CS3_QL_DU7_UA_TG 3 2 18
MO Gain: $ -0.34 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB4_OS2_CB5_CS5_RV_DU8 2 14
IMTX Gain: $ -0.24 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS5_CB3_CS2_RV_DU7 21
TSCO Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV_DB6 16
INFL Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB1_HI_QM_OB3_OS2_CB5_CS3_HM_AV_DU7 4
AZPN Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS5_CB3_CS5_AV_DU7_DL2 8
MNSO Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 1 20
UWMC Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS2_CB2_CS4_AV_UA_DU7 7
CHKP Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS2_CB2_CS5_RV_AV_DB6_DU6_AL 1
SBLK Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB3_CS5_AL_TS_DU8_AV_DL2 9
RIG Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 12
CCL Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 10
RIOT Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 15
ANF Gain: $ -0.04 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS5_CB2_CS2_RV_DU8_AL_DL2 17
HPQ Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB1_OS1_CB5_CS5_TS 5
TRI Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB5_HI_HL_QM_OB3_OS2_CB2_CS5_HM_AV_DB6_DU6 10
BJ Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB1_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AV_DB30 11
DNUT Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV 19
IRDM Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB4_CS3_AL_DU8_AV_DL2 7
PDCO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB4_OS2_CB4_CS5_HM_AL_DU7_DL1 13
SNA Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HL_HI_QM_OB4_OS4_CB4_CS4_HM_AL 12
SUPN Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB4_OS5_CB2_CS5_AV_DU8_AL_DL2 9
T Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 3 6 8 15 2 6 10 11 15 16 18 19 21
JPM Gain: $ 0.17 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB4_OS3_CB3_CS5_HM_AV_DB10_DU6_UA_UA 21
GE Gain: $ 0.18 Win %: 100.00 in 1 days with algo TB1_HI_QM_OB4_OS2_CB4_CS5_AV_IT_TG_AL_DU8_DL2 16
PPC Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS3_HM_DU7_UA_DL2 3
STE Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB2_OO_QM_OB3_OS3_CB5_CS5_AV 11
UTHR Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB3_HL_LO_QM_OB1_OS1_CB3_CS3_RV 2
V Gain: $ 0.43 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB2_OS4_CB4_CS4_RV_AV_DB30_DU7 5 6 20 6 15 17
ORCL Gain: $ 1.45 Win %: 100.00 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5 18
Days gain with 37 stocks: -10.07 20230914
