BABA Gain: $ -10.35 Win %: 0 in 1 days with algo TB5_LO_QM_OB3_OS3_CB5_CS4_AV_VI_DU6_UA_AL_DU7 5
MPC Gain: $ -3.05 Win %: 0 in 1 days with algo TB5_OO_QM_OB5_OS2_CB2_CS5_PM_DU7_UA_DL2_DU8_AL_TG 12
WM Gain: $ -1.4 Win %: 0 in 1 days with algo TB5_LO_HL_QM_OB3_OS2_CB3_CS2_RV_AV_UA_DU8_AL_DL2 13
ON Gain: $ -1.0 Win %: 0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB4_CS4_RV_TR_DB6_DU7 16
TME Gain: $ -0.93 Win %: 0 in 1 days with algo TB1_OO_QM_OB3_OS4_CB5_CS3_DU12_TG_AL 18
WDAY Gain: $ -0.9 Win %: 0 in 1 days with algo TB5_OO_QM_OB5_OS3_CB2_CS5_AL_TS_TG_DU7_DL2 14
INTC Gain: $ -0.74 Win %: 0 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 3
RIOT Gain: $ -0.5 Win %: 0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 4
CCL Gain: $ -0.48 Win %: 0 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 8
ERJ Gain: $ -0.48 Win %: 0 in 1 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_HM_AV 17
RIG Gain: $ -0.31 Win %: 0 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 11
UBS Gain: $ -0.31 Win %: 0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 15
SBS Gain: $ -0.15 Win %: 0 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 20
MNST Gain: $ -0.12 Win %: 0 in 1 days with algo TB5_LO_QM_OB4_OS3_CB4_CS4_RV_AL_UA 1
AU Gain: $ 0.03 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 10
EVGO Gain: $ 0.13 Win %: 100.00 in 1 days with algo TB1_HL_HI_QM_OB5_OS5_CB4_CS4_RV_AV 9
WOOF Gain: $ 0.55 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS4_DU6_TG_UA 7
MU Gain: $ 0.64 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP 19
TAL Gain: $ 0.78 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB3_OS3_CB3_CS4_LI_DU7_UA 6
LULU Gain: $ 3.71 Win %: 100.00 in 1 days with algo TB3_PL_QM_OB5_OS1_CB2_CS5_AL_TS_DU6_UA_AV 2
BA Gain: $ 4.61 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_DB6_DU7_AL_DL2 5 21
Days gain with 21 stocks: -10.27 20230330
