ADBE Gain: $ -23.62 Win %: 0.0 in 3 days with algo TB1_LO_HL_QM_OB2_OS2_CB2_CS5_LI_DU8_AV_DL2 4
ADBE Gain: $ -11.81 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB2_CS5_LI_DU8_AV_DL2 4
VLO Gain: $ -3.36 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB4_OS4_CB5_CS4_HM_AV_DU7_DL2_TG 11
VLO Gain: $ -3.36 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB4_OS4_CB5_CS4_HM_AV_DU7_DL2_TG 11
BLDR Gain: $ -3.21 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB5_OS3_CB4_CS5_HM_AV_DB30_DU7_UA_DL2 15
BLDR Gain: $ -3.21 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB5_OS3_CB4_CS5_HM_AV_DB30_DU7_UA_DL2 15
AMZN Gain: $ -2.2 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS3_CB5_CS5_LI_DU6_UA_TG_DU7_AV_DL2_AL 10
AMZN Gain: $ -2.2 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS3_CB5_CS5_LI_DU6_UA_TG_DU7_AV_DL2_AL 10
VMW Gain: $ -1.72 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB1_CS1_QL 1
DKNG Gain: $ -1.22 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_HM_AL_DU7 18
DKNG Gain: $ -1.22 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_HM_AL_DU7 18
VIGI Gain: $ -0.77 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS4_CB5_CS2_AV_TS_DU7_AL
VIGI Gain: $ -0.77 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS4_CB5_CS2_AV_TS_DU7_AL
TECL Gain: $ -0.66 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS2_CB5_CS4_AO_AC_DU7_UA_AV_DL1 17
TECL Gain: $ -0.66 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS2_CB5_CS4_AO_AC_DU7_UA_AV_DL1 17
TVTX Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS2_RV_AV_DB30_DU7_UA_DL2
TVTX Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS2_RV_AV_DB30_DU7_UA_DL2
BCH Gain: $ -0.44 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_TR_IR3_DU7_AV_DL2 5
BCH Gain: $ -0.44 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_TR_IR3_DU7_AV_DL2 5
CSCO Gain: $ -0.4 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_DL1 2
CSCO Gain: $ -0.4 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_DL1 2
MNSO Gain: $ -0.37 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 3
MNSO Gain: $ -0.37 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 3
GFI Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 21
GFI Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 21
AKAM Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB5_OS5_CB3_CS4_HM_AV_DU7_DL1 7
AKAM Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB5_OS5_CB3_CS4_HM_AV_DU7_DL1 7
ORCL Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5 16
Error check the CL dam it. exiting...
Error check the CL dam it. exiting...
ORCL Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5 16
VMW Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB1_CS1_QL 1
PSTG Gain: $ 0.21 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS5_QL_DU8_UA_AV_DL2 6
PSTG Gain: $ 0.21 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS5_QL_DU8_UA_AV_DL2 6
MRVL Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_IT_TS 19
MRVL Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_IT_TS 19
CAT Gain: $ 0.62 Win %: 100.00 in 1 days with algo TB5_HI_HL_QM_OB2_OS4_CB2_CS5_IT_QL_DB6_DU8_AV_DL2 12
CAT Gain: $ 0.62 Win %: 100.00 in 1 days with algo TB5_HI_HL_QM_OB2_OS4_CB2_CS5_IT_QL_DB6_DU8_AV_DL2 12
CELH Gain: $ 0.88 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB5_CS4_HM_AV_DB30 13
CELH Gain: $ 0.88 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB5_CS4_HM_AV_DB30 13
SBSW Gain: $ 1.1 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB2_OS2_CB3_CS5_DU12_AL_UA 8
SBSW Gain: $ 1.1 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB2_OS2_CB3_CS5_DU12_AL_UA 8
RACE Gain: $ 2.41 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB3_OS2_CB5_CS4_RV_AV_DU8_UA_DL2 9
RACE Gain: $ 2.41 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB3_OS2_CB5_CS4_RV_AV_DU8_UA_DL2 9
TQQQ Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB3_HS_HL_QM_OB5_OS2_CB4_CS5_SS_DU6 20
TQQQ Gain: $ 3.9 Win %: 100.00 in 1 days with algo TB3_HS_HL_QM_OB5_OS2_CB4_CS5_SS_DU6 20
NVDA Gain: $ 11.63 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 14
NVDA Gain: $ 11.63 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 14
Days gain with 25 stocks: -29.32 20230921
Days gain with 49 stocks: 3.57 20230921
