LIN Gain: $ -3.38 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS3_CB3_CS5_AL_TS_UA_AV 9
ABBV Gain: $ -1.65 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS3_CB5_CS5_HM_AV_DB6_DU7_UA_DL2 20
NIO Gain: $ -1.35 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_HM_AV_DB10_DU6_DU6_AL_TG_UA_UA_UA_UA_UA 4
KMB Gain: $ -1.09 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS4_CB4_CS3_UA_WT_DU8_AV_DL2 21
MNSO Gain: $ -0.94 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 2
SJM Gain: $ -0.78 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB3_OS2_CB5_CS4_DB6_UA 15
AVGR Gain: $ -0.7 Win %: 0.0 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB2_CS2_QL 1
LI Gain: $ -0.56 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB5_OS5_CB2_CS4_IT_QL_DB10_AV_TG_DU7_DL1_DU8_UA_DL2_AL 7 9
EURN Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS3_AV_VI_DU8_DL2_AL 10
COTY Gain: $ -0.31 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS5_LI 5
ALC Gain: $ -0.22 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_AV_TG_DU7 14
CL Gain: $ -0.19 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB5_OS2_CB2_CS5_RV_AV_DU7_DL1 6
GOGL Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 13
XLV Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB2_CS5_RV_AL_DU7_DL1 19
MRK Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS2_CB2_CS3_DB10_DU7_TG_AV_DL2 11
DRD Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_HS_HL_QM_OB2_OS3_CB4_CS3_DU8_DL2_AS
ACI Gain: $ 0.06 Win %: 100.00 in 1 days with algo TB5_HI_HL_QM_OB3_OS3_CB3_CS3_LI_DU7 12
SBLK Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB3_OS3_CB3_CS5_AL_TS_DU8_AV_DL2 16
SPG Gain: $ 0.08 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_HM_AV_DB6 17
RIG Gain: $ 0.17 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 8
SQ Gain: $ 0.25 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB2_OS3_CB3_CS3_RV_DU7_AL_DL2 18
UWMC Gain: $ 0.31 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB4_OS2_CB2_CS4_AV_UA_DU7 3
Days gain with 22 stocks: -11.12 20230919
