DG Gain: $ -8.3 Win %: 0.0 in 1 days with algo TB5_HL_QM_OB1_OS2_CB2_CS1_LI_DU8_AV_DL2 11
DOCS Gain: $ -6.27 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB4_OS2_CB4_CS5_AV_VI_DU6_UA 18
AMD Gain: $ -1.97 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS4_CB4_CS4_HM_AL_DU6_UA_AV 21
MMM Gain: $ -1.95 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB3_OS3_CB5_CS4_SS_DU7_AV_DL1 16
EA Gain: $ -1.68 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB5_OS2_CB4_CS4_IT_DU7_DL2 13
FANG Gain: $ -1.52 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS5_UA_WT_DU8_AV_DL2 17
OVV Gain: $ -1.11 Win %: 0.0 in 1 days with algo TB5_HI_HL_QM_OB3_OS5_CB5_CS3_WT_DU7 7
KHC Gain: $ -0.54 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_RV_QP_QL_DB10_DU6_UA_DU7_DL2 14
FRO Gain: $ -0.43 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 8
EURN Gain: $ -0.31 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS3_AV_VI_DU8_DL2_AL 2
CRH Gain: $ -0.25 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB3_OS2_CB4_CS3_RV_AV_DB6_DU7 10
KODK Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB4_OS2_CB5_CS4_RV_AL_DB10_DU6_UA_AV 4
RIOT Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 1
ABNB Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB3_OS2_CB3_CS5_RV_AV_DB10_DU7_UA_DL1 5
F Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS2_CB5_CS4_HM_AV_DU7_AL_UA 6 8 12 17
ISEE Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS4_CB5_CS3_UA_DU8_DL2 3
IONQ Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 9
RIG Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 15
YPF Gain: $ 0.33 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB4_OS2_CB4_CS4_HM_AV_DU8_DL2_UA 6
MRO Gain: $ 1.08 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB5_OS3_CB5_CS3_HM_AV_DU7 19
AAPL Gain: $ 13.06 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB2_OS2_CB2_CS5_IR3_DU4_AL_UA_UA_UA_UA_UA 20
Days gain with 21 stocks: -10.05 20230605
