PDD Gain: $ -3.65 Win %: 0.0 in 1 days with algo TB5_HL_QM_OB3_OS4_CB1_CS5_RV_DU6_AV 7
DG Gain: $ -2.99 Win %: 0.0 in 1 days with algo TB5_HL_QM_OB1_OS2_CB2_CS1_LI_DU8_AV_DL2 11
CELH Gain: $ -2.88 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB5_CS4_HM_AV_DB30 1
BBY Gain: $ -1.47 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS4_CB5_CS4_TR_UA_AL 9
MNSO Gain: $ -1.43 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 8
BABA Gain: $ -1.41 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS3_CB5_CS4_AV_VI_DU6_UA_AL_DU7 18
TJX Gain: $ -1.21 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB3_OS3_CB2_CS3_AL_TS_UA_DU8_DL2 3
ROST Gain: $ -0.96 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS4_CB5_CS5_HM 10
VIPS Gain: $ -0.94 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS2_DU8_TG 12
JD Gain: $ -0.25 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS3_CB4_CS2_AV_TS_UA 17
ALC Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_AV_TG_DU7 4
FRO Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 15
FANG Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS5_UA_WT_DU8_AV_DL2 6
UBS Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 16
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 19
PSO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB4_OS2_CB5_CS2_AV_TS_DU6_AV 14
TGT Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS5_AO_AC_UA 2
CAH Gain: $ 0.66 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU7_DL2 13
M Gain: $ 1.28 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS3_CB4_CS4_RV_TR_DB10_DU8_UA_DL2 8 20
AAP Gain: $ 1.8 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS5_AL_UA_AV 5
DLTR Gain: $ 4.62 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB3_OS2_CB3_CS5_AL_LI_DU8_AV_DL2 21
Days gain with 21 stocks: -8.67 20231115
