EDU Gain: $ -4.85 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS5_CB5_CS2_DU12_TG 5
ALB Gain: $ -3.6 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB3_OS5_CB5_CS4_RV_AL_DB30_UA_DU7_AV_DL2 20
ANVS Gain: $ -1.96 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB3_OS2_CB3_CS5_RV_DU7_DL2 6
RACE Gain: $ -1.47 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB3_OS2_CB5_CS4_RV_AV_DU8_UA_DL2 19
SPG Gain: $ -1.45 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_HM_AV_DB6 13
PLD Gain: $ -1.34 Win %: 0.0 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB2_CS2_AL_TS 10
CLX Gain: $ -1.29 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS3_AV_DU7_UA_DL2 12
KSS Gain: $ -1.0 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB2_OS3_CB4_CS5_AL_UA_AV_DU5_DL2 15
INTC Gain: $ -0.88 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 17
SBLK Gain: $ -0.54 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB3_CS5_AL_TS_DU8_AV_DL2 1
ROST Gain: $ -0.52 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS4_CB5_CS5_HM 14
CVS Gain: $ -0.36 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS4_CB5_CS2_RV_AV_DU7 4
SJM Gain: $ -0.34 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB3_OS2_CB5_CS4_DB6_UA 3
LTHM Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB4_CS4_HM_AV_DB30_DU7_UA_DL2 21
T Gain: $ -0.22 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 8 11 14 17 21
GOGL Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 2
MNSO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 7
UBS Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 9
HOOD Gain: $ 0.29 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB3_CS3_HM_TR 16
TAL Gain: $ 0.85 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB3_OS3_CB3_CS4_LI_DU7_UA 11
PDD Gain: $ 3.51 Win %: 100.00 in 1 days with algo TB5_HL_QM_OB3_OS4_CB1_CS5_RV_DU6_AV 18
Days gain with 21 stocks: -15.38 20231205
