KMB Gain: $ -2.77 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS4_CB4_CS3_UA_WT_DU8_AV_DL2 12
GPN Gain: $ -1.24 Win %: 0.0 in 1 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL 19
PG Gain: $ -1.12 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 9
DKNG Gain: $ -0.77 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_HM_AL_DU7 10
GIS Gain: $ -0.77 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB1_OS1_CB3_CS1_AL_UA_AV 3
MAT Gain: $ -0.54 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB4_OS2_CB4_CS4_SR_DU8_AV_DL2 5
GLD Gain: $ -0.48 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB4_OS2_CB5_CS5_AO_DU6 20
CAH Gain: $ -0.47 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU7_DL2 7
DDD Gain: $ -0.32 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB1_OS1_CB5_CS5_IT 21
VZ Gain: $ -0.24 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB4_OS3_CB5_CS4_AL_UA 1
NEM Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB3_OS2_CB5_CS5_RV_AV_DU7 11
T Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 2 5 17
IMMR Gain: $ 0.06 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 18
JNJ Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS3_AV_TS_DU8_UA_DL2 16
AXP Gain: $ 1.14 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB3_OS2_CB5_CS3_TR_TS_DU7_UA_DL2 6
JBL Gain: $ 1.56 Win %: 100.00 in 1 days with algo TB2_HL_HS_QM_OB1_OS1_CB4_CS4_SS 4
ORCL Gain: $ 1.8 Win %: 100.00 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5 15
K Gain: $ 2.06 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 10 12 14
UNH Gain: $ 5.54 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS3_CB4_CS4_RV_TR_AV_DU8_AL_DL2 13
BABA Gain: $ 6.65 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB3_OS3_CB5_CS4_AV_VI_DU6_UA_AL_DU7 8
COST Gain: $ 11.71 Win %: 100.00 in 1 days with algo TB5_PL_QM_OB4_OS3_CB5_CS4_DU8_UA_TG_AV_DL2_AL 17
Days gain with 21 stocks: 22.23 20230707
