LULU Gain: $ -7.14 Win %: 0 in 1 days with algo TB3_PL_QM_OB5_OS1_CB2_CS5_AL_TS_DU6_UA_AV 15
BA Gain: $ -5.1 Win %: 0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_DB6_DU7_AL_DL2 17
CSIQ Gain: $ -1.79 Win %: 0 in 1 days with algo TB5_CC_QM_OB4_OS2_CB5_CS4_AV_UA_TG_DU8_AL_DL2 9
VMW Gain: $ -1.57 Win %: 0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB1_CS1_QL 16
LAZR Gain: $ -1.46 Win %: 0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS2_AL_DU6_AL 4
IMVT Gain: $ -0.64 Win %: 0 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS3_DU8_AL 6
UBS Gain: $ -0.5 Win %: 0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 13
TH Gain: $ -0.33 Win %: 0 in 1 days with algo TB3_LO_QM_OB2_OS4_CB4_CS3_QL_DU7_UA_TG 5 11
ISEE Gain: $ -0.09 Win %: 0 in 1 days with algo TB1_HS_QM_OB3_OS4_CB5_CS3_UA_DU8_DL2 18
SUPN Gain: $ -0.02 Win %: 0 in 1 days with algo TB1_LO_HL_QM_OB4_OS5_CB2_CS5_AV_DU8_AL_DL2 19
CPG Gain: $ 0.01 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_AO_AC 20
SOFI Gain: $ 0.03 Win %: 100.00 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 7
KALV Gain: $ 0.23 Win %: 100.00 in 1 days with algo TB1_HI_QM_OB3_OS3_CB4_CS4_PM 21
DNUT Gain: $ 0.3 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV 1
GLSI Gain: $ 0.3 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB2_OS2_CB5_CS5_HM_AL 12
GME Gain: $ 0.6 Win %: 100.00 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB3_CS5_AV_TS_DU7 2
WOOF Gain: $ 0.86 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS4_DU6_TG_UA 3
ALDX Gain: $ 0.98 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB2_OS4_CB5_CS4_HM_AV_UA_DU7 8
UTHR Gain: $ 2.02 Win %: 100.00 in 1 days with algo TB3_HL_LO_QM_OB1_OS1_CB3_CS3_RV 5
AEHR Gain: $ 2.98 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 10
NVDA Gain: $ 10.04 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 14
Days gain with 21 stocks: -0.29 20230322
