MSTR Gain: $ -12.18 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AV 12
ON Gain: $ -3.85 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB4_CS4_RV_TR_DB6_DU7 17
LULU Gain: $ -3.48 Win %: 0.0 in 1 days with algo TB3_PL_QM_OB5_OS1_CB2_CS5_AL_TS_DU6_UA_AV 3
WDAY Gain: $ -2.48 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB5_OS3_CB2_CS5_AL_TS_TG_DU7_DL2 15
PLD Gain: $ -1.5 Win %: 0.0 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB2_CS2_AL_TS 21
CROX Gain: $ -1.46 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB2_OS4_CB5_CS4_QL_AV 8
BABA Gain: $ -1.15 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS3_CB5_CS4_AV_VI_DU6_UA_AL_DU7 7
SPG Gain: $ -1.01 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_HM_AV_DB6 20
TME Gain: $ -0.9 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB3_OS4_CB5_CS3_DU12_TG_AL 19
CCL Gain: $ -0.42 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 6
AU Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 9
BA Gain: $ -0.19 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_DB6_DU7_AL_DL2 7 11
EVGO Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB1_HL_HI_QM_OB5_OS5_CB4_CS4_RV_AV 2
WOOF Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS4_DU6_TG_UA 18
ET Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB4_OS2_CB3_CS4_AV_TS_DU7_AL_DL2 13
TAL Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB3_OS3_CB3_CS4_LI_DU7_UA 16
SJR Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS5_HM_DU7 5
UBS Gain: $ 0.12 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 14
INTC Gain: $ 0.19 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 4
RIOT Gain: $ 0.35 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 10
MNST Gain: $ 0.57 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB4_OS3_CB4_CS4_RV_AL_UA 1
Days gain with 21 stocks: -28.15 20230331
