A Gain: $ -3.49 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS5_CB4_CS5_HM_TR_DU7_UA_DL2 4 13
COIN Gain: $ -1.62 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV_DB8 8
V Gain: $ -1.48 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS4_CB4_CS4_RV_AV_DB30_DU7 7 14 17
BIDU Gain: $ -1.4 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB3_OS3_CB5_CS3_AL_TS_DU6_AV_DU6 21
TJX Gain: $ -1.4 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB3_OS3_CB2_CS3_AL_TS_UA_DU8_DL2 3
EA Gain: $ -1.19 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB5_OS2_CB4_CS4_IT_DU7_DL2 13
ROST Gain: $ -1.19 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS4_CB5_CS5_HM 18
VIPS Gain: $ -0.83 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS2_DU8_TG 14
EL Gain: $ -0.66 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB5_CS3_AL_DU7_AV_DL2_DU8_UA_TG 19
FLO Gain: $ -0.63 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 12
ZIM Gain: $ -0.49 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS3_CB2_CS5_AL_IT_DU7_TG 11
NIO Gain: $ -0.48 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_HM_AV_DB10_DU6_DU6_AL_TG_UA_UA_UA_UA_UA 10
EURN Gain: $ -0.45 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS3_AV_VI_DU8_DL2_AL 5
CRK Gain: $ -0.36 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB2_OS3_CB4_CS5_AL_UA_DU7_AV_DL2 15
XPEV Gain: $ -0.32 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB5_CS3_AV_TS_DU5_AV_AV_AV_AV_AV_AV_AV_AV 17
MQ Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB3_OS3_CB5_CS5_DB6 6
SBS Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 9
OHI Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB3_OS2_CB3_CS5_SH_DU8_DL2 20
HRB Gain: $ 1.57 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB2_OS5_CB5_CS2_SS_AL_DU8_UA_AV_DL2 1
TGT Gain: $ 1.85 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS5_AO_AC_UA 2
SEDG Gain: $ 3.78 Win %: 100.00 in 1 days with algo TB3_LO_HL_QM_OB4_OS2_CB2_CS5_HM_DU7_UA_AV_DL2_DU5 16
Days gain with 21 stocks: -9.02 20230816
