LMT Gain: $ -7.52 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB5_OS2_CB3_CS5_IT_QL_DU7 13
MMM Gain: $ -5.8 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB3_OS3_CB5_CS4_SS_DU7_AV_DL1 9
A Gain: $ -3.43 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS5_CB4_CS5_HM_TR_DU7_UA_DL2 11 17 19 21
TSCO Gain: $ -2.25 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV_DB6 8
RTX Gain: $ -1.82 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS3_CB5_CS2_RV_AV_DU7_UA_DL2 1
ABT Gain: $ -1.49 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS2_TR_QP_DB10_DU7_UA_DL2 21
AMC Gain: $ -0.69 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB5_OS2_CB2_CS5_DU12_TG_AL 17
LUV Gain: $ -0.58 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB4_CS3_HM_AV_DU8_UA_DL2 6
BEKE Gain: $ -0.54 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS5_CB4_CS3_HM_DU7_DL1_DL2 16
GLW Gain: $ -0.23 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB3_CS2_RV_DU5_DL2_AL_TG 15
VZ Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB4_OS3_CB5_CS4_AL_UA 7
VTNR Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS2_CB4_CS4_DU6_TG 2
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 5
LTHM Gain: $ 0.08 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB4_CS4_HM_AV_DB30_DU7_UA_DL2 20
NXPI Gain: $ 0.42 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB1_OS1_CB5_CS5_HM_AV 14
MNSO Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 10
GM Gain: $ 0.97 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB2_OS4_CB5_CS2_AL_TS_DU7 18
DAL Gain: $ 1.33 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB2_OS4_CB3_CS3_RV_AV_DU7 19
GE Gain: $ 2.26 Win %: 100.00 in 1 days with algo TB1_HI_QM_OB4_OS2_CB4_CS5_AV_IT_TG_AL_DU8_DL2 3
LOGI Gain: $ 3.12 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB5_OS3_CB5_CS4_SS_DU7_DL2 4
FTI Gain: $ 3.14 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB3_OS4_CB4_CS2_DU6_UA_AV 12
Days gain with 21 stocks: -12.74 20230725
