TSLA Gain: $ -10.6 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB3_CS3_AL_LI_DU6_AV_UA_DU7 6
AXP Gain: $ -2.46 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB3_OS2_CB5_CS3_TR_TS_DU7_UA_DL2 8
ANET Gain: $ -2.25 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB2_OS5_CB5_CS2_QP_QL_PM_DU6_UA_AV_DU7_AL 18
CL Gain: $ -1.34 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB5_OS2_CB2_CS5_RV_AV_DU7_DL1 12
F Gain: $ -0.78 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS2_CB5_CS4_HM_AV_DU7_AL_UA 15
PG Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 21
RTX Gain: $ -0.4 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS3_CB5_CS2_RV_AV_DU7_UA_DL2 16
MPC Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB5_OS2_CB2_CS5_PM_DU7_UA_DL2_DU8_AL_TG 20
ON Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB4_CS4_RV_TR_DB6_DU7 7 19
T Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 1 3 6 9 16 18
STX Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB3_CS3_RV_AV_DB30_DU7_DL1_UA_DL2_AL_TG_DU8 3
IONQ Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 19
VZ Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB5_BL_QM_OB4_OS3_CB5_CS4_AL_UA 5
WYNN Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB3_OS3_CB4_CS5_RV_AV_DU7 10
IBM Gain: $ 0.54 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB2_OS3_CB4_CS2_RV_AV_DB10_DU7 4
GM Gain: $ 0.55 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB2_OS4_CB5_CS2_AL_TS_DU7 13
BBWI Gain: $ 0.68 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB2_CS4_HM_AV_DU8_DL2_TG 17
TMUS Gain: $ 0.99 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS4_HM_AV_DU7_AL_DL2 9
MLCO Gain: $ 1.34 Win %: 100.00 in 1 days with algo TB1_CC_QM_OB2_OS2_CB4_CS5_UA_DU7 14
LVS Gain: $ 1.93 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB2_OS4_CB4_CS4_UA_WT_AL_TG_DU7 2
NXPI Gain: $ 3.66 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB1_OS1_CB5_CS5_HM_AV 11
Days gain with 21 stocks: -8.25 20230420
