RMD Gain: $ -5.15 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS4_CB4_CS4_TR_IR1_DU7_UA_AV_DL1 5
MCD Gain: $ -4.1 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB2_CS5_DU8_AL 14
KMX Gain: $ -2.06 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB3_OS2_CB4_CS5_RV_AV_TG_DU7 3
NEM Gain: $ -1.1 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB3_OS2_CB5_CS5_RV_AV_DU7 12
CVS Gain: $ -0.93 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS4_CB5_CS2_RV_AV_DU7 17
KMB Gain: $ -0.77 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS4_CB4_CS3_UA_WT_DU8_AV_DL2 13
GFI Gain: $ -0.66 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 11
TAL Gain: $ -0.41 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB3_OS3_CB3_CS4_LI_DU7_UA 6
GME Gain: $ -0.35 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB3_CS5_AV_TS_DU7 16
AU Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 8
GIS Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB1_OS1_CB3_CS1_AL_UA_AV 20
NOV Gain: $ -0.23 Win %: 0.0 in 1 days with algo TB3_HL_QM_TG_OB1_OS5_CB5_CS2_AV_IT_DU8_DL2 15
ANF Gain: $ -0.19 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS5_CB2_CS2_RV_DU8_AL_DL2 4
PEP Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS5_CB4_CS2_AL_UA_DU7_DL2 21
PG Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 18
COTY Gain: $ 0.03 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS5_LI 7
NEE Gain: $ 0.81 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB4_OS2_CB3_CS4_TR_TS_AL_DU7_AV_DL1_DL2 2
WDAY Gain: $ 2.48 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB5_OS3_CB2_CS5_AL_TS_TG_DU7_DL2 1
IMVT Gain: $ 4.15 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS3_DU8_AL 19
AN Gain: $ 5.07 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB4_OS2_CB4_CS4_HM_AV_DB6_DU7_DL2_DU8_AL 4 10
JBL Gain: $ 11.15 Win %: 100.00 in 1 days with algo TB2_HL_HS_QM_OB1_OS1_CB4_CS4_SS 9
Days gain with 21 stocks: 6.97 20230928
