NVDA Gain: $ -27.29 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 18
ARGX Gain: $ -2.26 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB4_CS3_HM_TR_DB30_DU7_DL1 19
MMM Gain: $ -1.82 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB3_OS3_CB5_CS4_SS_DU7_AV_DL1 10
KEYS Gain: $ -1.42 Win %: 0.0 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB4_CS4_TR_TS 1
FUTU Gain: $ -1.08 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB1_OS1_CB5_CS5_RV_TR_DU8_AL_DL2 20
RIOT Gain: $ -0.83 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 4
JBL Gain: $ -0.38 Win %: 0.0 in 1 days with algo TB2_HL_HS_QM_OB1_OS1_CB4_CS4_SS 9
XPEV Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB5_CS3_AV_TS_DU5_AV_AV_AV_AV_AV_AV_AV_AV 7
MARA Gain: $ -0.24 Win %: 0.0 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 6
DELL Gain: $ -0.21 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM 21
ROST Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS4_CB5_CS5_HM 2
RKT Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS2_CB3_CS4_QL_DU6_UA 11
EDU Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS5_CB5_CS2_DU12_TG 17
VTRS Gain: $ 0.06 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB4_OS5_CB5_CS4_IR1_DU7_AL 12
FRO Gain: $ 0.3 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 13
COIN Gain: $ 0.41 Win %: 100.00 in 1 days with algo TB4_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV_DB8 14
CCL Gain: $ 0.43 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 16
DKNG Gain: $ 0.49 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_HM_AL_DU7 8
EL Gain: $ 0.92 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB5_CS3_AL_DU7_AV_DL2_DU8_UA_TG 3 21
BLDR Gain: $ 2.79 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB5_OS3_CB4_CS5_HM_AV_DB30_DU7_UA_DL2 5
SHOP Gain: $ 3.94 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS5_CB5_CS5_HM_DU6 15
Days gain with 21 stocks: -26.87 20230818
