ABBV Gain: $ -4.03 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS3_CB5_CS5_HM_AV_DB6_DU7_UA_DL2 14
JWN Gain: $ -3.42 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB1_OS2_CB5_CS5_DU6_AV 10
CRM Gain: $ -2.39 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB5_OS2_CB3_CS5_TR_TS_DU7_DL1 2
SPG Gain: $ -1.97 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB2_CS2_HM_AV_DB6 5
ORCL Gain: $ -1.68 Win %: 0.0 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5 18
SOXL Gain: $ -1.13 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB5_OS2_CB5_CS4_SS_AL 4
IONQ Gain: $ -0.71 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 17
FLO Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 1
D Gain: $ -0.49 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS4_CB5_CS2_AV_TS_DU7_AL_DL2 13 20 21
PSTG Gain: $ -0.48 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS5_QL_DU8_UA_AV_DL2 3
DLTR Gain: $ -0.41 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS2_CB3_CS5_AL_LI_DU8_AV_DL2 13
PG Gain: $ -0.4 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 5 6
SOFI Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 12
EURN Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS3_AV_VI_DU8_DL2_AL 11
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 7
FRO Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 9
VIPS Gain: $ 0.67 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS2_DU8_TG 8
M Gain: $ 1.75 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS3_CB4_CS4_RV_TR_DB10_DU8_UA_DL2 2 16
AEHR Gain: $ 5.33 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 15
ON Gain: $ 9.2 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB4_CS4_RV_TR_DB6_DU7 17 19
NVDA Gain: $ 37.04 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 20
Days gain with 21 stocks: 36.22 20230601
