CLX Gain: $ -3.61 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS3_AV_DU7_UA_DL2 15
AAPL Gain: $ -1.05 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB2_OS2_CB2_CS5_IR3_DU4_AL_UA_UA_UA_UA_UA 13
ABNB Gain: $ -0.79 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB3_OS2_CB3_CS5_RV_AV_DB10_DU7_UA_DL1 12
FRO Gain: $ -0.49 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 4
MT Gain: $ -0.47 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB5_OS2_CB5_CS5_HM_AL_DU7_UA_DL2 17
RIOT Gain: $ -0.46 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 10
AZN Gain: $ -0.33 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS4_CB3_CS2_RV_DU7_AV_DL2_DU5 5
ALC Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_AV_TG_DU7 3
PG Gain: $ -0.21 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 1
T Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 6 7 10 11 14 16 17 20
STX Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB3_CS3_RV_AV_DB30_DU7_DL1_UA_DL2_AL_TG_DU8 16
XLP Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS5_CB5_CS3_IT_QL_DB6_AV_TG_DU7_UA_DL1 18
OSTK Gain: $ 0.11 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV 6
CL Gain: $ 0.18 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB5_OS2_CB2_CS5_RV_AV_DU7_DL1 8 15
TME Gain: $ 0.44 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB3_OS4_CB5_CS3_DU12_TG_AL 11
MARA Gain: $ 0.6 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 19
AMZN Gain: $ 0.72 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS3_CB5_CS5_LI_DU6_UA_TG_DU7_AV_DL2_AL 9
TSM Gain: $ 1.53 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB4_OS3_CB3_CS5_RV_DU7 20
STLD Gain: $ 2.05 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB2_CS3_HM_AV_DU8_UA_DL2 14
ARGX Gain: $ 3.23 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB4_CS3_HM_TR_DB30_DU7_DL1 21
SQM Gain: $ 7.26 Win %: 100.00 in 1 days with algo TB3_LO_HL_QM_OB4_OS2_CB2_CS5_AO_AC_AV_DU7_DL2 2
Days gain with 21 stocks: 8.24 20230421
