GS Gain: $ -5.41 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_RV_AV_DB6_DU6_UA_TG_DU7_DL2 18 14
VLO Gain: $ -2.76 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB4_OS4_CB5_CS4_HM_AV_DU7_DL2_TG 9 7
REGN Gain: $ -2.75 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB3_OS3_CB4_CS4_AV 18
BLDR Gain: $ -1.51 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB5_OS3_CB4_CS5_HM_AV_DB30_DU7_UA_DL2 12
PFGC Gain: $ -1.12 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS5_CB5_CS3_DU8_AL 16
SCHW Gain: $ -0.98 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB5_CS3_RV_TR_DU7_AL_DL2_UA 11
TSN Gain: $ -0.56 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS3_CB2_CS5_AL_TS_AV_DU8_DL2 10
ALDX Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB2_OS4_CB5_CS4_HM_AV_UA_DU7 2 2
EURN Gain: $ -0.33 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS3_AV_VI_DU8_DL2_AL 14 20
HRL Gain: $ -0.31 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_DU6_DL_TG_DU7_DL1 4
SBSW Gain: $ -0.3 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS2_CB3_CS5_DU12_AL_UA 16
PAAS Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB1_HI_QM_OB4_OS2_CB5_CS3_RV_AV_DB30_DU7_DL1 7
CCL Gain: $ -0.24 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 13
CSIQ Gain: $ -0.21 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS2_CB5_CS4_AV_UA_TG_DU8_AL_DL2 17
VTRS Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS5_CB5_CS4_IR1_DU7_AL 4
TDG Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB3_OS2_CB2_CS5_WT_UA_TG 9
GIS Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB1_OS1_CB3_CS1_AL_UA_AV 6
CPG Gain: $ -0.1 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_AO_AC 5 15
LTHM Gain: $ -0.1 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB4_CS4_HM_AV_DB30_DU7_UA_DL2 11
SWN Gain: $ -0.1 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB3_CS4_TR_TS_AL_UA_TG 12
KR Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS3_CB3_CS5_TR_IR3_DU8_DL2_UA_AV 8 17
PBF Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB5_HL_QM_OB1_OS5_CB5_CS1_IT_QP_DU7_UA_AV_DL2 13 6
LLY Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 8
BCRX Gain: $ 0.13 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_RV_AV_DB6 19 10
CERE Gain: $ 0.25 Win %: 100.00 in 1 days with algo TB1_HL_HS_QM_OB2_OS2_CB4_CS4 19
WEN Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB3_HS_HL_QM_TG_OB2_OS4_CB5_CS2_HM_DU8_AV_DL2 15 3
IMVT Gain: $ 0.85 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS3_DU8_AL 21
STZ Gain: $ 4.53 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB5_OS3_CB2_CS5_HM_AV_DB10_DU6 20
MCD Gain: $ 7.05 Win %: 100.00 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB2_CS5_DU8_AL 3 5
PWR Gain: $ 13.19 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB5_OS3_CB3_CS5_RV_AV_UA_DU6 1 1
NVDA Gain: $ 52.44 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 21
Days gain with 31 stocks: 61.06 20231003
