WYNN Gain: $ -11.71 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB4_CS5_RV_AV_DU7 17
NXPI Gain: $ -5.27 Win %: 0.0 in 1 days with algo TB4_OC_QM_OB1_OS1_CB5_CS5_HM_AV 11
META Gain: $ -2.02 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS5_HM_TR_DB6_DU7_UA_AV_DL1_DL2 1
MRK Gain: $ -1.64 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS2_CB2_CS3_DB10_DU7_TG_AV_DL2 14
CAT Gain: $ -1.48 Win %: 0.0 in 1 days with algo TB5_HI_HL_QM_OB2_OS4_CB2_CS5_IT_QL_DB6_DU8_AV_DL2 6
MO Gain: $ -1.06 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB4_OS2_CB5_CS5_RV_DU8 9
FISV Gain: $ -0.59 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB5_OS2_CB3_CS4_VI_DU7 5
RUN Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS5_RV_TR_DU7_UA_AV_DL2 21
GOGL Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 19
AEHR Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 16
EA Gain: $ 0.05 Win %: 100.00 in 1 days with algo TB3_LO_HL_QM_OB5_OS2_CB4_CS4_IT_DU7_DL2 20
TTD Gain: $ 0.61 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS3_SR_DU7_UA_AV_DL2_TG 15
PINS Gain: $ 0.83 Win %: 100.00 in 1 days with algo TB1_PL_QM_OB3_OS1_CB3_CS4_HM_AV_AL_DU7 13
LUV Gain: $ 0.87 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB4_CS3_HM_AV_DU8_UA_DL2 7
ON Gain: $ 1.4 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB4_CS4_RV_TR_DB6_DU7 8 10
CROX Gain: $ 1.77 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB2_OS4_CB5_CS4_QL_AV 2
AMZN Gain: $ 1.9 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS3_CB5_CS5_LI_DU6_UA_TG_DU7_AV_DL2_AL 12
QQQ Gain: $ 2.4 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB4_CS4_AL 18
ABBV Gain: $ 2.54 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB4_OS3_CB5_CS5_HM_AV_DB6_DU7_UA_DL2 3
HON Gain: $ 3.4 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB4_OS2_CB4_CS4_AL_LI_DU8_AV_DL2 8
LLY Gain: $ 3.69 Win %: 100.00 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 4
Days gain with 21 stocks: -4.78 20230427
