GS Gain: $ -1.76 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_RV_AV_DB6_DU6_UA_TG_DU7_DL2 21
PEP Gain: $ -1.44 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS5_CB4_CS2_AL_UA_DU7_DL2 20
WFC Gain: $ -1.4 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB2_OS3_CB5_CS4_AO_AC_AL 12
JPM Gain: $ -1.3 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB4_OS3_CB3_CS5_HM_AV_DB10_DU6_UA_UA 2
PG Gain: $ -1.04 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 16
DUK Gain: $ -0.42 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_QL_DU7_AL_DL2 18
FRO Gain: $ -0.34 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 15
BAC Gain: $ -0.33 Win %: 0.0 in 1 days with algo TB2_CC_QM_OB3_OS3_CB5_CS5_RV_AL_DB15 5
GFI Gain: $ -0.31 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 4
FAZ Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB2_OS5_CB5_CS3_RV_AL_DB30_DU7_UA_AV_DL2_DU8 17
AU Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 6
DB Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 10
SBS Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 9 13
USB Gain: $ 0.03 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS4_VI_DU7_UA_DL2 14
SBSW Gain: $ 0.09 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB2_OS2_CB3_CS5_DU12_AL_UA 13
HL Gain: $ 0.1 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB3_OS2_CB2_CS5_RV_TR_DU7_UA_AV_DL2 7
BA Gain: $ 0.21 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_DB6_DU7_AL_DL2 1 5
CHKP Gain: $ 0.23 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB2_OS2_CB2_CS5_RV_AV_DB6_DU6_AL 3
MARA Gain: $ 0.47 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 8
C Gain: $ 0.92 Win %: 100.00 in 1 days with algo TB1_HL_QM_OB5_OS5_CB5_CS5_RV_AV_DB30 3 5 12 19
GLD Gain: $ 3.22 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB4_OS2_CB5_CS5_AO_DU6 11
Days gain with 21 stocks: -3.55 20230414
