AAPL Gain: $ -3.84 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB2_OS2_CB2_CS5_IR3_DU4_AL_UA_UA_UA_UA_UA 6
TSM Gain: $ -2.5 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB4_OS3_CB3_CS5_RV_DU7 10
AMGN Gain: $ -1.89 Win %: 0.0 in 1 days with algo TB3_HL_QM_OB3_OS1_CB2_CS3_HM_AV_DB10_DU8_DL2 3
CLX Gain: $ -1.8 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS3_AV_DU7_UA_DL2 7
BIDU Gain: $ -1.59 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB3_OS3_CB5_CS3_AL_TS_DU6_AV_DU6 19
PG Gain: $ -1.15 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 13
GLD Gain: $ -0.96 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB4_OS2_CB5_CS5_AO_DU6 20
ORCL Gain: $ -0.83 Win %: 0.0 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5 5
STZ Gain: $ -0.83 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB5_OS3_CB2_CS5_HM_AV_DB10_DU6 21
AMAT Gain: $ -0.64 Win %: 0.0 in 1 days with algo TB4_LO_QM_OB3_OS3_CB4_CS4_HM 8
LEN Gain: $ -0.54 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB4_OS4_CB5_CS5_RV_AV 11
WYNN Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB4_CS5_RV_AV_DU7 4
UBS Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 15
OHI Gain: $ -0.3 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB3_OS2_CB3_CS5_SH_DU8_DL2 12
RY Gain: $ -0.25 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB4_OS2_CB4_CS5_RV_AV_DU7_UA_DL2 17
SBS Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 16
TMUS Gain: $ 0.1 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS4_HM_AV_DU7_AL_DL2 9
DELL Gain: $ 0.88 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM 18
MU Gain: $ 1.04 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP 1 9
STLD Gain: $ 1.8 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB2_CS3_HM_AV_DU8_UA_DL2 2
CROX Gain: $ 6.59 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB2_OS4_CB5_CS4_QL_AV 14
Days gain with 21 stocks: -7.81 20230410
