MDB Gain: $ -10.76 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_UA_DL1 21
SCHW Gain: $ -3.29 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB5_CS3_RV_TR_DU7_AL_DL2_UA 1
MS Gain: $ -1.86 Win %: 0.0 in 1 days with algo TB2_OO_QM_OB4_OS4_CB5_CS5_IT_QP_DB15 17
SOXL Gain: $ -0.89 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB5_OS2_CB5_CS4_SS_AL 3
PEP Gain: $ -0.72 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS5_CB4_CS2_AL_UA_DU7_DL2 2
PKG Gain: $ -0.72 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB2_OS3_CB4_CS5_AV_TG_DU7_AL_DL2 14
RIOT Gain: $ -0.54 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 11
GFI Gain: $ -0.43 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 13
U Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB4_CS4_HM 10 15 16 20
TTC Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_HM 6
AUPH Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB3_HL_HS_QM_OB2_OS2_CB4_CS4_RV 16
BAC Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB2_CC_QM_OB3_OS3_CB5_CS5_RV_AL_DB15 12
GIS Gain: $ 0.02 Win %: 100.00 in 1 days with algo TB5_PL_QM_OB1_OS1_CB3_CS1_AL_UA_AV 19
UWMC Gain: $ 0.1 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB4_OS2_CB2_CS4_AV_UA_DU7 10
NNOX Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB5_CS5_IR3 5
VZ Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB5_BL_QM_OB4_OS3_CB5_CS4_AL_UA 7
RIG Gain: $ 0.14 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 9
KHC Gain: $ 0.56 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_RV_QP_QL_DB10_DU6_UA_DU7_DL2 18
PINS Gain: $ 1.56 Win %: 100.00 in 1 days with algo TB1_PL_QM_OB3_OS1_CB3_CS4_HM_AV_AL_DU7 8
UNH Gain: $ 15.03 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS3_CB4_CS4_RV_TR_AV_DU8_AL_DL2 20
LMT Gain: $ 48.94 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB5_OS2_CB3_CS5_IT_QL_DU7 4
Days gain with 21 stocks: 47.21 20230718
