MPC Gain: $ -4.04 Win %: 0 in 1 days with algo TB5_OO_QM_OB5_OS2_CB2_CS5_PM_DU7_UA_DL2_DU8_AL_TG 7
HES Gain: $ -2.5 Win %: 0 in 1 days with algo TB3_OO_QM_OB3_OS4_CB3_CS3_DU7_DL1_AL_UA_DL2 18
FAZ Gain: $ -1.39 Win %: 0 in 1 days with algo TB1_LO_QM_OB2_OS5_CB5_CS3_RV_AL_DB30_DU7_UA_AV_DL2_DU8 13
ATVI Gain: $ -1.25 Win %: 0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB2_CS5_DU6_AL 1
BP Gain: $ -1.07 Win %: 0 in 1 days with algo TB3_HS_QM_OB5_OS2_CB4_CS5_HM_AV_DB10_DU7 9
FTI Gain: $ -0.56 Win %: 0 in 1 days with algo TB1_LO_QM_OB3_OS4_CB4_CS2_DU6_UA_AV 15
C Gain: $ -0.48 Win %: 0 in 1 days with algo TB1_HL_QM_OB5_OS5_CB5_CS5_RV_AV_DB30 5 7 17 20 21
DKS Gain: $ -0.42 Win %: 0 in 1 days with algo TB3_HI_QM_OB4_OS2_CB4_CS4_AL_TS_DU7_DL2 10
EURN Gain: $ -0.19 Win %: 0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS3_AV_VI_DU8_DL2_AL 4
RIG Gain: $ -0.1 Win %: 0 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 3
CM Gain: $ -0.08 Win %: 0 in 1 days with algo TB1_OC_QM_OB4_OS3_CB5_CS5_VI_DU7_AV_DL2 20
MS Gain: $ -0.04 Win %: 0 in 1 days with algo TB2_OO_QM_OB4_OS4_CB5_CS5_IT_QP_DB15 19
IMMR Gain: $ -0.02 Win %: 0 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 14
CRH Gain: $ 0.01 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB3_OS2_CB4_CS3_RV_AV_DB6_DU7 5
DB Gain: $ 0.02 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 2
RBLX Gain: $ 0.02 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB2_CS5_VI_DU7_AV_DL2 11
EA Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB3_LO_HL_QM_OB5_OS2_CB4_CS4_IT_DU7_DL2 16
CAT Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB5_HI_HL_QM_OB2_OS4_CB2_CS5_IT_QL_DB6_DU8_AV_DL2 21
UBS Gain: $ 0.53 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 6
STLD Gain: $ 1.92 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB2_CS3_HM_AV_DU8_UA_DL2 8
XOM Gain: $ 2.4 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB3_OS4_CB3_CS5_AL_LI_DU6_UA 12
Days gain with 21 stocks: -6.78 20230324
