UNH Gain: $ -17.93 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS3_CB4_CS4_RV_TR_AV_DU8_AL_DL2 8
LVS Gain: $ -2.37 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS4_CB4_CS4_UA_WT_AL_TG_DU7 7
VERV Gain: $ -1.56 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS4_CB5_CS3_RV_TR_DB6_DU7_AL_DL2 6
QCOM Gain: $ -1.42 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_AV_TS_UA_AL 17
CNC Gain: $ -1.17 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB3_OS2_CB4_CS3_RV_AV_DB30_AL_DU7 18
GM Gain: $ -0.67 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS4_CB5_CS2_AL_TS_DU7 3 5
GME Gain: $ -0.67 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB3_CS5_AV_TS_DU7 5
SBLK Gain: $ -0.35 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB3_CS5_AL_TS_DU8_AV_DL2 15
PINS Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB3_OS1_CB3_CS4_HM_AV_AL_DU7 19
GOGL Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 14
HRL Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_DU6_DL_TG_DU7_DL1 12
F Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS2_CB5_CS4_HM_AV_DU7_AL_UA 4 9 20
WDAY Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB5_OS3_CB2_CS5_AL_TS_TG_DU7_DL2 2
HOOD Gain: $ 0.04 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB3_CS3_HM_TR 21
FRO Gain: $ 0.3 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 20
UBS Gain: $ 0.55 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 13
FL Gain: $ 0.97 Win %: 100.00 in 1 days with algo TB3_PL_QM_OB3_OS1_CB4_CS3_SH_DU6_AL 4
BULZ Gain: $ 2.24 Win %: 100.00 in 1 days with algo TB5_BL_QM_OB5_OS2_CB5_CS4_HM_AV_DU7_UA_DL1 16
INTU Gain: $ 2.36 Win %: 100.00 in 1 days with algo TB1_HL_LO_QM_OB4_OS4_CB5_CS5_RV_AL_DB30 10
JBL Gain: $ 3.23 Win %: 100.00 in 1 days with algo TB2_HL_HS_QM_OB1_OS1_CB4_CS4_SS 1
DLTR Gain: $ 4.42 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB3_OS2_CB3_CS5_AL_LI_DU8_AV_DL2 11
Days gain with 21 stocks: -12.48 20231129
