MSFT Gain: $ -8.02 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB5_OS3_CB2_CS5_RV_AL_DB6_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA 15
META Gain: $ -7.48 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS5_HM_TR_DB6_DU7_UA_AV_DL1_DL2 2
AAPL Gain: $ -4.3 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB2_OS2_CB2_CS5_IR3_DU4_AL_UA_UA_UA_UA_UA 17
SNOW Gain: $ -4.09 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_RV_AL_DU7_UA_DL2 4
MDB Gain: $ -2.5 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_UA_DL1 14
CLX Gain: $ -2.0 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS3_AV_DU7_UA_DL2 16
SCHW Gain: $ -0.85 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB5_CS3_RV_TR_DU7_AL_DL2_UA 8
WM Gain: $ -0.48 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB3_OS2_CB3_CS2_RV_AV_UA_DU8_AL_DL2 5
GOOG Gain: $ -0.46 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 19
CRH Gain: $ -0.41 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB3_OS2_CB4_CS3_RV_AV_DB6_DU7 11
RIOT Gain: $ -0.23 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 9
KR Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS3_CB3_CS5_TR_IR3_DU8_DL2_UA_AV 21
FLO Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 13
ACI Gain: $ -0.1 Win %: 0.0 in 1 days with algo TB5_HI_HL_QM_OB3_OS3_CB3_CS3_LI_DU7 20
IMMR Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 6
EVO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS5_RV_DU7 18
KALV Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HI_QM_OB3_OS3_CB4_CS4_PM 12
MAT Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB4_OS2_CB4_CS4_SR_DU8_AV_DL2 1
TAP Gain: $ 0.19 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_AL_IT_DU8_UA_DL2 10
AAP Gain: $ 0.21 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS5_AL_UA_AV 3 17
GFI Gain: $ 0.33 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 7
Days gain with 21 stocks: -30.39 20230710
