NVDA Gain: $ -40.05 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 20
NEE Gain: $ -2.0 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB4_OS2_CB3_CS4_TR_TS_AL_DU7_AV_DL1_DL2 19
AZN Gain: $ -1.59 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS4_CB3_CS2_RV_DU7_AV_DL2_DU5 11
SU Gain: $ -0.86 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS2_CB4_CS5_IT_QL_DU8_AL_DL2 10
BCH Gain: $ -0.84 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_TR_IR3_DU7_AV_DL2 21
EVO Gain: $ -0.84 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS5_RV_DU7 17
AKAM Gain: $ -0.44 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB5_OS5_CB3_CS4_HM_AV_DU7_DL1 16
AU Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 12
APPS Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB3_HL_HI_QM_OB2_OS2_CB1_CS1_TR 7
CSCO Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_DL1 9
GOGL Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 13
LYFT Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB5_OS2_CB5_CS5_RV_AL_DU7_AV_DL2 14
MARA Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 4
RIOT Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 5
COIN Gain: $ 0.5 Win %: 100.00 in 1 days with algo TB4_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV_DB8 8
IONQ Gain: $ 0.64 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 6
MU Gain: $ 0.81 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP 18
IBM Gain: $ 1.15 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB2_OS3_CB4_CS2_RV_AV_DB10_DU7 15
AFRM Gain: $ 1.18 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB2_OS2_CB5_CS5_RV_AV 2
APP Gain: $ 1.78 Win %: 100.00 in 1 days with algo TB3_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR_DB10 1 7
MSTR Gain: $ 9.52 Win %: 100.00 in 1 days with algo TB4_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AV 3
Days gain with 21 stocks: -30.48 20231109
