ARGX Gain: $ -17.49 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB4_CS3_HM_TR_DB30_DU7_DL1 12
AMD Gain: $ -4.35 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS4_CB4_CS4_HM_AL_DU6_UA_AV 10
NFLX Gain: $ -4.21 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB5_CS5_AV_TS 13
CI Gain: $ -2.72 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AL 5
COIN Gain: $ -2.52 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV_DB8 19
U Gain: $ -1.6 Win %: 0.0 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB4_CS4_HM 11 14 18
QCOM Gain: $ -1.4 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_AV_TS_UA_AL 17
VZ Gain: $ -0.41 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB4_OS3_CB5_CS4_AL_UA 4
CCL Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 15
AZN Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS4_CB3_CS2_RV_DU7_AV_DL2_DU5 16
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 6
T Gain: $ 0.04 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 2 3 6 11 21
CSCO Gain: $ 0.27 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_DL1 8
RIOT Gain: $ 0.41 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 21
UPST Gain: $ 1.76 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV 11
CRM Gain: $ 1.79 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB5_OS2_CB3_CS5_TR_TS_DU7_DL1 9
JNJ Gain: $ 1.8 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS3_AV_TS_DU8_UA_DL2 7
VMW Gain: $ 2.81 Win %: 100.00 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB1_CS1_QL 1
UNH Gain: $ 3.72 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS3_CB4_CS4_RV_TR_AV_DU8_AL_DL2 18
KMX Gain: $ 4.66 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB3_OS2_CB4_CS5_RV_AV_TG_DU7 20
TOST Gain: $ 6.09 Win %: 100.00 in 1 days with algo TB5_HL_QM_OB5_OS1_CB1_CS5_SS_DU7_AL_DL2 2
Days gain with 21 stocks: -11.55 20230719
