SAM Gain: $ -15.66 Win %: 0.0 in 1 days with algo TB2_HL_HI_QM_OB2_OS2_CB2_CS2_LI 1
FUTU Gain: $ -5.18 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB1_OS1_CB5_CS5_RV_TR_DU8_AL_DL2 16
ANET Gain: $ -2.21 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB2_OS5_CB5_CS2_QP_QL_PM_DU6_UA_AV_DU7_AL 10 8
TAL Gain: $ -1.52 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB3_OS3_CB3_CS4_LI_DU7_UA 5 4
PEP Gain: $ -1.47 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS5_CB4_CS2_AL_UA_DU7_DL2 15
CL Gain: $ -1.43 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB5_OS2_CB2_CS5_RV_AV_DU7_DL1 3 6 16
SKX Gain: $ -1.21 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB4_OS2_CB5_CS5_AL_LI_UA_DU7_AV_DL2 2 3
PG Gain: $ -1.03 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 4 7
TTD Gain: $ -0.91 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS3_SR_DU7_UA_AV_DL2_TG 11
AZN Gain: $ -0.86 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS4_CB3_CS2_RV_DU7_AV_DL2_DU5 6 12
EXPI Gain: $ -0.79 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS2_CB5_CS5_PM 20 14
CLX Gain: $ -0.67 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS3_AV_DU7_UA_DL2 16
OLN Gain: $ -0.65 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB3_OS4_CB3_CS5_IT_QL_DB30_DU8_UA_AV_DL2 20
XPEV Gain: $ -0.37 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB5_CS3_AV_TS_DU5_AV_AV_AV_AV_AV_AV_AV_AV 7 11
TAP Gain: $ -0.32 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_AL_IT_DU8_UA_DL2 19
UNIT Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB1_OS4_CB3_CS3_AV_TS_DU7 17
XLP Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS5_CB5_CS3_IT_QL_DB6_AV_TG_DU7_UA_DL1 18
F Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS2_CB5_CS4_HM_AV_DU7_AL_UA 13 14 16 19 10 13
BILI Gain: $ 0.03 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS3_CB3_CS5_HM_TR_DU8_UA_AV_DL2 21 18
FTI Gain: $ 0.05 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB3_OS4_CB4_CS2_DU6_UA_AV 13 10
MNSO Gain: $ 0.39 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 8
QFIN Gain: $ 0.44 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_DU12_DU8_UA_AV_DL2 19 13
INTC Gain: $ 1.19 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 9 9
META Gain: $ 1.21 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS5_HM_TR_DB6_DU7_UA_AV_DL1_DL2 15
TME Gain: $ 1.6 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB3_OS4_CB5_CS3_DU12_TG_AL 17
VIPS Gain: $ 2.47 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS2_DU8_TG 21
UPST Gain: $ 2.66 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV 12 5
ROKU Gain: $ 4.74 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_SS 1 2
Days gain with 28 stocks: -19.78 20230728
