ALB Gain: $ -2.51 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB3_OS5_CB5_CS4_RV_AL_DB30_UA_DU7_AV_DL2 20
LEGN Gain: $ -1.69 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS3_CB5_CS5_HM_AL 19
LAC Gain: $ -0.32 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS2_CB2_CS4_TR_TS_DU7_AV_DL2_TG 21
FTI Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB3_OS4_CB4_CS2_DU6_UA_AV 10
BCH Gain: $ -0.1 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_TR_IR3_DU7_AV_DL2 14
EOLS Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS4_CB3_CS5_QL_DU8_AL_DL2 6
RAPT Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB5_CS5_HM_TR_DB15 16
VIPS Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS2_DU8_TG 13
IMMR Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 15
IONQ Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 17
SUPN Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB4_OS5_CB2_CS5_AV_DU8_AL_DL2 5
T Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 3 4 7 10 12 16
VTRS Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS5_CB5_CS4_IR1_DU7_AL 3
FRO Gain: $ 0.02 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 8
CTIC Gain: $ 0.05 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB2_OS3_CB4_CS3_IR5_DU7_UA_DL2 12
EURN Gain: $ 0.09 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS3_AV_VI_DU8_DL2_AL 9
NEWR Gain: $ 0.1 Win %: 100.00 in 1 days with algo TB5_EO_EC_QM_OB2_OS2_CB5_CS5_TR 18
MDT Gain: $ 0.2 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB3_CS3_AL_TS 4
CERE Gain: $ 0.31 Win %: 100.00 in 1 days with algo TB1_HL_HS_QM_OB2_OS2_CB4_CS4 11
PPSI Gain: $ 0.39 Win %: 100.00 in 1 days with algo TB5_HL_QM_OB2_OS2_CB5_CS5_HM_TR_DB6 2
ALDX Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB2_OS4_CB5_CS4_HM_AV_UA_DU7 1
Days gain with 21 stocks: -3.38 20230424
