ADBE Gain: $ -7.62 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB2_CS5_LI_DU8_AV_DL2 15
LLY Gain: $ -6.14 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 4
NVDA Gain: $ -5.16 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 21
NUE Gain: $ -1.2 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB3_OS2_CB2_CS5_HM_TR_DB30_DU8_UA_AV_DL2 10
SHOP Gain: $ -0.9 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS5_CB5_CS5_HM_DU6 16
ACMR Gain: $ -0.43 Win %: 0.0 in 1 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV 19
MNSO Gain: $ -0.34 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 1
TSCO Gain: $ -0.34 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV_DB6 17
PPC Gain: $ -0.29 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS3_HM_DU7_UA_DL2 11
INCY Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS2_CB5_CS4_RV_AV_DB30_DU7_AL_DL1 2
BLDR Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB5_OS3_CB4_CS5_HM_AV_DB30_DU7_UA_DL2 18
AUPH Gain: $ -0.04 Win %: 0.0 in 1 days with algo TB3_HL_HS_QM_OB2_OS2_CB4_CS4_RV 8
ALDX Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB2_OS4_CB5_CS4_HM_AV_UA_DU7 6
ACRS Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP_PM 9
DRD Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_HS_HL_QM_OB2_OS3_CB4_CS3_DU8_DL2_AS
RKT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS2_CB3_CS4_QL_DU6_UA 12
XLP Gain: $ 0.06 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB2_OS5_CB5_CS3_IT_QL_DB6_AV_TG_DU7_UA_DL1 13
HD Gain: $ 0.16 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 14
TGT Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS5_AO_AC_UA 20
MCD Gain: $ 1.44 Win %: 100.00 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB2_CS5_DU8_AL 5
CLX Gain: $ 2.23 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS3_AV_DU7_UA_DL2 7
LOW Gain: $ 4.98 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS5_AV_TS_DU7_AL_DL2 3
Days gain with 22 stocks: -13.48 20230918
