TZA Gain: $ -2.32 Win %: 0 in 1 days with algo TB3_HI_HL_QM_OB2_OS4_CB2_CS5_RV_AV_AL_TG_DU7 18
CSIQ Gain: $ -0.94 Win %: 0 in 1 days with algo TB5_CC_QM_OB4_OS2_CB5_CS4_AV_UA_TG_DU8_AL_DL2 1
UBS Gain: $ -0.86 Win %: 0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 2
USB Gain: $ -0.74 Win %: 0 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS4_VI_DU7_UA_DL2 3
BP Gain: $ -0.71 Win %: 0 in 1 days with algo TB3_HS_QM_OB5_OS2_CB4_CS5_HM_AV_DB10_DU7 16
IRDM Gain: $ -0.44 Win %: 0 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB4_CS3_AL_DU8_AV_DL2 19
DB Gain: $ -0.25 Win %: 0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 10
C Gain: $ -0.13 Win %: 0 in 1 days with algo TB1_HL_QM_OB5_OS5_CB5_CS5_RV_AV_DB30 1 12 15
RF Gain: $ -0.1 Win %: 0 in 1 days with algo TB5_LO_QM_OB2_OS2_CB5_CS4_PM_DU8_DL2_UA_AV 13
SCHW Gain: $ -0.09 Win %: 0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB5_CS3_RV_TR_DU7_AL_DL2_UA 12
RIG Gain: $ -0.08 Win %: 0 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 8
MT Gain: $ -0.07 Win %: 0 in 1 days with algo TB5_HI_QM_OB5_OS2_CB5_CS5_HM_AL_DU7_UA_DL2 20
FITB Gain: $ -0.04 Win %: 0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB3_CS5_AV_DU7 4
MS Gain: $ -0.03 Win %: 0 in 1 days with algo TB2_OO_QM_OB4_OS4_CB5_CS5_IT_QP_DB15 11
EURN Gain: $ 0.0 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS3_AV_VI_DU8_DL2_AL 17
PBT Gain: $ 0.0 Win %: 100.00 in 1 days with algo TB3_LO_HL_QM_OB2_OS3_CB5_CS3_QP_PM_AV 5
FAZ Gain: $ 0.01 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB2_OS5_CB5_CS3_RV_AL_DB30_DU7_UA_AV_DL2_DU8 6
FRO Gain: $ 0.25 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 9
JPM Gain: $ 2.13 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB4_OS3_CB3_CS5_HM_AV_DB10_DU6_UA_UA 14
META Gain: $ 3.42 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS5_HM_TR_DB6_DU7_UA_AV_DL1_DL2 21
AEHR Gain: $ 6.28 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 7
Days gain with 21 stocks: 5.29 20230321
