ON Gain: $ -7.47 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB4_CS4_RV_TR_DB6_DU7 3
ALC Gain: $ -1.54 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_AV_TG_DU7 6
SLB Gain: $ -1.36 Win %: 0.0 in 1 days with algo TB3_BL_QM_OB5_OS3_CB5_CS4_RV_AL_DU7_UA_DL2 7
VLO Gain: $ -0.79 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB4_OS4_CB5_CS4_HM_AV_DU7_DL2_TG 4
LAC Gain: $ -0.21 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS2_CB2_CS4_TR_TS_DU7_AV_DL2_TG 1
LOGI Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB5_OS3_CB5_CS4_SS_DU7_DL2 8
PSO Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB4_OS2_CB5_CS2_AV_TS_DU6_AV 15
RIG Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 21
ASML Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS2_CB2_CS4_PM_DU7_DL1 14
CPG Gain: $ 0.01 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB5_CS5_AO_AC 12
INTC Gain: $ 0.14 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 2
MRO Gain: $ 0.49 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB5_OS3_CB5_CS3_HM_AV_DU7 13
XOM Gain: $ 0.67 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB3_OS4_CB3_CS5_AL_LI_DU6_UA 16
FRO Gain: $ 0.87 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 11
NOV Gain: $ 0.96 Win %: 100.00 in 1 days with algo TB3_HL_QM_TG_OB1_OS5_CB5_CS2_AV_IT_DU8_DL2 20
SM Gain: $ 1.02 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB2_OS2_CB5_CS5_AV_TS 10 14
OXY Gain: $ 1.2 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB4_OS2_CB2_CS4_AV_UA_DU6_TG_DU7_DL2 18
BP Gain: $ 1.32 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB5_OS2_CB4_CS5_HM_AV_DB10_DU7 5
XLE Gain: $ 1.44 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB3_OS2_CB4_CS2_IT_TS_DU8_DL2_UA_AV 17
COP Gain: $ 2.56 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB2_OS2_CB2_CS5_IT_QL_TG_AL_DU7 9
BTU Gain: $ 4.15 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB4_OS2_CB2_CS5_AV_UA_DU7 19
Days gain with 21 stocks: 3.21 20231004
