NFLX Gain: $ -8.58 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB5_CS5_AV_TS 4
MVIS Gain: $ -3.3 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB5_OS2_CB3_CS5_HM_AV_DU7_TG 1
TSLA Gain: $ -2.03 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB3_CS3_AL_LI_DU6_AV_UA_DU7 16
MU Gain: $ -1.61 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP 21
NNOX Gain: $ -0.62 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB5_CS5_IR3 13
KHC Gain: $ -0.48 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_RV_QP_QL_DB10_DU6_UA_DU7_DL2 10
GME Gain: $ -0.46 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB3_CS5_AV_TS_DU7 6
RBLX Gain: $ -0.42 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB2_CS5_VI_DU7_AV_DL2 15
GIS Gain: $ -0.39 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB1_OS1_CB3_CS1_AL_UA_AV 7
SOFI Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 14
IMMR Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 17
JOBY Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS4_CB4_CS5_RV_DU7_UA_AV_DL2 11
HRL Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_DU6_DL_TG_DU7_DL1 19
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 12
K Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 3 10 18
GIII Gain: $ 0.39 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB2_OS5_CB3_CS5_AL_IT_DU7_DL2 8
MRVL Gain: $ 0.6 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_IT_TS 5
FLO Gain: $ 0.8 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 9
ROKU Gain: $ 0.82 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_SS 18
AFRM Gain: $ 2.51 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB2_OS2_CB5_CS5_RV_AV 2
CROX Gain: $ 3.18 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB2_OS4_CB5_CS4_QL_AV 20
Days gain with 21 stocks: -9.9 20230607
