ARGX Gain: $ -6.77 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB4_CS3_HM_TR_DB30_DU7_DL1 20
NFLX Gain: $ -4.12 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB5_CS5_AV_TS 19
ANET Gain: $ -2.64 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB2_OS5_CB5_CS2_QP_QL_PM_DU6_UA_AV_DU7_AL 13
LVS Gain: $ -1.22 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS4_CB4_CS4_UA_WT_AL_TG_DU7 11
TAP Gain: $ -0.79 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_AL_IT_DU8_UA_DL2 17
JPM Gain: $ -0.41 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB4_OS3_CB3_CS5_HM_AV_DB10_DU6_UA_UA 3
CVS Gain: $ -0.4 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS4_CB5_CS2_RV_AV_DU7 18
HRL Gain: $ -0.21 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_DU6_DL_TG_DU7_DL1 15
T Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 2 7 8 13 17
CSCO Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_DL1 6
AZN Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS4_CB3_CS2_RV_DU7_AV_DL2_DU5 12
MS Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB2_OO_QM_OB4_OS4_CB5_CS5_IT_QP_DB15 8 14
CIEN Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_PM 5
FLO Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 10
UWMC Gain: $ 0.2 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB4_OS2_CB2_CS4_AV_UA_DU7 16
GFI Gain: $ 0.54 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 9
WFC Gain: $ 1.08 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB2_OS3_CB5_CS4_AO_AC_AL 4
ATVI Gain: $ 1.55 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB2_OS2_CB2_CS5_DU6_AL 2
GS Gain: $ 4.08 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_RV_AV_DB6_DU6_UA_TG_DU7_DL2 21
MSFT Gain: $ 8.77 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB5_OS3_CB2_CS5_RV_AL_DB6_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA 8
UNH Gain: $ 16.21 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS3_CB4_CS4_RV_TR_AV_DU8_AL_DL2 1
Days gain with 21 stocks: 15.13 20230714
