CSIQ Gain: $ -3.86 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS2_CB5_CS4_AV_UA_TG_DU8_AL_DL2 3
WMT Gain: $ -1.42 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB5_OS3_CB5_CS5_TR_IR3_TG_DU7_AV_DL2 11
NNOX Gain: $ -1.31 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB5_CS5_IR3 13
BBWI Gain: $ -0.98 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB2_CS4_HM_AV_DU8_DL2_TG 2
IMVT Gain: $ -0.71 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS3_DU8_AL 15
GLD Gain: $ -0.58 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB4_OS2_CB5_CS5_AO_DU6 9
AU Gain: $ -0.34 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 12
KMB Gain: $ -0.32 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS4_CB4_CS3_UA_WT_DU8_AV_DL2 16
WEN Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB3_HS_HL_QM_TG_OB2_OS4_CB5_CS2_HM_DU8_AV_DL2 4
K Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 16 18 20
PG Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 6
GFI Gain: $ -0.1 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 14
HL Gain: $ -0.1 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS2_CB2_CS5_RV_TR_DU7_UA_AV_DL2 19
KHC Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_RV_QP_QL_DB10_DU6_UA_DU7_DL2 20
SBS Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 21
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 8
JNJ Gain: $ 0.09 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS3_AV_TS_DU8_UA_DL2 17
MMM Gain: $ 0.71 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB3_OS3_CB5_CS4_SS_DU7_AV_DL1 10
CSCO Gain: $ 0.98 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_DL1 1
NFLX Gain: $ 4.45 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB5_CS5_AV_TS 7
SNPS Gain: $ 5.58 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB3_OS3_CB5_CS4_RV_DU8_AV_DL2_TG 5
Days gain with 21 stocks: 1.55 20230518
