ADBE Gain: $ -20.23 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB2_CS5_LI_DU8_AV_DL2 13
CELH Gain: $ -5.12 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB5_CS4_HM_AV_DB30 14
BLDR Gain: $ -3.09 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB5_OS3_CB4_CS5_HM_AV_DB30_DU7_UA_DL2 16
BNTX Gain: $ -2.52 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB5_CS3_HM_AL_DU7 21
TSN Gain: $ -1.48 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS3_CB2_CS5_AL_TS_AV_DU8_DL2 11
AMAT Gain: $ -1.27 Win %: 0.0 in 1 days with algo TB4_LO_QM_OB3_OS3_CB4_CS4_HM 15
PKG Gain: $ -1.27 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB2_OS3_CB4_CS5_AV_TG_DU7_AL_DL2 17
VERV Gain: $ -1.22 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS4_CB5_CS3_RV_TR_DB6_DU7_AL_DL2 1
PPC Gain: $ -0.81 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS3_HM_DU7_UA_DL2 11
MU Gain: $ -0.71 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP 8
BBWI Gain: $ -0.56 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB2_CS4_HM_AV_DU8_DL2_TG 12
VYGR Gain: $ -0.56 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB3_OS2_CB3_CS5_DU6_AL 9 10
TH Gain: $ -0.54 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS4_CB4_CS3_QL_DU7_UA_TG 9 16
SUPN Gain: $ -0.44 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB4_OS5_CB2_CS5_AV_DU8_AL_DL2 4
FLO Gain: $ -0.39 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 14
UAA Gain: $ -0.33 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB1_OS5_CB4_CS4_AV_IT_DU8_DL2 13
BCH Gain: $ -0.32 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_TR_IR3_DU7_AV_DL2 4
KHC Gain: $ -0.26 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_RV_QP_QL_DB10_DU6_UA_DU7_DL2 17
NXE Gain: $ -0.23 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS3_CB3_CS5_HM_AV_DU8_DL2_UA 5
ACMR Gain: $ -0.19 Win %: 0.0 in 1 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV 19
INTC Gain: $ -0.19 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 18
UBS Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 20
IMMR Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 2
EXPI Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS2_CB5_CS5_PM 20
LTHM Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB4_CS4_HM_AV_DB30_DU7_UA_DL2 16
DNUT Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV 18
IONQ Gain: $ 0.16 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 5
LI Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB5_OS5_CB2_CS4_IT_QL_DB10_AV_TG_DU7_DL1_DU8_UA_DL2_AL 10 12 15
APP Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB3_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR_DB10 6
MDT Gain: $ 0.27 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB3_CS3_AL_TS 2 19
DELL Gain: $ 0.34 Win %: 100.00 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM 7
HD Gain: $ 0.54 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 21
LIN Gain: $ 0.8 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB2_OS3_CB3_CS5_AL_TS_UA_AV 10
ABT Gain: $ 1.55 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS2_TR_QP_DB10_DU7_UA_DL2 6
BA Gain: $ 1.58 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_DB6_DU7_AL_DL2 1 3
XBI Gain: $ 7.61 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS4_CB5_CS2_RV_AL_TG_DU7 8
LLY Gain: $ 37.76 Win %: 100.00 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 3 7
Days gain with 37 stocks: 8.94 20231113
