ARGX Gain: $ -9.55 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB4_CS3_HM_TR_DB30_DU7_DL1 7
AEHR Gain: $ -9.26 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 19
UPST Gain: $ -8.54 Win %: 0.0 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV 2
QQQ Gain: $ -5.43 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB4_CS4_AL 12 17
EDU Gain: $ -2.64 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS5_CB5_CS2_DU12_TG 9
SLB Gain: $ -1.85 Win %: 0.0 in 1 days with algo TB3_BL_QM_OB5_OS3_CB5_CS4_RV_AL_DU7_UA_DL2 4
U Gain: $ -1.4 Win %: 0.0 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB4_CS4_HM 2 9 21
ABT Gain: $ -1.28 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS2_TR_QP_DB10_DU7_UA_DL2 8
XLK Gain: $ -1.2 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB3_CS3_IT_QL_DB6 18
GOOG Gain: $ -0.98 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 13
MAT Gain: $ -0.41 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB4_OS2_CB4_CS4_SR_DU8_AV_DL2 3
SOXL Gain: $ -0.21 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB5_OS2_CB5_CS4_SS_AL 14
FTI Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB3_OS4_CB4_CS2_DU6_UA_AV 5
EVO Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS5_RV_DU7 10
TECL Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS2_CB5_CS4_AO_AC_DU7_UA_AV_DL1 11
VIGI Gain: $ -0.04 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS4_CB5_CS2_AV_TS_DU7_AL 15
ASML Gain: $ 0.54 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB2_OS2_CB2_CS4_PM_DU7_DL1 6
RIOT Gain: $ 0.71 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 20
AXP Gain: $ 1.37 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB3_OS2_CB5_CS3_TR_TS_DU7_UA_DL2 1
TQQQ Gain: $ 3.62 Win %: 100.00 in 1 days with algo TB3_HS_HL_QM_OB5_OS2_CB4_CS5_SS_DU6 12
NVDA Gain: $ 11.91 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 16
Days gain with 21 stocks: -24.9 20230721
