ACMR Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV 16
ADBE Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB2_CS5_LI_DU8_AV_DL2 1
ALDX Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB2_OS4_CB5_CS4_HM_AV_UA_DU7 6
AZN Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS4_CB3_CS2_RV_DU7_AV_DL2_DU5 11
BULZ Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB5_OS2_CB5_CS4_HM_AV_DU7_UA_DL1 12
CCL Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 17
CRH Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB3_OS2_CB4_CS3_RV_AV_DB6_DU7 10
CSIQ Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS2_CB5_CS4_AV_UA_TG_DU8_AL_DL2 13
DB Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 1 14
DKNG Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_HM_AL_DU7 21
ERJ Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_HM_AV 9
FLO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 5
INTC Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 15
ITUB Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS2_CB4_CS3_RV_AV_DU7_UA_AL_DL2_TG 20
LITE Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB5_CS3_VI_AL 3
MRVL Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_IT_TS 18
MU Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP 7
NVDA Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 8
SOFI Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 2
SOXL Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB5_OS2_CB5_CS4_SS_AL 19
STLD Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB2_CS3_HM_AV_DU8_UA_DL2 4
Days gain with 21 stocks: 0 20230616
