LULU Gain: $ -3.35 Win %: 0 in 1 days with algo TB3_PL_QM_OB5_OS1_CB2_CS5_AL_TS_DU6_UA_AV 1
ANVS Gain: $ -2.6 Win %: 0 in 1 days with algo TB1_EO_EC_QM_OB3_OS2_CB3_CS5_RV_DU7_DL2 8
MPC Gain: $ -1.0 Win %: 0 in 1 days with algo TB5_OO_QM_OB5_OS2_CB2_CS5_PM_DU7_UA_DL2_DU8_AL_TG 4
YPF Gain: $ -0.59 Win %: 0 in 1 days with algo TB3_OO_QM_OB4_OS2_CB4_CS4_HM_AV_DU8_DL2_UA 2
WOOF Gain: $ -0.56 Win %: 0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS4_DU6_TG_UA 3
MRK Gain: $ -0.53 Win %: 0 in 1 days with algo TB3_OO_QM_OB2_OS2_CB2_CS3_DB10_DU7_TG_AV_DL2 19
OXY Gain: $ -0.49 Win %: 0 in 1 days with algo TB1_EO_EC_QM_OB4_OS2_CB2_CS4_AV_UA_DU6_TG_DU7_DL2 12
VLO Gain: $ -0.34 Win %: 0 in 1 days with algo TB3_LO_HL_QM_OB4_OS4_CB5_CS4_HM_AV_DU7_DL2_TG 10
RIOT Gain: $ -0.28 Win %: 0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 20
DLTR Gain: $ -0.24 Win %: 0 in 1 days with algo TB5_LO_QM_OB3_OS2_CB3_CS5_AL_LI_DU8_AV_DL2 14
BCH Gain: $ -0.11 Win %: 0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_TR_IR3_DU7_AV_DL2 6
CCL Gain: $ -0.1 Win %: 0 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 7
ET Gain: $ -0.09 Win %: 0 in 1 days with algo TB1_EO_EC_QM_OB4_OS2_CB3_CS4_AV_TS_DU7_AL_DL2 13
UBS Gain: $ -0.09 Win %: 0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 15
ESLT Gain: $ 0.0 Win %: in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 5
EVO Gain: $ 0.0 Win %: in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS5_RV_DU7 11
IONQ Gain: $ 0.1 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 18
BA Gain: $ 0.13 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_DB6_DU7_AL_DL2 9
FTI Gain: $ 0.55 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB3_OS4_CB4_CS2_DU6_UA_AV 17
UNH Gain: $ 4.67 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS3_CB4_CS4_RV_TR_AV_DU8_AL_DL2 21
MSTR Gain: $ 9.14 Win %: 100.00 in 1 days with algo TB4_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AV 16
Days gain with 21 stocks: 4.22 20230329
