RBLX Gain: $ -0.96 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB2_CS5_VI_DU7_AV_DL2 1
AMAT Gain: $ -0.82 Win %: 0.0 in 1 days with algo TB4_LO_QM_OB3_OS3_CB4_CS4_HM 8
LITE Gain: $ -0.36 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB5_CS3_VI_AL 14
MSFT Gain: $ -0.35 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB5_OS3_CB2_CS5_RV_AL_DB6_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA 19
GOOG Gain: $ -0.26 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 6
MARA Gain: $ -0.26 Win %: 0.0 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 9
XPEV Gain: $ -0.23 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB5_CS3_AV_TS_DU5_AV_AV_AV_AV_AV_AV_AV_AV 12
UBS Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 4
RIOT Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 3
YMM Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB5_OS3_CB5_CS4_RV_AV_DU8_UA_DL2 20
MAXR Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS2_CB5_CS2_TR_TS_DU7 5
IMMR Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 11
DB Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 21
HPQ Gain: $ 0.25 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB1_OS1_CB5_CS5_TS 16
LI Gain: $ 0.38 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB5_OS5_CB2_CS4_IT_QL_DB10_AV_TG_DU7_DL1_DU8_UA_DL2_AL 14 18
DELL Gain: $ 0.51 Win %: 100.00 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM 10
ASML Gain: $ 0.63 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB2_OS2_CB2_CS4_PM_DU7_DL1 7
MSTR Gain: $ 1.49 Win %: 100.00 in 1 days with algo TB4_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AV 17
RACE Gain: $ 1.78 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB3_OS2_CB5_CS4_RV_AV_DU8_UA_DL2 15
BTU Gain: $ 3.56 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB4_OS2_CB2_CS5_AV_UA_DU7 2
SCHW Gain: $ 4.27 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB2_OS2_CB5_CS3_RV_TR_DU7_AL_DL2_UA 13
Days gain with 21 stocks: 9.09 20230417
