LLY Gain: $ -4.68 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 18
TAP Gain: $ -2.31 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_AL_IT_DU8_UA_DL2 5
SOXL Gain: $ -1.26 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB5_OS2_CB5_CS4_SS_AL 8
MVIS Gain: $ -1.19 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB5_OS2_CB3_CS5_HM_AV_DU7_TG 10
COIN Gain: $ -0.99 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV_DB8 1
CRH Gain: $ -0.81 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB3_OS2_CB4_CS3_RV_AV_DB6_DU7 15
ALDX Gain: $ -0.44 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB2_OS4_CB5_CS4_HM_AV_UA_DU7 11
EQNR Gain: $ -0.39 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB4_CS5_RV_AV_DU6_UA 21
RIOT Gain: $ -0.38 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 6
FAST Gain: $ -0.24 Win %: 0.0 in 1 days with algo TB3_HS_HL_QM_OB5_OS3_CB2_CS5_HM_TR_DU7 3
IONQ Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 7
UWMC Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS2_CB2_CS4_AV_UA_DU7 20
HOOD Gain: $ -0.04 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB3_CS3_HM_TR 16
ASML Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS2_CB2_CS4_PM_DU7_DL1 17
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 13
ICL Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS2_CB4_CS5_RV_AL_DB10_UA 2
U Gain: $ 0.25 Win %: 100.00 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB4_CS4_HM 19 20
MOS Gain: $ 0.32 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB3_OS4_CB3_CS3_DB6_UA 12
STZ Gain: $ 0.79 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB5_OS3_CB2_CS5_HM_AV_DB10_DU6 4
CI Gain: $ 3.44 Win %: 100.00 in 1 days with algo TB1_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AL 14
SHOP Gain: $ 6.42 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS5_CB5_CS5_HM_DU6 9
Days gain with 21 stocks: -1.89 20230606
