JPM Gain: $ -7.37 Win %: 0 in 1 days with algo TB3_OC_QM_OB4_OS3_CB3_CS5_HM_AV_DB10_DU6_UA_UA 20
XOM Gain: $ -5.8 Win %: 0 in 1 days with algo TB1_OC_QM_OB3_OS4_CB3_CS5_AL_LI_DU6_UA 21
AXP Gain: $ -5.5 Win %: 0 in 1 days with algo TB1_HS_HL_QM_OB3_OS2_CB5_CS3_TR_TS_DU7_UA_DL2 16
GS Gain: $ -3.32 Win %: 0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_RV_AV_DB6_DU6_UA_TG_DU7_DL2 18
WFC Gain: $ -2.32 Win %: 0 in 1 days with algo TB1_LO_QM_OB2_OS3_CB5_CS4_AO_AC_AL 8
CRH Gain: $ -1.84 Win %: 0 in 1 days with algo TB5_CC_QM_OB3_OS2_CB4_CS3_RV_AV_DB6_DU7 14
IRDM Gain: $ -1.56 Win %: 0 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB4_CS3_AL_DU8_AV_DL2 12
C Gain: $ -1.39 Win %: 0 in 1 days with algo TB1_HL_QM_OB5_OS5_CB5_CS5_RV_AV_DB30 5 6 8 14
FITB Gain: $ -1.01 Win %: 0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB3_CS5_AV_DU7 9
MPC Gain: $ -0.54 Win %: 0 in 1 days with algo TB5_OO_QM_OB5_OS2_CB2_CS5_PM_DU7_UA_DL2_DU8_AL_TG 5
EURN Gain: $ -0.51 Win %: 0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS3_AV_VI_DU8_DL2_AL 10
MT Gain: $ -0.46 Win %: 0 in 1 days with algo TB5_HI_QM_OB5_OS2_CB5_CS5_HM_AL_DU7_UA_DL2 4
EDU Gain: $ -0.45 Win %: 0 in 1 days with algo TB5_OO_QM_OB2_OS5_CB5_CS2_DU12_TG 15
UBS Gain: $ -0.34 Win %: 0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 2
DB Gain: $ -0.26 Win %: 0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 3
FRO Gain: $ -0.25 Win %: 0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 1
RIG Gain: $ -0.24 Win %: 0 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 11
VIGI Gain: $ -0.23 Win %: 0 in 1 days with algo TB5_LO_QM_OB2_OS4_CB5_CS2_AV_TS_DU7_AL 13
RWM Gain: $ -0.01 Win %: 0 in 1 days with algo TB1_HI_HL_QM_OB2_OS3_CB3_CS4_AV_IT_DU8_DL2_AL_DU7 19
FAZ Gain: $ 1.01 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB2_OS5_CB5_CS3_RV_AL_DB30_DU7_UA_AV_DL2_DU8 17
STLD Gain: $ 2.31 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB2_CS3_HM_AV_DU8_UA_DL2 7
Days gain with 21 stocks: -30.08 20230315
