TCOM Gain: $ -3.31 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS2_CB2_CS4_RV_AL_UA_DU7_DL2 12
BURL Gain: $ -2.17 Win %: 0.0 in 1 days with algo TB2_HL_HI_QM_OB1_OS1_CB5_CS5_AL_TS 1
CELH Gain: $ -2.17 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB5_CS4_HM_AV_DB30 20
A Gain: $ -1.68 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS5_CB4_CS5_HM_TR_DU7_UA_DL2 5 6 17
VMW Gain: $ -1.6 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB1_CS1_QL 4
LEN Gain: $ -1.38 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB4_OS4_CB5_CS5_RV_AV 21
CRH Gain: $ -1.02 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB3_OS2_CB4_CS3_RV_AV_DB6_DU7 15
JBL Gain: $ -0.91 Win %: 0.0 in 1 days with algo TB2_HL_HS_QM_OB1_OS1_CB4_CS4_SS 18
GOGL Gain: $ -0.53 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 11
COIN Gain: $ -0.42 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV_DB8 19
MDT Gain: $ -0.33 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB3_CS3_AL_TS 14
SBSW Gain: $ -0.3 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS2_CB3_CS5_DU12_AL_UA 3
INCY Gain: $ -0.29 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS2_CB5_CS4_RV_AV_DB30_DU7_AL_DL1 8
GLD Gain: $ -0.23 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB4_OS2_CB5_CS5_AO_DU6 16
LOW Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS5_AV_TS_DU7_AL_DL2 7
ZM Gain: $ 0.52 Win %: 100.00 in 1 days with algo TB1_HL_HS_QM_OB5_OS5_CB5_CS5_AL 13
KSS Gain: $ 0.7 Win %: 100.00 in 1 days with algo TB5_BL_QM_OB2_OS3_CB4_CS5_AL_UA_AV_DU5_DL2 10
CAH Gain: $ 0.77 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU7_DL2 17
BBY Gain: $ 1.42 Win %: 100.00 in 1 days with algo TB5_EO_EC_QM_OB3_OS4_CB5_CS4_TR_UA_AL 9
DKS Gain: $ 3.14 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS2_CB4_CS4_AL_TS_DU7_DL2 2
ANF Gain: $ 4.28 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB3_OS5_CB2_CS2_RV_DU8_AL_DL2 6
Days gain with 21 stocks: -5.52 20231121
