AMGN Gain: $ -11.57 Win %: 0.0 in 1 days with algo TB3_HL_QM_OB3_OS1_CB2_CS3_HM_AV_DB10_DU8_DL2 7
LLY Gain: $ -10.45 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 1
LOW Gain: $ -4.24 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS5_AV_TS_DU7_AL_DL2 20
SNOW Gain: $ -2.77 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_RV_AL_DU7_UA_DL2 9
JPM Gain: $ -1.7 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB4_OS3_CB3_CS5_HM_AV_DB10_DU6_UA_UA 21
FITB Gain: $ -1.42 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB3_CS5_AV_DU7 11
UWMC Gain: $ -0.9 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS2_CB2_CS4_AV_UA_DU7 3
ZG Gain: $ -0.86 Win %: 0.0 in 1 days with algo TB3_HL_HI_QM_OB2_OS2_CB5_CS5_IR3 14
BYND Gain: $ -0.82 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB4_OS4_CB5_CS5_RV_AV 2
CLX Gain: $ -0.71 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS3_AV_DU7_UA_DL2 19
RIOT Gain: $ -0.66 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 16
NIO Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_HM_AV_DB10_DU6_DU6_AL_TG_UA_UA_UA_UA_UA 15
UNIT Gain: $ -0.29 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB1_OS4_CB3_CS3_AV_TS_DU7 18
DB Gain: $ -0.21 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 6 12
SOFI Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 13
VIPS Gain: $ 0.42 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS2_DU8_TG 17
UPST Gain: $ 0.89 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV 4
RF Gain: $ 1.81 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB2_OS2_CB5_CS4_PM_DU8_DL2_UA_AV 10
UPS Gain: $ 2.03 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB4_OS2_CB2_CS5_TS_DU7_UA_DL2 4 8
USB Gain: $ 2.79 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS4_VI_DU7_UA_DL2 5
MDB Gain: $ 5.43 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_UA_DL1 6
Days gain with 21 stocks: -23.87 20230808
