BA Gain: $ -8.32 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_DB6_DU7_AL_DL2 7
V Gain: $ -5.09 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS4_CB4_CS4_RV_AV_DB30_DU7 5
GPN Gain: $ -3.0 Win %: 0.0 in 1 days with algo TB3_HL_HS_QM_OB1_OS1_CB5_CS5_AL 8
TTD Gain: $ -2.45 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS3_SR_DU7_UA_AV_DL2_TG 13
MSFT Gain: $ -2.42 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB5_OS3_CB2_CS5_RV_AL_DB6_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA 2
RY Gain: $ -0.89 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB4_OS2_CB4_CS5_RV_AV_DU7_UA_DL2 11
ON Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB4_CS4_RV_TR_DB6_DU7 15
FAST Gain: $ -0.43 Win %: 0.0 in 1 days with algo TB3_HS_HL_QM_OB5_OS3_CB2_CS5_HM_TR_DU7 19
GPS Gain: $ -0.33 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB3_OS2_CB5_CS5_DU6_AL 6
GLW Gain: $ -0.22 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB3_CS2_RV_DU5_DL2_AL_TG 9
GOGL Gain: $ -0.22 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 12
DB Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 3 18
ET Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB4_OS2_CB3_CS4_AV_TS_DU7_AL_DL2 21
TAL Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB3_OS3_CB3_CS4_LI_DU7_UA 17
PYPL Gain: $ 0.81 Win %: 100.00 in 1 days with algo TB1_CC_QM_OB5_OS2_CB4_CS4_DU7_DL2_AL_DL1 20
SNAP Gain: $ 1.05 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS3_RV_TR_DB6_DU6_UA_AV_DU7_TG_DU8_AL_DL2 14
AFRM Gain: $ 1.09 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB2_OS2_CB5_CS5_RV_AV 4
GOOG Gain: $ 1.29 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 1
DKNG Gain: $ 2.31 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_HM_AL_DU7 16
NXPI Gain: $ 2.65 Win %: 100.00 in 1 days with algo TB4_OC_QM_OB1_OS1_CB5_CS5_HM_AV 10
ADBE Gain: $ 10.66 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB2_CS5_LI_DU8_AV_DL2 18
Days gain with 21 stocks: -3.86 20231025
