MDB Gain: $ -12.46 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_UA_DL1 12
XBI Gain: $ -6.13 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS4_CB5_CS2_RV_AL_TG_DU7 6
RACE Gain: $ -5.89 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB3_OS2_CB5_CS4_RV_AV_DU8_UA_DL2 19
SNOW Gain: $ -4.71 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_RV_AL_DU7_UA_DL2 5
FRO Gain: $ -0.76 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 4
SNAP Gain: $ -0.74 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS3_RV_TR_DB6_DU6_UA_AV_DU7_TG_DU8_AL_DL2 13
KHC Gain: $ -0.53 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_RV_QP_QL_DB10_DU6_UA_DU7_DL2 11
UBS Gain: $ -0.22 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 7
MNSO Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 9
KR Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS3_CB3_CS5_TR_IR3_DU8_DL2_UA_AV 10
HOOD Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB3_CS3_HM_TR 15
D Gain: $ 0.08 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS4_CB5_CS2_AV_TS_DU7_AL_DL2 8 12 15 16 20
PSTG Gain: $ 0.09 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS5_QL_DU8_UA_AV_DL2 2
K Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 10 11 17 20
ERJ Gain: $ 0.17 Win %: 100.00 in 1 days with algo TB4_HL_HI_QM_OB2_OS2_CB3_CS3_HM_AV 18
VVOS Gain: $ 0.18 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB3_OS3_CB3_CS3_IT_QL_DB30 1
WEN Gain: $ 0.34 Win %: 100.00 in 1 days with algo TB3_HS_HL_QM_TG_OB2_OS4_CB5_CS2_HM_DU8_AV_DL2 21
EDU Gain: $ 0.7 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS5_CB5_CS2_DU12_TG 16
DUK Gain: $ 0.74 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_QL_DU7_AL_DL2 20
CRM Gain: $ 2.23 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB5_OS2_CB3_CS5_TR_TS_DU7_DL1 3
PINS Gain: $ 2.43 Win %: 100.00 in 1 days with algo TB1_PL_QM_OB3_OS1_CB3_CS4_HM_AV_AL_DU7 14
Days gain with 21 stocks: -24.62 20231130
