NVDA Gain: $ -12.29 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 3
LLY Gain: $ -9.38 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 10
PINS Gain: $ -3.12 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB3_OS1_CB3_CS4_HM_AV_AL_DU7 12
ON Gain: $ -1.59 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB4_CS4_RV_TR_DB6_DU7 20
SOXL Gain: $ -1.09 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB5_OS2_CB5_CS4_SS_AL 8
MLCO Gain: $ -0.97 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB2_OS2_CB4_CS5_UA_DU7 15
GIS Gain: $ -0.89 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB1_OS1_CB3_CS1_AL_UA_AV 1
TSM Gain: $ -0.87 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB4_OS3_CB3_CS5_RV_DU7 17
K Gain: $ -0.79 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 2 4 11
OSTK Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV 4
RIOT Gain: $ -0.46 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 21
KHC Gain: $ -0.42 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_RV_QP_QL_DB10_DU6_UA_DU7_DL2 11
AU Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 19
SBS Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 18
HRL Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_DU6_DL_TG_DU7_DL1 13
MRVL Gain: $ 0.56 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_IT_TS 5
SJM Gain: $ 0.75 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB3_OS2_CB5_CS4_DB6_UA 7
ATVI Gain: $ 1.36 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB2_OS2_CB2_CS5_DU6_AL 16
AMAT Gain: $ 1.38 Win %: 100.00 in 1 days with algo TB4_LO_QM_OB3_OS3_CB4_CS4_HM 6
AMD Gain: $ 4.71 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB3_OS4_CB4_CS4_HM_AL_DU6_UA_AV 9
NFLX Gain: $ 4.98 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB5_CS5_AV_TS 14
Days gain with 21 stocks: -18.81 20230628
