NVDA Gain: $ -6.73 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 16
LLY Gain: $ -5.7 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 14
AEHR Gain: $ -5.54 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 10
MMM Gain: $ -1.88 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB3_OS3_CB5_CS4_SS_DU7_AV_DL1 17
LEGN Gain: $ -1.85 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS3_CB5_CS5_HM_AL 14
LAC Gain: $ -1.5 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS2_CB2_CS4_TR_TS_DU7_AV_DL2_TG 15
QDEL Gain: $ -1.44 Win %: 0.0 in 1 days with algo TB3_HL_HI_QM_OB3_OS3_CB3_CS3_IR3 21
AZPN Gain: $ -1.25 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS5_CB3_CS5_AV_DU7_DL2 10
ROST Gain: $ -0.9 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS4_CB5_CS5_HM 12
IMTX Gain: $ -0.7 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS5_CB3_CS2_RV_DU7 20
CHKP Gain: $ -0.65 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS2_CB2_CS5_RV_AV_DB6_DU6_AL 4
KALV Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB1_HI_QM_OB3_OS3_CB4_CS4_PM 16
INFL Gain: $ -0.33 Win %: 0.0 in 1 days with algo TB1_HI_QM_OB3_OS2_CB5_CS3_HM_AV_DU7 8
PDCO Gain: $ -0.32 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB4_OS2_CB4_CS5_HM_AL_DU7_DL1 13
PPC Gain: $ -0.31 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS3_HM_DU7_UA_DL2 7
ANF Gain: $ -0.3 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS5_CB2_CS2_RV_DU8_AL_DL2 20
ABT Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS2_TR_QP_DB10_DU7_UA_DL2 13
AKAM Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB5_OS5_CB3_CS4_HM_AV_DU7_DL1 3
TH Gain: $ -0.26 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS4_CB4_CS3_QL_DU7_UA_TG 6 15
COIN Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV_DB8 18
UTHR Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB3_HL_LO_QM_OB1_OS1_CB3_CS3_RV 6
FLO Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 19
SWN Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB3_CS4_TR_TS_AL_UA_TG 21
HRL Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_DU6_DL_TG_DU7_DL1 9
INCY Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS2_CB5_CS4_RV_AV_DB30_DU7_AL_DL1 5
VTRS Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS5_CB5_CS4_IR1_DU7_AL 2 2
IMMR Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 11
SLVO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB4_OS3_CB3_CS3_DB10_UA 5 18
SUPN Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB4_OS5_CB2_CS5_AV_DU8_AL_DL2 9
DNUT Gain: $ 0.06 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV 19
RIOT Gain: $ 0.13 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 3
SLV Gain: $ 0.17 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB5_OS2_CB2_CS5_AV_TS_DU7_UA_DL1 5 12 18
VTGN Gain: $ 0.19 Win %: 100.00 in 1 days with algo TB4_CC_QM_OB2_OS2_CB4_CS4_HM 4
NEE Gain: $ 0.7 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB4_OS2_CB3_CS4_TR_TS_AL_DU7_AV_DL1_DL2 7
MARA Gain: $ 0.86 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 6
MCD Gain: $ 1.09 Win %: 100.00 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB2_CS5_DU8_AL 11
VYGR Gain: $ 1.18 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS2_CB3_CS5_DU6_AL 17
K Gain: $ 2.47 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 1 1 3 4 16
MSTR Gain: $ 11.81 Win %: 100.00 in 1 days with algo TB4_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AV 8
Days gain with 39 stocks: -12.97 20231002
