SRTY Gain: $ -18.58 Win %: 0 in 1 days with algo TB1_OC_QM_OB2_OS4_CB5_CS5_AL_UA_TG_DU7 13
SCHW Gain: $ -10.04 Win %: 0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB5_CS3_RV_TR_DU7_AL_DL2_UA 1
AEHR Gain: $ -6.34 Win %: 0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 17
TNA Gain: $ -3.07 Win %: 0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB3_CS5_IR1_DU7_AL_DL2 19
WFC Gain: $ -2.95 Win %: 0 in 1 days with algo TB1_LO_QM_OB2_OS3_CB5_CS4_AO_AC_AL 10
C Gain: $ -0.98 Win %: 0 in 1 days with algo TB1_HL_QM_OB5_OS5_CB5_CS5_RV_AV_DB30 1 5 6 10
UBER Gain: $ -0.9 Win %: 0 in 1 days with algo TB3_OO_QM_OB3_OS4_CB3_CS5_QL_DU7_UA_DL2 9
JPM Gain: $ -0.6 Win %: 0 in 1 days with algo TB3_OC_QM_OB4_OS3_CB3_CS5_HM_AV_DB10_DU6_UA_UA 20
USB Gain: $ -0.46 Win %: 0 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS4_VI_DU7_UA_DL2 3
MS Gain: $ -0.03 Win %: 0 in 1 days with algo TB2_OO_QM_OB4_OS4_CB5_CS5_IT_QP_DB15 8
RWM Gain: $ -0.02 Win %: 0 in 1 days with algo TB1_HI_HL_QM_OB2_OS3_CB3_CS4_AV_IT_DU8_DL2_AL_DU7 11
IWM Gain: $ 0.0 Win %: 100.00 in 1 days with algo TB1_HI_QM_OB5_OS3_CB5_CS4_IT_QP_QL_TG_DU7_AL_DL2 14
BAC Gain: $ 0.29 Win %: 100.00 in 1 days with algo TB2_CC_QM_OB3_OS3_CB5_CS5_RV_AL_DB15 6
RF Gain: $ 0.75 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB2_OS2_CB5_CS4_PM_DU8_DL2_UA_AV 4
FAZ Gain: $ 0.93 Win %: 100.00 in 1 days with algo TB1_LO_QM_OB2_OS5_CB5_CS3_RV_AL_DB30_DU7_UA_AV_DL2_DU8 7
TAL Gain: $ 1.11 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB3_OS3_CB3_CS4_LI_DU7_UA 15
DPST Gain: $ 1.26 Win %: 100.00 in 1 days with algo TB3_LO_HL_QM_OB3_OS2_CB4_CS3_HM_TR_DU7_AV_DL1 18
URTY Gain: $ 1.3 Win %: 100.00 in 1 days with algo TB5_HS_HL_QM_TG_OB3_OS2_CB3_CS2_SS_DU7_DL2 21
AXP Gain: $ 1.34 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB3_OS2_CB5_CS3_TR_TS_DU7_UA_DL2 16
TZA Gain: $ 7.74 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB2_OS4_CB2_CS5_RV_AV_AL_TG_DU7 12
FITB Gain: $ 12.24 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB3_CS5_AV_DU7 2
Days gain with 21 stocks: -17.01 20230314
