LLY Gain: $ -16.17 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 13
RMD Gain: $ -2.87 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS4_CB4_CS4_TR_IR1_DU7_UA_AV_DL1 16
VMW Gain: $ -1.58 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB1_CS1_QL 4
CRM Gain: $ -1.23 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB5_OS2_CB3_CS5_TR_TS_DU7_DL1 19
XBI Gain: $ -1.21 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS4_CB5_CS2_RV_AL_TG_DU7 20
IMVT Gain: $ -1.09 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS3_DU8_AL 1
OXY Gain: $ -1.03 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB4_OS2_CB2_CS4_AV_UA_DU6_TG_DU7_DL2 15
PPC Gain: $ -0.74 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS3_HM_DU7_UA_DL2 5
YPF Gain: $ -0.62 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB4_OS2_CB4_CS4_HM_AV_DU8_DL2_UA 2
LIN Gain: $ -0.37 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS3_CB3_CS5_AL_TS_UA_AV 21
ASAN Gain: $ -0.3 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB5_OS2_CB2_CS5_RV_AV_DB6_TG_DU7_DL2 17
VTRS Gain: $ -0.3 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS5_CB5_CS4_IR1_DU7_AL 3
AGNC Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB4_OS2_CB2_CS4_HM_AV_DU8_UA_DL2_DU7_DL1_AL 18
BCRX Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_RV_AV_DB6 12
NEE Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB4_OS2_CB3_CS4_TR_TS_AL_DU7_AV_DL1_DL2 14
DUK Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_QL_DU7_AL_DL2 9
SBLK Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB3_CS5_AL_TS_DU8_AV_DL2 6
MOS Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB3_OS4_CB3_CS3_DB6_UA 8
D Gain: $ 0.5 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS4_CB5_CS2_AV_TS_DU7_AL_DL2 7 9 16
WM Gain: $ 0.77 Win %: 100.00 in 1 days with algo TB5_LO_HL_QM_OB3_OS2_CB3_CS2_RV_AV_UA_DU8_AL_DL2 11
PBR Gain: $ 1.33 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB3_OS2_CB2_CS5_HM_TR_DU6_AL_UA 10
Days gain with 21 stocks: -25.26 20231023
