ARGX Gain: $ -37.79 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB4_CS3_HM_TR_DB30_DU7_DL1 1
LOW Gain: $ -6.12 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS5_AV_TS_DU7_AL_DL2 12
IMVT Gain: $ -5.85 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS3_DU8_AL 2
AKAM Gain: $ -0.9 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB5_OS5_CB3_CS4_HM_AV_DU7_DL1 16
KHC Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_RV_QP_QL_DB10_DU6_UA_DU7_DL2 11
GOOG Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 21
SH Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS5_TR_TS_DU7_UA_AV_DL2_DL1 7
K Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 9 11 16
TMUS Gain: $ 0.01 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS4_HM_AV_DU7_AL_DL2 19
PSQ Gain: $ 0.1 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB2_OS4_CB5_CS5_TR_TS_DU7_DL2 14
GIS Gain: $ 0.23 Win %: 100.00 in 1 days with algo TB5_PL_QM_OB1_OS1_CB3_CS1_AL_UA_AV 3
RIOT Gain: $ 0.27 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 8
RWM Gain: $ 0.37 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB2_OS3_CB3_CS4_AV_IT_DU8_DL2_AL_DU7 17
BCH Gain: $ 0.53 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_TR_IR3_DU7_AV_DL2 18
DOG Gain: $ 0.64 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB2_OS4_CB3_CS4_AL_LI_DU7_DL2 10
UPS Gain: $ 0.89 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB4_OS2_CB2_CS5_TS_DU7_UA_DL2 6
MARA Gain: $ 1.24 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 5
MO Gain: $ 1.79 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB4_OS2_CB5_CS5_RV_DU8 4
ZM Gain: $ 1.82 Win %: 100.00 in 1 days with algo TB1_HL_HS_QM_OB5_OS5_CB5_CS5_AL 15
COST Gain: $ 4.73 Win %: 100.00 in 1 days with algo TB5_PL_QM_OB4_OS3_CB5_CS4_DU8_UA_TG_AV_DL2_AL 13
CRM Gain: $ 12.63 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB5_OS2_CB3_CS5_TR_TS_DU7_DL1 20
Days gain with 21 stocks: -25.89 20231220
