SNPS Gain: $ -8.08 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS3_CB5_CS4_RV_DU8_AV_DL2_TG 12
COST Gain: $ -5.73 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB4_OS3_CB5_CS4_DU8_UA_TG_AV_DL2_AL 18
NFLX Gain: $ -3.43 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB5_CS5_AV_TS 5
MRK Gain: $ -3.04 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS2_CB2_CS3_DB10_DU7_TG_AV_DL2 15
KMB Gain: $ -1.49 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS4_CB4_CS3_UA_WT_DU8_AV_DL2 13
CROX Gain: $ -1.21 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB2_OS4_CB5_CS4_QL_AV 11
MRVL Gain: $ -0.96 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_IT_TS 2
INTC Gain: $ -0.88 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 10
QCOM Gain: $ -0.86 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB5_CS5_AV_TS_UA_AL 17
ATVI Gain: $ -0.58 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB2_CS5_DU6_AL 7
F Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS2_CB5_CS4_HM_AV_DU7_AL_UA 3 5 14
RIG Gain: $ -0.26 Win %: 0.0 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 20
AGNC Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB4_OS2_CB2_CS4_HM_AV_DU8_UA_DL2_DU7_DL1_AL 16
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 8
SOFI Gain: $ 0.03 Win %: 100.00 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 3
ANET Gain: $ 0.24 Win %: 100.00 in 1 days with algo TB1_CC_QM_OB2_OS5_CB5_CS2_QP_QL_PM_DU6_UA_AV_DU7_AL 6
CHPT Gain: $ 0.3 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB3_OS4_CB3_CS2_AV_TS_DU8_UA_DL2_AL 21
IONQ Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 4
GPS Gain: $ 0.58 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB3_OS2_CB5_CS5_DU6_AL 19
K Gain: $ 1.26 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 9 13 15
AAP Gain: $ 4.81 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS5_AL_UA_AV 1
Days gain with 21 stocks: -19.13 20230531
