LOW Gain: $ -3.45 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS5_AV_TS_DU7_AL_DL2 5
HD Gain: $ -3.24 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 6
FUTU Gain: $ -1.91 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB1_OS1_CB5_CS5_RV_TR_DU8_AL_DL2 4
LAZR Gain: $ -1.12 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS2_AL_DU6_AL 15
NKE Gain: $ -1.03 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB3_CS5_SS_DU7_AL_DL1 19
ATVI Gain: $ -0.88 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB2_CS5_DU6_AL 20
TAP Gain: $ -0.49 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_AL_IT_DU8_UA_DL2 16
LABU Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS2_CB2_CS5_AL_LI_DU7_AV_DL2 7
IONQ Gain: $ -0.26 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 9
K Gain: $ -0.26 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 12 19
TVTX Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS2_RV_AV_DB30_DU7_UA_DL2 13
ISEE Gain: $ 0.02 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS4_CB5_CS3_UA_DU8_DL2 10
CALT Gain: $ 0.08 Win %: 100.00 in 1 days with algo TB2_HS_QM_OB1_OS1_CB4_CS4_IT_QL 1
RIOT Gain: $ 0.27 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 18
TTC Gain: $ 0.53 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_HM 21
XBI Gain: $ 0.77 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS4_CB5_CS2_RV_AL_TG_DU7 3
MPC Gain: $ 0.83 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB5_OS2_CB2_CS5_PM_DU7_UA_DL2_DU8_AL_TG 14
TME Gain: $ 1.16 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB3_OS4_CB5_CS3_DU12_TG_AL 11
SE Gain: $ 3.03 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS2_CB2_CS4_HM_TR_DU8_DL2 2 10
TGT Gain: $ 3.6 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS5_AO_AC_UA 17
ARGX Gain: $ 8.67 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB4_CS3_HM_TR_DB30_DU7_DL1 8
Days gain with 21 stocks: 5.84 20230516
