TGT Gain: $ -4.93 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB3_CS5_AO_AC_UA 16
BJ Gain: $ -2.0 Win %: 0.0 in 1 days with algo TB1_HL_HI_QM_OB5_OS5_CB5_CS5_RV_AV_DB30 4
AMAT Gain: $ -1.51 Win %: 0.0 in 1 days with algo TB4_LO_QM_OB3_OS3_CB4_CS4_HM 12
COST Gain: $ -1.33 Win %: 0.0 in 1 days with algo TB5_PL_QM_OB4_OS3_CB5_CS4_DU8_UA_TG_AV_DL2_AL 3
ON Gain: $ -1.27 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB4_CS4_RV_TR_DB6_DU7 7 18
ALC Gain: $ -1.12 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_AV_TG_DU7 10
ABBV Gain: $ -0.78 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS3_CB5_CS5_HM_AV_DB6_DU7_UA_DL2 14
AU Gain: $ -0.78 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 15
ANET Gain: $ -0.64 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB2_OS5_CB5_CS2_QP_QL_PM_DU6_UA_AV_DU7_AL 5
BKE Gain: $ -0.5 Win %: 0.0 in 1 days with algo TB1_HI_QM_OB4_OS4_CB5_CS5_AO_AC 1
MOS Gain: $ -0.31 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS4_CB3_CS3_DB6_UA 11
CSCO Gain: $ -0.19 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_DL1 9
VZ Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB4_OS3_CB5_CS4_AL_UA 6
GFI Gain: $ -0.15 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 17
T Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 3 5 8 12 16
OHI Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB3_OS2_CB3_CS5_SH_DU8_DL2 20
IONQ Gain: $ 0.21 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 7
AAPL Gain: $ 0.23 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB2_OS2_CB2_CS5_IR3_DU4_AL_UA_UA_UA_UA_UA 19
ORCL Gain: $ 1.13 Win %: 0.0 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5 13
CIEN Gain: $ 1.81 Win %: 0.0 in 1 days with algo TB3_HL_LO_QM_OB2_OS2_CB5_CS5_PM 2
AMD Gain: $ 2.29 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS4_CB4_CS4_HM_AL_DU6_UA_AV 21
Days gain with 21 stocks: -10.13 20230406
