PWR Gain: $ -15.48 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB5_OS3_CB3_CS5_RV_AV_UA_DU6 16
AEHR Gain: $ -9.91 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 1
STZ Gain: $ -8.19 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB5_OS3_CB2_CS5_HM_AV_DB10_DU6 17
XOM Gain: $ -7.06 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB3_OS4_CB3_CS5_AL_LI_DU6_UA 2
FANG Gain: $ -4.69 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB5_CS5_UA_WT_DU8_AV_DL2 14
LEN Gain: $ -1.7 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB4_OS4_CB5_CS5_RV_AV 10
JBL Gain: $ -1.11 Win %: 0.0 in 1 days with algo TB2_HL_HS_QM_OB1_OS1_CB4_CS4_SS 7
DUK Gain: $ -1.09 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_QL_DU7_AL_DL2 8
FRO Gain: $ -0.71 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 4
STX Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB3_CS3_RV_AV_DB30_DU7_DL1_UA_DL2_AL_TG_DU8 20
T Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS3_CB5_CS4_SR_DU7_UA_DL2_AL 5 11 12 15 17 20 21
NXE Gain: $ 0.21 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS3_CB3_CS5_HM_AV_DU8_DL2_UA 13
COTY Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS5_LI 15
VZ Gain: $ 0.26 Win %: 100.00 in 1 days with algo TB5_BL_QM_OB4_OS3_CB5_CS4_AL_UA 3
GIS Gain: $ 0.53 Win %: 100.00 in 1 days with algo TB5_PL_QM_OB1_OS1_CB3_CS1_AL_UA_AV 6
SBS Gain: $ 0.54 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 19
FLO Gain: $ 1.53 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 9
UPST Gain: $ 1.73 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV 11
XLY Gain: $ 8.54 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB3_OS4_CB2_CS4_RV_TR_AV_AL_DU7 18
META Gain: $ 34.34 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS5_HM_TR_DB6_DU7_UA_AV_DL1_DL2 21
TSLA Gain: $ 43.63 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB3_CS3_AL_LI_DU6_AV_UA_DU7 12
Days gain with 21 stocks: 41.36 20231006
