MSTR Gain: $ -13.28 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AV 9
LLY Gain: $ -4.0 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 15
META Gain: $ -2.69 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS5_HM_TR_DB6_DU7_UA_AV_DL1_DL2 11
ASAN Gain: $ -1.53 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB5_OS2_CB2_CS5_RV_AV_DB6_TG_DU7_DL2 5
BABA Gain: $ -1.5 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS3_CB5_CS4_AV_VI_DU6_UA_AL_DU7 14
DD Gain: $ -1.15 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB4_OS1_CB4_CS3_DU6 1 13
UPS Gain: $ -1.07 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB4_OS2_CB2_CS5_TS_DU7_UA_DL2 10
RIOT Gain: $ -1.05 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 3
ABT Gain: $ -1.03 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS2_TR_QP_DB10_DU7_UA_DL2 12
WMT Gain: $ -0.54 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB5_OS3_CB5_CS5_TR_IR3_TG_DU7_AV_DL2 17
YINN Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB2_OS2_CB5_CS3_AV_IT_DU7_AL_DL2 8
EQNR Gain: $ -0.19 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB4_CS5_RV_AV_DU6_UA 16
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 4
MU Gain: $ 0.36 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP 2
GOOG Gain: $ 0.69 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 6
EQT Gain: $ 0.75 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB2_OS4_CB5_CS3_IR3_DU8_DL2_UA 20
PDD Gain: $ 1.88 Win %: 100.00 in 1 days with algo TB5_HL_QM_OB3_OS4_CB1_CS5_RV_DU6_AV 13
COIN Gain: $ 2.05 Win %: 100.00 in 1 days with algo TB4_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV_DB8 18
BIDU Gain: $ 3.39 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB3_OS3_CB5_CS3_AL_TS_DU6_AV_DU6 7
FUTU Gain: $ 3.65 Win %: 100.00 in 1 days with algo TB5_PL_QM_OB1_OS1_CB5_CS5_RV_TR_DU8_AL_DL2 19
Days gain with 20 stocks: -15.77 20230515
