LLY Gain: $ -15.0 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 10
META Gain: $ -10.19 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS5_HM_TR_DB6_DU7_UA_AV_DL1_DL2 14
V Gain: $ -3.68 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS4_CB4_CS4_RV_AV_DB30_DU7 7 9 16
BTU Gain: $ -3.64 Win %: 0.0 in 1 days with algo TB1_EO_EC_QM_OB4_OS2_CB2_CS5_AV_UA_DU7 2
PINS Gain: $ -3.34 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB3_OS1_CB3_CS4_HM_AV_AL_DU7 17
UPS Gain: $ -2.08 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB4_OS2_CB2_CS5_TS_DU7_UA_DL2 5
MAT Gain: $ -1.24 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB4_OS2_CB4_CS4_SR_DU8_AV_DL2 1
EQNR Gain: $ -0.46 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB4_CS5_RV_AV_DU6_UA 18
SU Gain: $ -0.37 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS2_CB4_CS5_IT_QL_DU8_AL_DL2 20
LUV Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB4_CS3_HM_AV_DU8_UA_DL2 9
WM Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB3_OS2_CB3_CS2_RV_AV_UA_DU8_AL_DL2 19
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 8
F Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS2_CB5_CS4_HM_AV_DU7_AL_UA 13
XLV Gain: $ 0.04 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB3_OS2_CB2_CS5_RV_AL_DU7_DL1 16
GOOG Gain: $ 0.16 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 11
GOGL Gain: $ 0.23 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 6
CCL Gain: $ 0.37 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 15
IBM Gain: $ 0.92 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB2_OS3_CB4_CS2_RV_AV_DB10_DU7 4
TTD Gain: $ 3.16 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS3_SR_DU7_UA_AV_DL2_TG 21
SE Gain: $ 5.25 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB3_OS2_CB2_CS4_HM_TR_DU8_DL2 12
MO Gain: $ 10.9 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB4_OS2_CB5_CS5_RV_DU8 3
Days gain with 21 stocks: -19.04 20231026
