AEHR Gain: $ -6.89 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 19
CAT Gain: $ -1.94 Win %: 0.0 in 1 days with algo TB5_HI_HL_QM_OB2_OS4_CB2_CS5_IT_QL_DB6_DU8_AV_DL2 8
GPS Gain: $ -1.43 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB3_OS2_CB5_CS5_DU6_AL 9
INCY Gain: $ -1.27 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS2_CB5_CS4_RV_AV_DB30_DU7_AL_DL1 2
AU Gain: $ -0.87 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 3
CCL Gain: $ -0.7 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 12
SBS Gain: $ -0.46 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 4 14
SBSW Gain: $ -0.38 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS2_CB3_CS5_DU12_AL_UA 14
XPEV Gain: $ -0.38 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB5_CS3_AV_TS_DU5_AV_AV_AV_AV_AV_AV_AV_AV 18
SOFI Gain: $ -0.32 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 15
CRK Gain: $ -0.21 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB2_OS3_CB4_CS5_AL_UA_DU7_AV_DL2 6
IMMR Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 13
PSO Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB4_OS2_CB5_CS2_AV_TS_DU6_AV 7
RIG Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 20
AEO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB4_OS4_CB5_CS4_HM_TG_DU8_UA_AV_DL2 16
ATVI Gain: $ 0.16 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB2_OS2_CB2_CS5_DU6_AL 17
GFI Gain: $ 1.26 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 5
JNJ Gain: $ 2.84 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS3_AV_TS_DU8_UA_DL2 10
ANET Gain: $ 3.02 Win %: 100.00 in 1 days with algo TB1_CC_QM_OB2_OS5_CB5_CS2_QP_QL_PM_DU6_UA_AV_DU7_AL 1
MRK Gain: $ 3.76 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB2_OS2_CB2_CS3_DB10_DU7_TG_AV_DL2 11
UPST Gain: $ 4.22 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV 21
Days gain with 21 stocks: 0.1 20230801
