CI Gain: $ -9.89 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB4_OS4_CB4_CS4_RV_AL 1
ZM Gain: $ -3.66 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB5_OS5_CB5_CS5_AL 13
MSFT Gain: $ -3.23 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB5_OS3_CB2_CS5_RV_AL_DB6_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA 21
EDU Gain: $ -2.35 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS5_CB5_CS2_DU12_TG 11
JWN Gain: $ -1.89 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB1_OS2_CB5_CS5_DU6_AV 10
SE Gain: $ -1.76 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB3_OS2_CB2_CS4_HM_TR_DU8_DL2 8
COIN Gain: $ -1.51 Win %: 0.0 in 1 days with algo TB4_HL_HS_QM_OB5_OS5_CB1_CS1_RV_AV_DB8 5
BCH Gain: $ -1.32 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS2_CB5_CS3_TR_IR3_DU7_AV_DL2 9
ABBV Gain: $ -1.25 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS3_CB5_CS5_HM_AV_DB6_DU7_UA_DL2 19
MARA Gain: $ -1.25 Win %: 0.0 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 6
PINS Gain: $ -1.13 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB3_OS1_CB3_CS4_HM_AV_AL_DU7 12
EQT Gain: $ -0.97 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB2_OS4_CB5_CS3_IR3_DU8_DL2_UA 15
SNAP Gain: $ -0.95 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS3_RV_TR_DB6_DU6_UA_AV_DU7_TG_DU8_AL_DL2 3
GOOG Gain: $ -0.65 Win %: 0.0 in 1 days with algo TB5_HL_HS_QM_OB1_OS1_CB5_CS5_HM_AV_DB6 17
LTHM Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB4_CS4_HM_AV_DB30_DU7_UA_DL2 20
AR Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB1_HI_QM_OB2_OS4_CB2_CS2_AL_TS_DU7_UA_DL2_DL1_TG_AV_DU8 6 18
FLO Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS2_RV_DU7 16
RIOT Gain: $ 0.33 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 7
KSS Gain: $ 1.1 Win %: 100.00 in 1 days with algo TB5_BL_QM_OB2_OS3_CB4_CS5_AL_UA_AV_DU5_DL2 14
M Gain: $ 2.15 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS3_CB4_CS4_RV_TR_DB10_DU8_UA_DL2 2 4 6 13 20 21
MSTR Gain: $ 15.04 Win %: 100.00 in 1 days with algo TB4_HL_HS_QM_OB2_OS2_CB3_CS3_RV_AV 4
Days gain with 21 stocks: -13.92 20231211
