PINS Gain: $ -7.67 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB3_OS1_CB3_CS4_HM_AV_AL_DU7 1
RACE Gain: $ -4.43 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB3_OS2_CB5_CS4_RV_AV_DU8_UA_DL2 19
LLY Gain: $ -2.33 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 13
EA Gain: $ -2.32 Win %: 0.0 in 1 days with algo TB3_LO_HL_QM_OB5_OS2_CB4_CS4_IT_DU7_DL2 18
FISV Gain: $ -1.51 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB5_OS2_CB3_CS4_VI_DU7 15
LOGI Gain: $ -1.41 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB5_OS3_CB5_CS4_SS_DU7_DL2 14
PPC Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB3_CS3_HM_DU7_UA_DL2 10
CRH Gain: $ -0.42 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB3_OS2_CB4_CS3_RV_AV_DB6_DU7 17
SNAP Gain: $ -0.23 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS3_RV_TR_DB6_DU6_UA_AV_DU7_TG_DU8_AL_DL2 2
SOFI Gain: $ -0.21 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 21
PSO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB4_OS2_CB5_CS2_AV_TS_DU6_AV 8
TMUS Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS4_HM_AV_DU7_AL_DL2 7
OHI Gain: $ 0.06 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB3_OS2_CB3_CS5_SH_DU8_DL2 6
MNSO Gain: $ 0.11 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 20
CL Gain: $ 0.16 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB5_OS2_CB2_CS5_RV_AV_DU7_DL1 11
PBR Gain: $ 0.19 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB3_OS2_CB2_CS5_HM_TR_DU6_AL_UA 4
WEN Gain: $ 0.19 Win %: 100.00 in 1 days with algo TB3_HS_HL_QM_TG_OB2_OS4_CB5_CS2_HM_DU8_AV_DL2 9
INTC Gain: $ 0.35 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_AL_IT_DU7_UA_AV_DL2 3
C Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB1_HL_QM_OB5_OS5_CB5_CS5_RV_AV_DB30 3 10 11 12 17 19
KMB Gain: $ 1.7 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB3_OS4_CB4_CS3_UA_WT_DU8_AV_DL2 16
AMGN Gain: $ 3.32 Win %: 100.00 in 1 days with algo TB3_HL_QM_OB3_OS1_CB2_CS3_HM_AV_DB10_DU8_DL2 5
Days gain with 21 stocks: -14.05 20230428
