BLDR Gain: $ -1.64 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB5_OS3_CB4_CS5_HM_AV_DB30_DU7_UA_DL2 1
MARA Gain: $ -0.77 Win %: 0.0 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 7
RBLX Gain: $ -0.54 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB2_CS5_VI_DU7_AV_DL2 19
FTI Gain: $ -0.26 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB3_OS4_CB4_CS2_DU6_UA_AV 16
TH Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS4_CB4_CS3_QL_DU7_UA_TG 20
IMVT Gain: $ -0.19 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS4_CB3_CS3_DU8_AL 9
MNSO Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 2
SOFI Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 21
DDD Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB1_OS1_CB5_CS5_IT 6
K Gain: $ -0.05 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 4
APP Gain: $ 0.03 Win %: 100.00 in 1 days with algo TB3_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR_DB10 12
UAL Gain: $ 0.11 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB3_OS3_CB2_CS5_HM_DU7_AV_DL2 10
U Gain: $ 0.12 Win %: 100.00 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB4_CS4_HM 3 10 11
EXPI Gain: $ 0.13 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB2_OS2_CB5_CS5_PM 5
NNOX Gain: $ 0.14 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB5_CS5_IR3 8
RIOT Gain: $ 0.38 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 18
QFIN Gain: $ 0.46 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB2_OS4_CB4_CS5_DU12_DU8_UA_AV_DL2 14
AAL Gain: $ 0.54 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_DU6_DU7 17
LEN Gain: $ 0.77 Win %: 100.00 in 1 days with algo TB4_HL_HS_QM_OB4_OS4_CB5_CS5_RV_AV 15
UPST Gain: $ 0.91 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV 11
DAL Gain: $ 1.43 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB2_OS4_CB3_CS3_RV_AV_DU7 13
Days gain with 21 stocks: 0.99 20230627
