MCD Gain: $ -14.23 Win %: 0.0 in 1 days with algo TB5_LO_HL_QM_OB2_OS2_CB2_CS5_DU8_AL 11
STLD Gain: $ -1.89 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB2_CS3_HM_AV_DU8_UA_DL2 10
TTC Gain: $ -1.6 Win %: 0.0 in 1 days with algo TB5_HL_HI_QM_OB2_OS2_CB4_CS4_HM 17
RTX Gain: $ -1.48 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS3_CB5_CS2_RV_AV_DU7_UA_DL2 13
ISEE Gain: $ -1.46 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB3_OS4_CB5_CS3_UA_DU8_DL2 6
CLX Gain: $ -0.87 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS3_AV_DU7_UA_DL2 4
FCX Gain: $ -0.37 Win %: 0.0 in 1 days with algo TB1_PL_QM_OB1_OS4_CB3_CS2_AV_TS_DU8_UA_DL2 16
TTWO Gain: $ -0.14 Win %: 0.0 in 1 days with algo TB3_HI_QM_OB4_OS2_CB4_CS5_DU7_DL1_UA_DL2 15
VZ Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB4_OS3_CB5_CS4_AL_UA 5
UWMC Gain: $ -0.08 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS2_CB2_CS4_AV_UA_DU7 12
EVO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS5_RV_DU7 14
FRO Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 18
DB Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 8
NUE Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB3_OS2_CB2_CS5_HM_TR_DB30_DU8_UA_AV_DL2 20
LAZR Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS2_AL_DU6_AL 9
GLW Gain: $ 0.83 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB3_CS2_RV_DU5_DL2_AL_TG 21
GE Gain: $ 1.03 Win %: 100.00 in 1 days with algo TB1_HI_QM_OB4_OS2_CB4_CS5_AV_IT_TG_AL_DU8_DL2 19
NEE Gain: $ 1.27 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB4_OS2_CB3_CS4_TR_TS_AL_DU7_AV_DL1_DL2 2
PEP Gain: $ 1.66 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB2_OS5_CB4_CS2_AL_UA_DU7_DL2 3
A Gain: $ 3.62 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB3_OS5_CB4_CS5_HM_TR_DU7_UA_DL2 7 9
UPS Gain: $ 3.86 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB4_OS2_CB2_CS5_TS_DU7_UA_DL2 1
Days gain with 21 stocks: -9.12 20230425
