EVO Gain: $ -7.4 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS5_RV_DU7 6
AMGN Gain: $ -6.06 Win %: 0.0 in 1 days with algo TB3_HL_QM_OB3_OS1_CB2_CS3_HM_AV_DB10_DU8_DL2 14
KMB Gain: $ -2.43 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS4_CB4_CS3_UA_WT_DU8_AV_DL2 19
SJM Gain: $ -2.16 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB3_OS2_CB5_CS4_DB6_UA 21
FRO Gain: $ -2.01 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 7
ABT Gain: $ -1.86 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB2_OS2_CB5_CS2_TR_QP_DB10_DU7_UA_DL2 4
DUK Gain: $ -1.24 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_QL_DU7_AL_DL2 7
TSN Gain: $ -1.18 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS3_CB2_CS5_AL_TS_AV_DU8_DL2 20
EQNR Gain: $ -1.1 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB4_CS5_RV_AV_DU6_UA 12
SBLK Gain: $ -0.85 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB3_CS5_AL_TS_DU8_AV_DL2 2 4
TME Gain: $ -0.73 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB3_OS4_CB5_CS3_DU12_TG_AL 17
MNSO Gain: $ -0.61 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 8
MRO Gain: $ -0.49 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB5_OS3_CB5_CS3_HM_AV_DU7 8
LOGI Gain: $ -0.42 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB5_OS3_CB5_CS4_SS_DU7_DL2 16
UBS Gain: $ -0.39 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS2_AL_UA_DU8_DL2 15
SLV Gain: $ -0.33 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB5_OS2_CB2_CS5_AV_TS_DU7_UA_DL1 11
BP Gain: $ -0.26 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB5_OS2_CB4_CS5_HM_AV_DB10_DU7 5 18
AU Gain: $ -0.24 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB3_OS2_CB5_CS3_HM_UA_DU8_AL_DL2_TG 9
GLD Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB4_OS2_CB5_CS5_AO_DU6 9
GOGL Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB2_CS4_AL_IT_DU7_AV_DL2 2
GFI Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB3_CS3_HM_AV_DU7_AL 10
SBS Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 1 3
COTY Gain: $ -0.06 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS5_LI 3
NXE Gain: $ -0.02 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB2_OS3_CB3_CS5_HM_AV_DU8_DL2_UA 5
ACI Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_HI_HL_QM_OB3_OS3_CB3_CS3_LI_DU7 13
XPEV Gain: $ 0.28 Win %: 100.00 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB5_CS3_AV_TS_DU5_AV_AV_AV_AV_AV_AV_AV_AV 6
YPF Gain: $ 1.42 Win %: 100.00 in 1 days with algo TB3_OO_QM_OB4_OS2_CB4_CS4_HM_AV_DU8_DL2_UA 1
Days gain with 27 stocks: -28.74 20231123
