RACE Gain: $ -1.88 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB3_OS2_CB5_CS4_RV_AV_DU8_UA_DL2 15
DKNG Gain: $ -1.63 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_HM_AL_DU7 20
VMW Gain: $ -1.63 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB1_CS1_QL 18
MRK Gain: $ -1.37 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS2_CB2_CS3_DB10_DU7_TG_AV_DL2 18
LITE Gain: $ -1.05 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB5_CS3_VI_AL 1 2
PG Gain: $ -0.87 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB3_OS4_CB3_CS5_AL_LI_DU7_AV_DL1 13
ANET Gain: $ -0.64 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB2_OS5_CB5_CS2_QP_QL_PM_DU6_UA_AV_DU7_AL 10
UPS Gain: $ -0.53 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB4_OS2_CB2_CS5_TS_DU7_UA_DL2 4
RY Gain: $ -0.49 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB4_OS2_CB4_CS5_RV_AV_DU7_UA_DL2 17
EVO Gain: $ -0.45 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS5_RV_DU7 21
MMM Gain: $ -0.4 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB3_OS3_CB5_CS4_SS_DU7_AV_DL1 15
CRH Gain: $ -0.35 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB3_OS2_CB4_CS3_RV_AV_DB6_DU7 7
CL Gain: $ -0.3 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB5_OS2_CB2_CS5_RV_AV_DU7_DL1 16
NEE Gain: $ -0.29 Win %: 0.0 in 1 days with algo TB1_HS_QM_OB4_OS2_CB3_CS4_TR_TS_AL_DU7_AV_DL1_DL2 19
TAP Gain: $ -0.29 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB2_OS2_CB2_CS5_AL_IT_DU8_UA_DL2 9
AAL Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_DU6_DU7 13
MNST Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB4_OS3_CB4_CS4_RV_AL_UA 3 12
MS Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB2_OO_QM_OB4_OS4_CB5_CS5_IT_QP_DB15 17
RIG Gain: $ -0.19 Win %: 0.0 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 1
VIGI Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB2_OS4_CB5_CS2_AV_TS_DU7_AL 7
F Gain: $ -0.09 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_TG_OB2_OS2_CB5_CS4_HM_AV_DU7_AL_UA 21
SBS Gain: $ -0.04 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS5_CB4_CS2_WT_DU7_UA_AV_DL2_TG_AL 10
SBLK Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB3_OS3_CB3_CS5_AL_TS_DU8_AV_DL2 8
SLV Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB5_OS2_CB2_CS5_AV_TS_DU7_UA_DL1 6
COTY Gain: $ 0.1 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB2_OS2_CB5_CS5_LI 11
CSCO Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_DL1 11
DIA Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB3_CC_QM_OB3_OS2_CB2_CS4_RV_AV_UA_DU7_DL1 14
DB Gain: $ 0.2 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 4 20
WYNN Gain: $ 0.2 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB3_OS3_CB4_CS5_RV_AV_DU7 14
JBL Gain: $ 0.31 Win %: 100.00 in 1 days with algo TB2_HL_HS_QM_OB1_OS1_CB4_CS4_SS 19
AKAM Gain: $ 0.33 Win %: 100.00 in 1 days with algo TB3_LO_HL_QM_OB5_OS5_CB3_CS4_HM_AV_DU7_DL1 12
RIOT Gain: $ 0.34 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 6
AZN Gain: $ 0.44 Win %: 100.00 in 1 days with algo TB3_OC_QM_OB2_OS4_CB3_CS2_RV_DU7_AV_DL2_DU5 5
TSM Gain: $ 0.54 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB4_OS3_CB3_CS5_RV_DU7 16
MARA Gain: $ 0.64 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 2 9
STLD Gain: $ 2.15 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB2_CS3_HM_AV_DU8_UA_DL2 3
LIN Gain: $ 3.63 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB2_OS3_CB3_CS5_AL_TS_UA_AV 8
AEHR Gain: $ 22.34 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 5
Days gain with 38 stocks: 18.09 20230704
