LLY Gain: $ -5.79 Win %: 0 in 1 days with algo TB5_EO_EC_QM_OB3_OS2_CB5_CS2_DU6_DU8_AV_DL2 8
GS Gain: $ -3.06 Win %: 0 in 1 days with algo TB5_OO_QM_OB2_OS4_CB5_CS3_RV_AV_DB6_DU6_UA_TG_DU7_DL2 16
SJM Gain: $ -1.95 Win %: 0 in 1 days with algo TB5_HI_QM_OB3_OS2_CB5_CS4_DB6_UA 3
ROKU Gain: $ -1.73 Win %: 0 in 1 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_SS 20
JPM Gain: $ -1.58 Win %: 0 in 1 days with algo TB3_OC_QM_OB4_OS3_CB3_CS5_HM_AV_DB10_DU6_UA_UA 10
NEM Gain: $ -1.29 Win %: 0 in 1 days with algo TB1_EO_EC_QM_OB3_OS2_CB5_CS5_RV_AV_DU7 18
PINS Gain: $ -1.23 Win %: 0 in 1 days with algo TB1_PL_QM_OB3_OS1_CB3_CS4_HM_AV_AL_DU7 7
MS Gain: $ -1.17 Win %: 0 in 1 days with algo TB2_OO_QM_OB4_OS4_CB5_CS5_IT_QP_DB15 14
C Gain: $ -1.12 Win %: 0 in 1 days with algo TB1_HL_QM_OB5_OS5_CB5_CS5_RV_AV_DB30 12 13 15 19
BAC Gain: $ -0.96 Win %: 0 in 1 days with algo TB2_CC_QM_OB3_OS3_CB5_CS5_RV_AL_DB15 12
FAZ Gain: $ -0.67 Win %: 0 in 1 days with algo TB1_LO_QM_OB2_OS5_CB5_CS3_RV_AL_DB30_DU7_UA_AV_DL2_DU8 5
GLW Gain: $ -0.52 Win %: 0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB3_CS2_RV_DU5_DL2_AL_TG 11
RWM Gain: $ -0.47 Win %: 0 in 1 days with algo TB1_HI_HL_QM_OB2_OS3_CB3_CS4_AV_IT_DU8_DL2_AL_DU7 21
ICL Gain: $ -0.01 Win %: 0 in 1 days with algo TB3_OO_QM_OB2_OS2_CB4_CS5_RV_AL_DB10_UA 19
DB Gain: $ 0.0 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 9
AGNC Gain: $ 0.01 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB4_OS2_CB2_CS4_HM_AV_DU8_UA_DL2_DU7_DL1_AL 15
GLD Gain: $ 0.02 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB4_OS2_CB5_CS5_AO_DU6 4
RIG Gain: $ 0.04 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 17
USB Gain: $ 1.7 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB3_OS2_CB4_CS4_VI_DU7_UA_DL2 1
FITB Gain: $ 2.25 Win %: 100.00 in 1 days with algo TB1_EO_EC_QM_OB5_OS2_CB3_CS5_AV_DU7 6
BNTX Gain: $ 14.21 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS3_CB5_CS3_HM_AL_DU7 2
Days gain with 21 stocks: -3.32 20230327
