FL Gain: $ -6.44 Win %: 0.0 in 1 days with algo TB3_PL_QM_OB3_OS1_CB4_CS3_SH_DU6_AL 3
MRNA Gain: $ -3.51 Win %: 0.0 in 1 days with algo TB5_HS_HL_QM_OB5_OS2_CB2_CS5_RV_DU7_AL_DL2 21
LOW Gain: $ -3.22 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS3_CB2_CS5_AV_TS_DU7_AL_DL2 9
NVDA Gain: $ -2.8 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 18
KSS Gain: $ -1.54 Win %: 0.0 in 1 days with algo TB5_BL_QM_OB2_OS3_CB4_CS5_AL_UA_AV_DU5_DL2 8
MNSO Gain: $ -1.35 Win %: 0.0 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 4
DKS Gain: $ -1.3 Win %: 0.0 in 1 days with algo TB3_HI_QM_OB4_OS2_CB4_CS4_AL_TS_DU7_DL2 1
NKE Gain: $ -1.25 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB3_CS5_SS_DU7_AL_DL1 12
ACMR Gain: $ -1.2 Win %: 0.0 in 1 days with algo TB1_HL_HI_QM_OB2_OS2_CB4_CS4_RV 15
ANF Gain: $ -1.1 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS5_CB2_CS2_RV_DU8_AL_DL2 2
MDT Gain: $ -0.65 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB3_CS3_AL_TS 10
M Gain: $ -0.51 Win %: 0.0 in 1 days with algo TB3_HI_QM_OB4_OS3_CB4_CS4_RV_TR_DB10_DU8_UA_DL2 4 6 10 15 21
GPS Gain: $ -0.43 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB3_OS2_CB5_CS5_DU6_AL 11
TJX Gain: $ -0.31 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB3_OS3_CB2_CS3_AL_TS_UA_DU8_DL2 20
SCHW Gain: $ -0.28 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB2_OS2_CB5_CS3_RV_TR_DU7_AL_DL2_UA 14
PTON Gain: $ -0.16 Win %: 0.0 in 1 days with algo TB1_HI_QM_OB4_OS2_CB2_CS5_AL_LI_DU7_UA_DL2 5
VTRS Gain: $ 0.01 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB4_OS5_CB5_CS4_IR1_DU7_AL 17
RIG Gain: $ 0.07 Win %: 100.00 in 1 days with algo TB3_HI_QM_OB4_OS4_CB5_CS5_DB10 16
RF Gain: $ 0.11 Win %: 100.00 in 1 days with algo TB5_LO_QM_OB2_OS2_CB5_CS4_PM_DU8_DL2_UA_AV 13
CSIQ Gain: $ 0.37 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB4_OS2_CB5_CS4_AV_UA_TG_DU8_AL_DL2 7
NVAX Gain: $ 0.44 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB2_OS3_CB3_CS2_HM_AV_DB10_DU8_DL2 19
Days gain with 21 stocks: -25.05 20230823
