ADBE Gain: $ -10.24 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS2_CB2_CS5_LI_DU8_AV_DL2 20
BABA Gain: $ -4.62 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS3_CB5_CS4_AV_VI_DU6_UA_AL_DU7 10
TECL Gain: $ -3.2 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS2_CB5_CS4_AO_AC_DU7_UA_AV_DL1 16
RACE Gain: $ -2.11 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB3_OS2_CB5_CS4_RV_AV_DU8_UA_DL2 9
ALC Gain: $ -1.55 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_AV_TG_DU7 4
APP Gain: $ -1.13 Win %: 0.0 in 1 days with algo TB3_HL_LO_QM_OB5_OS5_CB4_CS4_HM_TR_DB10 1
K Gain: $ -0.49 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS4_HM_TR_DB10_DU7_AL_DL2 8 14
SBSW Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB1_BL_QM_OB2_OS2_CB3_CS5_DU12_AL_UA 19
PENN Gain: $ -0.17 Win %: 0.0 in 1 days with algo TB1_HL_LO_QM_OB1_OS1_CB5_CS5_AL 13
SSL Gain: $ -0.07 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS2_CB5_CS5_RV_AL_DU7_DL2_DU8_UA_AV 7
ASML Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS2_CB2_CS4_PM_DU7_DL1 17
ESLT Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB1_LO_HL_QM_OB2_OS5_CB2_CS3_QP_PM_UA_TG_DU7_DL2_DL1_DU5_DU8_AV_AL 5
DB Gain: $ 0.2 Win %: 100.00 in 1 days with algo TB1_LO_HL_QM_OB3_OS2_CB2_CS3_AV_TS_UA_DU7 18 20
MNSO Gain: $ 0.48 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 6
DNUT Gain: $ 0.69 Win %: 100.00 in 1 days with algo TB5_HL_HS_QM_OB2_OS2_CB5_CS5_RV_AV 2
DKNG Gain: $ 0.92 Win %: 100.00 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_HM_AL_DU7 8
RL Gain: $ 1.13 Win %: 100.00 in 1 days with algo TB3_HL_HI_QM_OB5_OS5_CB5_CS5_RV_TR 3
TCOM Gain: $ 2.55 Win %: 100.00 in 1 days with algo TB1_OO_QM_OB2_OS2_CB2_CS4_RV_AL_UA_DU7_DL2 11
TQQQ Gain: $ 4.39 Win %: 100.00 in 1 days with algo TB3_HS_HL_QM_OB5_OS2_CB4_CS5_SS_DU6 12
MSFT Gain: $ 5.62 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB5_OS3_CB2_CS5_RV_AL_DB6_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA 15
PDD Gain: $ 7.77 Win %: 100.00 in 1 days with algo TB5_HL_QM_OB3_OS4_CB1_CS5_RV_DU6_AV 21
Days gain with 21 stocks: -0.01 20230810
