STZ Gain: $ -6.23 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB5_OS3_CB2_CS5_HM_AV_DB10_DU6 1
NKE Gain: $ -3.76 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB5_OS2_CB3_CS5_SS_DU7_AL_DL1 21
RACE Gain: $ -2.46 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB3_OS2_CB5_CS4_RV_AV_DU8_UA_DL2 18
AAPL Gain: $ -1.27 Win %: 0.0 in 1 days with algo TB3_EO_EC_QM_OB2_OS2_CB2_CS5_IR3_DU4_AL_UA_UA_UA_UA_UA 14
ALC Gain: $ -0.8 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_AV_TG_DU7 3
FRO Gain: $ -0.61 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB2_OS2_CB3_CS4_TS_UA_TG_DU7_DL2 5
DELL Gain: $ -0.46 Win %: 0.0 in 1 days with algo TB1_HL_HS_QM_OB1_OS1_CB4_CS4_HM 9
TQQQ Gain: $ -0.39 Win %: 0.0 in 1 days with algo TB3_HS_HL_QM_OB5_OS2_CB4_CS5_SS_DU6 12
TECL Gain: $ -0.18 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS2_CB5_CS4_AO_AC_DU7_UA_AV_DL1 11
NVDA Gain: $ -0.13 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 17
UPST Gain: $ 0.01 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV 15
RIOT Gain: $ 0.06 Win %: 100.00 in 1 days with algo TB5_HL_HI_QM_OB3_OS3_CB3_CS3_HM 8
MARA Gain: $ 0.15 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV_AV 13
XPEV Gain: $ 0.17 Win %: 100.00 in 1 days with algo TB5_LO_HL_QM_OB3_OS3_CB5_CS3_AV_TS_DU5_AV_AV_AV_AV_AV_AV_AV_AV 7
NNOX Gain: $ 0.37 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB5_CS5_IR3 4
SOFI Gain: $ 0.39 Win %: 100.00 in 1 days with algo TB4_HL_HI_QM_OB3_OS3_CB5_CS5_AC 10
XLK Gain: $ 0.74 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB2_OS2_CB3_CS3_IT_QL_DB6 20
CCL Gain: $ 0.79 Win %: 100.00 in 1 days with algo TB1_BL_QM_OB2_OS4_CB5_CS5_DU6_DU8_AV_DL2 2
OSTK Gain: $ 0.98 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV 6
KEYS Gain: $ 1.18 Win %: 100.00 in 1 days with algo TB2_HL_LO_QM_OB3_OS3_CB4_CS4_TR_TS 16
QQQ Gain: $ 1.75 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB1_OS1_CB4_CS4_AL 12 19
Days gain with 21 stocks: -9.7 20230630
