NVDA Gain: $ -10.32 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 7
AMGN Gain: $ -4.31 Win %: 0.0 in 1 days with algo TB3_HL_QM_OB3_OS1_CB2_CS3_HM_AV_DB10_DU8_DL2 14
BLDR Gain: $ -4.25 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB5_OS3_CB4_CS5_HM_AV_DB30_DU7_UA_DL2 20
OSTK Gain: $ -2.28 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB2_OS2_CB5_CS5_RV_AV 1 1
JNJ Gain: $ -2.02 Win %: 0.0 in 1 days with algo TB3_HS_QM_OB2_OS3_CB3_CS3_AV_TS_DU8_UA_DL2 6 6
AAL Gain: $ -1.21 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB2_OS2_CB5_CS2_HM_DU6_DU7 18
LEGN Gain: $ -0.75 Win %: 0.0 in 1 days with algo TB3_LO_QM_OB3_OS3_CB5_CS5_HM_AL 9
DAL Gain: $ -0.67 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB2_OS4_CB3_CS3_RV_AV_DU7 19
MRK Gain: $ -0.27 Win %: 0.0 in 1 days with algo TB3_OO_QM_OB2_OS2_CB2_CS3_DB10_DU7_TG_AV_DL2 5 13
UAL Gain: $ -0.12 Win %: 0.0 in 1 days with algo TB3_CC_QM_OB3_OS3_CB2_CS5_HM_DU7_AV_DL2 21
ACI Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB5_HI_HL_QM_OB3_OS3_CB3_CS3_LI_DU7 7 15
FTI Gain: $ -0.11 Win %: 0.0 in 1 days with algo TB1_LO_QM_OB3_OS4_CB4_CS2_DU6_UA_AV 10
IMMR Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB4_OS4_CB5_CS5_RV_AV 11
VTRS Gain: $ -0.01 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB4_OS5_CB5_CS4_IR1_DU7_AL 8 4
ACRS Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_HL_LO_QM_OB1_OS1_CB5_CS5_QP_PM 19
ASAN Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB5_CC_QM_OB5_OS2_CB2_CS5_RV_AV_DB6_TG_DU7_DL2 3 2
KR Gain: $ 0.0 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS3_CB3_CS5_TR_IR3_DU8_DL2_UA_AV 9 18
VRTX Gain: $ 0.01 Win %: 100.00 in 1 days with algo TB3_HS_QM_OB3_OS4_CB5_CS2_SS_UA_AL_DU8_AV_DL2 17 11
SNAP Gain: $ 0.05 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS3_RV_TR_DB6_DU6_UA_AV_DU7_TG_DU8_AL_DL2 12 8
LAZR Gain: $ 0.22 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS2_AL_DU6_AL 17
PFE Gain: $ 0.65 Win %: 100.00 in 1 days with algo TB3_PL_QM_OB2_OS2_CB4_CS2_RV_AV_DB10_DU7_UA_DL2 12
UPST Gain: $ 0.94 Win %: 100.00 in 1 days with algo TB4_HL_LO_QM_OB1_OS1_CB5_CS5_RV 16
CELH Gain: $ 1.06 Win %: 100.00 in 1 days with algo TB1_HS_HL_QM_OB2_OS4_CB5_CS4_HM_AV_DB30 13
ROKU Gain: $ 1.18 Win %: 100.00 in 1 days with algo TB2_HL_HI_QM_OB2_OS2_CB4_CS4_SS 2
ABBV Gain: $ 1.54 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB4_OS3_CB5_CS5_HM_AV_DB6_DU7_UA_DL2 15 21
AAPL Gain: $ 1.92 Win %: 100.00 in 1 days with algo TB3_EO_EC_QM_OB2_OS2_CB2_CS5_IR3_DU4_AL_UA_UA_UA_UA_UA 5
MNSO Gain: $ 2.12 Win %: 100.00 in 1 days with algo TB1_OC_QM_OB5_OS2_CB3_CS5_DU6_DU8_DL2_UA_AV 10 14
ZS Gain: $ 3.36 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB4_OS2_CB4_CS4_AV_IT_DU8_DL2_AL 20
LMT Gain: $ 10.49 Win %: 100.00 in 1 days with algo TB3_HI_HL_QM_OB5_OS2_CB3_CS5_IT_QL_DU7 4 3
TSLA Gain: $ 18.77 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS2_CB3_CS3_AL_LI_DU6_AV_UA_DU7 16
Days gain with 30 stocks: 15.87 20230906
