NVDA Gain: $ -8.06 Win %: 0.0 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_AL_LI_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA_DU6_UA 1
TSM Gain: $ -7.32 Win %: 0.0 in 1 days with algo TB1_OO_QM_OB4_OS3_CB3_CS5_RV_DU7 7
DLTR Gain: $ -7.01 Win %: 0.0 in 1 days with algo TB5_LO_QM_OB3_OS2_CB3_CS5_AL_LI_DU8_AV_DL2 2
MSFT Gain: $ -5.97 Win %: 0.0 in 1 days with algo TB5_HI_QM_OB5_OS3_CB2_CS5_RV_AL_DB6_DU6_UA_UA_UA_UA_UA_UA_UA_UA_UA_UA 15
ANET Gain: $ -1.64 Win %: 0.0 in 1 days with algo TB1_CC_QM_OB2_OS5_CB5_CS2_QP_QL_PM_DU6_UA_AV_DU7_AL 6
AEHR Gain: $ -1.5 Win %: 0.0 in 1 days with algo TB5_OO_QM_OB2_OS2_CB4_CS5_AL_UA_DU7 10
MDT Gain: $ -1.19 Win %: 0.0 in 1 days with algo TB3_HI_HL_QM_OB2_OS2_CB3_CS3_AL_TS 8
MU Gain: $ -1.0 Win %: 0.0 in 1 days with algo TB3_OC_QM_OB3_OS3_CB5_CS5_HM_QP 16 21
ASML Gain: $ -0.89 Win %: 0.0 in 1 days with algo TB1_HS_HL_QM_OB2_OS2_CB2_CS4_PM_DU7_DL1 18
BBY Gain: $ -0.42 Win %: 0.0 in 1 days with algo TB5_EO_EC_QM_OB3_OS4_CB5_CS4_TR_UA_AL 11
SNOW Gain: $ -0.2 Win %: 0.0 in 1 days with algo TB1_HI_HL_QM_OB5_OS3_CB2_CS5_RV_AL_DU7_UA_DL2 4
TECL Gain: $ -0.03 Win %: 0.0 in 1 days with algo TB5_HS_QM_OB3_OS2_CB5_CS4_AO_AC_DU7_UA_AV_DL1 17
SOXL Gain: $ 0.34 Win %: 100.00 in 1 days with algo TB5_HS_QM_OB5_OS2_CB5_CS4_SS_AL 13
APPS Gain: $ 0.43 Win %: 100.00 in 1 days with algo TB3_HL_HI_QM_OB2_OS2_CB1_CS1_TR 3
IONQ Gain: $ 0.45 Win %: 100.00 in 1 days with algo TB1_HS_QM_OB3_OS3_CB4_CS4_LI 12
TMUS Gain: $ 0.45 Win %: 100.00 in 1 days with algo TB5_CC_QM_OB2_OS2_CB4_CS4_HM_AV_DU7_AL_DL2 21
MRVL Gain: $ 0.71 Win %: 100.00 in 1 days with algo TB5_OC_QM_OB2_OS2_CB5_CS5_IT_TS 14
CSCO Gain: $ 0.93 Win %: 100.00 in 1 days with algo TB5_OO_QM_OB2_OS4_CB3_CS3_AV_VI_DU7_DL1 19
XLK Gain: $ 1.15 Win %: 100.00 in 1 days with algo TB5_HI_QM_OB2_OS2_CB3_CS3_IT_QL_DB6 20
RL Gain: $ 2.02 Win %: 100.00 in 1 days with algo TB3_HL_HI_QM_OB5_OS5_CB5_CS5_RV_TR 9
AMD Gain: $ 4.15 Win %: 100.00 in 1 days with algo TB3_LO_QM_OB3_OS4_CB4_CS4_HM_AL_DU6_UA_AV 5
Days gain with 21 stocks: -24.6 20230525
